### ISSUE TITLE
Use MAVEN_HOME property when looking for local repository to run stubs

### ISSUE THREAD

**Issue by saikrishnamns** [spring-cloud/spring-cloud-contract#1007]
Hi All,

When running cloud contract tests locally the default repository for windows is being searched. If i have a different maven settings with a different repo then i have to always provide an override option maven.repo.local.  It will be nice if MAVEN_HOME is read first and use that to read the repo location.

**Comment by marcingrzejszczak** [comment]
Hi @saikrishnamns ! Can you remind me how this should be changed? I remember that we discussed it but I don't remember the conclusions ;)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by saikrishnamns** [comment]
@marcingrzejszczak - Currently spring cloud contract looks at the default maven repository location like /Users/<username>/.m2 , but if the maven settings are pointing to a different location then currently to provide the repo to cloud contract using -D option . It will be nice if the maven repo location is ready from MAVEN_HOME env variable.

**Comment by marcingrzejszczak** [comment]
Are you sure you're talking about `MAVEN_HOME`? You can change that location by providing `-Dmaven.repo.local=...` . `MAVEN_HOME` points to your maven installation e.g. `/home/marcin/.sdkman/candidates/maven/current`

**Comment by saikrishnamns** [comment]
@marcingrzejszczak - it has been a long back, i am trying to recollect. The problem that we had was the maven repo was different in different CI/CD environments, so we had to give different repo options in different machines. So, not MAVEN_HOME but finding out the repo of the local machine should be possible i think. This way we don't have to specify the -Dmaven.repo.local everytime.

**Comment by marcingrzejszczak** [comment]
Ok I understand. So sth like evaluation of `mvn help:evaluate -Dexpression=settings.localRepository` that would retrieve the local repository setting basing on the current machine's setup?

**Comment by saikrishnamns** [comment]
yeah exactly. I was looking for that command :)

**Comment by marcingrzejszczak** [comment]
Hi @saikrishnamns ! I had some time to look into this

https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/AetherFactories.java#L93

we already retrieve this information.

Can you please create a small sample that reproduces this problem? Otherwise it will be difficult for me to replicate it :/

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
