### ISSUE TITLE
Stub runner cannot be used with a jar that has no classifier

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-contract#101]
Apparently there is no way to ask `@AutoConfigureStubRunner` to run a jar with no classifier (would be useful).

Also the docs are inconsistent: User guide says "com.example:http-server-dsl:2.1.1:stubs:8080", javadocs of `@AutoConfigureStubRunner` says "groupId:artifactId[:classifier]:version[:port]".

**Comment by dsyer** [comment]
If you leave off the port it downloads the jar correctly, but then you don't know the port.

**Comment by marcingrzejszczak** [comment]
You can find the port via the `StubFinder`. It find a URL of the registered stub. Currently it returns null if there is no stub. As you suggested I'll change it to throwing an exception

**Comment by marcingrzejszczak** [comment]
Done here - https://github.com/spring-cloud/spring-cloud-contract/issues/102
