### ISSUE TITLE
Verifier docker image support for custom stubs jar classifier

### ISSUE THREAD

**Issue by Dominick1993** [spring-cloud/spring-cloud-contract#1031]
There is no support for custom stubs classifier in current state of the verifier docker image.
We are using SCC as part of our tests and we wanted to elevate stubs classifier as some kind of tag, putting those tags into version is not suitable.

On the side of stub runner these custom stub classifiers are easily supported by the ability to provide any classifier in `STUBRUNNER_IDS` chain of artifacts.

https://github.com/spring-cloud/spring-cloud-contract/pull/1030 solves this issue.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/8f0db8ffe206cac1fdfb73052d7c722c1f891283 - https://github.com/spring-cloud/spring-cloud-contract/blob/master/docker/spring-cloud-contract-docker/project/build.gradle#L63
