### ISSUE TITLE
SCC gradle plugin does not apply some properties

### ISSUE THREAD

**Issue by Dominick1993** [spring-cloud/spring-cloud-contract#1032]
While trying to provide custom stubs classifier by setting the property `stubSuffix` under the `contracts{}` extension I was unable to have stubs published with my classifier, I kept getting the default classifier which is `stubs`.

SCC version: `2.2.0-BUILD-SNAPSHOT`
How to reproduce: Try simply changing the property mentioned above in any build that uses the SCC gradle plugin. You can do that easily by setting it in `build.gradle` in verifier docker image, rebuild plugin and verifier image and try running some tests. Your stubs will still be published with `stubs` classifier despite providing some different classifier.

Closely investigating I found that the stubs jar task is created before the extension contains the properties from`build.gradle`.

https://github.com/spring-cloud/spring-cloud-contract/pull/1030 solves this issue.

**Comment by OlgaMaciaszek** [comment]
Hello @Dominick1993 Thanks for reporting this issue. I've been able to reproduce it. Will have a look at your PR.

**Comment by Dominick1993** [comment]
Thanks @OlgaMaciaszek , unfortunately I didn't have time to fix it properly yet. The workaround in the PR works, but tests fail. And it seems that the tests on master branch currently fail with some other issues as well.

**Comment by OlgaMaciaszek** [comment]
yes, @Dominick1993 unfortunately, the master is failing. We are working on it.

**Comment by OlgaMaciaszek** [comment]
Master is green now. Waiting for fixes in the PR.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Dominick1993** [comment]
Master seems to be broken again, I was testing my fix on 2.1.1.RELEASE tag, still failing on tests. I'll be working on a solution soon.

**Comment by OlgaMaciaszek** [comment]
Ok, please get back to us when you have sth ready to review or you have any questions.

**Comment by marcingrzejszczak** [comment]
Should be fixed via https://github.com/spring-cloud/spring-cloud-contract/pull/1030
