### ISSUE TITLE
Incorrect headers from groovy contracts to wiremock json

### ISSUE THREAD

**Issue by guenichone** [spring-cloud/spring-cloud-contract#1033]
Hello,

I'm using spring-cloud-contract-maven-plugin in version 2.1.1.RELEASE to generate a stubs jar from my groovy contracts.

I have a very simple contract in src/test/resources/contracts :

package contracts

```groovy
org.springframework.cloud.contract.spec.Contract.make {
    request {
        method 'POST'
        headers {
            header('''Accept''', '''application/json''')
            header('''Content-Type''', '''application/json''')
        }
        url '/service/v1/path'
        body([
            "id": "1234"
        ])
        headers {
            contentType('application/json')
        }
    }
    response {
        status OK()
        headers {
            contentType('application/json')
        }
    }
}
```

Then I simply run the goal 'convert' of the spring-cloud-contract-maven-plugin.

It produces the following file in target/subs/META-INF/\<package\>/\<project\>/\<version\>/mappings:

```json
{
  "id" : "1e78a9c8-89b9-4008-9079-d42252d11060",
  "request" : {
    "url" : "/service/v1/path",
    "method" : "POST",
    "headers" : {
      "Content-Type" : {
        "matches" : "application/json.*"
      }
    },
    "bodyPatterns" : [ {
      "matchesJsonPath" : "$[?(@.['id'] == '1234')]"
    } ]
  },
  "response" : {
    "status" : 200,
    "headers" : {
      "Content-Type" : "application/json"
    },
    "transformers" : [ "response-template" ]
  },
  "uuid" : "1e78a9c8-89b9-4008-9079-d42252d11060"
}
```
Also the initial groovy contract is in target/subs/META-INF/\<package\>/\<project\>/\<version\>/contracts.

I tried differents ways to declare the headers that I want to match, but it's always generating that header signature : 

```json
    "headers" : {
      "Content-Type" : {
        "matches" : "application/json.*"
      }
    },
```

Is it a real bug or did I missed something ?

Thank you.

**Comment by marcingrzejszczak** [comment]
Can you paste your project setup?

> I tried differents ways to declare the headers that I want to match, but it's always generating that header signature :

That's a feature. If you want to have an exact entry for content type set

```
header("Content-Type", "application/json")
```

**Comment by marcingrzejszczak** [comment]
BTW you have duplicated headers

```

        headers {
            header('''Accept''', '''application/json''')
            header('''Content-Type''', '''application/json''')
        }
        headers {
            contentType('application/json')
        }
```

just remove the second section

**Comment by guenichone** [comment]
^

**Comment by guenichone** [comment]
Works better ... thank you very much :)
