### ISSUE TITLE
Groovy DSL. JSON header is converted to stringified map.

### ISSUE THREAD

**Issue by ahlinist** [spring-cloud/spring-cloud-contract#1034]
Hi, I'm using spring-cloud-contract-2.1.0 along with groovy DSL.

Here is my contract:

```
make {
    name 'my name'
    request {
        method POST()
        urlPath '/my-url'
        headers {
            contentType(applicationJson())
            accept(applicationJson())
            header('my-json-header', ''' { "value": "123" } ''')
        }
    }
    response {
        status OK()
    }
}
```

The issue is that despite trying various combinations of passing the `my-json-header` value as JSON - I always get a "stringified" groovy map in my generated test:

```
.header("my-json-header", "[value:123]")
```

How to achieve passing a JSON string (as given in an example above) as a header value? What am I missing?

Thanks in advance!

**UPD**:

Gradle plugin configuration:

```
configure<ContractVerifierExtension> {
    testMode = EXPLICIT
    testFramework = JUNIT5
    contractsDslDir = ...
    baseClassForTests = ...
    basePackageForTests = ...
    nameSuffixForTests = ...
}
```

**Comment by marcingrzejszczak** [comment]
I think it got reported once. It's really strange to pass such data in the header value, but indeed it shouldn't work like that

**Comment by ahlinist** [comment]
The source of the issue lies in `MethodBodyBuilder#getTestSideValue(Object object)`.

`MapConverter.getTestSideValues(object)` returns a LinkedHashMap instanse with further `toString()` invocation on it.

See: https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/MethodBodyBuilder.groovy#L567

**Comment by marcingrzejszczak** [comment]
Care for a test and a pr that would fix it? :)
