### ISSUE TITLE
Inconsistent behaviour in creating MessageChannels in production code and tests code

### ISSUE THREAD

**Issue by marekdominiak** [spring-cloud/spring-cloud-contract#1044]
I have recently upgraded Spring Cloud Stream from 1.2.x to version 2.1.x Release. I got the following issue with the Spring Cloud Stream 2.1.x. I use SCS it in tests with Spring Cloud Contract to run contract tests for integrations - StreamListeners using Kafka binder.

In my configuration I have to very similar configurations: 
```java
public interface Processor {
    String CUSTOMER_INPUT = "customerInput";

    @Input(CUSTOMER_INPUT)
    SubscribableChannel customerInput();

    String PERSON_INPUT = "personInput";

    @Input(PERSON_INPUT)
    SubscribableChannel personInput();
}
```
together with properties in `application.properties`

```
# spring cloud stream 
spring.cloud.stream.bindings.customerInput.destination=customerEventsTopic
spring.cloud.stream.bindings.customerInput.group=competence-customer
#
spring.cloud.stream.bindings.personInput.destination=personEventsTopic
spring.cloud.stream.bindings.personInput.group=competence-person`
```
and `application.properties` in tests code
```
spring.main.allow-bean-definition-overriding=true
spring.cloud.stream.bindings.customerInput.destination=customerEventsTopic
spring.cloud.stream.bindings.customerInput.group=competence-backend-customer
spring.cloud.stream.bindings.personInput.destination=personEventsTopic
spring.cloud.stream.bindings.personInput.group=competence-backend-person
```

and binding 

```
@Configuration
@EnableBinding({Processor.class})
public class MessagingConfiguration {
}
```

And the problem is when running spring cloud contract tests - which use the StreamListeners. The issue is that for some reason this setup works fine for personInput and it doesn't for customerInput. For tests I had to change the name of `    String CUSTOMER_INPUT = "customerInput";` to     `String CUSTOMER_INPUT = "customerEventsTopic";`  in order for message channel to be created correctly according to my settings, otherwise StreamListener method wasn't found at all. 

To make it funnier in production code after changing the property I mentioned above I get the similar problem - the stream listener wasn't invoked. So either prod code worked or test code worked. Again - all works fine for personInput but it doesn't work for customerInput. 

Finally I have written work around using EnableBinding with customer Processor for test with @Profile ("test") and similar configuration separately for prod code @EnableBinding @Profile("!test").

In spring cloud contract the name of the concrete destination in Kafka was used (customerEventsTopic).

Question:
Is there something wrong with my understanding of the base configuration, maybe an error in my configuration? How to make the setup consistent for all inputs and destinations?

**Comment by OlgaMaciaszek** [comment]
Looks like an issue within Spring Cloud Contract. Reopening.
