### ISSUE TITLE
Not all tests in spring-cloud-contract-stub-runner project are being executed.

### ISSUE THREAD

**Issue by boothen** [spring-cloud/spring-cloud-contract#1047]
Hi there,

It looks to me that only the StubRunnerJUnit5Extension tests are being executed during the build process for the spring-cloud-contract-stub-runner. I've verified this my checking the latest build good master build.

https://circleci.com/gh/spring-cloud/spring-cloud-contract/7118

The build output shows the following for spring-cloud-contract-stub-runner:

> [INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ spring-cloud-contract-stub-runner ---
> [INFO] 
> [INFO] -------------------------------------------------------
> [INFO]  T E S T S
> [INFO] -------------------------------------------------------
> [INFO] Running org.springframework.cloud.contract.stubrunner.junit.StubRunnerJUnit5ExtensionExceptionThrowingTests
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.05 s - in org.springframework.cloud.contract.stubrunner.junit.StubRunnerJUnit5ExtensionExceptionThrowingTests
> [INFO] should_throw_exception_when_no_message_verifier_was_passed_and_message_related_method_was_triggered  Time elapsed: 0.118 s
> [INFO] Running org.springframework.cloud.contract.stubrunner.junit.StubRunnerJUnit5ExtensionTests
> [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.703 s - in org.springframework.cloud.contract.stubrunner.junit.StubRunnerJUnit5ExtensionTests
> [INFO] should_start_WireMock_servers  Time elapsed: 0.112 s
> [INFO] should_output_mappings_to_output_folder  Time elapsed: 0.006 s
> [INFO] Running org.springframework.cloud.contract.stubrunner.junit.StubRunnerJUnit5ExtensionCustomMessageVerifierTests
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.477 s - in org.springframework.cloud.contract.stubrunner.junit.StubRunnerJUnit5ExtensionCustomMessageVerifierTests
> [INFO] should_use_provided_message_verifier_in_junit5_extension  Time elapsed: 0.03 s
> [INFO] Running org.springframework.cloud.contract.stubrunner.junit.StubRunnerJUnit5ExtensionCustomPortTests
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.429 s - in org.springframework.cloud.contract.stubrunner.junit.StubRunnerJUnit5ExtensionCustomPortTests
> [INFO] should_start_wiremock_servers  Time elapsed: 0.038 s
> [INFO] 
> [INFO] Results:
> [INFO] 
> [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0

There are numerous test classes in that project that don't seem to be executed. Is this by design?

I raise this as I'm looking to add a test case here that verifies a bug fix in another project, but unfortunately it doesn't get executed during the build.

**Comment by marcingrzejszczak** [comment]
Oh, that's a great catch! Thanks for pointing it out. I've just applied the fix

**Comment by marcingrzejszczak** [comment]
Fixed via 

- https://github.com/spring-cloud/spring-cloud-contract/commit/94062d5478877baf04de184ccf5c5a3cf77eb97e
- https://github.com/spring-cloud/spring-cloud-contract/commit/fabb3d6269ba4621aac13ec996d96ca398e19bd4
