### ISSUE TITLE
Spring Cloud Contract generates uncompilable test when multiline response body specified in contact

### ISSUE THREAD

**Issue by v-eshchelovanov** [spring-cloud/spring-cloud-contract#1049]
Hi!
I have a contract  with a response section like this
```
response {
    status OK()
    headers {
        contentType('application/x-research-info-systems;charset=UTF-8')
    }
    body("1\n2\n3\n")
}
```

Contract with multiline string (same goes for file) in the body will produce java test with compilation errors:

![image](https://user-images.githubusercontent.com/7442282/56431862-018b3580-62d4-11e9-8593-62fe7f3138a8.png)

I use spring cloud contract **2.1.1.RELEASE**

**Comment by mgoltzsche** [comment]
Same here also when using `bodyFromFile` (yaml format).
Is there any workaround?
_(This is a blocker for us since our project setup is now completely automated and contract-driven.)_

**Comment by marcingrzejszczak** [comment]
It's already fixed but not yet released. The release should take place fairly soon.
