### ISSUE TITLE
Does YML contract supports matcher for queryParameters? 

### ISSUE THREAD

**Issue by tony-haibo-zhu** [spring-cloud/spring-cloud-contract#1053]
I found there are some different matchers can be used in queryParameters in Groovy, but when I write some match expression in YML, it doesn't work. I wonder how to make matcher work for queryParamters in YML definition?

**Comment by marcingrzejszczak** [comment]
Check this out: https://github.com/spring-cloud/spring-cloud-contract/blob/2.1.x/spring-cloud-contract-verifier/src/test/resources/yml/contract_matchers.yml#L51-L71

**Comment by tony-haibo-zhu** [comment]
@marcingrzejszczak Thank you very much.
