### ISSUE TITLE
Enhancement - Metadata to identify consumer side of contract

### ISSUE THREAD

**Issue by springframeworkguru** [spring-cloud/spring-cloud-contract#1055]
Enhancement

In having a discussion with a team member, question came up, how does the producer know which consumer is defining the contract? 

For example, a producer will have X number of consumers, and N number of contracts. How does a producer know which contracts affect with consumers? 

We continued to the discussion around the properties on the contract. We thought it would be a nice enhancement to a property on the contract to identify the consumer (or consumers)

Just a string property, or maybe a list of strings to help ID the consumer side of the contract.

We reviewed label, description, and name - each seem to have other purposes. Hence the enhancement request.

**Comment by marcingrzejszczak** [comment]
We know it via the convention of folders. Please check out this project https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/master/producer_with_stubs_per_consumer/src/test/resources/contracts where each consumer has their own folder.

**Comment by springframeworkguru** [comment]
ah - good approach. 

I'm looking at it from the perspective of defining contracts in OA3. So, no folders.

**Comment by marcingrzejszczak** [comment]
You can push metadata to description and parse it

**Comment by springframeworkguru** [comment]
We did consider that too. Thought having a formal property could he useful for downstream tooling / documentation. 

My colleague @reardonm, is just waking up (Seattle). I'd like to get his input.

**Comment by reardonm** [comment]
Yeah, that should work out fine. It seems to me that metadata is really what the folder structure is providing anyway.

**Comment by marcingrzejszczak** [comment]
Yup. There are ways to do that. I'm closing the issue then.
