### ISSUE TITLE
Should not covert Chinese character in array of response body to unicode

### ISSUE THREAD

**Issue by tony-haibo-zhu** [spring-cloud/spring-cloud-contract#1064]

**Comment by tony-haibo-zhu** [comment]
When I write some Chinese character in an array of the contract response body, I got Unicode (for Chinese character, not letter or number etc.) in response from mock server. Then I debug in the source code, I found when the response body is an array, the spring contract will use JsonBuilder not JSONArray or JSONObject(just like in Map type). So I think it is a bug.     

Spring-contract-verifier version: 2.1.1.RELEASE
FileName: BaseWireMockStubStrategy.groovy
Line number: 196
Method name: toJson(String, ContentType)

**Comment by marcingrzejszczak** [comment]
Can you create a sample or a test that will replicate the issue, please? You can create a PR to branch `2.1.x` with a failing test and we can take over it (unless you have an idea how to fix it, then please apply a suggested solution).

**Comment by halucki** [comment]
I think this has related with  https://github.com/spring-cloud/spring-cloud-contract/issues/1038
