### ISSUE TITLE
Error stub when using file() and bodyMatchers in request

### ISSUE THREAD

**Issue by jiangtj** [spring-cloud/spring-cloud-contract#1065]
When I used `file()` and bodyMatchers in request as following:
```groovy
Contract.make {
    request {
        //....
        body(file('index.json'))
        bodyMatchers {
            jsonPath('$.name', byRegex(nonBlank()))
        }
    }
}
```
index.json
```json
{
  "name": "Jack"
}
```

When I exec `spring-cloud-contract-maven-plugin:convert`, and I found the stub like this:
```
"bodyPatterns" : [ {
      "matchesJsonPath" : "$[?(@.['name'] == 'Jack')]"
    }, {
      "matchesJsonPath" : "$[?(@.name =~ /(^\\s*\\S[\\S\\s]*)/)]"
    } ]
```

I want to accept all non-blank strings, but it has to be `Jack`.

**Comment by marcingrzejszczak** [comment]
Oh, nice catch! Which version of scc are you using?

**Comment by JiangTJ** [comment]
> Oh, nice catch! Which version of scc are you using?

2.1.1.RELEASE

**Comment by marcingrzejszczak** [comment]
Thanks, are the generated tests looking ok?

**Comment by JiangTJ** [comment]
Yeah, I think tests are ok.
![image](https://user-images.githubusercontent.com/15902347/56943824-cac6e200-6b53-11e9-8aca-70c21d18a497.png)

**Comment by erlkoing** [comment]
The issue is still present (3.0.2). The simple workaround I found is to use the `asString()` method.
`body(file('index.json').asString())`

**Comment by marcingrzejszczak** [comment]
Since we don't have the capacity to look into this problem in depth let's go with the provided workaround as the proper solution.
