### ISSUE TITLE
File handles are never released for discovered stub files

### ISSUE THREAD

**Issue by driabtchik** [spring-cloud/spring-cloud-contract#1075]
https://github.com/spring-cloud/spring-cloud-contract/blob/857da51950a87b393286e3bb1b2208c420c01087/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfiguration.java#L149

As a result, if new servers are created frequently (due to context refreshes), eventually running a substantial number of unit tests is running out of file handles, thus resulting in rather cryptic behavior.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/7d91bb61baf2eb952dc5a6e37db53a0bfc4ea91d
