### ISSUE TITLE
Wrong WireMock.defaultInstance when switching back to previous application context

### ISSUE THREAD

**Issue by oberlies** [spring-cloud/spring-cloud-contract#1081]
I have a test suite with tests that use two different `@SpringBootTest` configurations, say A and B. Due to its caching capabilities, the Spring test support will only create two application contexts, regardless of how many tests there are. Depending on the order in which test classes are executed, it may be that tests first use the contexts for A, then B, and then A again. In this situation, WireMock will not work for the tests that use A again because `WireMock.defaultInstance` always points to the `WireMock` instance belonging to the application context that was **last created**, not to the one belonging to the currently active application context.

The reason is that `WireMock.defaultInstance` is only updated on context creation, where `org.springframework.cloud.contract.wiremock.WireMockConfiguration.start()` is called, which in turn calls `updateCurrentServer()` and this calls `com.github.tomakehurst.wiremock.client.WireMock.configureFor(WireMock)`.

**Comment by oberlies** [comment]
I was able to work around this problem with a custom `TestExecutionListener`:

```
public class MyWireMockTestExecutionListener implements TestExecutionListener {
	private static final Logger LOGGER = LoggerFactory.getLogger(WireMockTestExecutionListener.class);

	@Override
	public void beforeTestClass(TestContext testContext) throws Exception {
		WireMockInstanceStore instanceStore = testContext.getApplicationContext().getBean(WireMockInstanceStore.class);

		if (instanceStore.get() != null) {
			// WireMock was started for this application context before; make this the (thread local) current instance in case a different application context was active in between
			WireMock.configureFor(instanceStore.get());
		} else {
			LOGGER.info("Detected a new application context; storing WireMock instance for this context");
			instanceStore.set(getConfiguredWireMockInstance());
		}
	}

	private static WireMock getConfiguredWireMockInstance() throws Exception {
		Field wireMockInstanceField = WireMock.class.getDeclaredField("defaultInstance");
		wireMockInstanceField.setAccessible(true);
		ThreadLocal<?> fieldValue = (ThreadLocal<?>) wireMockInstanceField.get(null);

		WireMock wireMockInstance = (WireMock) fieldValue.get();
		if (wireMockInstance == null) {
			throw new IllegalStateException("WireMock is not started");
		}
		return wireMockInstance;
	}
}
```
... and a simple helper to hold the `WireMock` instance:
```
@Component
public class WireMockInstanceStore {
	private WireMock wireMockInstance;

	public void set(WireMock wireMockInstance) {
		this.wireMockInstance = wireMockInstance;
	}

	public WireMock get() {
		return wireMockInstance;
	}
}
```

This listener (or something similar) should probably be part of the library.

**Comment by oberlies** [comment]
BTW, I'm not running into the [documented port limitation](https://cloud.spring.io/spring-cloud-static/spring-cloud-contract/1.2.4.RELEASE/single/spring-cloud-contract.html#_limitations) – I just get a separate random random port per application context. This works because `org.springframework.cloud.contract.wiremock.WireMockApplicationListener.registerPort(ConfigurableEnvironment)` runs once per application context.

**Comment by OlgaMaciaszek** [comment]
Hi @oberlies ; would using `@DirtiesContext` help here? I know it's not the best thing to do, but it would be helpful to know if that solves the issue or not.

**Comment by oberlies** [comment]
No, `@DirtiesContext` doesn't help. The `WireMock.defaultInstance` still always points to the instance of the last created `ApplicationContext`.
