### ISSUE TITLE
Provide a hook that allows docker verifier image to generate stubs without verifying them against the the producer

### ISSUE THREAD

**Issue by wkorando** [spring-cloud/spring-cloud-contract#1085]
Enhancement

Currently the Docker contract verifier image always tests contracts against the producer before generating the stubs. While often this behavior is desirable, it also means that a client/consumer won't have the stubs available to develop/test against until at least part of the service has been written. 

Allowing an environment variable to be passed in that allows a client/consumer to create contracts and generate stubs without verifying them against the producer can allow client/consumer developers the ability to work asynchronously with producers.

**Comment by OlgaMaciaszek** [comment]
Hi @wkorando I remember we talked about it during Spring I/O :) , but we already have this enhancement in the backlog: https://github.com/spring-cloud/spring-cloud-contract/issues/881 I guess that would address your issue?

**Comment by wkorando** [comment]
Hmmm yea, I think actually makes more sense from the perspective of a consumer as well as. I'll go ahead and close this ticket as that suggested enhancement makes more sense than my own. Thanks for the response!
