### ISSUE TITLE
spring-cloud-contract-maven-plugin: convertToYaml ignores queryParameters

### ISSUE THREAD

**Issue by abadelt** [spring-cloud/spring-cloud-contract#1086]
Hi,

I have a several contracts defined in groovy files, each contract having urlPath with an individual list of queryParameters.
Like this:
```groovy
org.springframework.cloud.contract.spec.Contract.make {
    request {
        method 'GET'
        name('Some request variant 1')
        urlPath('/resourcexyz') {
            queryParameters {
                parameter 'someParam': 'someValue'
            }
        }
    }
    response {
      ...
    }
}
```
When I create contracts using the spring-cloud-contract-maven-plugin (2.1.0 or 2.1.1) with 
convertToYaml set to true, the generated YAML files in the stubs jar will _not_ contain any queryParameter definitions. Subsequently, client tests using the stubs will not match requests properly (i.e. including the queryParameter matchers). 
Turning off convertToYaml in the POM will (obviously) not create any YAML files, hence the stubs will be based on the original groovy definition, and everything works as expected.

Is this a bug, or am I missing something?

Best regards,
Andreas

**Comment by OlgaMaciaszek** [comment]
Hi, @abadelt thanks for reporting it. I was able to reproduce it and it's a bug that we'll have to fix.
