### ISSUE TITLE
MissingMethodExceptionNoStack at creating assertion for spock test

### ISSUE THREAD

**Issue by artemptushkin** [spring-cloud/spring-cloud-contract#1089]
Hi!

I m using:
SCC version: 2.1.1.RELEASE,
spockVersion: 1.0-groovy-2.4
jdk 8
testFramework = SPOCK

Failed running a generated test from the contract:
```
...
bodyMatchers {
            jsonPath('$.cards[*].cardType', byRegex('[A-Z]{2}'))
}
....
```
My JSON looks like:
```
{
 "cards": [
   {
     ....
     "cardType": "AT",
     ...
    }
  ]
}
```
Relevant generated code section:
```
assertThat((java.lang.Iterable) parsedJson.read("\$.cards[*].cardType", java.util.Collection.class)).as("\$.cards[*].cardType").allElementsMatch("[A-Z]{2}")
```

I have an error at run generated test: `org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: org.assertj.core.api.ListAssert.allElementsMatch() is applicable for argument types: (java.lang.String) values: [[A-Z]{2}]`

The issue is in first `assertThat..` call, because the result is - ListAssert object but should be `springframework..contract...CollectionAssert`

When I debug I see an appropriate class (SpringCloudContractAssertions) to make `staticCall` but at last I got breakpoint at `org.assertj.core.api.Assertions - assertThat(List<?...) - 2662 (v. 3.11.1)`
![image (1)](https://user-images.githubusercontent.com/22632802/58561853-c7954380-8230-11e9-8171-1bd50aece07b.png)
Expected: at `SpringCloudContractAssertions - assertThat(Iterable<?..)`

I found at the documentation of `assertj..Assertions` class that they had such an issue with static and generics. As the result they created new classes for _class_ input and for the _interface_. See [assertj doc](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/Assertions.html)
Running under jdk 7 jdk 12 - same error

I think a solution for this issue is the same with https://github.com/spring-cloud/spring-cloud-contract/issues/1067

**Comment by OlgaMaciaszek** [comment]
Hi @hustleone Looks like a bug. Thanks for reporting it.

**Comment by hustleone** [comment]
I found that it is kind of Spock bug.
Works fine:
```
SpringCloudContractAssertions.assertThat(collection).allElementsMatch("account.*")
```
But this one goes with bug:
```
when:
		Collection collection = collectionWithNulls();

		then:
		SpringCloudContractAssertions.assertThat(collection).allElementsMatch("account.*")
```

I have a test case and can fix it, I'll open PR
