### ISSUE TITLE
Issue with empty urlPath with contract 2.1

### ISSUE THREAD

**Issue by witchedwiz** [spring-cloud/spring-cloud-contract#1094]
Long story short.
With spring-cloud-contract 2.0 you could supply an empty urlpath parameter in the json stub and in this condition the requestmapper would be built based on 

```
private String request(RequestPattern request) {
		return this.baseUrl + (request.getUrlPath() == null ? (request.getUrl() == null ? "/" : request.getUrl()): request.getUrlPath());
	}
```

As of 2.1 instead the SAME stubs are not working anymore, as this change was introduced while setting the expectancy of the stubs:
```
	private ResponseActions responseActions(MockRestServiceServer server, StubMapping mapping) {
		if (StringUtils.hasText(mapping.getRequest().getUrl()) || StringUtils.hasText(mapping.getRequest().getUrlPath())) {
			return server.expect(requestTo(request(mapping.getRequest())));
		}
		return server.expect(requestTo(requestMatcher(mapping.getRequest())));
	}
```
This makes it so that whereas the OLD behavior was "if empty urlpath is provided in the stub, the baseurl provided during the istantiation of the wiremock is used and then the emptystring is "added" at the end." the new behavior is "if empty//non-existing urlpath is provided in the stub AND empty//non-existing url is provided in the stub, provide a patternmatcher that will match exactly the stub, meaninng "" , else go with the old behavior "

This creates a breaking change whereas previously you could supply empty urlpath and the matching will work like a charm, now those stubs no longer works as the matcher will attempt matching towards "" url whereas the call will be towards the "baseurl". If the call has any get parameters for example this is unaffected and works like before.

Is this a breaking change introduced willingly or this is just an aftereffect introduced without taking into consideration the way stubs pattern matching worked previously?

Thanks,
Vito

**Comment by marcingrzejszczak** [comment]
That change was introduced via https://github.com/spring-cloud/spring-cloud-contract/issues/740

Can you elaborate exactly on your usecase? Or show us a test where this approach is no longer valid?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
