### ISSUE TITLE
execute doesn't work in URL

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#11]
_From @jakubnabrdalik on July 5, 2016 13:21_

In my contract I do "get" on a resource, but I have no hard-coded id. I need to have a generated id (object created before test and saved to mongo) so I can run tests concurrently without interference. During runtime the id is available in the base class, but I cannot hardcode it in the contract Groovy. So in other words, I need to execute a method, in URL part, like this:

```
org.springframework.cloud.contract.spec.Contract.make {
    request {
        method 'GET'
        url $(client(regex('/api/articles/.*')), server(execute('getArticleId()')))
        headers {
            header 'Content-Type': 'application/json;charset=UTF-8'
        }
    }

```

But instead of creating a call to getArticleId() this snippet generates a toString on ExecutionProperty, like so:

```
def validate_shouldFetchArticle() throws Exception {
        given:
            def request = given()
                    .header('Content-Type', 'application/json;charset=UTF-8')

        when:
            def response = given().spec(request)
            .get("org.springframework.cloud.contract.spec.internal.ExecutionProperty@26d445e9")
```

Can you make it possible to use "execute" in url as well? The documentation doesn't give that example but also suggests it should be possible.

_Copied from original issue: Codearte/accurest#292_

**Comment by fallflame** [comment]
I have the same issue, with version 1.0.3.RELEASE

**Comment by marcingrzejszczak** [comment]
Hmm I guess I haven't fixed this... That's unfotunate. I'll try to fix it tomorrow and it should be ready for Dalston M1.
