### ISSUE TITLE
Lack of support for password protected repositories with stubs

### ISSUE THREAD

**Issue by yacekmm** [spring-cloud/spring-cloud-contract#110]
I upload stubs to the password protected nexus repository. In the client app, there is currently no way of providing the credentials and downloading such stubs.

Suggestion: I have those repositories defined in my `build.gradle` file with passwords (protected in separate variables). Could this setup be reused in Cloud Contract?

**Comment by marcingrzejszczak** [comment]
We're using Aether underneath to download the jars. Assuming that I've found the proper doc it's enough to put the username and pass in settings.xml https://wiki.eclipse.org/Aether/Ant_Tasks#Authentication

**Comment by marcingrzejszczak** [comment]
If that doesn't work you actually in the Stub Runner can provide that the repository root is `classpath://mappings/` . That way you can point to the stubs from your `build.gradle`. That should work I think :)

**Comment by yacekmm** [comment]
`repositoryRoot = "classpath://mappings"` gives me `FileNotFoundException: class path resource [mappings] cannot be resolved to URL because it does not exist`

had no enough time to test settings.xml in m2 directory, but after first tries i still get 401 from nexus. I'll try later as well, now the end of sprint is chasing me :)

**Comment by marcingrzejszczak** [comment]
Yeah it seems that we have to modify `org.springframework.cloud.contract.stubrunner.AetherFactories#newRepositories` to contain this http://git.eclipse.org/c/aether/aether-demo.git/tree/aether-demo-snippets/src/main/java/org/eclipse/aether/examples/aether/Aether.java?id=52f81d2904801458f9ce317f16f4f71d585838a8#n102 ; in other words sth like this:

```
 Authentication auth = new AuthenticationBuilder().addUsername( "admin" ).addPassword( "admin123" ).build();
        RemoteRepository nexus =
            new RemoteRepository.Builder( "nexus", "default", remoteRepository ).setAuthentication( auth ).build();
```

**Comment by mogronalol** [comment]
This actually looks trickier than I thought to test.  I took a quick look but realised I didn't know how to modify the existing test repositories so they become authenticated... Any ideas?

**Comment by marcingrzejszczak** [comment]
Good question. I'd do a manual test cause I have no good idea how to simulate an encrypted repo.

**Comment by mogronalol** [comment]
You know one option would be to do a test against a real encrypted repo, get it to pass, and then use hoverfly to record the test and play it back in future runs. I wrote a blog post about something similar with simulating github auth2:

https://opencredo.com/simulating-github-oauth2-login-junit-webdriver-hoverfly/

What do you think? Shouldn't be too hard to implement...

**Comment by marcingrzejszczak** [comment]
Sounds like a good idea. I wonder if it's worth it. If you think it won't take much time let's try it. I'd timebox it though.

**Comment by yacekmm** [comment]
ok, so after those changes, finally how can I download stubs from password protected repo?

**Comment by marcingrzejszczak** [comment]
It's not yet done. You have to ask @mogronalol to speed this up ;)

**Comment by yacekmm** [comment]
Well I'm still waiting for this fix... I'm not able to use Spring Cloud Contract in CI until this is not enabled. @mogronalol - please :)

It would also be good if I could externalize the login and password from the source code to non-versioned files or spring properties. To prevent commiting it to the repo with the code.

**Comment by marcingrzejszczak** [comment]
Ok I'll try to take a look at this then myself ;)
