### ISSUE TITLE
Quotes at the attribute value of xml body

### ISSUE THREAD

**Issue by artemptushkin** [spring-cloud/spring-cloud-contract#1104]
Hello!

I found that **rest-assured** awaits double quotes at the attribute values of the XML body section.

Example XML body:
```
...
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
...
```
Request part of the contract:
```
...
body(
                $(
                        consumer(
                                ....
                        ),
                        producer(
                                file('__files/offer13-request.xml').asString()
                        )
                )
        )
```
Response:
```
...
javax.xml.stream.XMLStreamException: The value of attribute "xmlns:soapenv" must begin with either a single or double quote character.
...
```

If change double quotes to single quote everything is ok.
There is not about quotes at [the relevant documentation part](https://cloud.spring.io/spring-cloud-contract/single/spring-cloud-contract.html#_xml_support_for_rest) but you can guess by the doc example.

I think it should be added to the doc or to handled in some way

**Comment by OlgaMaciaszek** [comment]
Hello, @artemptushkin I was not able to reproduce the bug using the code snippets you have presented. 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue, as a GH sample link or a .zip file.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by artemptushkin** [comment]
Sorry, cannot reproduce also... maybe something other was wrong
