### ISSUE TITLE
:1:1: Content is not allowed in prolog for the xml body

### ISSUE THREAD

**Issue by artemptushkin** [spring-cloud/spring-cloud-contract#1105]
Hi!

I try to create a request body in this way:
```
body(
                file('__files/offer13-request.xml')
        )
```
But I get:
```
...:1 ..:1: Content is not allowed in prolog
```
Everything is ok in the way with _equalToXml_:
```
body(
			equalToXml(
				file('AKJUZB-request.xml')
			)
		)
```
I found that at the [XmlToXPathsConverter](https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/xml/XmlToXPathsConverter.groovy)

```
Document parsedXml = documentBuilder
            .parse(new InputSource(new StringReader(body as String)))
```
Here `body as String` calls toString() of FromFileProperty class and there is an irrelevant result. There is should be called asString() inside toString(). I think i'll open a suggestion PR

**Comment by marcingrzejszczak** [comment]
Which version are you using? Can you create a test that replicates this problem and then a fix that fixes it? Thanks!

**Comment by hustleone** [comment]
2.1.1.RELEASE
Yes, I'll start with a test

**Comment by marcingrzejszczak** [comment]
Fixed by https://github.com/spring-cloud/spring-cloud-contract/commit/b46463e0d38a026ec45340d96011191f0e20a504
