### ISSUE TITLE
bodyMatchers - minOccurrences failing with SimpleObjects List. 

### ISSUE THREAD

**Issue by kszosze** [spring-cloud/spring-cloud-contract#1108]
We are trying to implement contracts for list of objects which contains a list of basic objects (Integer) we just saw that having something like
``` groovy
body([
            [
               listNumbers: [
                   50, 100, 150, 200, 300, 1000
              ],
           ]
       ])
       bodyMatchers {
            jsonPath('$[*].listNumbers[*]', byRegex(positiveInt()))
            jsonPath('$[*].listNumbers', byType {
                minOccurrence(0)
            })
        }
```
is generating
```groovy
assertThat((java.lang.Iterable) parsedJson.read("$[*].listNumbers[*]", java.util.Collection.class)).as("$[*].listNumbers[*]").allElementsMatch("([1-9]\\d*)");
assertThat((Object) parsedJson.read("$[*].listNumbers")).isInstanceOf(java.util.List.class);
assertThat((java.lang.Iterable) parsedJson.read("$[*].listNumbers", java.util.Collection.class)).as("$[*].listNumbers").hasFlattenedSizeGreaterThanOrEqualTo(0);
```
which fail for whatever minOcurrence greater than 0 since counter in the implementation is never update if we have an simple list of objects..
```java
private int flattenedSize(int counter, Object object) {
		if (object instanceof Map) {
			return counter + ((Map) object).size();
		}
		else if (object instanceof Iterator) {
			Iterator iterator = ((Iterator) object);
			while (iterator.hasNext()) {
				Object next = iterator.next();
				counter = flattenedSize(counter, next);
			}
			return counter;
		}
		else if (object instanceof Collection) {
			return flattenedSize(counter, ((Collection) object).iterator());
		}
		return counter;
}
```
May be I miss a call to the _size(Iterable iterable)_ function.

But if we just have
```groovy
 body(
         [
              listNumbers: [
                  50, 100, 150, 200, 300, 1000
               ],
                ]
        )
        bodyMatchers {
            jsonPath('$.listNumbers[*]', byRegex(positiveInt()))
            jsonPath('$.listNumbers', byType {
                minOccurrence(0)
            })
        }
```
we got 
```groovy
assertThat((java.lang.Iterable) parsedJson.read("$.listNumbers[*]", java.util.Collection.class)).as("$.listNumbers[*]").allElementsMatch("([1-9]\\d*)");
assertThat((Object) parsedJson.read("$.listNumbers")).isInstanceOf(java.util.List.class);
assertThat((java.lang.Iterable) parsedJson.read("$.listNumbers", java.util.Collection.class)).as("$.listNumbers").hasSizeGreaterThanOrEqualTo(0);
```
which works more better with values greater than 1, in fact it works.

So we are a bit lost about if the actual behaviour is the expected one or there is a bug but it's like a bit frustrating trying to understand why this behaviour.

Nowadays we found this is happening with Spring Cloud Versions 2.0.4.RELEASE and 2.1.1.RELEASE, so looks like is the expected way to be? is this is true, how we can achieve to get a contract as we want, have the same validation expresion for a return object and a list of objects of the same type.
Kind Regards.

**Comment by OlgaMaciaszek** [comment]
Hello @kszosze Please provide example of bodies that this endpoint returns. If the json you return, looks like this:
```[json]
{
    "listNumbers": [
        50,
        100,
        150,
        200,
        300,
        1000
    ]
}
```, the jsonPath `$[*].listNumbers[*]`  is not matched to any element.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by kszosze** [comment]
Of course not. because you are wrong with the example.
{code}
{
 [
    "listNumbers": [
        50,
        100,
        150,
        200,
        300,
        1000
    ]
]
}
{code}
This is the one which match the issue and the jsonpath expression you put.

**Comment by OlgaMaciaszek** [comment]
Ok. Will have a look at it tomorrow.

**Comment by OlgaMaciaszek** [comment]
Passing the `json` above causes `ParseException` to be thrown from [Jayway JsonPath parser ](https://github.com/json-path/JsonPath), so executing the test with it would cause it to fail before reaching the line in question. 
Do you mean something like the `json` below, instead?
```[json]
{
    "objects": [
        {
            "listNumbers": [
                50,
                100,
                150,
                200,
                300,
                1000
            ]
        }
    ]
}
```
If not, please provide a sample controller endpoint method code that can be used to replicate the problem or a correct `json` String that we can use to replicate the issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by kszosze** [comment]
I was using example from DSL groovy contracts in that case my example is correct, a list of elements which contains a property which is a list. If you want a plain JSON example
```
[
    "listNumbers": [
        50,
        100,
        150,
        200,
        300,
        1000
    ]
]
```
this one should do the trick

**Comment by OlgaMaciaszek** [comment]
@kszosze a json with only the excerpt you put above will not be parsed correctly either; please pass the entire plain json that your endpoint is returning, so that we can test with it.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by kszosze** [comment]
Ok, let's gonna start from the start.. 
I'm creating contracts using groovy dsl not a json file.. so the code snippet I'm using is the right one which is wrongly parsed.
As you know the Spring Contracts project, convert the groovy definition into a Json stream with is parsed and verify. So is my believe that the problem is in the flattenedSize function I pasted before.

**Comment by marcingrzejszczak** [comment]
Hey @kszosze, can you please send what @OlgaMaciaszek asked you for? We need to see the json that you're endpoint returns in the test.

**Comment by kszosze** [comment]
something like that,
```
[
    {
        "id": 45,
        "listnumbers": [
            10,
            30,
            50,
            60
        ]
    },
    {
        "id": 49,
        "listnumbers": [
            20,
            40,
            60,
            80
        ]
    },
    {
        "id": 50,
        "listnumbers": [
            5,
            15,
            25,
            35
        ]
    },
    {
        "id": 60,
        "listnumbers": [
            6,
            26,
            36,
            46
        ]
    }
]
```

**Comment by marcingrzejszczak** [comment]
Ok, thanks.

> which fail for whatever minOcurrence greater than 0 since counter in the implementation is never update if we have an simple list of objects..

What's the stacktrace?

**Comment by kszosze** [comment]
There is not a stacktrace. The test fail because the condition fail if you put something different than 0.

**Comment by marcingrzejszczak** [comment]
Ok I'll need a sample to replicate this. Could you create a small one please?

**Comment by kszosze** [comment]
You mean a project that generate this JSON (no i have one to share right no) or a Contract in DSL as I already share from the start ( I can share a more complete one )

**Comment by marcingrzejszczak** [comment]
We need to replicate the issue you have. We need to have the DSL that generates the test, your plugin setup, the controller that returns the aforementioned JSON and the base class for your tests.

**Comment by kszosze** [comment]
Well that gonna take a bit of time so I need to recreate it just for you. Actual problem came at work I cannot disclosure the code, as you understand. But I'll try to recreate it asap.

**Comment by marcingrzejszczak** [comment]
Great, that will be extremely helpful, thank you.

**Comment by kszosze** [comment]
OK, I manage to adapt an existing project of mine in order to replicate the issue.. more or less.. here I'm using latest version in order to test contracts with collections of elements.
https://github.com/kszosze/rock_game
There are two contracts created for that case and both are failing. 
Cheers

**Comment by kszosze** [comment]
Hello there, any feedback about?

**Comment by OlgaMaciaszek** [comment]
Hi @kszosze  thanks - will have a look.

**Comment by OlgaMaciaszek** [comment]
Ok, I see which issue you mean now. Yes, looks like a bug. We'll provide a fix. Thanks.

**Comment by OlgaMaciaszek** [comment]
Actually, we should not use `hasFlattenedSizeGreaterThanOrEqualTo()` here at all, since the jsonPath points to the `stats` element and not `stats[*]`. So actually, for the example code you have provided, we should verify that the number of `stats` occurrences is greater than 1, which indeed it is, as there are 3 `stats` occurrences in the produced json.

**Comment by OlgaMaciaszek** [comment]
If you want to get `minOcurrence` for all the elements of the `stats` array, then I assume the right jsonPath would be `stats[*]` - granted, this also does not work properly at the moment. We'll be fxing this as well.

**Comment by OlgaMaciaszek** [comment]
After further analyzing it, I don't think we should use `hasFlattenedSize` at all. It should be up to the user to point to the correct element, either list (`$[*].stats`) or all its elements (`$[*].stats[*]`), or particular named elements (`$[*].stats[*].statA`) to verify the min/max ocurrence for.

**Comment by OlgaMaciaszek** [comment]
Nevertheless, this functioning of the method has been documented:
```

**Comment by kszosze** [comment]
Thank you!!!
