### ISSUE TITLE
Version 2.1.2 not in gradle plugin portal

### ISSUE THREAD

**Issue by bjartek** [spring-cloud/spring-cloud-contract#1114]
https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-contract-verifier lists 2.1.2 as released

https://plugins.gradle.org/plugin/org.springframework.cloud.contract says that 2.1.1 is the latest version. 

Please upload the release to gradle plugin portal.

**Comment by marcingrzejszczak** [comment]
@szpak any ideas what could go wrong?

**Comment by marcingrzejszczak** [comment]
Uploaded the latest version manually

**Comment by szpak** [comment]
Your commit looks ok ;)
