### ISSUE TITLE
fixedDelayMilliseconds with restTemplate is not working

### ISSUE THREAD

**Issue by theburhan** [spring-cloud/spring-cloud-contract#1118]
I have the following contract with fixedDelayMilliseconds

```
Contract.make {
    request {
        method POST()
       body('{"key":"hellow"}')
        url '/gateway/rest/hellow'
    }
    response {
        status 200
        headers {
            contentType 'application/json'
        }
       
        fixedDelayMilliseconds 5000
    }
}
```
when I try curl command then it exactly respond in 5 seconds, however when I use RestTemplate then I get the response immediately, thus I cannot test my contract against Hystrix timeout. 

```
curl -X POST \
  http:///localhost:8008/gateway/rest/hellow \
  -d '{
        "key": "hellow"
}'
```

**Comment by marcingrzejszczak** [comment]
Hmm it has nothing to do with Spring Cloud Contract. Are you sure you've setup the RestTemplate timeouts properly? Or are you saying that you get the correct response from the WireMock stub immediately?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
