### ISSUE TITLE
Wiremock @Value property injection: Could not resolve placeholder 'wiremock.server.port' in value "${wiremock.server.port}"

### ISSUE THREAD

**Issue by yarodinD** [spring-cloud/spring-cloud-contract#1126]
With Spring boot 2.1.6 and spring-cloud-dependencies Greenwich.SR1 (including spring-cloud-starter-contract-stub-runner 2.1.1), this worked:

```java
@Configuration
public class TestConfiguration {  // in src/it/java

     @Bean
     @Primary
     public MyGateway(@Value("${wiremock.server.port}") String wiremockport) {
           ....
     }
}

// in test class:
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureWireMock(port = 0, stubs = "classpath:/wiremock-stubs")
class MyIntegrationTestIT {
....
}

```
During integration tests, the default `MyGateway` from the service is replaced by the one from `TestConfiguration` class which gets the wiremock.server.port injected as a `@Value` property.

With the upgrade to Spring cloud spring-cloud-dependencies to Greenwich.SR2, I get the error: 
```
java.lang.IllegalArgumentException: Could not resolve placeholder 'wiremock.server.port' in value "${wiremock.server.port}"
```
As a workaround, I can inject the Environment to the `TestConfiguration` class an call `environment.getProperty("wiremock.server.port")`, which works as shown below:

```java
@Configuration
public class TestConfiguration {  // in src/it/java

     @Autowired
     private Environment environment;

     @Bean
     @Primary
     public MyGateway() {
           ....
           environment.getProperty("wiremock.server.port")
     }
}
```

Still, this is a breaking change in my case and I couldn't find anything related in the change logs.

**Comment by OlgaMaciaszek** [comment]
Hello, @yarodinD - thanks for reporting the issue. Unfortunately, I was not able to reproduce this. Could you please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by yarodinD** [comment]
Hello @OlgaMaciaszek .
I do have a real project where the described behavior is reproducible when changing Spring Cloud from Greenwich.SR1 to SR2. 
However, I was not able to reproduce it in a minimal project. Maybe some weird combination of other libraries.... However, since I can't provide a simple example for now, I'll close the ticket.

If I should stumble over this behavior again, I'll reopen it.
For now, thank you for your effort.

**Comment by SergeantGrumbles** [comment]
For the record, I have this in a gradle multi module project and the absence of `org.springframework.boot:spring-boot-test-autoconfigure` from the class path for that particular module meant the properties were not resolved when the test executed.

Fixed by including a dependency on `org.springframework.boot:spring-boot-test-autoconfigure`.

Note that the dependency `org.springframework.boot:spring-boot-test` contains the `SpringBootTest` annotation and will allow the test to execute with a Spring context but the autoconfigure dependency is enabling the property resolution.
