### ISSUE TITLE
Uses stubs downloaded from custom repository, but resolver can't find maven-metadata.xml

### ISSUE THREAD

**Issue by Sloloem** [spring-cloud/spring-cloud-contract#1128]
I'm trying to setup the stub runner without duplicating any configuration, IE I don't want to explicitly include the repo URL in my test code as well as the maven POM file.  So I'm trying to use LOCAL StubMode:

`    @ClassRule
    public static StubRunnerRule rule = new StubRunnerRule()
            .stubsMode(StubRunnerProperties.StubsMode.LOCAL)
            .downloadStub("com.company.otherservice", "OtherService")
            .withPort(10550);`

So I've actually setup maven to download the stubs as a test-scope dependency to make sure they end up in the local M2 before the tests run.

`        <dependency>
            <groupId>com.company.otherservice</groupId>
            <artifactId>OtherService</artifactId>
            <version>${otherservice-domain-version}</version>
            <scope>test</scope>
            <classifier>stubs</classifier>
            <exclusions>
                <exclusion>
                    <artifactId>*</artifactId>
                    <groupId>*</groupId>
                </exclusion>
            </exclusions>
        </dependency>`

Unfortunately the custom repository my company uses creates a maven metadata file named "maven-metadata-customrepo.xml" instead of the "maven-metadata.xml" the resolver looks for so I always get the error:

`java.lang.IllegalArgumentException: For groupId [com.company.otherservice] artifactId [OtherService] and classifier [stubs] the version was not resolved! The following exceptions took place [org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata com.company.otherservice:OtherService/maven-metadata.xml in local (C:\Users\ME\.m2\repository), org.eclipse.aether.transfer.MetadataNotFoundException: Cannot access remote0 (file:/C:/dev/checkouts/thisservice/ThisService/web/target/test-classes/) in offline mode and the metadata com.company.otherservice:OtherService/maven-metadata.xml has not been downloaded from it before]`

If I don't have this setup wrong and the stubrunner could be made to do this, I guess this is a feature ask...otherwise it's mostly an implementation question I wasn't able to discern from the documentation.

Is there a proper way to configure the stub runner to use local M2 so I don't need the entire repo URL in there but allow for some variability with the metadata XML filename?  Or if I need to, pass that repo ID to the resolver?

Is there some way to get maven to save the metadata file with the generic name?

Is it possible to use the remote repo without duplicating the URL configuration that I just haven't seen?

Thanks

**Comment by marcingrzejszczak** [comment]
Hmm I didn't know that you can have a different file for the maven-metadata.xml. If you know how to set up Maven as such to look at that file then we can tweak stub runner (or Aether) to search for that.

**Comment by Sloloem** [comment]
Seemingly if you include a <repositories> section in your project's POM file, maven will tag the file in local M2 with the ID.  I was kindof hoping I was just missing something and could tweak my setup to fix the naming or something.  As far as debugging through the StubRunner code, the last place I see the filename is as a constant in DefaultVersionRangeResolver that sets that into a MetadataRequest object for DefaultMetadataResolver, but haven't debugged any further to see if there's a way to wildcard it.

resolver-status.properties file seems created by the Maven Resolver automatically and shows all the maven-metadata-repo-.xml files with when they were last updated.  IE `maven-metadata-snapshots.xml.lastUpdated=1562175927133`

_remote.repositories also includes the most recent version of each artifact downloaded from each repository and can be used to reconstruct the name.  IE `OtherService-1.4.7-20190703.165743-43-stubs.jar>snapshots=` can point to maven-metadata-snapshots.xml

**Comment by marcingrzejszczak** [comment]
SC-Contract is delegating the work to Aether. Maybe there's an option there to configure this?

**Comment by Sloloem** [comment]
Unfortunately I'm just not familiar with the inner workings here or where the boundary between projects is.  I can go run off to another github and create a linked issue if you point me at the right one?

**Comment by marcingrzejszczak** [comment]
I think Aether needs to be debugged. Currently I won't have time to do that but be my guest if you have some spare time. You can just continue debugging as you started and continue through `org.springframework.cloud.contract.stubrunner.AetherStubDownloader`

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Sloloem** [comment]
For posterity and wayward google searches:  Since aether has not been updated in quite some time and no longer seems active it would be far too much effort to update it to stop using the hardcoded "maven-metadata.xml" everywhere it's specified.  You can use maven to automatically resolve the stubs instead of duplicating the repo URL.

1. Include the stubs jar in the test scope via pom.xml
2. Configure the StubRunnerRule using CLASSPATH StubMode
3.  Upgrade Cloud Contract to 2.1.2.RELEASE/2.2.0.RELEASE or later, there is a bug in earlier versions of StubRunnerRule that fails to properly set the classpath to scan to include the default classpath.
