### ISSUE TITLE
Wiremock config options

### ISSUE THREAD

**Issue by ati90ati** [spring-cloud/spring-cloud-contract#1136]
Hello,
There is a possibility to easily configure additional Wiremock option configs?

I had some problems with some Wiremock options described in the above comments:
https://github.com/tomakehurst/wiremock/issues/914#issuecomment-474269973
https://github.com/tomakehurst/wiremock/issues/914#issuecomment-474347034

I succeed to configure some options on the `Options` bean but in this I lost all the default configs what are configured by the spring cloud contract.

```
@Configuration
public class WiremockConfig {

    @Bean
    public Options wiremockOptions() {
        final com.github.tomakehurst.wiremock.core.WireMockConfiguration wireMockConfiguration = WireMockSpring
                .options();

        wireMockConfiguration.useChunkedTransferEncoding(Options.ChunkedEncodingPolicy.BODY_FILE);
        wireMockConfiguration.port(12345);

        return wireMockConfiguration;
    }

}
```

Maybe if a solution can be found to this issue would be great.

Suggestion solutions:
 * config can be via specific annotations for options
 * or via properties in the application.properties file
 * or via auto-wire somehow the default Options bean from spring cloud contract.

**Comment by marcingrzejszczak** [comment]
Would this help?https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfigurationCustomizer.java

**Comment by ati90ati** [comment]
`WireMockConfigurationCustomizer` is great!

I succeeded to use it and configure the options.

```java
@Configuration
public class WiremockConfig {

    @Bean
    public WireMockConfigurationCustomizer wireMockConfigurationCustomizer() {
        return config -> config.useChunkedTransferEncoding(Options.ChunkedEncodingPolicy.BODY_FILE);
    }
}
```

Thank you very much!
