### ISSUE TITLE
Message Verifier for JMS / ActiveMQ

### ISSUE THREAD

**Issue by tomcastro89** [spring-cloud/spring-cloud-contract#1141]
Follow up to:
https://stackoverflow.com/questions/57184249/consumer-driven-contract-testing-with-spring-jms-and-activemq/57204775?noredirect=1#comment100937079_57204775

> Thanks Tommaso! So you got the idea perfectly! From what I see you're using standard mechanism of sending and receiving the JMS messages. It means that you require the e.g. ActiveMQ to be running there in memory, right? I'm not saying that's wrong, but I wonder if we can somehow work this around (as we do with rabbitmq). BTW can you please file a PR to the master branch of Spring Cloud Contract and we can continue the discussion there? Also we're in progress of changing the docs so don't add them just yet

For the tests we decided to use ActiveMQ in-memory, if you can work something out that makes the in-memory ActiveMQ broker obsolete that would be fine too.

Mentioned repo:
https://github.com/tomcastro89/seat-reservervation-active-mq

**Comment by marcingrzejszczak** [comment]
Hey @tomcastro89 . I don't have a better IDEA atm ;) Care for a PR with what you did? :)

**Comment by tomcastro89** [comment]
Sure, but i don't know what you need and how to integrate it.
Should i just add the JmsMessageVerifier as an example in some example folder?

**Comment by marcingrzejszczak** [comment]
I needed to add some additional integration. Anyways, with https://github.com/spring-cloud/spring-cloud-contract/commit/c7b4f0125bcb11e34e4119be136495aba7de4ff0 it seems that the JMS integration is working fine!
