### ISSUE TITLE
RestDocs should use JSON matching with JSON Content-type

### ISSUE THREAD

**Issue by Kaali** [spring-cloud/spring-cloud-contract#116]
spring-cloud-contract-wiremock RestDocs stub generator uses WireMock equalTo matcher for JSON instead of equalToJson. Which makes the stubs near unusable as different applications can generate completely different JSON for the same data.

It would be nice if WireMockSnippet would check the Content-type and generate the request matcher accordingly.

**Comment by patrice-conil** [comment]
Hi,
+1 for me.
This enhancement will be of a great help.
Patrice
