### ISSUE TITLE
Wrong log warning "You've used fixed ports for WireMock setup"

### ISSUE THREAD

**Issue by robeatoz** [spring-cloud/spring-cloud-contract#1160]
Hi!

In the Spring Cloud Contract sample `consumer_with_junit5`, I recognized the following log message:

```
You've used fixed ports for WireMock setup - will mark context as dirty. Please use random ports, as much as possible. Your tests will be faster and more reliable and thiswarning will go away
```

But there is no fixed port configured in the tests.
It seems that #1048 did not fix this issue here.

BTW: There is a small typo: `thiswarning ` :)

**Comment by Cameronjmayfield** [comment]
This also marks the context as dirty.
