### ISSUE TITLE
Disable/Remove stubsJar implicit publication

### ISSUE THREAD

**Issue by shanman190** [spring-cloud/spring-cloud-contract#1168]
The idea is to remove the publication by default and instead flip the inclusion of the stubsJar to be on the end user. This helps to resolve #482, but it will be a breaking change that will have to wait until v3.0.0.

A similar story can be found [here](https://github.com/spring-cloud/spring-cloud-contract/pull/1165#issuecomment-520514551).

Possible solution (Gradle):

```
publishing {
    publications {
        maven(MavenPublication) {
            // Other settings
            artifact stubsJar
        }
    }
}
```

**Comment by shanman190** [comment]
When doing this the reference to Maven legacy publishing should also be removed (`project.artifacts{}`).

**Comment by OlgaMaciaszek** [comment]
Actually, making use of this setup will make sense once we upgrade it and switch the default off, cause until then, this is included anyway. Moving this to Ilford.

**Comment by marcingrzejszczak** [comment]
Hey @shanman190 , are you willing to disable `stubsJar` by default for Ilford and document how to enable it?

**Comment by shanman190** [comment]
@marcingrzejszczak, sure! I'll see if I can't get a PR out this weekend.

**Comment by shanman190** [comment]
@marcingrzejszczak, one question I have for you all is given Illford is a major release, I think, how would you all feel about more change beyond just this aspect? Thinking in terms of more of the plugin written in Java and continuing to more closely model to the typical Gradle setup?

**Comment by spencergibb** [comment]
Separate PRs
