### ISSUE TITLE
spring-cloud-contract-shade guava conflict with swagger2

### ISSUE THREAD

**Issue by dirkmurphy** [spring-cloud/spring-cloud-contract#1176]
Hi Team

I am using spring cloud contract 2.1.2-RELEASE with springfox-swagger-2.9.2
When I run my spring cloud contract test at consumer side(invoke stubs). I will get an error as below.
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-08-20 19:42:22.824 ERROR  --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    springfox.documentation.spring.web.PropertySourcedRequestMappingHandlerMapping.mappingPath(PropertySourcedRequestMappingHandlerMapping.java:82)

The following method did not exist:

    com.google.common.base.Optional.transform(Lcom/google/common/base/Function;)Lcom/google/common/base/Optional;

The method's class, com.google.common.base.Optional, is available from the following locations:

    jar:file:/D:/repoMaven/org/springframework/cloud/spring-cloud-contract-shade/2.1.2.RELEASE/spring-cloud-contract-shade-2.1.2.RELEASE.jar!/com/google/common/base/Optional.class
    jar:file:/D:/repoMaven/com/google/guava/guava/20.0/guava-20.0.jar!/com/google/common/base/Optional.class

It was loaded from the following location:

    file:/D:/repoMaven/org/springframework/cloud/spring-cloud-contract-shade/2.1.2.RELEASE/spring-cloud-contract-shade-2.1.2.RELEASE.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of com.google.common.base.Optional
```

When I disable swagger at my consumer side. This error will be disappeared and the test passed.
And I have tried to exclude guava from spring-cloud-contract-shade and import guava as independent dependency, it not work.

I hope use swagger as API doc and spring cloud contract a the same time. Can you give me some help?

I check the source code in spring-cloud-contract-shade-2.1.2.RELEASE.jar. There are google, apache, codehaus, eclipse code in this jar, but no spring code in it.Why?

**Comment by marcingrzejszczak** [comment]
> When I disable swagger at my consumer side. This error will be disappeared and the test passed.
And I have tried to exclude guava from spring-cloud-contract-shade and import guava as independent dependency, it not work.

You'd have to go with our Guava. You won't be able to exclude it since it's in a shaded jar.

> I check the source code in spring-cloud-contract-shade-2.1.2.RELEASE.jar. There are google, apache, codehaus, eclipse code in this jar, but no spring code in it.Why?

Cause we're shading libraries so as not to have conflicts, for example with Guava.

> I hope use swagger as API doc and spring cloud contract a the same time. Can you give me some help?

Can you try with the latest `Hoxton.M2` release? I remember that in Hoxton we've managed to improve the shading.

**Comment by dirkmurphy** [comment]
Hi Marcin
Thank you for kindly help.

> You'd have to go with our Guava. You won't be able to exclude it since it's in a shaded jar.

Yes. spring cloud contract using spring-cloud-contract-shade.jar.
But when I use swagger2.9.2 as the same time, swagger can not choose a fit Class to use. The class "com.google.common.base.Optional" in spring-cloud-contract-shade.jar and guava.jar at the same time. I want to know how to solve this conflict. Can you give some help?

**Comment by marcingrzejszczak** [comment]
Can you check the latest Hoxton release to see if the problem persists? Cause I think that it got already solved.

**Comment by dirkmurphy** [comment]
Hi Marcin.
I have upgrade spring cloud to Hoxton.M2.
This problem have been solved.
Thank you very much.
But there are more problems emerged, I will debug them.
Thank you again!
