### ISSUE TITLE
Add new values to common properties, clarify docker documentation

### ISSUE THREAD

**Issue by wkorando** [spring-cloud/spring-cloud-contract#1179]
Under section "5.11.1. Common Properties for JUnit and Spring"

It is missing a couple of the new properties for consumer side stubs generation. Specifically:

stubrunner.failOnNoStubs

stubrunner.generateStubs

stubrunner.properties

Also the Docker documentation "3.1. Environment Variables" could be clarified

Specifically this portion is incorrect: 

"You can run the docker image and pass any of the Common Properties for JUnit and Spring as environment variables. The convention is that all the letters should be upper case. The dot (.) should be replaced with underscore (_) characters. For example, the stubrunner.repositoryRoot property should be represented as a STUBRUNNER_REPOSITORY_ROOT environment variable."

As underscore would also be used in place of camelCase. Granted the example in the follow sentence demonstrates that behavior.

This might be more stylistic and a bit of "easy for me to say", but it would be nice if the "Envrionment Varibles" section under consumer matched the style of what is under the producer side, i.e. explicitly showing all the variables and what they mean, to help prevent anything being lost in translation. 

Screenshots:

![Screen Shot 2019-08-22 at 10 27 41 AM](https://user-images.githubusercontent.com/3010635/63528614-deae9f00-c4c8-11e9-8bc4-5e57b50647dc.png)

![Screen Shot 2019-08-22 at 10 27 49 AM](https://user-images.githubusercontent.com/3010635/63528615-deae9f00-c4c8-11e9-9f28-486e4dcc63f2.png)

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-build/commit/941340a58893dd24a66c1ac0749ae5d8d78bc2dc

all the properties are available here https://cloud.spring.io/spring-cloud-contract/reference/html/appendix.html#appendix
