### ISSUE TITLE
Invalid API Usage to Get Project Final Name

### ISSUE THREAD

**Issue by akefirad** [spring-cloud/spring-cloud-contract#1180]
[Here](https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/main/java/org/springframework/cloud/contract/maven/verifier/GenerateStubsMojo.java#L116) to get the project final name:
```
String stubArchiveName = this.project.getBuild().getFinalName() + "-"
				+ this.classifier + ".jar";
```
This does not work if one sets `finalName` in `build` element in the POM file. The method simply returns the raw value of the property (e.g. `${project.name}`).
Instead the value should be injected:
```
@Parameter(defaultValue = "${project.build.finalName}", readonly = true, required = true)
private String projectFinalName;
```

**Comment by marcingrzejszczak** [comment]
Care to create a PR to fix this? Preferably against the 2.1.x branch?

**Comment by akefirad** [comment]
there you go: https://github.com/spring-cloud/spring-cloud-contract/pull/1181

**Comment by akefirad** [comment]
Ah I made it against master. Should I create a new one?

**Comment by marcingrzejszczak** [comment]
Great! Yeah, could you please close that one and create one against the `2.1.x` branch? I'll then merge 2.1.x to master.

**Comment by akefirad** [comment]
Roger.

**Comment by akefirad** [comment]
there you go https://github.com/spring-cloud/spring-cloud-contract/pull/1183

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/ea2d6b65807923c454a881efdfe1afe7186e67ad

Great job @akefirad !
