### ISSUE TITLE
Consider not making the Kotlin dep implicitly fetched

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#1189]
Currently `spring-cloud-contract-kotlin-spec` is part of `spring-cloud-contract-spec`. That means, that even if you don't use Kotlin, you will download Kotlin (which is around 50 mb).

Maybe we should consider making Kotlin and all the next specs opt-in ? That way we will not download the whole world. 

The funny thing is that if you add the `pact` module then you will download Scala, Groovy & Kotlin.

**Comment by OlgaMaciaszek** [comment]
I agree, the additional modules (like kotlin) can depend on core modules, but not the other way round.

**Comment by marcingrzejszczak** [comment]
That's a breaking change with regards to `Hoxton.M2`
