### ISSUE TITLE
Stubrunner does not cause test to fail when unable to find stubs

### ISSUE THREAD

**Issue by mogronalol** [spring-cloud/spring-cloud-contract#120]
I noticed that when a stub artefact isn't found by the `StubRunner`, the test still continues:

`o.s.c.c.stubrunner.AetherStubDownloader  : For groupId [casdasdasddasdsad.ample] artifactId [httpsadasdsa-server-dsl] and classifier [stubs] the version was not resolved!
o.s.c.c.stubrunner.AetherStubDownloader  : Resolved version is [null]`

I'd find it easier for feedback if the test immediately failed on this.  I may be missing something though, is there a particular reason for this behaviour?

**Comment by marcingrzejszczak** [comment]
Good catch :) I actually don't see any reason for this behaviour. That was an assumption that we took but most likely it wasn't the best one. What we can do is to either enforce breaking or add an option where you can chose a strategy. The latter seems like an overkill. We can actually make some poll over here ;) I agree with you and I'd vote for breaking the build. 

Rationale would be that 
- if you know that there is no stub yet present for the provided coordinates, just don't pass it in the `AutoConfigure...` annotation. 
- If you expect one and it's not there and your tests pass, then it means that you're not actually using the stubs. 
- If you expect one and it's not there and your tests fail - very good, that's the idea

WDYT?

**Comment by marcingrzejszczak** [comment]
Fixed in https://github.com/SpectoLabs/spring-cloud-contract/commit/a0178988efd208aae95f9dd1002ad501be8bb426
