### ISSUE TITLE
@AutoConfigureWireMock should be @Inherited

### ISSUE THREAD

**Issue by fdw** [spring-cloud/spring-cloud-contract#1201]
We have many similar test classes that all rely on WireMock for mocking the server. To make things easier, we would like to use inheritance. However, `@AutoConfigureWireMock` is not marked as `@Inherited`, so we'd still have to annotate each child class.

**Comment by marcingrzejszczak** [comment]
Are you sure it's not working fine either way?

```
public class AutoConfigureWireMockRandomPortInheretedApplicationTests extends AutoConfigureWireMockRandomPortApplicationTests {

	@Autowired
	private Service service;

	@Test
	public void should_work_with_inherited_config() throws Exception {
		stubFor(get(urlEqualTo("/test")).willReturn(aResponse()
				.withHeader("Content-Type", "text/plain").withBody("Hello World!")));
		assertThat(this.service.go()).isEqualTo("Hello World!");
	}

}
```

This code works for me well.

**Comment by fdw** [comment]
This works, but the context is not reset between the classes. It looks to me like the `ExecutionListener` checks only whether the test class itself is annotated with `AutoConfigureWireMock`, and not whether the annotation was inherited.

**Comment by marcingrzejszczak** [comment]
Ah, I see. I'm trying to write a test that would break with the current implementation. 

If the configuration is the same, the context should not be reset, it should be reused. Are you able to show a small sample of when this wouldn't work?

**Comment by fdw** [comment]
I don't want the context reset, but the mappings/stubbings, and possibly the request counts too.

**Comment by marcingrzejszczak** [comment]
Ah ok, maybe I can try to check the counts, that should be easy to verify, thanks for the hint.

**Comment by fdw** [comment]
Sure, thank you for your work! :)

**Comment by fdw** [comment]
That was fast! Thank you! :)

I was going to add a similar problem with meta-annotations, but I'll open a separate issue for that.
