### ISSUE TITLE
Minor bug: push false positive

### ISSUE THREAD

**Issue by Sam-Kruglov** [spring-cloud/spring-cloud-contract#1202]
In bitbucket:
setup "app password" with read and write permissions.
setup branch permissions to not allow direct commits to master for anyone (i.e. only pull requests to master allowed).
try to execute `pushStubsToScm` goal of `spring-cloud-contract-maven-plugin`

Expect to see some error.
Actually it says that pushed successfully, while only a local commit was made.

off-topic: don't feel like it deserves an issue, but if the "app password" does not allow "write" then this goal will retry itself 10 times which does not seem to be configurable and it is also pointless to retry that case.

**Comment by marcingrzejszczak** [comment]
Can you explain exactly your use-case? How to replicate it and what would be the expected outcome?

**Comment by Sam-Kruglov** [comment]
I just did.. What's should I elaborate?

**Comment by marcingrzejszczak** [comment]
I have no idea which version you're using, I have no idea how you setup your plugin, I have no idea what was there in the logs when the plugin tried to push the code.
