### ISSUE TITLE
Enhancement: allow Git stubs storage to use branches for snapshots

### ISSUE THREAD

**Issue by Sam-Kruglov** [spring-cloud/spring-cloud-contract#1203]
To practice Consumer Driven Contracts with Git stubs storage, I have to use local maven repository and a bunch of redundant `pom.xml` files for each producer (like shown in the "common git repository" example).
As a first step, we could force consumers and producers all just point to the local git repository version but there are problems with this approach:
1. It does not seem to work at all if you try to use local git repository as described in #1155
2. It is a bit of extra work to manually checkout the changes your colleague made and then cherry pick that into local master branch.
3. It is conceptually wrong to use master branch for development like that.

**Comment by marcingrzejszczak** [comment]
> It does not seem to work at all if you try to use local git repository as described in #1155

I didn't have yet time to look into this, but it does work. What is a local git repo? It's a repo stored locally. It's enough to just pass `git://file:///path/to/your/repo` and that will work.

> It is a bit of extra work to manually checkout the changes your colleague made and then cherry pick that into local master branch.

What do you mean by that? 

It seems that I've accidentally removed the properties from the documentation, however if you check the code https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/ScmStubDownloaderBuilder.java#L222-L226 you'l see that it's enough to pass the properties via the `properties` section of the downloader or plugin and you can provide the branch

**Comment by Sam-Kruglov** [comment]
> git://file:///path/to/your/repo and that will work.

Exactly that does not seem to work. In my case at least.

I will try out the properties thanks!

**Comment by Sam-Kruglov** [comment]
Talking about Consumer Driven Contracts, I just noticed that the version here is semantic. When I am using Git as a replacement for maven repository, I guess, it makes sense to have a version for each producer build. But that will not be human-readable.
I want it to be human-readable, so I won't use my server version there. This Git repository must only contain the description of the endpoints that are currently available and who is using what. We don't use the version, but I feel like this case would be considered invalid in Spring Cloud Contract, so, we could hardcode the version to `1` (non-versioned APIs support could be another feature request). As I understand, the stub runner will clone the repository each time, so it will use the latest revision anyway. Please, correct me if I am wrong.

**Comment by Sam-Kruglov** [comment]
Having spent a whole day on this, I conclude the following:
1. Use common Git Repository to store contracts, handle pull requests, store stubs.
2. Hardcode the version to `1` and reference it in consumers and producers CIs.
3. In each producer's `contracts` folder, have `pom.xml` with version `1-SNAPSHOT`.
4. Near that `pom.xml` also have a `generate_stubs` script that will commit and push the mapping (not using the plugin, but actual git cli to avoid having to provide the credentials)
5. Attach CI to this common git repo that will watch only pull requests and deploy the snapshots to maven artifactory. That is to avoid having to provide the credentials during local development.
6. In consumers' and producers' CIs, only use this common git repository for stubs, do not use artifactory.

Having to provide the credentials is really annoying for local development, because you may forget and accidentally commit that code to production and only test against in-progress stubs. There must be a way to use local git user to pull the stubs from Git without any manual credentials.

**Comment by Sam-Kruglov** [comment]
Also, I would like to confirm that the properties do work, so I think I may close this issue and open another one
