### ISSUE TITLE
Stub Mappings are not found

### ISSUE THREAD

**Issue by Raj-Kishan** [spring-cloud/spring-cloud-contract#1208]
I need to build a standalone wiremock service which will act a replacement for a future service. It wont have any tests in it. Just mock templates.

Trying to use the `spring-cloud-contract-wiremock`, with spring boot... Reason being, it provides some functionalities that i want to use. All my json mappings are located under `resources/wiremock/mappings/v1` (5 template files) and the files under `resources/wiremock/__files` (5 corresponding response body files).

My Dependencies:
```        
       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-contract-wiremock</artifactId>
            <version>2.1.2.RELEASE</version>
        </dependency>
```

Configuration:

```
@Configuration
@AutoConfigureWireMock(stubs = "classpath:/wiremock")
public class WireMockConfig {

    @Bean
    public WireMockConfigurationCustomizer wireMockConfigurationCustomizer() {
        return config -> config.preserveHostHeader(true)
                .containerThreads(150)
                .notifier(new Slf4jNotifier(true))
                .extensions(new ResponseTemplateTransformer(false));
    }

    @Bean
    public ObjectMapper objectMapper() {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());
        return objectMapper;
    }
}
```

Since, content of `resources` (src/main/resources) folder is available at classpath, i have given stub location as `classpath:/wiremock`.

However its unable to find any mappings. I get response that `No response could be served as there are no stub mappings in this WireMock instance.`

**NOTE: My application works fine if i use plain wiremock dependency with spring boot**

**Comment by marcingrzejszczak** [comment]
Please check https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMockConfigurationCustomizerTests.java

Can you change the annotation to @AutoConfigureWireMock(port = 0, stubs = "file:src/main/resources/wiremock/mappings")

**Comment by Raj-Kishan** [comment]
Tried. Same `404` replay. No stub mappings found.

**Comment by marcingrzejszczak** [comment]
I guess I'd need you to produce a sample cause we have a test that works so I don't know exactly what the problem might be.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by fsantiag** [comment]
I am experiencing the same problem. Have you guys found a solution for this issue?

**Comment by marcingrzejszczak** [comment]
I didn't cause no feedback was provided and I couldn't replicate the issue.

**Comment by fsantiag** [comment]
@marcingrzejszczak should I open another issue? I can provide you some piece of code to help debug it.

**Comment by marcingrzejszczak** [comment]
No, once you prepare a sample you can post the link to it here and I'll reopen the issue

**Comment by fsantiag** [comment]
@marcingrzejszczak I have uploaded the sample project here: https://github.com/fsantiag/stub-server
In this example, I expected the .json file to be loaded because since the annotation `@AutoConfigureWireMock(stubs="classpath:/stubs")` is pointing to the stubs folder. I can see the stub using the wiremock api works fine, however the json file doesn't get loaded.

**Comment by marcingrzejszczak** [comment]
You're using  the WireMock integration in compile scope, you should use it in test scope and write a test that uses the annotation

```java
package com.app.stubserver;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class StubServerApplication {

	public static void main(String[] args) {
		SpringApplication.run(StubServerApplication.class, args);
	}

}
```

and the test

```java
package com.app.stubserver;

import com.github.tomakehurst.wiremock.client.WireMock;
import org.assertj.core.api.BDDAssertions;
import org.junit.jupiter.api.Test;

import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.contract.wiremock.AutoConfigureWireMock;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.client.RestTemplate;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.get;
import static com.github.tomakehurst.wiremock.client.WireMock.urlEqualTo;

@SpringBootTest
@AutoConfigureWireMock(stubs="classpath:/stubs")
class StubServerApplicationTests {

	@Test
	void should_have_two_stubs() {
		String object = new RestTemplate().getForObject("http://localhost:8080/resource", String.class);

		BDDAssertions.then(object).isEqualTo("{\"id\": 1}");

		object = new RestTemplate().getForObject("http://localhost:8080/some/thing", String.class);

		BDDAssertions.then(object).isEqualTo("Hello world!");
	}

	@Configuration
	static class MyConfig {

		@Bean
		public void stubUsingWiremockApi() {
			WireMock.stubFor(get(urlEqualTo("/resource"))
					.willReturn(aResponse().withStatus(200).withHeader("Content-Type", "application/json")
							.withBody("{\"id\": 1}")));
		}
	}
}
```

**Comment by fsantiag** [comment]
Is that a way for me to use it in compile scope? I am trying to create an application that stubs different services so I can run integration tests. This app would run as an isolated application.

**Comment by marcingrzejszczak** [comment]
Just use plain WireMock then, it also comes with a standalone version.

**Comment by fsantiag** [comment]
Sure, thank you for your help and patience @marcingrzejszczak. Cheers!
