### ISSUE TITLE
Generated tests with " in contract definition are escaped in wrong way. 

### ISSUE THREAD

**Issue by smilasek** [spring-cloud/spring-cloud-contract#1209]
I have noticed that values in contract definition, which contains " are escaped in wrong way in generated tests cases. 

Testcase:
```groovy
Contract.make {
    request {
        method 'GET'
        url "/test"
    }
    response {
        status OK()
        headers {
            contentType(applicationJson())
            header('ETag','"some-value"')
            header('ETag2','\"some-value\"')
        }
  // some other assertions
```

Generated source:
```java
// then:
			assertThat(response.statusCode()).isEqualTo(200);
			assertThat(response.header("Content-Type")).matches("application/json.*");
			assertThat(response.header("ETag")).isEqualTo("\\\"some_value\\\"");
			assertThat(response.header("ETag2")).isEqualTo("\\\"some_value\\\"");
```

As you can see both `ETag` and `ETag2` headers are compared to same value.
IMO value for `ETag` should be compared to `"\\"some_value\\""

Version of:
spring-cloud-contract-maven-plugin => 2.2.0.M2
spring-cloud-contract => 2.1.2.RELEASE

**Comment by marcingrzejszczak** [comment]
Please use the latest stable release pf contract and plugin. Why are you using a m2 version

**Comment by marcingrzejszczak** [comment]
Also you're using incompatible version of spring cloud contract. The plugin is 2.2 and Contract version is 2.1

**Comment by smilasek** [comment]
Right. Changing version to 2.1.2.RELEASE fixed an issue.
