### ISSUE TITLE
StubRunner creates Wiremock server with consumer's context path

### ISSUE THREAD

**Issue by tommysitu** [spring-cloud/spring-cloud-contract#121]
When we use `@AutoConfigureStubRunner` to mock producer's API, the WireMock server is created with URL prefix of the consumer's context path, and breaking tests with a 404 error.

Is this because the WireMock stub server shares the same context path of the Spring Boot embedded container? I think this is an unwanted behavior.

**Comment by marcingrzejszczak** [comment]
Yeah that's exactly why. ATM you have to add the context path to the URL. That does sound bizarre indeed come to think of it. Thanks for reporting that

**Comment by tommysitu** [comment]
Adding the consumer's context path will fix the test, but the URL will be no longer pointing to the producer in reality. We are going to give up on context path to get around this issue.

**Comment by dsyer** [comment]
Was this ever a good idea: https://github.com/spring-cloud/spring-cloud-contract/blob/8e7d06b/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/StubRunnerConfiguration.java#L69? I think I'll just take it out and see if anyone squawks.

**Comment by marcingrzejszczak** [comment]
No it wasn't but then you'll break the consumer side. Without this Stub Runner can't register any stubs cause WireMocks are sharing the server's context path. So I fixed this but it makes no sense :P

**Comment by dsyer** [comment]
Fixed in 8914523 (stub runner no longer has a context path)
