### ISSUE TITLE
Using aBoolean() in response generates null on consumer side

### ISSUE THREAD

**Issue by wabrit** [spring-cloud/spring-cloud-contract#1213]
I'm using Spring Cloud Contract 2.1.2-RELEASE and have a contract that returns a JSON response body containing a boolean field

```
response {
		status OK()
		headers {
			contentType applicationJson()
		}
		body (
                  foo: value(consumer(aBoolean()), producer(true))
		)
	}
```

The generated mapping file contains a body that assigns null to foo:

```
"response" : {
    ...
    "body" : "{\"foo\":null}",
    ...
  },
```

This is not what I was expecting - I would expect a random **non-null** boolean value.

If I've understood this correctly the cause seems to be in this code in `PatternValueDslProperty.java`:

```
       @Override
	T aBoolean() {
		return createAndValidateProperty(RegexPatterns.TRUE_OR_FALSE)
	}
```

It feels to me that this should be passing `random.nextBoolean()` as the second parameter to the function.

Is there a workaround in lieu of a fix?

**Comment by marcingrzejszczak** [comment]
That's because in the response side the consumer needs to be a concrete value and the producer can be a regex

**Comment by wabrit** [comment]
Hi @marcingrzejszczak 

Apologies if I have misunderstood the workings of Spring Cloud Contract; I thought consumer()-side responses could be wildcarded but I can see now that's misguided,

I did notice that doing e.g. 

```
response {
		status OK()
		body (
                   foo: value(consumer(anyOf('Bar1', 'Bar2', ...)), producer("Bar10")),
```

Generated the mapping 

```
   body" : "{\"foo\":\"Bar1\"}"
```

But perhaps that's an (un)happy accident?
