### ISSUE TITLE
Declare the Gradle plugin using the plugin DSL not the legacy plugin application 

### ISSUE THREAD

**Issue by sdeleuze** [spring-cloud/spring-cloud-contract#1217]
Spring Cloud Contract uses [in its documentation](https://cloud.spring.io/spring-cloud-contract/reference/html/gradle-project.html#gradle-add-gradle-plugin) the [legacy plugin application](https://docs.gradle.org/current/userguide/plugins.html#sec:old_plugin_application) instead of the recommended [plugin DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block) which is now used widely on https://start.spring.io.

In addition to follow the best practices, using the plugin DSL is almost mandatory with Gradle Kotlin DSL (now used by default for Kotlin projects on start.spring.io) otherwise the static accessors are not generated which makes Gradle plugins very difficult to configure and hence is highly discouraged.

Could you please update the documentation in order to make Spring Cloud Contract usable with Kotlin + Gradle (seems very important since you now have the Kotlin DSL introduced via #1151), follow the Gradle best practices and improve the consistency across our portfolio in order to reduce the "noise" for our users?

**Comment by marcingrzejszczak** [comment]
> Could you please update the documentation in order to make Spring Cloud Contract usable with Kotlin + Gradle (seems very important since you now have the Kotlin DSL introduced via #1151), follow the Gradle best practices and improve the consistency across our portfolio in order to reduce the "noise" for our users?

We will definitely suggest this approach whenever there's no need for additional dependencies passed to the classpath. For example if you want to use Pact with Spring Cloud Contract, then you have to add the plugin and add the given dependency to the classpath. To do that you need to use the `buildscript` mechanism.

**Comment by snicoll** [comment]
start.spring.io is currently broken with Kotlin (https://github.com/spring-io/start.spring.io/issues/273) as we don't let a build uses `buildscript`. We'll move to the new plugin syntax but it would be nice to see the official doc recommends the same thing as what we generate (i.e. a backport to `2.1.x` would be much appreciated).

**Comment by marcingrzejszczak** [comment]
Yeah, so I'll just write down wherever necessary that there's no way to use the new flow.

**Comment by eddumelendez** [comment]
> We will definitely suggest this approach whenever there's no need for additional dependencies passed to the classpath.

This also applies to the `kotlin` support added in the current version `2.2.x`
