### ISSUE TITLE
Impossible to generate stub with custom transformer - is it possible?

### ISSUE THREAD

**Issue by JulianAffaire** [spring-cloud/spring-cloud-contract#1219]
Hello,
I defined my custom transformer (as said here https://cloud.spring.io/spring-cloud-static/spring-cloud-contract/2.0.1.RELEASE/single/spring-cloud-contract.html#_registering_your_own_wiremock_extension) but it's impossible on a contract to say what transformer to use. 
When the stubs are generated we can see on the mapping file :

`"transformers" : [ "response-template" ]`

It seems impossible to customize this value. But it seems possible in the documentation. Is it a bug? Something is missing?

I put my class in `src/main/java/com/xxx/xxx/` :

```
public class TestWireMockExtensions implements WireMockExtensions {
	@Override
	public List<Extension> extensions() {
		return Arrays.asList(new DefaultResponseTransformer(), new MyCustomResponseTransformer());
	}
}
```

and in `src/main/resources/META-INF/spring.factories` :

```
org.springframework.cloud.contract.verifier.dsl.wiremock.WireMockExtensions=\
com.xxx.xxx.TestWireMockExtensions
```

I tries on the contract many things like this:
`transformers : [ "my-custom-response-transformer" ]`

Thanks a lot,
Best regards,
Julian

**Comment by marcingrzejszczak** [comment]
Can you upgrade to the latest version and check if things work fine? `2.0.1` is old. Also all of our tests work fine so you must be doing sth wrong :grimacing: maybe you could show a sample or sth?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
