### ISSUE TITLE
Make a contract for nested objects with regex

### ISSUE THREAD

**Issue by devdeegaw** [spring-cloud/spring-cloud-contract#1222]
Struggling to make contract for nested objects with regex. 
Like below example Employee have Address. The build failed with error : Unable to make conversion of shouldCreateEmployee.groovy:

body(
        name: anyNonBlankString(),
        address: {
            city: anyNonBlankString(),
            postCode: anyAlphaNumeric()
        }
)

Does anyone know how to make a contract for nested object ?

**Comment by marcingrzejszczak** [comment]
Write address: [] instead of address : {}

**Comment by snehal20gawade** [comment]
Thanks!  it woks for me
