### ISSUE TITLE
Docker SCC Verifier image uploads artifacts twice

### ISSUE THREAD

**Issue by Dominick1993** [spring-cloud/spring-cloud-contract#1224]
When trying to publish verifier stubs to Nexus releases via the Docker image, I stumbled across a problem, that stubs are uploaded twice. This was an issue, because the Nexus that I am using is set up in a way, that prevents updating anything in release repository. It caused a failure every time.

SCC version: 2.2.0-BUILD-SNAPSHOT from September 25th 2019, freshly built from master.

Reproducer: Try running provider verification using docker with `PUBLISH_ARTIFACTS: "true"` into a release repository, that does not allow updates.

Proposal (or possibly the solution) is available in #1223.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/f436d7fca9413cc7ecc3f6b41debe9e8b37c63cd
