### ISSUE TITLE
MissingMethodExceptionNoStack: No signature of method: org.assertj.core.api.ListAssert.hasSizeGreaterThanOrEqualTo()

### ISSUE THREAD

**Issue by konopka90** [spring-cloud/spring-cloud-contract#1227]
Hi, I've got problem similar to the 
https://github.com/spring-cloud/spring-cloud-contract/issues/381#issuecomment-323145348

Problem appeared when I've added verification of min occurence: 
```
        bodyMatchers {
            jsonPath('$.NetworkSliceSubnet.mFIdList', byType {
                // results in verification of size of array (min 0)
                minOccurrence(0)
            })
```
Now I'm using 2.1.3.RELEASE version.
Can you please verify if it is working on your site?

**Comment by marcingrzejszczak** [comment]
Can you show your maven / gradle setup please?

**Comment by konopka90** [comment]
Yes, you're right :) I had old version of org.springframework.cloud:spring-cloud-contract-gradle-plugin version:2.1.1.RELEASE.
After updating to 2.1.3.RELEASE it is working now. Thank you.
