### ISSUE TITLE
Cannot deserialize instance of `com.github.tomakehurst.wiremock.stubbing.StubMapping` out of START_ARRAY token

### ISSUE THREAD

**Issue by mbesoft** [spring-cloud/spring-cloud-contract#1228]
Hi,

I'm currently facing an issue when I try to run  the below code:
@SpringBootTest(classes = { AppConfig.class })
@AutoConfigureWireMock(stubs="classpath:/stubs", port = 8089)
public class PhotoServiceTest {

	@Autowired
	private Service service;

	@Test
	public void contextLoads() throws Exception {
		assertThat(this.service.getFooList()).isNot(null);
	}
}

I get :
Caused by: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'org.springframework.cloud.contract.wiremock.WireMockConfiguration': Invocation of init method failed; nested exception is com.github.tomakehurst.wiremock.common.JsonException: {
  "errors" : [ {
    "code" : 10,
    "source" : {
      "pointer" : "/"
    },
    "title" : "Error parsing JSON",
    "detail" : "Cannot deserialize instance of `com.github.tomakehurst.wiremock.stubbing.StubMapping` out of START_ARRAY token"
  } ]
}

Inside stubs, response is defined in a json file (i'm using "bodyFileName" ) having an array of objects : 
[ {"idobj : "1"}, {idobj : "2"}] 

With the spring-cloud-contract-wiremock 2.1.3.RELEASE.

Could you please check and advise ?

Thanks

**Comment by marcingrzejszczak** [comment]
Apparently inside the stubs folder you have a json file which is not a stub. Can you create a sample that replicates this?

**Comment by mbesoft** [comment]
@marcingrzejszczak Thanks for getting back quickly. You're right ! I fixed it by moving my ref file response.json to __files.
