### ISSUE TITLE
StubRunnerConfiguration defaults to offline mode when repository root is not specified

### ISSUE THREAD

**Issue by mogronalol** [spring-cloud/spring-cloud-contract#124]
I think the `workOffline` property should take precedence, regardless of whether or not there's a `repositoryRoot` or not.  In otherword I would expect:

| Valid Repository Root Specified  | Work Offline | Outcome |
| ------------- | ------------- | ------------- |
| True  | True  | Look offline only |
| True  | False  | Look in remote repository only |
| False  | False  | Look in remote repository only and fail |

The path to the remote repo is just a path IMO, and it's least surprising for only the flag to determine whether it's used or not.

**Comment by marcingrzejszczak** [comment]
Hmm but doesn't it make sense (and isn't it intuitive) that if you don't provide the repository URL then you're working with the contracts installed locally?

**Comment by mogronalol** [comment]
If I do `workOffline=false` explicitly, I think it's a confusing that it switches it back to true based on a missing repository path.  I think failing saying that there's no path specified would be more intuitive.

**Comment by marcingrzejszczak** [comment]
Yeah maybe you're right. Care for a PR? :)
