### ISSUE TITLE
Kotlin Gradle not copying contracts when contracts are stored in remote git repo

### ISSUE THREAD

**Issue by dmfrey** [spring-cloud/spring-cloud-contract#1240]
Spring Boot 2.1.9.RELEASE
Spring Cloud Contract 2.1.3.RELEASE
Kotlin 1.2.71
Gradle 5.6.2 (build.gradle.kts)

Remote Repo gets downloaded and directories get created in `/build/stubs` but contracts never show up in the `.../contracts` directory

**Comment by marcingrzejszczak** [comment]
Confirmed with @dmfrey that the issue got resolved
