### ISSUE TITLE
Spring cloud contract with JAXRS resource.

### ISSUE THREAD

**Issue by devdeegaw** [spring-cloud/spring-cloud-contract#1241]
Looking for an example to use spring cloud contract with JAXRS resource.
Any help appreciated

**Comment by marcingrzejszczak** [comment]
I think a day before you filed this issue I came to the conclusion that there is no such example. I will try to add one.

**Comment by devdeegaw** [comment]
Thanks.

**Comment by marcingrzejszczak** [comment]
Example added here https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/master/producer_jaxrs via https://github.com/spring-cloud-samples/spring-cloud-contract-samples/commit/6fc413c5d6c821bf602f4c8aac7daef646233542
