### ISSUE TITLE
How to use local groovy to convert and push scm for one configuration

### ISSUE THREAD

**Issue by wuzhongwu** [spring-cloud/spring-cloud-contract#1246]
I want use local groovy to convert and generate stubs ,and when this groovy happen change,I can push them to scm.
But on one plugin configuration ,only choose convert and push from git,not support convert for local and push for scm.
How to configure them

**Comment by marcingrzejszczak** [comment]
Can you please read this article https://stackoverflow.com/help/how-to-ask and the whole comment section we've created when you open an issue? Right now I have no idea which version of scc you are using, what your problem is and what you want to achieve.

**Comment by wuzhongwu** [comment]
I have configure the contractsRepositoryUrl,but i find when you configure the contractsRepositoryUrl,it will convert stubs mappings  from the contracts repository,when my local contract happen change, i want reconvert stubs mappings,it always convert from contracts repository,but the remote is old stubs mappings.
so,my question is how to convert from local repository,because my local groovy have change, i cant convert the new stubs mappings

**Comment by marcingrzejszczak** [comment]
I'm sorry I don't understand what you're saying. 

If you point to a remote repo it will always generate stubs from that repo. What else would you expect it to do?

If you want to use some local contract setup you can always not use the `contractsRepositoryUrl` url.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
