### ISSUE TITLE
WireMockCustomiser for the docker image

### ISSUE THREAD

**Issue by Sic4Parvis9Magna** [spring-cloud/spring-cloud-contract#1251]
Hello all, There is no secret in that Wiremock utilized by stub-runner under the hood,  there is some possibility to configure that server like [here](https://cloud.spring.io/spring-cloud-static/spring-cloud-contract/2.1.3.RELEASE/multi/multi__spring_cloud_contract_wiremock.html#_customization_of_wiremock_configuration): 
```java
    @Bean
    WireMockConfigurationCustomizer optionsCustomizer() {
      return new WireMockConfigurationCustomizer() {
        @Override
        public void customize(WireMockConfiguration options) {
// perform your customization here
        }
      };
    }
```
In my case, I have to work with an image for the Runner and provide stubs ids via the environment variable.
 Is it correct that if I would like to configure Wiremock for that Runner I have to build up my own image of the Runner with that customization `@Bean` or there are some other options to do so which I missed?

**Comment by marcingrzejszczak** [comment]
Nope, the only way is to create your own image with your own customizations. What exactly would you like to customize ?

**Comment by Sic4Parvis9Magna** [comment]
> Nope, the only way is to create your own image with your own customizations. What exactly would you like to customize ?

I use this Runner for some kind of performance testing. At the moment I found that the `requests journals` critically affect the test execution process.
I would like to turn off requests journaling for Wiremock' server.
```
package com.github.tomakehurst.wiremock.core;
   private boolean requestJournalDisabled;
```
I do not see here any notes regarding CI/DI for contributors, how you build images here?

**Comment by Sic4Parvis9Magna** [comment]
**UPD:**
the issue was resolved via making a custom image from the [spring-cloud-contract-stub-runner-boot](https://github.com/spring-cloud/spring-cloud-contract/tree/master/spring-cloud-contract-stub-runner-boot) module.
Before module was transformed to the docker image the following configuration was added:
**Custom configurer:**
```java
public class WireMockConfigurer implements HttpServerStubConfigurer<WireMockConfiguration> {

    @Override
    public boolean isAccepted(Object httpStubConfiguration) {
        return httpStubConfiguration instanceof WireMockConfiguration;
    }

    @Override
    public WireMockConfiguration configure(WireMockConfiguration httpStubConfiguration, HttpServerStubConfiguration httpServerStubConfiguration) {
        return httpStubConfiguration.disableRequestJournal();
    }
}
```
and **application.yaml**
```yaml
stubrunner:
  httpServerStubConfigurer: ${CUSTOM_PACKAGE}.WireMockConfigurer
```
