### ISSUE TITLE
Exclusions in the Rest-Assured test dependencies are leaking in the BOM

### ISSUE THREAD

**Issue by fpavageau** [spring-cloud/spring-cloud-contract#1253]
**Version: 2.2.0.RC1, through Spring Cloud Hoxton.RC1**

`spring-cloud-contract-dependencies` is included in `spring-cloud-dependencies`, and [excludes some Groovy dependencies](https://github.com/spring-cloud/spring-cloud-contract/blob/v2.2.0.RC1/spring-cloud-contract-dependencies/pom.xml#L118) from Rest-Assured since [the migration to Rest Assured 4.0.0](https://github.com/spring-cloud/spring-cloud-contract/commit/b48dd4905f00853ec7d92347f89f189e26b0eecf). That impacts any user of the Spring Cloud BOM, whatever version of Rest Assured they use: in our case Rest-Assured 3.3.0, since that's the version managed by Spring Boot 2.2.

I understand the need for a common configuration of the test dependencies in Spring Cloud Contract, but I don't think it should be exposed in the BOM.

**Comment by marcingrzejszczak** [comment]
Makes perfect sense. Thanks for pointing it out!
