### ISSUE TITLE
any value in PathVariable

### ISSUE THREAD

**Issue by devdeegaw** [spring-cloud/spring-cloud-contract#1258]
Is it possible to use anyUuid or anyString in path parameter ?  like below : 

```
Contract.make {
    request {
        method 'GET'
        url '/api/orders/'+ anyUuid()
    }
    response {
        status OK()
        body(
                id: anyUuid(),
      
        )
        headers {
            contentType applicationJson()
        }
    }
}
```
it throws : java.lang.IllegalArgumentException: Not enough variable values available to expand '8'

**Comment by marcingrzejszczak** [comment]
try this

```
Contract.make {
    request {
        method 'GET'
        url $(regex('/api/orders/'+ uuid()))
    }
    response {
        status OK()
        body(
                id: anyUuid(),
        )
        headers {
            contentType applicationJson()
        }
    }
}
```

**Comment by devdeegaw** [comment]
Thanks thats working fine.
I was trying something like
`url $(regex('/api/orders/'+ $(consumer(uuid()), producer("4b81307a-d9fa-11e9-8a34-2a2ae2dbcce4"))))`

```
Contract.make {
    description 'Retrieve an order'
    request {
        method 'GET'
        url $(regex('/api/orders/'+ $(consumer(uuid()), producer("4b81307a-d9fa-11e9-8a34-2a2ae2dbcce4"))))
    }
    response {
        status OK()
        body(
                id: anyUuid(),
                orderStatus: "SAVED",
        )

        headers {
            contentType applicationJson()
        }
    }
}
```
mentioning order id in producer so that I can differentiate between 404 and 200 response .
but somehow above  its giving bad request

**Comment by marcingrzejszczak** [comment]
Remember to set value of priorities. The more concrete example should have a higher priority (smaller value of the priority field), the less concrete should have a lower priority (higher value of that field)
