### ISSUE TITLE
Verifiying AMQP message fails when template is transacted

### ISSUE THREAD

**Issue by hgarus** [spring-cloud/spring-cloud-contract#1259]
When a message is sent using the mocked AmqpTemplate and the originally configured RabbitTemplate is transacted the call to AmqpTemplate.send fails and throws a java.lang.IllegalStateException: Channel closed during transaction.

I have set up a minimal example project to demonstrate the issue: https://github.com/hgarus/transacted-amqp-contract-minimal-example

I can reproduce this using both spring-cloud-contract 2.2.0.RC1 and 2.1.3.RELEASE.

**Comment by hjohn** [comment]
I can also reproduce this with 2.3.3.RELEASE
