### ISSUE TITLE
timeout generated out of fixedDelayMilliseconds cannot be resolved

### ISSUE THREAD

**Issue by djohs** [spring-cloud/spring-cloud-contract#1262]
Hello,

we try to include spring-cloud-contract into our services. We would like to achieve that the responses encounter a delay of a few milliseconds. In the documentation we found the [fixedDelayMilliseconds](https://cloud.spring.io/spring-cloud-contract/reference/htmlsingle/#contract-dsl-async 
) property, but this leads to a compilation error in the generated Test. It seems like the generated `.timeout()` cannot be resolved.

Although the property is listet under the Asynchronous Support section, the second example shows the usage without an additional `async` property. Which leads us to the assumption that it could be used without it, which seems not to be the case.   

We use spring-cloud Greenwich.SR1 and spring-cloud-contract-maven-plugin 2.1.2.RELEASE

We provided you a sample project which reproduces our issue:
https://github.com/djohs/spring-cloud-contract-sample

Can anybody provide us some clarification about this?

**Comment by marcingrzejszczak** [comment]
Have you tried upgrading to the latest version? Is the situation the same?

**Comment by djohs** [comment]
Thank you for the fast response!

Shows the same behaviour with Spring Boot 2.1.8, Spring Cloud Greenwich.SR3 and Spring Cloud Contract 2.1.3

**Comment by krunalshahbeit2006** [comment]
Hi,

I am still getting the behaviour where the test does not wait for given timeout and returns quickly.
Can you help me how I can define it only for consumer and get it workout ?

I have below code

import org.springframework.cloud.contract.spec.Contract

Contract.make {
description "should return person by id=1"

request {
	url "/person/1"
	method GET()
}

response {
	status OK()
	value(
			**producer(fixedDelayMilliseconds(0)),
			consumer(fixedDelayMilliseconds(120000))**
	)
	headers {
		contentType applicationJson()
	}
	body (
		id: 1,
		name: "foo",
		surname: "bee"
	)
}
}
