### ISSUE TITLE
Trying to use Bearer Token when connecting to Pactflow Broker

### ISSUE THREAD

**Issue by mrc535s** [spring-cloud/spring-cloud-contract#1279]
I am trying to connect to the PactFlow Broker, but I can't seem to find a way to connect using the Bearer token as shown in their [documentation](https://docs.pactflow.io/docs/getting-started/).  I only see the ability to use username and password, but not sure that it is even possible with Pactflow API as I keep getting a 401.  Is this something available already?  If so, can someone point me to the documentation on how to do this?  If not, is this something we can get added to as a feature?

**Comment by marcingrzejszczak** [comment]
Are you sure you're asking the question at the proper place? Or are you trying to use Spring Cloud Contract together with Pactflow?

**Comment by mrc535s** [comment]
I think so, but let me know if not.  Essentially I am trying to push the contracts to the pact broker hosted by Pactflow.  

Here is the contracts configuration in my build.gradle for my Provider:

`contracts {
    // When + is passed, a latest tag will be applied when fetching pacts
    contractDependency {
        stringNotation = "${project.group}:${project.name}:+"
    }
    contractRepository {
        repositoryUrl = "pact://https:username//path.pact.dius.com.au:443/"
        username = "myemail@domain.com"
        password = "mypassword"

    }
    // The mode can't be classpath
    contractsMode = "REMOTE"
    // Base class mappings etc.
}`

This returns a 401

**Comment by marcingrzejszczak** [comment]
The url shouldn't be sth like? `repositoryUrl = "pact://https://path.pact.dius.com.au:443/"`

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
