### ISSUE TITLE
TemporaryFileStorage.TEMP_FILES_LOG full queue exception in larger projects

### ISSUE THREAD

**Issue by xyloman** [spring-cloud/spring-cloud-contract#1282]
**Overview**
After upgrading to spring-cloud-contract-stub-runner 2.2.0.RELEASE we experienced an issue where TemporaryFileStorage.TEMP_FILES_LOG would fail to clear the queue which would result in test failures because the temp files log would be full.

After reviewing the cleanup method it appears to only execute on JVM shutdown hook.  When used in practice the JVM shutdown hook will only execute once after all tests have executed.  However, for a project with a lot of contracts this can lead to the queue filling up and not clearing after each test suite. 

Also, in the cleanup method the try catch when an IO exception is thrown should likely exist with in the for look such as the following:

```JAVA
		for (File file : TemporaryFileStorage.files()) {
			try {
				if (file.isDirectory()) {
					Files.walkFileTree(file.toPath(), new SimpleFileVisitor<Path>() {
						@Override
						public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
							if (log.isTraceEnabled()) {
								log.trace("Removing file [" + file + "]");
							}
							Files.delete(file);
							return FileVisitResult.CONTINUE;
						}

						@Override
						public FileVisitResult postVisitDirectory(Path dir, IOException exc) throws IOException {
							if (log.isTraceEnabled()) {
								log.trace("Removing dir [" + dir + "]");
							}
							Files.delete(dir);
							return FileVisitResult.CONTINUE;
						}
					});
				} else {
					Files.delete(file.toPath());
				}
			} catch (NoClassDefFoundError | IOException e) {
				// Added NoClassDefFoundError cause sometimes it's visible in the builds
				// this error is completely harmless
				if (log.isTraceEnabled()) {
					log.trace("Failed to remove temporary file", e);
				}
			}
		}
		
		TemporaryFileStorage.files().clear();
```

to work around this we have added an after method to each stub runner test suite to make sure that the TemporaryFileStorage.files() is cleared and that the for loop iteration gracefully handles exceptions.

see: https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/TemporaryFileStorage.java#L63

**Comment by marcingrzejszczak** [comment]
Hi! Thanks for the issue. Are you willing to file a pull request to fix this?

**Comment by marcingrzejszczak** [comment]
fixed by https://github.com/spring-cloud/spring-cloud-contract/commit/632cbe28654efd339757c6431350e5025b2a8a28

**Comment by xyloman** [comment]
@marcingrzejszczak thank you for responding this looks like it would do a great job of fixing our issue.  So if I understand the changes made the cleanup method will be invoked on close but when is on close invoked?

**Comment by marcingrzejszczak** [comment]
Whenever StubRunner is closed https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunner.java#L195, e.g. after the test has finished (https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/junit/StubRunnerRule.java#L75)
