### ISSUE TITLE
YamlContract does not implement the requested interface GroovyObject

### ISSUE THREAD

**Issue by Schlese** [spring-cloud/spring-cloud-contract#1289]
**Bug report**

Converting a .yaml Contract results in `java.lang.IncompatibleClassChangeError: Class org.springframework.cloud.contract.verifier.converter.YamlContract does not implement the requested interface groovy.lang.GroovyObject`

After examining the problem in more detail, I found that in `spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/converter/` the `YamlContract `was checked in as a Java file and not Groovy (like in the branch 2.1.x). Therefore, the GroovyObject interface is missing, which results in the specified exception.

Spring-cloud-contract Version: 2.2.0-RELEASE

**Comment by marcingrzejszczak** [comment]
You're talking about the 2.1.x and 2.2.x interop?

**Comment by Schlese** [comment]
With 2.1.1 the conversion of the yaml File is working. But I tried to update it to 2.2.0 and there it is not working. Did not change anything else.

When I look at the YamlContract class in the version 2.2.0 the GroovyObject interface is missing.

**Comment by marcingrzejszczak** [comment]
No wonder since it's a java class. It doesn't need to have this interface. Can you create a sample that replicates this issue?

**Comment by Schlese** [comment]
> No wonder since it's a java class. It doesn't need to have this interface. 

Sure but in the past (version 2.1.1) it was a groovy file in your repository and so (I assume) it had an implementation of the GroovyObject interface and therefore not causing this issue.
https://github.com/spring-cloud/spring-cloud-contract/tree/2.1.x/spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/converter

I will try to provide a sample until tomorrow.

**Comment by marcingrzejszczak** [comment]
No wonder, since we've migrated to Java. Unless you're mixing versions of Spring Cloud Contract you shouldn't even care that it has the `GroovyObject` interface.

**Comment by Schlese** [comment]
Since I can't reproduce the error you may be right. Thanks for the help and sorry for bothering you.
