### ISSUE TITLE
RAML <> SC dsl conversion

### ISSUE THREAD

**Issue by wesaidso** [spring-cloud/spring-cloud-contract#129]
It would be great if I could use our existing RAML files to generate the SC dsl!

**Comment by marcingrzejszczak** [comment]
@wesaidso I've just merge the pluggability thing to master. Now you can easily create the `org.springframework.cloud.contract.spec.ContractConverter` to convert from RAML to DSL and back. Check https://github.com/spring-cloud/spring-cloud-contract/pull/161 for more info

**Comment by eddumelendez** [comment]
Hi @marcingrzejszczak I took this issue and I have some progress converting `raml` files to `Contract` but become harder in the other way. I can send my PR in order to review and continue with this.

**Comment by marcingrzejszczak** [comment]
WOW!! Sure! I'd love to see it!!maybe we'll manage to add it for Dalston :D

**Comment by marcingrzejszczak** [comment]
Following the discussion here https://github.com/spring-cloud/spring-cloud-contract/pull/227 it turns out that schema based solutions are not really suitable as input for Spring Cloud Contract. The contents of the PR will be moved to Spring Cloud Incubator.
