### ISSUE TITLE
RegexPattern for iso8601WithOffset() isn't correct

### ISSUE THREAD

**Issue by atcollins06** [spring-cloud/spring-cloud-contract#1296]
Bug report

The iso8601WithOffset() call internally uses the ISO8601_WITH_OFFSET regex pattern defined in org.springframework.cloud.contract.spec.internal.RegexPatterns.  The regex is:

([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\\.\\d{3})?(Z|[+-][01]\\d:[0-5]\\d)

This pattern expects exactly 3 digits to be included in the milliseconds portion of the timestamp, no more, no less.  But, the default formatting of ISO 8601 timestamps used by Java/Jackson removes insignificant zeros from the milliseconds in the timestamp when serializing to JSON.  The matcher then fails.

For example, for this timestamp **_"effectiveDateTime": "2019-12-27T23:33:09.74Z"_**, I get the following error: **_[?(@.['effectiveDateTime'] =~ /([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.\d{3})?(Z|[+-][01]\d:[0-5]\d)/)]_** even though it is a legitimate timestamp generated by Java and serialized by Jackson.

Spring Cloud Contract version: 2.1.2

**Comment by marcingrzejszczak** [comment]
Can you please show how you're setting up Jackson?  Cause the Javadocs of the `SerializationFeature.WRITE_DATES_AS_TIMESTAMP` shows that there should be 3 x `S`, `yyyy-MM-dd'T'HH:mm:ss.SSSZ`

```
 /**
     * Feature that determines whether Date (and date/time) values
     * (and Date-based things like {@link java.util.Calendar}s) are to be
     * serialized as numeric timestamps (true; the default),
     * or as something else (usually textual representation).
     * If textual representation is used, the actual format is
     * one returned by a call to
     * {@link com.fasterxml.jackson.databind.SerializationConfig#getDateFormat}:
     * the default setting being {@link com.fasterxml.jackson.databind.util.StdDateFormat},
     * which corresponds to format String of "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
     * (see {@link java.text.DateFormat} for details of format Strings).
     *<p>
     * Note: whether this feature affects handling of other date-related
     * types depend on handlers of those types, although ideally they
     * should use this feature
     *<p>
     * Note: whether {@link java.util.Map} keys are serialized as Strings
     * or not is controlled using {@link #WRITE_DATE_KEYS_AS_TIMESTAMPS}.
     *<p>
     * Feature is enabled by default, so that date/time are by default
     * serialized as timestamps.
     */
    WRITE_DATES_AS_TIMESTAMPS(true),
```

Can you create a simple sample that breaks with the latest Spring Cloud Contract release?

**Comment by atcollins06** [comment]
I think that comment is wrong (or maybe out-of-date).  I think it is also a little besides the point.  The real issue is that, as far as I know (based on web searches I did in researching this issue) the ISO 8601 spec does not require a fixed format of exactly 3 digits for the fractional seconds part of the date time specification.  It can have less precision; it can have more.

Below is a simple example that demonstrates the problem.  Sorry, I'm still running against the 2.1.2 version of spring cloud contract.  There is some Gradle issue I have yet to figure out that prevents me from moving to the latest version:

Sample:

**_Controller_**:
```java
@RestController
public class Controller {

    @GetMapping("/api/v1/currentDateTime")
    public CurrentDateTime getCurrent() {
        return new CurrentDateTime(Instant.now().truncatedTo(ChronoUnit.MILLIS).atZone(ZoneOffset.UTC));
    }

    static class CurrentDateTime {
        private ZonedDateTime current;

        public CurrentDateTime(ZonedDateTime current) {
            this.current = current;
        }

        public ZonedDateTime getCurrent() {
            return current;
        }
    }
}
```
**_Main_**:
```java
@SpringBootApplication(scanBasePackages = "isotest")
public class Main {

    public static void main(String[] args) {
        SpringApplication.run(Main.class, args);
    }
}
```
**_Test base_**:
```java
public class IsoTestBase {

    @BeforeEach
    public void setUp() {
        ObjectMapper objectMapper = new ObjectMapper()
                .registerModule(new Jdk8Module())
                .registerModule(new JavaTimeModule())
                .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        StandaloneMockMvcBuilder b = MockMvcBuilders.standaloneSetup(new Controller())
                .setMessageConverters(new MappingJackson2HttpMessageConverter(objectMapper));
        RestAssuredMockMvc.standaloneSetup(b);
    }
}
```
Contract test:
```groovy
package isoTest

import org.springframework.cloud.contract.spec.Contract

[
        Contract.make {
            request {
                headers {
                    contentType(applicationJsonUtf8())
                }
                method 'GET'
                urlPath '/api/v1/currentDateTime'
            }
            response {
                status 200
                headers {
                    contentType(applicationJsonUtf8())
                }
                body(
                        [
                                current : regex(iso8601WithOffset())
                        ]
                )
            }
        }
]
```

build.gradle:
```
buildscript {
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:2.1.6.RELEASE")
        classpath("org.springframework.cloud:spring-cloud-contract-gradle-plugin:2.1.2.RELEASE")
    }
}

apply plugin: 'org.springframework.boot'
apply plugin: 'spring-cloud-contract'

repositories {
    jcenter()
}

dependencies {
    compile("org.springframework.boot:spring-boot-starter-web:2.1.2.RELEASE")

    // Use JUnit test framework
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.3.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.3.1")
    testCompile("org.junit.jupiter:junit-jupiter-params:5.3.1")

    // contract test framework
    testCompile("org.springframework.cloud:spring-cloud-starter-contract-verifier:2.1.2.RELEASE")
    testCompile("org.springframework.cloud:spring-cloud-starter-contract-stub-runner:2.1.2.RELEASE")
    testCompile("org.springframework.cloud:spring-cloud-contract-wiremock:2.1.2.RELEASE")
}

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

contracts {
    packageWithBaseClasses = 'isotest.contracts'
    basePackageForTests = 'isotest.contracts.verifier.tests'
    generatedTestSourcesDir = project.file("${project.rootDir}/src/test/contractTests")
    testFramework = 'JUNIT5'
}

test {
    testLogging {
        events "passed", "skipped", "failed"
    }

    useJUnitPlatform()
}

bootRun {
}

```

Note that in our code, we are truncating the fractional seconds to milliseconds using `Instant.now().truncatedTo(ChronoUnit.MILLIS)`.  As long as the generated milliseconds value has 3 digits, the test passes.  But intermittently it fails when the milliseconds has only 1 or 2 digits.  Also note that if you remove the `truncatedTo(ChronoUnit.MILLIS)` part, the fractional seconds will have microsecond resolution which will generate 6 digits.  This will cause the test to fail every time.

**Comment by marcingrzejszczak** [comment]
Can you show me where the iso format doesn't require 3 digits for mills? I couldn't find such information myself?

Also which comment str you referring to that is outdated?

**Comment by atcollins06** [comment]
I think the ISO 8601 spec itself is probably the only definitive source.  I don't have the latest since it costs money to get it.  Looks like someone posted a version from 2016 here though:

http://www.loc.gov/standards/datetime/iso-tc154-wg5_n0038_iso_wd_8601-1_2016-02-16.pdf

The language is very "spec-eze", but you can look at section 4.2.2.4 on page 18.  Also, here are a couple of other links about the format:

https://www.w3.org/TR/NOTE-datetime
(see Formats section)

https://stackoverflow.com/questions/25842840/representing-fraction-of-second-with-iso-86012004
(see first answer)

And, hopefully the code sample I provided shows the issue.  You may have to run a few times to see a failure (or remove the millisecond truncation to see consistent failures)
