### ISSUE TITLE
Stubrunner with Git Remote pulling contracts in alphabetical order, not by date

### ISSUE THREAD

**Issue by dmfrey** [spring-cloud/spring-cloud-contract#1305]
We currently have a git repo that houses our contracts. Listing the directory lists the versions like such:

* 0.0.10-SNAPSHOT (updated 1 month ago)
* 0.0.11-SNAPSHOT (updated 1 day ago)
* 0.0.5-SNAPSHOT (updated 2 months ago)
* 0.0.6-SNAPSHOT (updated 2 months ago)
* 0.0.7-SNAPSHOT (updated 2 months ago)
* 0.0.8-SNAPSHOT (updated 1 month ago)

If you then reference the contract in the Stubrunner configuration with the `+` operator for the version, it always picks `0.0.10-SNAPSHOT`. It never picks the latest dated one.

As a workaround, you can specify the version directly `0.0.11-SNAPSHOT` and it will resolve the correct version.

Will build a sample at a later time.

**Comment by cassiemichelleroberts** [comment]
Here is the sample project:

CONSUMER REPO: https://github.com/cassiemichelleroberts/contract-consumer
STUB REPO: https://github.com/cassiemichelleroberts/contract-producer

the consumer project has a failing test to show unexpected behavior

**Comment by Rukato** [comment]
We tried this with the BUILD-SNAPSHOT. It's no longer pulling from the top of the directory, but from the bottom. So from the list above, it's pulling 0.0.8-SNAPSHOT, not 0.0.11-SNAPSHOT.
<img width="234" alt="Screen Shot 2020-01-22 at 4 35 35 PM" src="https://user-images.githubusercontent.com/20954967/72936693-b9eb7b80-3d35-11ea-8f0b-383eb21758bf.png">
