### ISSUE TITLE
spring-amqp auto config not applied because spring-integration is pulled when using gradle 

### ISSUE THREAD

**Issue by mduesterhoeft** [spring-cloud/spring-cloud-contract#131]
Recently I tried the spring-cloud-contract spring-amqp integration in a standalon project using gradle - I realized that spring-cloud-starter-contract-stub-runner pulls in spring-integration. It is optional but gradle does not seem to support that (is that correct?) - in this case the conditionals on `ContractVerifierAmqpAutoConfiguration` do not match because of
```java
@ConditionalOnMissingClass("org.springframework.integration.core.MessageSource")
```

So I ended up having to exclude the spring-integration dependency like so:

```java
testCompile ("org.springframework.cloud:spring-cloud-starter-contract-stub-runner") {
    exclude group: 'org.springframework.integration‘
}
```

Please see the sample project here https://github.com/mduesterhoeft/spring-cloud-contract/tree/feature/amqp-sample/samples/standalone/messaging/amqp-consumer

Currently, I do not have an idea on how to solve this. If we can come up with a solution idea I would be happy to implement it.

**Comment by marcingrzejszczak** [comment]
BTW which Gradle version are you using?

**Comment by mduesterhoeft** [comment]
I think that's 2.14:

```
task wrapper(type: Wrapper) {
    gradleVersion = '2.14'
}
```

https://github.com/mduesterhoeft/spring-cloud-contract/blob/59390b8fb8488382581576807db6073baf4a90c4/samples/standalone/messaging/amqp-consumer/build.gradle#L58

**Comment by marcingrzejszczak** [comment]
Hmm but actually `org.springframework.cloud:spring-cloud-starter-contract-stub-runner` is declaring those entries as non-optional.

```
		<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-java-dsl</artifactId>
		</dependency>
```

I'm talking about this thing ^^

**Comment by marcingrzejszczak** [comment]
So now we have a problem... Cause either we remove it from starter and document that in order to use Stub Runner with Spring Integration you have to explicitly provide it, or we leave it and make the condition for `ContractVerifierAmqpAutoConfiguration` better

**Comment by mduesterhoeft** [comment]
Don't think so:
https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-stub-runner/pom.xml#L67

Or is this the wrong place?

**Comment by mduesterhoeft** [comment]
I would like to improve the condition on `ContractVerifierAmqpAutoConfiguration` but don' t have a good idea now. We could use a property based approach.

Why is the dependency required? Is it used also for other integrations?

**Comment by marcingrzejszczak** [comment]
It's required cause when you're using Spring Integration you might be using that without the Java DSL. For Stub Runner to work with integration Java DSL is required. Meh, this is getting complicated.

Can you elaborate more on when the AMQP should be turned on? If you're using Spring AMQP there has to be a class that is available only there, and not in Spring Integration . We could also improve the Spring Integration Autoconfiguration to NOT activate itself if there's sth from Spring AMQP present on the classpath. WDYT ?

**Comment by mduesterhoeft** [comment]
If I got this right you can also use spring-integration and spring-cloud-stream with rabbit. So spring-amqp would also be on the classpath there - so the spring-amqp integration can just rely on the absence of the other integrations that might use rabbit.

At least that my understanding. Maybe you have the chance to talk to someone from the spring-amqp team

**Comment by marcingrzejszczak** [comment]
I'd do it like this... 

AMQP config

```
@Configuration
// BTW this is wrong cause it's conditional if ANY of these classes are present. If we want all we need AllNestedCondition or sth like that
// @ConditionalOnClass({Message.class, RabbitTemplate.class, Mockito.class})
@ConditionalOnClass(org.springframework.amqp.core.AmqpTemplate.class)
@AutoConfigureBefore(ContractVerifierIntegrationConfiguration.class)
@AutoConfigureAfter(ContractVerifierStreamAutoConfiguration.class)
public class ContractVerifierAmqpAutoConfiguration {
```

Integration

```
@Configuration
@ConditionalOnClass(Message.class)
@ConditionalOnMissingClass(org.springframework.amqp.core.AmqpTemplate.class)
@AutoConfigureBefore(NoOpContractVerifierAutoConfiguration.class)
@AutoConfigureAfter(ContractVerifierStreamAutoConfiguration.class)
public class ContractVerifierIntegrationConfiguration {
```

Stream

```
@Configuration
@ConditionalOnClass({EnableBinding.class, MessageCollector.class})
@ConditionalOnMissingClass(org.springframework.amqp.core.AmqpTemplate.class)
@ConditionalOnProperty(name="stubrunner.stream.enabled", havingValue="true", matchIfMissing=true)
@AutoConfigureBefore(NoOpContractVerifierAutoConfiguration.class)
public class ContractVerifierStreamAutoConfiguration {
```

WDYT?

**Comment by mduesterhoeft** [comment]
That would not work if you want to use e.g spring-cloud-streams with rabbit `spring-cloud-starter-stream-rabbit` or spring-integration using rabbit. In both cases `AmqpTemplate` would be on the classpath and we would always apply `ContractVerifierAmqpAutoConfiguration`

**Comment by marcingrzejszczak** [comment]
Ah indeed. So we want this to work when you have `spring-amqp` but DON'T have `integration` or `stream`? If that's the case then we'd have to do it like this that Integration and Stream remains the same and AMQP looks like this

```
@Configuration
// BTW this is wrong cause it's conditional if ANY of these classes are present. If we want all we need AllNestedCondition or sth like that
@ConditionalOnClass(RabbitTemplate.class)
@ConditionalOnMissingClass({EnableBinding.class, SomethingFromSpringIntegrations.class})
@AutoConfigureBefore(ContractVerifierIntegrationConfiguration.class)
@AutoConfigureAfter(ContractVerifierStreamAutoConfiguration.class)
public class ContractVerifierAmqpAutoConfiguration {
```

**Comment by marcingrzejszczak** [comment]
Pinging @garyrussell for help

**Comment by mduesterhoeft** [comment]
Exactly - and `SomethingFromSpringIntegrations` was `org.springframework.integration.core.MessageSource` in my implementation - which of course breaks if the stub-runner-starter pulls spring-integrations in every case 😐

**Comment by garyrussell** [comment]
@marcingrzejszczak @mduesterhoeft Can you provide me with some more context? Why would having Spring Integration (and/or the DSL) on the classpath affect Spring AMQP auto config? SI (or the DSL) does not declare any beans that would turn off auto config.

Is there any information in the

```
=========================
AUTO-CONFIGURATION REPORT
=========================
```

that indicates what is happening?

**Comment by marcingrzejszczak** [comment]
Ok so the context is as follows. In Spring Cloud Contract we integrate via AutoConfigurations with

- Spring Cloud Stream
- Spring Integration
- Spring AMQP

In the Stub Runner Starter we add SI Java Dsl dependency. Due to this SI dependency is taken too. So when you're working with Spring AMQP you get the Stub Runner Spring Integration autoconfig executed which is undesired. 

Now we have 2 options 

- remove the obligatory Spring Integration Java DSL dependency (but then whenever someone is using Spring Integration one will need to add the Java DSL dependency explicitly for the Spring Cloud Contract Integration to work).
- leave the obligatory Spring Integration Java DSL dependency but fix the AutoConfigurations so that if you have Spring AMQP but didn't declare Spring Integration explicitly, then the Spring Integration will not work.

Currently it seems that it's close to impossible to go with 2) since Spring Integration Java DSL is using Spring Integration as a transitive dependency.

**Comment by garyrussell** [comment]
I am still missing something (sorry - no coffee yet).

I don't understand why having SI or the DSL on the class path would disable AMQP auto configuration; we simply don't declare any beans that could cause the `@Conditional`s to trip.

However, I see @artembilan has been having a discussion with @mduesterhoeft on gitter so perhaps he can explain what the issue is to my dense brain.

**Comment by mduesterhoeft** [comment]
@garyrussell 
It is not the AutoConfig in spring-amqp - it is the auto config inside spring-cloud-contract responsible for the spring-amqp.

We have three auto configurations there for 
- Spring Cloud Stream
- Spring Integration
- Spring AMQP

And only one should kick in and be responsible for converting the contracts to messages and sending them into the application.

If a client is using spring-integration or spring-cloud-stream he could be using those with spring-amqp. So this could also be on the classpath there. So how can we tell that a client is using plain-amqp (and not spring-cloud-stream or spring-integration).

Is there a clever way to do this

**Comment by garyrussell** [comment]
Ah; ok, sorry; thought you were talking about boot's amqp auto config.

Can you not use a property like @marcingrzejszczak suggested for stream...

    @ConditionalOnProperty(name="stubrunner.stream.enabled", havingValue="true", matchIfMissing=true)

but with `matchIfMissing` false, perhaps.

i.e. explicit opt-in for SI

Or

> For Stub Runner to work with integration Java DSL is required. Meh, this is getting complicated.

Can you explain why the DSL is **required**?

**Comment by marcingrzejszczak** [comment]
> Can you explain why the DSL is required?

We're creating dynamic routes at runtime. That's why we need the DSL.

> Can you not use a property like @marcingrzejszczak suggested for stream...

Actually @mduesterhoeft suggested that and that's the easiest solution. For some reason I've forgotten about this.

**Comment by mduesterhoeft** [comment]
@marcingrzejszczak I think if you generally shy away from removing the spring-integration java dsl from the cp of the stubrunner, we should go the property route I think.

So sth like this?!
```java
@ConditionalOnProperty(name="stubrunner.amqp.enabled", havingValue="true", matchIfMissing=false)
```

**Comment by marcingrzejszczak** [comment]
Actually I do feel bad about all of this but most likely (I don't have any data to prove it other than my gut feeling) more people will be using Spring Integration than Spring AMQP. That's why I feel that it will be better to require the AMQP users (sorry @mduesterhoeft :P ) to provide the property. WDYT?

**Comment by mduesterhoeft** [comment]
👍  from my side - I don't see a way to handle this transparently for the user

**Comment by marcingrzejszczak** [comment]
Awesome! Care to file a PR? :D

**Comment by mduesterhoeft** [comment]
Sure - I clean up my own mess :wink:
