### ISSUE TITLE
Support stubrunner's dependency with empty classifier

### ISSUE THREAD

**Issue by dstepanov** [spring-cloud/spring-cloud-contract#132]
Looks like it isn't possible to have stub defined as `company:service:+::`

**Comment by marcingrzejszczak** [comment]
The current workaround is to use `@AutoConfigureWiremock` and provide the stub as a project dependency

**Comment by marcingrzejszczak** [comment]
Fixed by https://github.com/spring-cloud/spring-cloud-contract/pull/134
