### ISSUE TITLE
Reset WireMock calls after each test

### ISSUE THREAD

**Issue by fdw** [spring-cloud/spring-cloud-contract#1322]
Similar to #1027, we would like the call count to be reset after each test. Currently, we either have to manually call `reset` before each test or verify the accumulated count over all tests. Both are less than ideal.

Since the mapping is already reset for each test, could a new (or the same) property be used to reset the request count?

Thank you!

**Comment by marcingrzejszczak** [comment]
Are you using the latest version? How do you use Spring Cloud Contract for that matter? Are you using Stub Runner? Can you describe your use case in more details please?

**Comment by fdw** [comment]
> Are you using the latest version?
We're using Spring Cloud 2.2.1.

> How do you use Spring Cloud Contract for that matter?
Our tests are annotated with `@AutoConfigureWireMock(port = 0)`. The tests themselves mock and verify the behavior of WireMock, like `stubFor(...)` and `verify(...)`.

> Are you using Stub Runner?
No

> Can you describe your use case in more details please?
It is very similar to the linked #1027: We want to stub WireMock programmatically, which works perfectly now :)
In the end, we want to verify that a certain request was sent to WireMock a certain number of times, using `verify(2, getRequestedFor(...))` or something similar. However, currently the number of requests for one endpoint is not reset between each test, so if two tests are supposed to send the same request to WireMock once, their `verify(1...)` will fail as there have been two requests (one in each test).

Does this help?

**Comment by marcingrzejszczak** [comment]
Yeah it helps, although it should work. I see that there are other `reset...` methods in WireMock API. Do you have a sample I could reuse to do proper testing?

**Comment by fdw** [comment]
I'll see that I can whip up something. Should I use a gist, or what do you prefer?

I think `WireMock.resetRequests()` could be the correct one.

**Comment by marcingrzejszczak** [comment]
You can create a Github project with a failing test and I'll check it out.

**Comment by fdw** [comment]
Okay, I'll see what I can do.

**Comment by fdw** [comment]
Okay, that was unexpected and scarily fast 🙂

Do you still need a sample? 😉

**Comment by marcingrzejszczak** [comment]
Heh, you can check out the samples and see if that helped. In your spare time I'd definitely could use a sample

**Comment by fdw** [comment]
From what I can see in the changes, this should be working :)
