### ISSUE TITLE
Stubs generated from Restdocs tests end up only matching double url-escaped query string values

### ISSUE THREAD

**Issue by jorahood** [spring-cloud/spring-cloud-contract#1325]
Spring Cloud Hoxton.SR1
Contracts 2.2.1.RELEASE

With Rest docs, the wiremock stubs queryParameters values get stored url escaped even though Wiremock escapes them again to check against request parameters.

**Sample**
In a SpringCloudContractRestDocs test, a query param of .param("seasoning","salt,pepper") generates a stub like 
```"seasoning" : {
          "equalTo" : "salt%2Cpepper"
           } 
       }
```
The actual request to the stub server has to be double escaped to match, so `?seasoning=salt%252Cpepper`

**Comment by marcingrzejszczak** [comment]
Could you please create a small sample that replicates this issue?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
