### ISSUE TITLE
anyBoolean reference in response generates invalid tests

### ISSUE THREAD

**Issue by katrikken** [spring-cloud/spring-cloud-contract#1329]
When I have parameter `anyBoolean` in the request, and in response, I reference that as `fromRequest`, the test generates as 

`assertThatJson(parsedJson).field("['param']").isEqualTo("true");` But then when I actually send boolean in my response, the test fails, because it expected to find `"true"` string in JSON and not `true` as boolean.

**Comment by marcingrzejszczak** [comment]
As a workaround you can just hardcode the value instead of resolving it from request

**Comment by marcingrzejszczak** [comment]
Can you create a small sample that reproduces the problem or at least a contract?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
