### ISSUE TITLE
When the property contains an array an assertion to validate an empty field is generated

### ISSUE THREAD

**Issue by jdmesalosada** [spring-cloud/spring-cloud-contract#1331]
Hi everyone, when I tried to run the generated tests for the following response body the tests are failing due the following assertion is being generated:

**assertThatJson(parsedJson).field("['**something**']").isEmpty();**

 response {
        status 200

        headers {
            contentType(applicationJson())
        }
        body(
                something: [
                        "fields":
                                [
                                        field1: 49.75,
                                        field2: 6.1667
                                ],

                ],

                "transactionId": consumer(regex('[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}'))

        )

        bodyMatchers {
       
            jsonPath('$.something.fields.field1', byRegex(nonBlank()))
            jsonPath('$.something.fields.field2', byRegex(nonBlank()))

        }
    }

Version: 2.1.1.RELEASE

This happens when I have the body and the body matchers defined in the response.

I really appreciate your help.

Thanks.

**Comment by marcingrzejszczak** [comment]
Please always upgrade to the latest version before filing an issue. We already have 2.1.5.RELEASE and maybe your issue is already fixed?

**Comment by jdmesalosada** [comment]
Ok thanks.
