### ISSUE TITLE
Contract stub with non fixed delay

### ISSUE THREAD

**Issue by JulianAffaire** [spring-cloud/spring-cloud-contract#1340]
Hi,

we wonder if you plan to add more customisation for the delay in the spring cloud contract.
For the moment there is only fixedDelayMilliseconds. I saw that wiremock used fixedDelay, delayDistribution and chunkedDribbleDelay.

It will be a real nice to have, because sometimes we want to use the stub generated to simulate the real call to the service (with realistic delay).

Thanks,
Best regards, 
Julian

**Comment by marcingrzejszczak** [comment]
Sure, we can consider that.

However you know that for the sake of contract tests you don't even need a delay? Contract tests are there to verify that you can communicate. You can use plain old WireMock to verify all the error cases and latencies without using the concept of contract tests.

**Comment by JulianAffaire** [comment]
Yes for sure, for the contract tests we don't want to use any delay :)
But we would like to enjoy the force of spring coul dcontract to generate a stub automatically with the contract. So it would be a real nice to have if the stub could have more customisation on delay.
Or maybe a way to enable disable those delay on the stub depending of an environnement variable (i'm trying to thing of a nice solution).

**Comment by antoinephung** [comment]
@marcingrzejszczak I'm also looking for customize my API response time. It would be very nice if spring cloud contract has function like "delayDistribution" of Wiremocks
