### ISSUE TITLE
Why Wiremock on the Producer side of the contract

### ISSUE THREAD

**Issue by smfaizalkhan** [spring-cloud/spring-cloud-contract#1345]
**Describe the bug**
We are using CDC as part of the project,and we have a maven dependency plugin as well for checking dependency

As we are not using the wiremock,when the maven plugin is executed we get "Unused dependency"

,Why Wiremock is needed (as part of the Managed dependencies) from the spring cloud contract verifier on the producer side.

**Comment by marcingrzejszczak** [comment]
Until now, WireMock's internals are used in some parts of test and stub generation. We're planning on removing that one day in the future but until then this dependency is required.
