### ISSUE TITLE
Error: constant string too long

### ISSUE THREAD

**Issue by Mike497** [spring-cloud/spring-cloud-contract#1348]
Hi, I'm using spring-cloud-contract version 1.2.7.RELEASE.

When I try to load 'text/html' response body data from a file (when defining Groovy contract) and that data is more than 65536 bytes, I get an error 'constant string too long' when compiling Java generated test class. 

Generated test has a lines similar to these:
`String responseBody = response.getBody().asString();
 assertThat(responseBody).isEqualTo("Here goes a very long string read from file in Groovy contract."); // here's the failure`

Loading file to response body in a contract:
`...
contentType(textHtml())
...
body(file("myFileWithLongString.txt"))
...`

**Comment by marcingrzejszczak** [comment]
Please upgrade to the latest release version. 1.2.x is not supported anymore.

**Comment by Mike497** [comment]
Thanks for response, @marcingrzejszczak !

I've updated to the version 2.1.5.RELEASE and still getting the same error. Couldn't upgrade to version 2.2.2.RELEASE (latest ATM) cuz there's a specific 4.x version of gradle at the project and seems like 2.2.x requires 5.x gradle.

Could you please help on the issue?

**Comment by marcingrzejszczak** [comment]
I don't think we'll have another greenwich release so it would be best for you to upgrade really.

Anyways, i don't know why you have this issue. Can you check the sample https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/master/producer/src/test/resources/contracts/beer/rest/shouldGrantABeerIfOldEnoughFromFile.groovy where we have everything working fine?

**Comment by Mike497** [comment]
Please, try to load a file for response with one long string as a contents.
As I see in the above example, you've provided, there is just:

`{
  "status": "OK"
}`

in response.json. 

What if a contract supposed to return a very long string with length more than 65536 bytes?
In my case it generates a non-compilable test class.

**Comment by marcingrzejszczak** [comment]
Ahhh now i get it. The class is too long! What you can do as a workaround is on the producer side pass in the execute method and perform custom verification.

**Comment by marcingrzejszczak** [comment]
BTW why do you need the whole gigantic response body? Is it mandatory for your consumers?

**Comment by Mike497** [comment]
Unfortunately yes.:(

We're developing content-as-a-service solution and in particular cases it is required to have such gigantic responses.

I didn't get clearly your idea about workaround. Do you have an examples on how to "pass in the execute method and perform custom verification"?

**Comment by marcingrzejszczak** [comment]
> We're developing content-as-a-service solution and in particular cases it is required to have such gigantic responses.

Maybe a better idea would be to use mockMvc + rest docs + spring cloud contract? That way you would get tests, documentation and stubs!

> I didn't get clearly your idea about workaround. Do you have an examples on how to "pass in the execute method and perform custom verification"?

Check this out https://cloud.spring.io/spring-cloud-contract/reference/html/project-features.html#contract-dsl-custom-methods

**Comment by Mike497** [comment]
Thanks, will check that out.

**Comment by Mike497** [comment]
@marcingrzejszczak ,

I've checked suggested workaround. Looks like it is working only when response data is expected to be in JSON format. Like this:

`        body(
                data: $(c(file('myFileWithVeryLongString.txt')), p(execute('assertLength($it)')))
        )`

Where assertLength is a method from my baseClassForTests. In this case generated test is compiling fine.

But what if my response is not JSON? Just text/html? If doing something like:

`        body(
                $(c(file('ApcHeaderV1HtmlResponse.txt')), p(execute('assertLength($it)')))
        )`

Is not working. Generated test is asserting 'assertLength($it)' as a string.

**Comment by marcingrzejszczak** [comment]
Yeah you would have to parse it in your assertion method yourself i guess

**Comment by Mike497** [comment]
Unfortunately I cannot...

Due to it is generated as:

`			String responseBody = response.getBody().asString();
			assertThat(responseBody).isEqualTo("assertLength($it)");`

Could you please provide correct groovy syntax on how to write body contract correctly for that case? For now I have:

`body( $(c(file('myFileWithVeryLongString.txt')), p(execute('assertLength($it)'))) )`

**Comment by Mike497** [comment]
@marcingrzejszczak ,

So it looks like that for now it is not possible to get a compilable generated test class for the contract that expects 'text/html' response with a data more than 65536 bytes?

Here's full sample:

`package test

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    description "Sample > 65536 bytes text/html response contract'"
    request {
        headers {
            header 'Accept': 'text/html'
        }
        method GET()
        url("/example") {
            queryParameters {
                parameter("test", "true")
            }
        }
    }
    response {
        headers {
            contentType(textHtml())
        }
        status 200
        body(
                file('fileWithALongStringMoreThan65536Bytes.txt')
        )
    }
}
`

That will generate a test with non-compilable line:

`assertThat(responseBody).isEqualTo("A very long non-compilable string");`

Playing around with 'execute' function and passing there a method from baseClassForTests leads to a generated line like this:

`assertThat(responseBody).isEqualTo("assertLength($it)");`

As soon as response type becomes 'text/html' generated test checks body for exact equality.

**Comment by marcingrzejszczak** [comment]
> So it looks like that for now it is not possible to get a compilable generated test class for the contract that expects 'text/html' response with a data more than 65536 bytes?

Yes.

> assertThat(responseBody).isEqualTo("assertLength($it)");

This is a bug actually :/

**Comment by marcingrzejszczak** [comment]
Please change `file('fileWithALongStringMoreThan65536Bytes.txt')` to `fileAsBytes('fileWithALongStringMoreThan65536Bytes.txt')`. Then your generated test will look like this:

```java
@SuppressWarnings("rawtypes")
public class ContractVerifierTest {

	@Test
	public void validate_readFromLongFile() throws Exception {
		// given:
			MockMvcRequestSpecification request = given()
					.header("Accept", "text/html");

		// when:
			ResponseOptions response = given().spec(request)
					.queryParam("test","true")
					.get("/example");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);
			assertThat(response.header("Content-Type")).matches("text/html.*");

		// and:
			assertThat(response.getBody().asByteArray()).isEqualTo(fileToBytes(this, "readFromLongFile_response_longFile.txt"));
	}

}
```
