### ISSUE TITLE
Documentation - The 2.2 section "On the Consumer Side" has not the correct title style.

### ISSUE THREAD

**Issue by aukustomx** [spring-cloud/spring-cloud-contract#1349]
The 2.2 section of the [documentation](https://spring.io/projects/spring-cloud-contract) page "On the Consumer Side" has not the correct style like section 2.1 has - "On the Producer Side".
I have attached an image as evidence of the issue.
![scc documentation - two different styles](https://user-images.githubusercontent.com/49178465/76572375-7ed90f00-647f-11ea-916b-7241163b6413.png)

**Comment by marcingrzejszczak** [comment]
Care for a pull request against 2.2.x branch?

**Comment by darek1024** [comment]
I want this one 😇

**Comment by marcingrzejszczak** [comment]
Go for it :) @darek1024. Can you please create a PR against 2.2.x branch?

**Comment by OlgaMaciaszek** [comment]
Already fixed.
