### ISSUE TITLE
generateContractTests give StackOverflowError with (no error messages)

### ISSUE THREAD

**Issue by danielbernier** [spring-cloud/spring-cloud-contract#1355]
Hi,

I have a bug using Spring-Cloud-Contract.  The error appears when I use, in the response body with a json file or body directly added, like in the next example : 
```
response {
          headers {
              contentType(applicationJson())
          }
          status OK()
          body( file('reponseCarteADA.json') )
          /*body (
                  "statutProfilAcces": value($(producer("ACTIF")))
          )*/

      }
```
If the body is not the present, all my stubs are created and everything woth as expected.  The full error message is : 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateContractTests'.
> java.lang.StackOverflowError (no error message)

springCloudVersion = "Hoxton.SR2"
Spring-Cloud-Contract : 2.2.2.RELEASE
Spring-Cloud-Services-Dependencies : 2.2.3.RELEASE (I have try with 2.2.2 as well)
Junit 5
spring-cloud-starter-contract-verifier : 2.2.2.RELEASE

That's it I think

Thanks

Daniel

**Comment by danielbernier** [comment]
Hi.  I found the solution to my problem but it will be great if the error message is more explicit.  In the Body of my Request, i used $(producer(... instead of consumer.  When using only producer, it give the error.  What's weird is that the error is their only if their is a body in the Response.  So, it may not be a bug but it could be a nice enhancement.  Tks

**Comment by marcingrzejszczak** [comment]
I can't replicate this with the latest snapshots. I'll close this for now and if you are able to replicate this we'll reopen it.
