### ISSUE TITLE
Spring Cloud Stream doesn't support pollable consumers

### ISSUE THREAD

**Issue by TYsewyn** [spring-cloud/spring-cloud-contract#1357]
When running the SC Contract Verifier in docker in combination with a running broker (eg. Rabbit or Kafka), we get the message that `This binder does not support pollable consumers`.
This issue is to track a possible solution to have a solution with eg. a `SubscribableChannel`.

**Comment by marcingrzejszczak** [comment]
This will be solved by using the Docker with the middleware standalone option: https://docs.spring.io/spring-cloud-contract/docs/3.0.0-SNAPSHOT/reference/html/docker-project.html#docker-middleware-standalone
