### ISSUE TITLE
ignored() call in a contract marks the whole generated tests class as the one to be ignored

### ISSUE THREAD

**Issue by ensigner** [spring-cloud/spring-cloud-contract#1372]
After I mark one of the contract with in one of a few contracts in a contracts folder like following: 

`
Contract.make {
    ignored()
    description "descr"
    request {
        url "/discovery.svc/Environment/WebCapability"
        method GET()
    }

    response {
        status 200
        body(
                file("response/DefaultWeb.xml")
        )
    }
}
`

after a build that follows I get whole generated test class marked as ignored: 

`@SuppressWarnings("rawtypes")
public class ContractVerifierTest extends BaseClass {

	@Test
	@Ignore
	public void method1() throws Exception {
		// given:
...

		// when:
...		// then:
...
		// and:;
	}

	@Test
	@Ignore
	public void method2() throws Exception {
		// given:
...

		// when:
	...
		// then:
	...
		// and:;
	}

	@Test
	@Ignore
	public void method3() throws Exception {
		// given:
...

		// when:
...
		// then:
...
		// and:;
	}

	@Test
	@Ignore
	public void method4() throws Exception {
		// given:
	...

		// when:
	...
		// then:
...
		// and:;
	}
///etc.
	}
`

I use: 
<artifactId>spring-cloud-contract-starters</artifactId>
		<version>2.2.0.RC2</version>

**Comment by marcingrzejszczak** [comment]
2.2.0.RC2 ? Please use the latest version.
