### ISSUE TITLE
Documentation for 3.0.0.M1 not properly published

### ISSUE THREAD

**Issue by jwalter** [spring-cloud/spring-cloud-contract#1380]
**Describe the bug**
On the Spring Cloud Contract site in the Learn section, https://spring.io/projects/spring-cloud-contract#learn, there is a link to 3.0.0.M1, https://cloud.spring.io/spring-cloud-static/spring-cloud-contract/3.0.0.M1/, but trying to navigate to it returns a 404 error page.

**Comment by spencergibb** [comment]
We need to update the link to https://cloud.spring.io/spring-cloud-static/spring-cloud-contract/3.0.0.M1/reference/html/

**Comment by spencergibb** [comment]
it's done
