### ISSUE TITLE
StubRunnerStreamMessageSelector doesn't correctly match RegexProperties

### ISSUE THREAD

**Issue by mtthwcmpbll** [spring-cloud/spring-cloud-contract#1382]
**Describe the bug**
We've got a message-based contract that describes a message triggered by an input message.  The contract contains a header using the `anyUuid()` regex pattern.  The producer side tests generate correctly and validate things are doing the right thing, but the consumer-side stubs can't seem to correctly match this contract.

When debugging the consumer tests, I see that the consumer publishes the input message and it triggers the StubRunnerStreamMessageSelector, which then goes through each contract in the stub to find the one matching the input message.  When it gets to the correlationId header using the anyUuid() matcher, it compares the regex string as a string and not as a RegexPattern and fails to match the contract correctly.

The tests pass if I replace the anyUuid() with a specific value for the stub/consumer, but it seems like this should work given the check in StubRunnerStreamsMessageSelector that tries to check if a property is an instance of RegexProperty.

**Sample**

The contract showing this issue:
```groovy
org.springframework.cloud.contract.spec.Contract.make {
    description 'Fetch additional user details using an RPC-style interface'
    label 'fetch-user-details-rpc'

    input {
        messageFrom('getUserDetailsRequests')
        messageBody([
                userId: 1234
        ])
        messageHeaders {
            header('contentType', 'application/json')
            header('correlationId', anyUuid())
        }
    }

    outputMessage {
        sentTo('getUserDetailsResponses')
        body([
                "userId": $(stub(1234), test(anyPositiveInt())),
                "userFirstName": $(stub("John"), test(anyNonEmptyString())),
                "userLastName": $(stub("Doe"), test(anyNonEmptyString())),
                "storeName":  $(stub("\"Store 8001\""), test(anyNonEmptyString())),
                "storeId": $(stub("8001"), test(regex('\\d+'))),
        ])
        headers {
            header('contentType', 'application/json')
            header('correlationId', $(execute('assertThat(response.getHeader("correlationId")).isEqualTo(inputMessage.getHeaders().get("correlationId"))')))
        }
    }
}
```

A consumer test that fails due to the stubs not matching the input message and generating the output message:

```java
@SpringBootTest
@AutoConfigureStubRunner(ids = {"com.example:producer:+:stubs:9090"}, stubsMode = StubRunnerProperties.StubsMode.LOCAL)
public class ConsumerApplicationTests {

	@Autowired
	private UserClientRpc userClientRpc;

	@Test
	public void getUserDetailsRpc_respondsWithValidDetails() {
		// when
		UserDetailsDto userDetails = userClientRpc.getUserDetails(1234).block(Duration.ofMillis(5000));

		// then
		Assertions.assertNotNull(userDetails);
		Assertions.assertEquals("John", userDetails.getUserFirstName());
		Assertions.assertEquals("Doe", userDetails.getUserLastName());
		Assertions.assertEquals("Shoppers Drug Mart 1000", userDetails.getStoreName());
		Assertions.assertEquals(8001, userDetails.getStoreId());
	}

}
```

Attached is the full project containing the producer and consumer example projects.  See the contract in `producer/src/test/resources/contracts/consumer1/rpc` and the last test in the `ConsumerApplicationTests` for the failing scenario.

**Comment by mtthwcmpbll** [comment]
Example project:  [contracts-regex-issue.zip](https://github.com/spring-cloud/spring-cloud-contract/files/4487874/contracts-regex-issue.zip)

**Comment by OlgaMaciaszek** [comment]
I was able to reproduce the issue.
