### ISSUE TITLE
Error generateTests when using JDK14

### ISSUE THREAD

**Issue by rphua** [spring-cloud/spring-cloud-contract#1387]
When performing mvn clean install on our project. Results in a error in the generateTests:

Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.2.2.RELEASE:generateTests (default-generateTests) on project bff-verevening: Unable to parse configuration of mojo org.springframework.cloud:spring-cloud-contract-maven-plugin:2.2.2.RELEASE:generateTests for parameter testFramework: Cannot set 'testFramework' in class org.springframework.cloud.contract.maven.verifier.GenerateTestsMojo

I found on gradle that this is a gradle issue. But we don't use gradle in our project so we don't want to install gradle to fix this particular problem.
(https://github.com/gradle/gradle/issues/10248  if you search for "springframework.cloud" then you'll see someone else having the same problem).

**Comment by OlgaMaciaszek** [comment]
Hi @rphua Thanks for reporting it. Was able to reproduce it.

**Comment by rphua** [comment]
Hello! 

What is the estimated time for the fix? Then we can take it into account :) 

Thanks in advance!

**Comment by OlgaMaciaszek** [comment]
We'll have to upgrade Gradle in the `2.2.x` branch to `6.3`. Will work on it next week.

**Comment by OlgaMaciaszek** [comment]
Fixed.
