### ISSUE TITLE
RestEasy client and Groovy: Content-type with suffix '+json' not working (broken with 2.2.2)

### ISSUE THREAD

**Issue by gpietrek** [spring-cloud/spring-cloud-contract#1388]
**Describe the bug**
RestEasy client and Groovy: When using a Content-type with the suffix '+json' the generated code has the wrong Content-type. Seems like it is always 'application/json'.
It works with 2.1.3.RELEASE and is broken with 2.2.2.RELEASE.

**Sample**
Groovy:
```
package contracts
import org.springframework.cloud.contract.spec.Contract
Contract.make {
  request {
    method("POST")
    url("/ping")
    headers {
      header('Content-Type': 'application/my-content-type+json')
    }
    body($(test(value: "test"), stub(anyNonEmptyString())))
  }
  response {
    status 200
  }
}
```

Java code generated with 2.1.3.RELEASE:
```
	@Test
	public void validate_test() throws Exception {
		// when:
			Response response = webTarget
					.path("/ping")
					.request()
					.method("POST", entity("{\"value\":\"test\"}", "application/my-content-type+json"));
		// then:
			assertThat(response.getStatus()).isEqualTo(200);
	}
```

Java code generated with 2.2.2.RELEASE:
```
        @Test
	public void validate_test() throws Exception {
		// when:
			Response response = webTarget
							.path("/ping")
							.request()
							.build("POST", entity("{\"value\":\"test\"}", "application/json"))
							.invoke();
		// then:
			assertThat(response.getStatus()).isEqualTo(200);
	}
```

**Comment by Xexanos** [comment]
I would also be interested in a solution of this Bug.

**Comment by DominikPieper** [comment]
A fix would be great

**Comment by OlgaMaciaszek** [comment]
Hi, @gpietrek 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by gpietrek** [comment]
Hi @OlgaMaciaszek 
A complete example is here: https://github.com/gpietrek/ping
Please take a look at the README there.

**Comment by OlgaMaciaszek** [comment]
I was able to confirm it. It's a bug.

**Comment by marcingrzejszczak** [comment]
Thanks @gpietrek for filing the issue. It should be fixed in the upcoming release.

**Comment by gpietrek** [comment]
OK, I tried it, it's fixed
Thanks for your response!
