### ISSUE TITLE
Provide stub-based load-balancing with Spring Cloud LoadBalancer

### ISSUE THREAD

**Issue by hughwphamill** [spring-cloud/spring-cloud-contract#1391]
**Describe the bug**
Using ribbon for contract tests works fine, using the Spring Reactive Loadbalancer results in contract tests returning 503 with errror "unable to find instance for \<serviceId\>"

**Sample**
Example: https://github.com/hughwphamill/spring-contract-test-issue

**Comment by hughwphamill** [comment]
I should say, this is with Spring Boot 2.2.5, and Spring Cloud Hoxton.SR3 and 2.0.1.RELEASE of the Spring Cloud Contract Maven Plugin

**Comment by OlgaMaciaszek** [comment]
Have verified it. In fact, in the case of Ribbon implementation, there are custom implementations of `DiscoveryClient` and Ribbon `ServerList` that make it possible to use stub instances from StubRunner during load-balancing.

We need to add implementation that will provide feature parity for SC LoadBalancer.

**Comment by marcingrzejszczak** [comment]
Could you please check the latest snapshots and confirm that the issue got resolved?

**Comment by hughwphamill** [comment]
Stupid question, but is that 2.2.3-SNAPSHOT as referenced on https://spring.io/projects/spring-cloud-gateway#learn ?

**Comment by marcingrzejszczak** [comment]
It's not a stupid question :) wait 15 minutes or so for the snapshots to get built and published and indeed update to `2.2.3.BUILD-SNAPSHOT` and `Hoxton.BUILD-SNAPSHOT`. I did that with your sample and it worked fine for me but getting a second pair of :eyes: is always much appreciated ;)

**Comment by hughwphamill** [comment]
Will do, and I'll let you know, thanks for the quick turnaround, I love this project!

**Comment by hughwphamill** [comment]
@marcingrzejszczak I updated to 2.2.3.BUILD-SNAPSHOT and Hoxton.BUILD-SNAPSHOT and can confirm the issue is resolved, thank you!

**Comment by marcingrzejszczak** [comment]
Great to hear!
