### ISSUE TITLE
Incorrect parsing of fully qualified class names when using the Java DSL (v2.2.2)

### ISSUE THREAD

**Issue by emilemil1** [spring-cloud/spring-cloud-contract#1398]
When using Spring Cloud Contract Gradle Plugin (v2.2.2) and the Java DSL, I noticed that the following exception was thrown when generating stubs.

java.lang.IllegalStateException: Class with name [ClassName] not found

After some debugging I concluded that this is due to incorrect parsing of the fully qualified class name, more specifically the class package. The culprit is the PACKAGE_PATTERN in ContractVerifierDslConverter.groovy, which specifies the pattern: .+?package (.+?);.+?
This pattern requires that the package keyword is preceded by at least one symbol.

So the package would not be matched in this example:
```
package foo.bar;
...
```
But it would in this example:
```
//fix
package foo.bar;
...
```
Even though both should be perfectly valid.

Adding a comment to each contract is a workaround until this gets fixed.

**Comment by OlgaMaciaszek** [comment]
Thanks, @emilemil1.  Was able to reproduce it. Will fix it now.
