### ISSUE TITLE
How can I use SpringCloudContract for third party providers to create stubs

### ISSUE THREAD

**Issue by d-yandrapu** [spring-cloud/spring-cloud-contract#1399]
In our project, we need to work on multiple services. so started implementing Spring cloud contract testing between two services. (internal services ex: BookService, Employee Service)

Our Requriment : 
----------------
- How Can I implement Spring cloud contact for Third-party service( ex: AccessService) where we can access only API's but no control on Dev Code Base.

**Comment by ramareddy88** [comment]
Hi
Me too facing the same need help on how to achieve my requirement

**Comment by OlgaMaciaszek** [comment]
The base idea of contracts is that you can ensure that the producer API matches the requirements codified in the contract files. If that is not possible (you don't own the producer code base and you cannot do contract PRs to producer codebase), this approach will not be helpful for you. So you can use contracts for the services in which you can verify producer code against them and use a different approach for external services.
