### ISSUE TITLE
WireMockRestAssuredConfiguration overwrites the default snippets

### ISSUE THREAD

**Issue by dimitri-rebrikov** [spring-cloud/spring-cloud-contract#1400]
**Describe the bug**
The org.springframework.restdocs.config.SnippetConfigurer defines a list of default snippets widely used in the REST documentation generation.
For the case you application does both, provides a REST API and accesses to another "foreign" REST API,
the application has unit tests where both RestAssured&Co. and WireMock are used.
In this case the WireMockRestAssuredConfiguration overwrites the default list of snippets by using of "configurer.snippets().withDefaults(new WireMockSnippet());" so the default snippets are not generated and the documentation relaying on them is broken.

**Proposal**
The WireMockRestAssuredConfiguration shall use "configurer.snippets().withAdditionalDefaults(new WireMockSnippet());" so it will register its own default snippet without removing the existing some.

**Sample**
1. Define an application which provides a REST Interface and uses another REST Interface.
2. Implement the unit test of the own REST Interface using RestAssured and simulate the "another" REST Interface using WireMock
3. Configure RestDocs accordingly to the "Auto-configured Spring REST Docs Tests" Spring Boot Docs Chapter
4. Run the tests
5. Inspect the build/generated-snippets
6. See that no snippets except the WireMock's stups are generated

**Workaround**
The only way I found is to add all "default" snippets I need to the document filter in the RestAssured call.

**Comment by OlgaMaciaszek** [comment]
Thanks @dimitri-rebrikov . Makes sense. Will change that.

**Comment by OlgaMaciaszek** [comment]
Fixed by: https://github.com/spring-cloud/spring-cloud-contract/commit/ca90c521b3d4e236271146674a7c4d7260976579
