### ISSUE TITLE
SpringAmqpStubMessages does not utilize amqp post processors

### ISSUE THREAD

**Issue by jaredculp** [spring-cloud/spring-cloud-contract#1403]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

Spring cloud version `Hoxton.SR4`.

It appears that the `SpringAmqpStubMessages` class does not respect any post processors configured on a `RabbitTemplate` like this:
```
@Bean
RabbitTemplate rabbitTemplate(ConnectionFactory connectionFactory) {
  final RabbitTemplate rabbitTemplate = new RabbitTemplate(connectionFactory);
  rabbitTemplate.setMessageConverter(messageConverter());
  rabbitTemplate.setBeforePublishPostProcessors(new GZipPostProcessor());
  rabbitTemplate.setAfterReceivePostProcessors(new GUnzipPostProcessor());
  return rabbitTemplate;
}
```

Running the generated producer test yields:
```
org.springframework.amqp.support.converter.MessageConversionException: Failed to convert Message content
```

Is this a bug or intended feature?

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Sample is here: https://github.com/jaredculp/spring-cloud-contract-amqp.

The first commit sets up a basic producer/consumer with contracts over amqp. The second commit introduces a GZipPostProcessor which causes the contract to break. Stack trace is included in that commit.

**Comment by jaredculp** [comment]
If I do gzip/gunzip in a message converter like this it works fine:
```
  @Bean
  MessageConverter messageConverter() {
    final MessageConverter delegate = new Jackson2JsonMessageConverter();
    return new MessageConverter() {
      @Override
      public Message toMessage(Object o, MessageProperties messageProperties)
          throws MessageConversionException {
        final Message m = delegate.toMessage(o, messageProperties);
        final ByteArrayOutputStream os = new ByteArrayOutputStream();
        try (GZIPOutputStream gz = new GZIPOutputStream(os)) {
          gz.write(m.getBody());
        } catch (IOException e) {
          throw new MessageConversionException(e.getMessage());
        }

        return new Message(os.toByteArray(), messageProperties);
      }

      @Override
      public Object fromMessage(Message message) throws MessageConversionException {
        final ByteArrayOutputStream os = new ByteArrayOutputStream();
        try (GZIPInputStream is = new GZIPInputStream(new ByteArrayInputStream(message.getBody()))) {
          byte[] b = new byte[8096];
          int r;
          while ((r = is.read(b)) != -1) {
            os.write(b, 0, r);
          }
        } catch (IOException e) {
          throw new RuntimeException(e);
        }

        return delegate.fromMessage(new Message(os.toByteArray(), message.getMessageProperties()));
      }
    };
  }

```

So the question is really just whether or not the afterReceivePostProcessor should be running inside the `ContractVerifierAmqpAutoConfiguration#ContractVerifierHelper` class.

**Comment by jaredculp** [comment]
This is further complicated on the consumer side. If the contract has a non-gzipped message body, then _that_ is what gets stubbed out to be sent to the consumer-side test.

I tried setting the body as the gzipped contents (by reading from a file), but that failed on the producer side, since the generated test assumes the content is JSON-parseable.

**Comment by marcingrzejszczak** [comment]
I'll have to take your sample for a spin. I'm just back from a PTO so give me some time.

**Comment by marcingrzejszczak** [comment]
Would the option to use the actual RabbitMQ broker via test containers like here [producer](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.0.x/producer_rabbit_middleware) and here [consumer](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.0.x/consumer_rabbit_middleware) be ok to you? Would it solve your problem?

**Comment by jaredculp** [comment]
I'll take a closer look, but it seems like the right idea.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
