### ISSUE TITLE
Need support for webhooks / callback URI

### ISSUE THREAD

**Issue by rohitdev** [spring-cloud/spring-cloud-contract#1406]
I've a use case where i call a service and it responds back via webhook. 

In wiremock we have a step for postserve action which is something that can help me in solving this if i use wiremock directly but i want to use SCC to test out my contracts as well as allow consumers a completness in their testing with the stub.
PACT has this feature  -> https://docs.pact.io/pact_broker/advanced_topics/api_docs/webhooks

Request you to please consider this feature as an enhancement as part of SCC

**Comment by marcingrzejszczak** [comment]
We'd need to extend the DSL to support webhooks and add support on stub side (https://github.com/wiremock/wiremock-webhooks-extension)
