### ISSUE TITLE
Can't pass artifactId to spring-cloud-contract-docker

### ISSUE THREAD

**Issue by ahlinist** [spring-cloud/spring-cloud-contract#1408]
I'm trying to publish stubs generated from yaml DSL in a nodejs project. I'm following this document: https://cloud.spring.io/spring-cloud-contract/reference/html/docker-project.html

The issue is that the full artifactory url is composed from groupId, artifactId and version. But I can't set up an artifactId as given in the doc. I'm setting the PROJECT_NAME env variable with the value I need but artifactId is set as "spring-cloud-contract" (the documentation states that it should default to "example")

I've prepared a reproducible example with DSL and script containing docker run command:
https://github.com/ahlinist/spring-cloud-contract-docker

My expectation is that it will try to push to:
https://my.jfrog/com/ahlinisty/myprojectname/LATEST/myprojectname-LATEST...

But instead it pushes to:
https://my.jfrog/com/ahlinisty/spring-cloud-contract/LATEST/spring-cloud-contract-LATEST...

Could you kindly advise what am I missing? How can I pass an artifactId properly?

**Comment by marcingrzejszczak** [comment]
I think I've replied to you in an email but let's move it here. Can you confirm that in the running container the `settings.gradle` file contains the updated project name? I think that due to the fact that you're running your own command the `settings.gradle` is not updated properly. Maybe we should change the publication mechanism to include the artifact name from the environment variables?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
