### ISSUE TITLE
ANY_DATE pattern invalid date

### ISSUE THREAD

**Issue by aaguila** [spring-cloud/spring-cloud-contract#1412]
**Describe the bug**

Error in generated date using RegexPatterns.ANY_DATE. Regex could generate invalid dates, in this example the date is 31 of April.

Version: 2.2.2

**Sample**
`Contract.make {
  request {
    method('GET')
    urlPath('/data') {
      queryParameters {
        parameter('search',value(regex("created\\>" + RegexPatterns.ANY_DATE + ",created\\<" + RegexPatterns.ANY_DATE)))
      }
    }`

Regex generate a `1037-04-31` -> But April has not 31 days.

**Comment by marcingrzejszczak** [comment]
We can't do much about that date. I mean if there are any regex experts out there then we're more than happy to accept PRs ;) For now I'm closing this.
