### ISSUE TITLE
Regex in Status Response

### ISSUE THREAD

**Issue by siddiqarz** [spring-cloud/spring-cloud-contract#1413]
> I am unable to verify a range of status responses in contract. 

Question was asked on stackoverflow and asked to raise as an issue. 

Bug report
Using version 2.1

Issues is that when posting on server start up, the item gets created and status comes back as 201, afterwards, item exists and status comes back as 200. I'd like to be able to have the test pass on any 200 range. 
 
package contracts
```
org.springframework.cloud.contract.spec.Contract.make
request {
            method 'POST'
            url value (p('/api/test')), c(~/\/api/test\/.*/))
            headers {
                 contentType(applicationJson)
               }
           body(["value":"someValue"])
        }
        response {
            status (regex'...')
              headers {
                 contentType(applicationJson)
               }
             body([
                    "_index": "",
                    "_type": "",
                    "_id":"someValue"
                 ])
        }
    }

```
ERROR: groovy.lang.MissingMethodException: No signature of method: contracts.test.status() is applicable for argument types: (org.springframework.cloud.contract.spec.internal.RegexProperty, org.springframework.cloud.contract.spec.internal.ClientDslProperty) values: [regexValueUsed], org.springframework.cloud.contract.spec.internal.ClientDslProperty(DslProperty(clientValue:201, serverValue: 201))

**Comment by marcingrzejszczak** [comment]
Have you tried using version `2.x` ? I do see a `status(...)` version that should allow picking `regex()`

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
