### ISSUE TITLE
SpringCloudLoadBalancerAutoConfiguration references LoadBalancerAutoConfiguration in spring-cloud-loadbalancer

### ISSUE THREAD

**Issue by tjoner** [spring-cloud/spring-cloud-contract#1419]
When upgrading spring-cloud-dependencies to Hoxton.SR5 we received errors in our spring cloud contract client stub tests where we're using Spring Cloud Contract Stub Runner for running the WireMock instances to simulate the actual service being called. When running the test, we received class not found exception for java.lang.ClassNotFoundException: org.springframework.cloud.loadbalancer.config.LoadBalancerAutoConfiguration

It works fine with spring-cloud-dependencies Hoxton.SR4 but not with Hoxton.SR5. By adding additional dependency to spring-cloud-loadbalancer, the contract client stub tests pass. 

It seems that SpringCloudLoadBalancerAutoConfiguration references the `org.springframework.cloud.loadbalancer.config.LoadBalancerAutoConfiguration` located in the spring-cloud-loadbalancer

**Comment by marcingrzejszczak** [comment]
Please wait until snapshots are available (~15 minutes) and can you please try again with the latest snapshots? 

If someone else has a similar issue please follow this workaround

> By adding additional dependency to spring-cloud-loadbalancer, the contract client stub tests pass.

**Comment by sguillope** [comment]
For us a better workaround was to set the property `stubrunner.cloud.loadbalancer.enabled` to `false` in our `@SpringBootTest`

```kotlin
@SpringBootTest(
    properties = [
        "stubrunner.cloud.loadbalancer.enabled=false"
    ]
)
```

Adding `spring-cloud-loadbalancer` as test dependency caused all sort of other integration tests to fail in our project.

**Comment by martinvisser** [comment]
This issue still exists in Hoxton.SR6

**Comment by marcingrzejszczak** [comment]
Do you have a sample that replicates the problem?

**Comment by martinvisser** [comment]
No, because it's part of a big project. I made a diff between the dependencies from SR5 and SR6, but the only difference I see is `org.springframework.cloud:spring-cloud-function-compiler:jar:3.0.7.RELEASE` and `org.springframework.cloud:spring-cloud-function-core:jar:3.0.7.RELEASE`, they both went to `3.0.8.RELEASE`.
Should I expect more changes? Maybe for sleuth?

**Comment by marcingrzejszczak** [comment]
The sr6 was only for stream.
