### ISSUE TITLE
No way to provide Pact token for Dius Pact broker

### ISSUE THREAD

**Issue by lukes1979** [spring-cloud/spring-cloud-contract#1420]
The Dius hosted pact solution now requires a token rather then username / password.  Is there a way to provide this?
Similar to [this](https://github.com/spring-cloud/spring-cloud-contract/issues/636) previous issue, but with a token auth.  

```
<configuration>
  <contractsRepositoryUrl>pact://https://pocJKHSAJ.pact.dius.com.au:443</contractsRepositoryUrl>
  ...
</configuration>
```
Thanks

**Comment by marcingrzejszczak** [comment]
I think we've added that in the latest release 3.0.0-m2 https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-tools/spring-cloud-contract-pact/src/main/groovy/org/springframework/cloud/contract/stubrunner/PactStubDownloaderBuilder.java#L312 you can try adding the property

**Comment by lukes1979** [comment]
I tried on 3.0.0-M2 using both of the approaches below, neither seemed to work.

Maven plugin:
`<contractsRepositoryToken>myToken</contractsRepositoryToken>`

Env variable property:
`-Dpactbroker.auth.token=myToken`

**Comment by marcingrzejszczak** [comment]
Can you please try the system property in such a form `-Dstubrunner.pactbroker.auth.token=myToken` ? Or like described in https://docs.spring.io/spring-cloud-contract/docs/3.0.0-SNAPSHOT/reference/html/maven-project.html#maven-configuration-options  `<contractsProperties><pactbroker.auth.token>myToken</pactbroker.auth.token></contractsProperties>` ?

**Comment by lukes1979** [comment]
I tried system property and via plugin configuration in the POM and neither resolve the issue for me unfortunately.

For example the following failed:
```
<plugin>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-contract-maven-plugin</artifactId>
	<version>3.0.0-M2</version>
	<extensions>true</extensions>
	<configuration>
		<contractsRepositoryUrl>${pact.url}</contractsRepositoryUrl>
		<contractsProperties>
			<pactbroker.auth.token>${pact.auth}</pactbroker.auth.token>
		</contractsProperties>
		<contractsMode>REMOTE</contractsMode>
		<contractsPath>my-path</contractsPath>
		<contractDependency>...</contractDependency>
		<baseClassForTests>MyBaseClass</baseClassForTests>
	</configuration>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-contract-pact</artifactId>
			<version>3.0.0-M2</version>
		</dependency>
	</dependencies>
</plugin>
```

Do you have a sample POM plugin configuration that uses auth that I can attempt to follow please?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
