### ISSUE TITLE
Make anyOf randomly return any of the values, not always the 1st one

### ISSUE THREAD

**Issue by sguillope** [spring-cloud/spring-cloud-contract#1424]
**Is your feature request related to a problem? Please describe.**
We're using messaging contract tests quite a bit in our pipelines and we've just found an issue where one of the enum values being passed down had a typo in it. It was never caught by the consumer contract tests because it happened to be the 2nd value declared for the field int he contract, using `anyOf(...)`.

**Describe the solution you'd like**
I'm not sure if it was a deliberate decision to [always use the 1st value provided to `anyOf()`](https://github.com/spring-cloud/spring-cloud-contract/blob/v2.2.3.RELEASE/specs/spring-cloud-contract-spec-java/src/main/java/org/springframework/cloud/contract/spec/internal/PatternValueDslProperty.java). I'm wondering if it could instead randomly pick from any of the values declared in the contract. Most of the other DSL properties already leverage random value generation so it seems reasonable to also do it for enums.

Change: (haven't tested at all)
```java
@Override
public T anyOf(String... values) {
    return createAndValidateProperty(RegexPatterns.anyOf(values), values[0]);
}
```
to
```java
@Override
public T anyOf(String... values) {
    final int d = this.random.nextInt(values.length)
    return createAndValidateProperty(RegexPatterns.anyOf(values), values[d]);
}
```

**Describe alternatives you've considered**
Create separate contracts, 1 per enum value. This obviously doesn't scale as we can have many different enums and enum values.

**Additional context**
N/A

**Comment by marcingrzejszczak** [comment]
With WireMock 2.27.0 (#1440) we'll be able to call `{{pickRandom ...}} Handlebars helper to randomly select an item from a list.`

**Comment by sguillope** [comment]
Hey Marcin, when I opened this issue it was in the context of messaging contract tests, not REST, so there is so AFAIK WireMock wouldn't help right?
What do you think?

**Comment by marcingrzejszczak** [comment]
Yeah, that's correct.
