### ISSUE TITLE
Contract verifier fails to generate tests with xml with namespaces

### ISSUE THREAD

**Issue by javiersvg** [spring-cloud/spring-cloud-contract#1427]
**Describe the bug**
When defining a contract with an xml that has defined namespaces the generated tests validations are wrongly generated.
I was able to trace the issue to this class in the verifier module ```XmlToXPathsConverter``` but I am not sure about what the solution might be. 
The method ```getNodeValue``` returns an empty string even though the xml has a value.

**Sample**
This repo has an example of the bug.
https://github.com/javiersvg/contract-verifier-xml-bug-demo
It has a minimal contract and runs it with the test runner docker image.

**Comment by javiersvg** [comment]
I created a test that should help reproduce the issue. For some reason I am not able to run the tests though. Hope this helps.

**Comment by javiersvg** [comment]
Do you have any eta for this problem or anything I could do to help get this solved as this problem is preventing me from adopting spring contract for my project. Also I can not run the tests in the verifier as java doc fails in java 11. Which jdk should I run it with?

**Comment by marcingrzejszczak** [comment]
I didn't have time to start working on this. If you want to help please be my guest. Checkout 2.2.x branch and use jdk8.

**Comment by javiersvg** [comment]
I have crated this pr but is failing due to security issues but can't see why.
https://github.com/spring-cloud/spring-cloud-contract/pull/1444

**Comment by javiersvg** [comment]
I recreated the PR because there was a problem with the branch now should be correct. Though it is still failing due to a security test failure in the tests run by spring's snyk profile that I can't see. 
https://github.com/spring-cloud/spring-cloud-contract/pull/1445

**Comment by javiersvg** [comment]
I have created this PR to fix the remaining places where XPath is used so that the library handles the XML with namespaces everywhere. @marcingrzejszczak please reopen the issue if it is OK with you as I am not bale the find how to do so.

PR: https://github.com/spring-cloud/spring-cloud-contract/pull/1446

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/pull/1446
