### ISSUE TITLE
Content Type being append with charset=ISO-8859-1

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [spring-cloud/spring-cloud-contract#1428]
Hello!

I'm updating a Spring Boot 2.2 app with Spring Cloud Hoxton.SR1 to Spring Boot 2.3 with Hoxton.SR5, and the provider tests started to fail. The test fail with the following message:

```
DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'application/json;charset=ISO-8859-1' not supported]
```

Something is appending the `charset=ISO-8859-1` to the `Content-Type` header, even tho our contract DSL sets it to `application/json` only:

```groovy
Contract.make {
    description 'create something'
    request {
        method POST()
        url '/something'
        body(
            property: 'value'
        )
        headers {
            contentType(applicationJson()) // This is "application/json"
        }
    }
    response {
        status OK()
    }
}
```

I think UTF-8 is the default for Spring Boot 2.2 onward, so it was not necessary anymore to use `applicationJsonUtf8()` as content type. If I do change the content type to `applicationJsonUtf8()`, then that `charset=ISO-8859-1` is not appended and the test pass.

Is appending a default charset an expected behavior for Spring Cloud Contract?

Best regards,
Rafael Pacheco.

**Comment by bidadh** [comment]
I've created a sample repo for this issue:

https://github.com/bidadh/scc-content-type-issue

**Comment by michaelvanbosch** [comment]
Also seeing this issue

**Comment by LiaminRoman** [comment]
Hi all, 
I had a simial issue, here my investigations:
 Spring Boot 2.3 uses Spring-web 5.2.7, (Spring Boot 2.2 used Spring-Web 5.2.6)
 Spring-web v.5.2.7 has a class AbstractJackson2HttpMessageConverter and it was modified - it started to check encoding for Json body (canRead(@Nullable MediaType mediaType)), so now only null encodign or UTF-xx supported.
 
 On other hand RestAssured (3.3 in my case) by default uses ISO_8859_1 as defaultContentCharset (see deafult constructor of RestAssuredMockMvcConfig -> new EncoderConfig()) and if you don't specify any charset excplisitly in the request content-type - it will add the defalt one.

 So Spring Boot 2.3 (Spring Web 5.2.7) becomes more strict to headers.

 My solution was to bring custom configuration to RestAssured:
`         RestAssuredMockMvc.config =  new RestAssuredMockMvcConfig()
            					.encoderConfig(new EncoderConfig(UTF_8.name(), UTF_8.name()));`

**Comment by kuberr** [comment]
> Hi all,
> ...
> My solution was to bring custom configuration to RestAssured:
> ` RestAssuredMockMvc.config = new RestAssuredMockMvcConfig() .encoderConfig(new EncoderConfig(UTF_8.name(), UTF_8.name()));`
> 

I have this exact issue in my MockMvC mockHttRequests (unit tests):

```
  mockMvc.perform(MockMvcRequestBuilders.post(ENUM_BODY_ENDPOINT)
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"testEnum\": \"CODE_A  \"}"))
                .andExpect(status().isBadRequest());
```

Suddenly gave the error "http 415: application/json;charset_ISO_8859_1" is not supported. I fixed the unit test by changing the MediaType:

```
  mockMvc.perform(MockMvcRequestBuilders.post(ENUM_BODY_ENDPOINT)
                .contentType(MediaType.APPLICATION_JSON_UTF8_VALUE)
                .content("{\"testEnum\": \"CODE_A  \"}"))
                .andExpect(status().isBadRequest());
```

But this media type is deprecated. Could you guide me towards how can I can configure for MockMvc what you did for RestAssured?

**Comment by jekanik** [comment]
Hi! There was a small bug https://github.com/rest-assured/rest-assured/pull/1341 in Rest Assured lib that was appending `charset=ISO-8859-1` instead of using `charset=UTF-8` as default for content type `application/json`. I've fixed it, maintainer merged and created release **4.3.1** (2020-07-03). Updating artifact is fixing this issue for me. 
Pls feel free to try and share your thoughts. Thanks.

**Comment by marcingrzejszczak** [comment]
Since Spring Boot is using 3.3.0 version of rest assured I asked for applying the fix in 3.3.x branch.

**Comment by leonard84** [comment]
Just FYI Spring removed the charset parameter completely https://github.com/spring-projects/spring-framework/issues/22788 since https://tools.ietf.org/html/rfc7159#section-11 does not define any parameters for `application/json`.

**Comment by marcingrzejszczak** [comment]
Maybe we should add this as the documentation entry until this https://github.com/spring-projects/spring-boot/issues/22303 issue gets resolved...

**Comment by mattdimond** [comment]
@MaciejZiarko this seems to give us the same effect. 
java.lang.IllegalStateException: You haven't configured a MockMVC instance. You can do this statically

**Comment by mattdimond** [comment]
@marcingrzejszczak 
    java.lang.IllegalStateException: You haven't configured a MockMVC instance. You can do this statically Still occurs. Also we have noticed the github examples have the only structure not the new structure with package contractTest. Is there a working example of this?

**Comment by marcingrzejszczak** [comment]
> java.lang.IllegalStateException: You haven't configured a MockMVC instance. You can do this statically Still occurs

Most likely you're generating tests in JUnit 5 and have the JUnit 4 before section which is not executed.

> Is there a working example of this?

https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/master/producer_with_latest_3_0_features_gradle/src/contractTest

**Comment by marcingrzejszczak** [comment]
This got fixed https://github.com/spring-projects/spring-boot/issues/22303 so I guess we can close this issue

**Comment by RSevumyan** [comment]
Found workaround without configuring MockMvc, just need add charset=UTF-8 to the content type header
```
headers {
   contentType('application/json;charset=UTF-8')
}
```

**Comment by sub10xsen** [comment]
Hi, 

We are using 4.5.1 rest assured , Spring boot 2.7.3   - The issue with content-type getting appended with charset=ISO-8859-1 is still there. Could anyone please suggest how you resolved it please. Thank you

**Comment by sub10xsen** [comment]
We managed to use this feature https://github.com/rest-assured/rest-assured/issues/635 and resolved it .. Thank you
