### ISSUE TITLE
Sample code in documentation is unreadable (black on black text)

### ISSUE THREAD

**Issue by ddebree** [spring-cloud/spring-cloud-contract#1432]
**Describe the bug**
Due to the coloring of the code blocks, it is really hard to read the documentation.

**Sample**
For example, accessing: [https://cloud.spring.io/spring-cloud-contract/2.2.x/reference/html/getting-started.html#getting-started-first-application-producer](https://cloud.spring.io/spring-cloud-contract/2.2.x/reference/html/getting-started.html#getting-started-first-application-producer) - The text in the xml block appears to be black on black background.

**Comment by marcingrzejszczak** [comment]
We've migrated the documentation to docs.spring.io. Please check it out here https://docs.spring.io/spring-cloud-contract/docs/2.2.x-SNAPSHOT/reference/html/getting-started.html#getting-started-first-application-producer
