### ISSUE TITLE
Base class with several configurations for same exchange fails to identify the configuration to use

### ISSUE THREAD

**Issue by gorkagaray** [spring-cloud/spring-cloud-contract#1439]
**Describe the bug**
Using spring-cloud-contract-gradle-plugin version 2.1.5.RELEASE, when trying to use a unique Base class for two different configurations for one exchange (the routing key is different for the two messages that have the same contract to be validated), one of the contract test will fail as the configuration is not properly taken from the destination (exchange) used.

The code at DestinationResolver, method String resolvedDestination(String destination, DefaultChannels defaultChannel), may not resolve the proper channel when the destination (the exchange) is setup twice, once per configuration given to the Base class:

```
else if (channels.size() > 0) {
				if (log.isDebugEnabled()) {
					log.debug("Found following channels [" + channels
							+ "] for destination [" + destination + "]. "
							+ "Will pick the one that matches the default channel name or the first one if none is matching");
				}
				String defaultChannelName = channels
						.get(defaultChannel.name().toLowerCase());
				String matchingChannelName = StringUtils.hasText(defaultChannelName)
						? defaultChannel.name().toLowerCase()
						: channels.keySet().iterator().next();
				if (log.isDebugEnabled()) {
					log.debug("Picked channel name is [" + matchingChannelName + "]");
				}
				return matchingChannelName;
			}
```

If more than one channel found for the destination (the exchange), the code will pick just the first one found, so one of both tests fails.

**Sample**
Having a Base class with:

```@SpringBootTest(
        classes = {ContractTestConfig.class},
        properties = {
                "spring.cloud.stream.bindings.pause.destination=my.exchange",
                "spring.cloud.stream.bindings.stop.destination=my.exchange"
        }
        )
```

The ContractVerifierMessaging tries to verify:

```ContractVerifierMessage response = contractVerifierMessaging.receive("my.exchange");```

through:

```
public ContractVerifierMessage receive(String destination) {
		return convert(this.exchange.receive(destination));
	}
```

That "this.exchange.receive(destination)" gives null for one of the tests as it comes from StreamStubMessages':
```	@Override
	public Message<?> receive(String destination) {
		return this.receiver.receive(destination);
	}
```

which uses StreamMessageCollectorMessageReceiver's:

```	@Override
	public Message<?> receive(String destination) {
		return receive(destination, 5, TimeUnit.SECONDS);
	}
```

And:

```	@Override
	public Message<?> receive(String destination, long timeout, TimeUnit timeUnit) {
		try {
			MessageChannel messageChannel = this.context.getBean(
					this.resolver.resolvedDestination(destination, DefaultChannels.INPUT),
					MessageChannel.class);
			return messageCollector().forChannel(messageChannel).poll(timeout, timeUnit);
		}
		catch (Exception e) {
			log.error("Exception occurred while trying to read a message from "
					+ " a channel with name [" + destination + "]", e);
			throw new IllegalStateException(e);
		}
	}
```

Here, when deciding which messageChannel to receive the message from, it uses DestinationResolver's:

```String resolvedDestination(String destination, DefaultChannels defaultChannel)```

Maybe too long to add it here, but, the thing is that here:

```
else if (channels.size() > 0) {
				if (log.isDebugEnabled()) {
					log.debug("Found following channels [" + channels
							+ "] for destination [" + destination + "]. "
							+ "Will pick the one that matches the default channel name or the first one if none is matching");
				}
				String defaultChannelName = channels
						.get(defaultChannel.name().toLowerCase());
				String matchingChannelName = StringUtils.hasText(defaultChannelName)
						? defaultChannel.name().toLowerCase()
						: channels.keySet().iterator().next();
				if (log.isDebugEnabled()) {
					log.debug("Picked channel name is [" + matchingChannelName + "]");
				}
				return matchingChannelName;
			}
```

When more than one channel found (as there are two configured for the Base class), it picks the first one for both tests, so one fails, as the message should be received from the other.

In my case, when trying pause and stop, it always tries to receive from pause, and never from stop, so the stop test fails.

I guess some kind of "alias" or something related to the binding name to be able to "choose" the proper channel to receive the message from here would help. No idea how to implement it though 😅.

**Comment by marcingrzejszczak** [comment]
Would the option to use the actual Kafka broker via test containers like here [producer](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.0.x/producer_kafka_middleware) and here [consumer](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.0.x/consumer_kafka_middleware) be ok as a workaround?

**Comment by olegz** [comment]
Why do you have several channels/bindings per destination? By doing so you are  creating multiple subscribers and probably hitting the load balancing issue. 
Also, i see you are using the very old testing method via `messageCollector`. It has been deprecated for several years now and we are considering removing it very soon (upcoming - 3.1.0  or next 3.2.0 release of s-c-stream). See the [testing](https://docs.spring.io/spring-cloud-stream/docs/3.0.10.RELEASE/reference/html/spring-cloud-stream.html#_testing) section for more details

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
