### ISSUE TITLE
workOffline = true ignored when repositoryRoot is specified

### ISSUE THREAD

**Issue by piekarskim** [spring-cloud/spring-cloud-contract#144]
When running my tests with

`@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment= SpringBootTest.WebEnvironment.NONE, properties="server.context-path=/app")
@AutoConfigureStubRunner(ids = {"com.example:server:+:stubs:8080"},
        workOffline = false, repositoryRoot = " http://repo.mycompany.com/artifactory/operations-local")
public class ConsumerTest {
[...]
}
`

everything is fine and the artifact is resolved using the remote repo. When I change to `workOffline = true` while still providing the repositoryRoot I get the following:

> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'stubFlowRegistrar' defined in class path resource [org/springframework/cloud/contract/stubrunner/messaging/integration/StubRunnerIntegrationConfiguration.class]: Unsatisfied dependency expressed through method 'stubFlowRegistrar' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'batchStubRunner' defined in class path resource [org/springframework/cloud/contract/stubrunner/spring/StubRunnerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.contract.stubrunner.BatchStubRunner]: Factory method 'batchStubRunner' threw exception; nested exception is java.lang.IllegalStateException: Remote repositories for stubs are specified and work offline flag is set. You have to provide one of them.
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]

Running with 

`@AutoConfigureStubRunner(ids = {"com.example:server:+:stubs:8080"},
            workOffline = false)`

(i.e without specifying the repo) is also perfectly fine.

Is that an expected behaviour?

**Comment by marcingrzejszczak** [comment]
Yes it is. Like we write in the logs: `Remote repositories for stubs are specified and work offline flag is set. You have to provide one of them`. That's because you can accidentally turn the flag on and your tests might pass accidentally. Working offline is a very specific situation so we wanted to separate those 2 cases. Does it make any sense? :P

**Comment by piekarskim** [comment]
Yeah, makes perfect sense actually after giving it a thought :)

Thanks for a really quick response!

**Comment by marcingrzejszczak** [comment]
No problem :)
