### ISSUE TITLE
JSON assert does not create proper path for nested arrays

### ISSUE THREAD

**Issue by megaskins** [spring-cloud/spring-cloud-contract#1448]
**Describe the bug**
When using a YAML contract definition, we have multiple nested arrays in the YAML file. When the path to the nested arrays is generated, we encounter an error describing the improper pathway to the nested array in the JSON. 

**Sample YAML**
---
name: "Should get reference data by SEVERITY_SYMBOL"
request:
  headers:
    Accept: application/json
  method: GET
  queryParameters:
    dataTypes: SEVERITY_SYMBOL
  url: /reference-data
response:
  body:
    -
      field1: val1
      field2: val2
      field3:
      - item1: item1
         item2: item2
      field4: val4
      field5: val5

**Comment by marcingrzejszczak** [comment]
Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
