### ISSUE TITLE
inProgress() should skip generating just single contract in a package

### ISSUE THREAD

**Issue by jm-ck** [spring-cloud/spring-cloud-contract#1449]
**Describe the bug**
Tests from contracts are not generated when at least one file in the package is marked as `inProgress()`. They should be generated for `Contract.make` definitions that are not inProgress and skipped for `inProgress()` annotated.

I have 5 files with `Contract.make` definitions in a single `registration` package. Each file has one `Contract.make`. All of them are marked as `inProgress()` as I did not start implementing them yet on producer side. Now when I'm implementing one of those APIs from registration flow / package, I remove `inProgress()` from there. Keeping it in 4 remaining APIs in this package. No tests are generated in this case. I'd expect tests to be generated with this single Contract I'm implementing.

**Comment by marcingrzejszczak** [comment]
So would I. That must be a bug.

**Comment by jkubrynski** [comment]
In my opinion `inProgress()` shouldn't skip the contract, but just generate ignored test. That is a stage where the contract is not yet finished, however, developer can expect a support from the framework, like being able to use generated test to verify the implementation when coding.

**Comment by jm-ck** [comment]
makes sense as it explicitly shows that there is some contract yet to be implemented. as opposed to now, when in the test report it is hidden. Makes it easier to be forgotten

However this sounds more like a feature request, not the bug itself.

**Comment by marcingrzejszczak** [comment]
I've fixed the bug by introducing the in progress tests as disabled ones
