### ISSUE TITLE
Remove global wiremock dependency exlcusion from maven BOM

### ISSUE THREAD

**Issue by shollander** [spring-cloud/spring-cloud-contract#146]
I am using spring cloud and followed the instructions on http://projects.spring.io/spring-cloud/ including the following in my build.gradle:
```
dependencyManagement {
  imports {
    mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Camden.SR2'
  }
}
```
Unfortunately, this had the effect of breaking all of my unit tests that use wiremock. Doing a little research I discovered that `spring-cloud-dependencies` imports `spring-cloud-contract-dependencies` which in turn has exclusions for all (or most) of the dependencies needed by wiremock. I am not using `spring-cloud-contract` so I should not have to deal with exclusions needed by `spring-cloud-contract`. If `spring-cloud-contract` needs those exclusions in place it should place them in a place where it does not interfere with those who are not using `spring-cloud-contract`.

Thank you.

**Comment by dsyer** [comment]
That's a little irritating, I agree. We can have a think, but I'm pretty sure the outcome will be that if you want to use spring cloud dependency management with wiremock then you will need to use spring-cloud-contract-wiremock to locate the dependencies, or else add back all those exclusions manually. I suppose we could make it more palatable by packaging them up in some way. I expect the best solution might involve changes in wiremock to make it less opinionated, but I'm not sure how easy that would be for non-spring wiremockers.

**Comment by jkubrynski** [comment]
You can use `wiremock-standalone` instead of `wiremock` and everything will work correctly.

**Comment by shollander** [comment]
@jkubrynski Thanks for the suggestion. That does work, although I don't think it was intended to be used in that manner. `wiremock-standalone` is basically a shadow jar that incorporates and relocates the wiremock dependencies.

**Comment by jkubrynski** [comment]
In fact that was the original intention as there were issues with for example Jetty versioning:
https://github.com/tomakehurst/wiremock/issues/296

**Comment by dsyer** [comment]
Yes but it doesn't play well with Spring Boot. I don't recommend using the standalone jar unless you want to use the same version of Jetty.
