### ISSUE TITLE
Allow to extend contracts & stubs

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#1465]
We will add a `metadata` field to contracts so that you can pass in custom data there. Example of such data will be extending WireMock stubs with webhooks, additional timeouts etc - whatever that is supported by WireMock. Users will be able to add their own metadata entries and register their own post processors.

Related issues:
* #1340
* #1078 
* #1406 
* #1084

**Comment by gabbigum** [comment]
Hello, where can I find webhooks example for producer side? And do we need to register webhook-extension on the consumer side? I'm having trouble setting all of this up. If there's some guide/tips somewhere it would be really helpful, thanks!

**Comment by marcingrzejszczak** [comment]
Here you have an example of such a contract https://github.com/spring-cloud/spring-cloud-contract/blob/e73d6526bfb3240f9dc33d6afcf2be17e5383f49/docs/src/test/resources/contract.yml#L60-L72
