### ISSUE TITLE
Customize maven meta data for generated stubs

### ISSUE THREAD

**Issue by dman0613** [spring-cloud/spring-cloud-contract#1469]
As far as I see here
https://github.com/spring-cloud/spring-cloud-contract/blob/704be942cffe2d01a85e0a8c282de31a1b88b8ad/spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/main/java/org/springframework/cloud/contract/maven/verifier/GenerateStubsMojo.java
spring-cloud-contract-maven-plugin generates stubs with maven group as project calling the plugin. In my project stubs are used widely which leads to circular maven dependencies: app1 uses stubs of app2 and app2 uses stubs of app1.

I'm trying to avoid all circular dependencies changing maven group in generated artifacts but this plugin does not allow to change maven group externally.

Have I missed some solution? hidden settings?
Anyway it would be pretty useful to have ability to customize maven meta data for generated stubs (in plugin configuration I guess).

**Comment by marcingrzejszczak** [comment]
So maven is telling you that there's a circular dependency? Can you show us the stacktrace?

**Comment by dman0613** [comment]
I didn't mean it is a bug. My maven build has no exceptions or errors as artifacts with stubs are used only on test stage. Circular dependencies are found by build/validation job.
But it seems weird to me that stub maven group can not be preconfigured or changed.

**Comment by marcingrzejszczak** [comment]
Can you show the build/validation job report or sth? I mean it's obvious that you can have circular dependencies.

>  But it seems weird to me that stub maven group can not be preconfigured or changed.

No one has asked for it until now.

**Comment by dman0613** [comment]
It is custom internal CI job, I don't think you can find something useful in its logs.
If this feature is not needed the issue can be closed. I will try to fix from another side.
