### ISSUE TITLE
It should be easier to use the built in regex matchers.

### ISSUE THREAD

**Issue by Fitzoh** [spring-cloud/spring-cloud-contract#148]
The built in regexes (email, hostname, uuid, etc) return a String which needs to be wrapped in a `regex()` call.  This leads to a lot of noise, and should be handled automatically.
It might make sense to provide anyXxx() matchers which handle this without breaking backwards compatibility.

before:
```	
body(
	email: $(consumer(optional(regex(email()))), producer('abc@abc.com')),
	callback_url: $(consumer(regex(hostname())), producer('http://partners.com'))
	)
```
after

```	
body(
	email: $(consumer(optional(anyEmail())), producer('abc@abc.com')),
	callback_url: $(consumer(anyHostname()), producer('http://partners.com'))
	)
```

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/pull/151
