### ISSUE TITLE
Generating docs in tests

### ISSUE THREAD

**Issue by Buzzardo** [spring-cloud/spring-cloud-contract#1483]
Marcin and I discussed this issue in a Zoom call, but I'll describe it here as a reminder.

There's a test called `should_produce_an_adoc_with_all_of_metadata_classes` that generates `metadata.adoc`. That file then gets included when the docs are built.

I usually don't run the tests when I build the docs, so I never knew that was there. Also, the build for the docs (at the bottom of the README file) doesn't generate `metadata.adoc`.

It would be much easier to maintain and more reliably generated if that file were generated in code other than a test.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/commit/a2fac971488c7df0bb445d3b6c3bcc612e4c1579
