### ISSUE TITLE
Body with array of Objects is parsed incorrectly in version 2.2.+

### ISSUE THREAD

**Issue by yankskwesi** [spring-cloud/spring-cloud-contract#1485]
Describe the bug
The test generation in maven plugin 2.2.+ isn't generating correct JSON when body has an array of an Objects.

Sample:

```
package contracts

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    description "TEST OBJECT ARRAY"
    request {
        method POST()
        urlPath($(c('/TEST'), p('/TEST')))
        body([
               "ObjectNameList" to value(
                        arrayOf(
                                mapOf(
                                        "ObjectFieldName" to value(
                                                consumer(anyNonBlankString),
                                                producer("Element")
                                        ),
                                        "ObjectFieldName1" to value(
                                                consumer(anyNonBlankString),
                                                producer("Element1")
                                        ),
                                        "ObjectFieldName2" to value(
                                                consumer(anyNonBlankString),
                                                producer("Element2")
                                        ),
                                        "ObjectFieldName3" to value (
                                                consumer(anyNonBlankString),
                                                producer("Element3")
                                        )
                                )
                        )
                )
        ])
    }
    response {
        status OK()
    }
}
```

expected:

	@Test
	public void validate_list_object_bug() throws Exception {
		// given:
			MockMvcRequestSpecification request = given()
					.body("ObjectsList: 
							    [
								    {
									  "ObjectFieldName": {"PEHXGRWQKODYRYBEMJPX"},
									  "ObjectFieldName1": {"NVYMXNDMMFLQMHWTDOXY"},
									  "ObjectFieldName2": {"NOOAXDBOAHVMWZGNFATC"},
									  "ObjectFieldName3": {"ESRQFIOKPPNTHVFJIVGG"}
									}
								]
							");

		// when:
			ResponseOptions response = given().spec(request)
					.post("/TEST");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);
	}

actual:

	@Test
	public void validate_bug() throws Exception {
		// given:
			MockMvcRequestSpecification request = given()
					.body("ObjectsList: 
							    [
								    {
									  "ObjectFieldName": {
									    "singleValue": false,
									    "serverValue": "Element",
									    "clientValue": {
									      "singleValue": false,
									      "serverValue": "PEHXGRWQKODYRYBEMJPX",
									      "clientValue": {
									        "cursor": 13
									      }
									    }
									  },
									  "ObjectFieldName1": {
									    "singleValue": false,
									    "serverValue": "Element1",
									    "clientValue": {
									      "singleValue": false,
									      "serverValue": "NVYMXNDMMFLQMHWTDOXY",
									      "clientValue": {
									        "cursor": 13
									      }
									    }
									  },
									  "ObjectFieldName2": {
									    "singleValue": false,
									    "serverValue": "Element2",
									    "clientValue": {
									      "singleValue": false,
									      "serverValue": "NOOAXDBOAHVMWZGNFATC",
									      "clientValue": {
									        "cursor": 13
									      }
									    }
									  },
									  "ObjectFieldName3": {
									    "singleValue": false,
									    "serverValue": "Element3",
									    "clientValue": {
									      "singleValue": false,
									      "serverValue": "ESRQFIOKPPNTHVFJIVGG",
									      "clientValue": {
									        "cursor": 13
									      }
									    }
									  }
									}
								]
							");

		// when:
			ResponseOptions response = given().spec(request)
					.post("/TEST");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);
	}

**Comment by marcingrzejszczak** [comment]
Interesting cause this

```
 "ObjectFieldName3": {
								    "singleValue": false,
								    "serverValue": "Element3",
								    "clientValue": {
								      "singleValue": false,
								      "serverValue": "ESRQFIOKPPNTHVFJIVGG",
								      "clientValue": {
								        "cursor": 13
								      }
								    }
								  }
								}
```

is actually a bug. It contains `clientValue` and `serverValue` and `cursor` which means that a `Pattern` object got improperly parsed.

**Comment by marcingrzejszczak** [comment]
Hi can you create a small sample that replicates this? I understand that this is Kotlin code? Do you have the same problem when using Groovy / YAML or Java? I can't make the contract code compile in the Kotlin samples.

**Comment by yankskwesi** [comment]
Replicating the contract itself or the error?

**Comment by marcingrzejszczak** [comment]
Hey @TYsewyn WDYT? Do you have time to check this out?

**Comment by TYsewyn** [comment]
@yankskwesi can you create a sample app in which the base test class has been set up, together with the contract and a dummy controller?
I'm really wondering how you set this up.
Your contract has a Groovy syntax (`Contract.make` is telling me) so it'll never use any of the Kotlin specs.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
