### ISSUE TITLE
You shouldn't need to provide a consumer and producer value if you just want to match a pattern

### ISSUE THREAD

**Issue by Fitzoh** [spring-cloud/spring-cloud-contract#149]
There are many instances where you don't care about the actual value used in the contract, just that it matches a pattern.
I started out with an example sort of like this:
```
request {
	method 'POST'
	url '/thing'
	body(
		id: $(consumer(regex(uuid())), producer('some-really-long-uuid'))
	)
}
```
@marcingrzejszczak informed me that it can be simplified to something like this, by omitting the producer call:

```
request {
	method 'POST'
	url '/thing'
	body(
		id: $(consumer(regex(uuid())))
	)
}
```
If you incorporate the changes from #148, that becomes further simplified to this:

```
request {
	method 'POST'
	url '/thing'
	body(
		id: $(consumer(anyUuid()))
	)
}
```
But if we're not providing a provider value, it would be nice to just imply that it's a consumer value.
That would leave us with something like this:

```
request {
	method 'POST'
	url '/thing'
	body(
		id: $(anyUuid())
	)
}
```
This leaves us with a lot less noise and a much clearer intent. The id field should always be a UUID, no other details required.

**Comment by marcingrzejszczak** [comment]
I don't like this part either

```
headers {
           header('Content-Type': value(
                   producer(regex('application/json.*')),
                   consumer('application/json')
           ))
       }
```

we could add sth like 

```
headers {
   contentTypeApplicationJson()
}

```
