### ISSUE TITLE
Xml with empty child elements causing the assertions to be wrongly created

### ISSUE THREAD

**Issue by javiersvg** [spring-cloud/spring-cloud-contract#1494]
**Describe the bug**
Given an contract with and xml output body with at least one child element that has attributes but does not have content.
When test are generated with the maven plugin

Actual result:
Then the generated test's assertions are duplicated validations of the attributes of the most parent element and no validation for the child elements attributes.

Expected result:
The generated tests contains a single validation per attribute in the xml for all xml attributes.

spring-cloud-contract version: 2.2.4.RELEASE

**Sample**

Given the following xml:
```xml
<customer first_custom_attribute="first_value">
      <email second_custom_attribute="second_value" >customer@test.com</email>
      <address third_custom_attribute="third_value"/>
    </customer>
```
Spring cloud contract generates the following assertions:
```java
assertThat(valueFromXPath(parsedXml,"/customer/email/text()").isEqualTo("customer@test.com");
assertThat(valueFromXPath(parsedXml,"/customer/@first_custom_attribute").isEqualTo("first_value");
assertThat(valueFromXPath(parsedXml,"/customer/@first_custom_attribute").isEqualTo("first_value");
assertThat(valueFromXPath(parsedXml,"/customer/@first_custom_attribute").isEqualTo("first_value");
assertThat(valueFromXPath(parsedXml,"/customer/@first_custom_attribute").isEqualTo("first_value");
```
and instead should generate
```java
assertThat(valueFromXPath(parsedXml,"/customer/email/text()").isEqualTo("customer@test.com");
assertThat(valueFromXPath(parsedXml,"/customer/@first_custom_attribute").isEqualTo("first_value");
assertThat(valueFromXPath(parsedXml,"/customer/email/@second_custom_attribute").isEqualTo("second_value");
assertThat(valueFromXPath(parsedXml,"/customer/address/@third_custom_attribute").isEqualTo("third_value");
```

This is caused by an error in the class XmlToXPathsConverter line 221:
```java
private static List<Node> addValueNodes(Node node, List<List<Node>> valueNodes, List<Node> attributes) {
		getChildNodesAsList(node).each {
			attributes.addAll(getAttributesAsList(node))
			if (isValueNode(it) && !isBlank(it.nodeValue)) {
				valueNodes << withParents(it)
			}
			else {
				addValueNodes(it, valueNodes, attributes)
			}
		}
	}
```

In this method which is recursively called, in the third line there is a call to the `getAttributesAsList(node)` in the each clause for the list of child elements. This then adds to the list of attributes, used to create the matchers, the attributes of the parent element contained in the variable `node` instead of using the variable `it` as the code should.

I have created tests and a fix for this and will create the PR shortly.

**Comment by marcingrzejszczak** [comment]
@javiersvg can you check the latest snapshots if this is stlil a problem?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by javiersvg** [comment]
I have a crazy week but will take a look at it over the weekend.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
