### ISSUE TITLE
When spring-cloud-contract-wiremock 2.2.5.RELEASE is expected?

### ISSUE THREAD

**Issue by ilgrosso** [spring-cloud/spring-cloud-contract#1496]
Spring Cloud Gateway 2.2.5.RELEASE is now available for a while, but `spring-cloud-contract-wiremock` is still on 2.2.4.RELEASE.

Can you please provide an expected release date for 2.2.5.RELEASE?

**Comment by marcingrzejszczak** [comment]
It will come with https://github.com/spring-cloud/spring-cloud-release/milestone/97 release so please check out there for a release date.

**Comment by ilgrosso** [comment]
thanks @marcingrzejszczak
