### ISSUE TITLE
Incorrect pattern used when project version != contracts version

### ISSUE THREAD

**Issue by jkubrynski** [spring-cloud/spring-cloud-contract#1497]
When using git contract storage there is inconsistent behaviour for different versions of the producer and contracts.

1. producer version == contracts version
```
[INFO] Pattern to pick contracts equals [^/var/folders/4w/bz0nmbb50c5_099vnjx2mv8m0000gn/T/git-contracts-1599411817978-0/META-INF/com.group/sample/0.0.1/contracts.*$]
[INFO] Ant Pattern to pick files equals [**/]
```

1. producer version != contracts version
```
[INFO] Pattern to pick contracts equals [^/var/folders/4w/bz0nmbb50c5_099vnjx2mv8m0000gn/T/git-contracts-1599412143392-0/META-INF/com.group/sample/0.0.1(/)?.*com/kubrynski/workshop/warehouse/.*$]
[INFO] Ant Pattern to pick files equals [**/com/group/sample/**/]
```

This can be probably related to the `hasVersionInPath` implementation from the https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/ContractDownloader.java#L167

**Comment by jkubrynski** [comment]
Potential walkaround to this issue is to set ```<contractsPath>contracts</contractsPath>```

**Comment by marcingrzejszczak** [comment]
hey @jkubrynski could you please present a sample that replicates such behaviour? You can modify one of those samples - https://github.com/spring-cloud-samples/spring-cloud-contract-samples if you don't have one that you can work on

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
