### ISSUE TITLE
Remove contracts from SCM which are deleted or renamed

### ISSUE THREAD

**Issue by ArjanSchouten** [spring-cloud/spring-cloud-contract#1498]
**Is your feature request related to a problem? Please describe.**
We use the `publishStubsToScm` gradle task. When we rename or delete a contract, the old contracts are still in SCM. This causes problems with integration tests. To solve this, we manually delete the stubs and contracts from the repo.

**Describe the solution you'd like**
Is it possible to create a  configuration option to delete all contents from the directories and then add the new contracts?

**Describe alternatives you've considered**

**Additional context**

**Comment by marcingrzejszczak** [comment]
Which version of Spring Cloud Contract are you using?

**Comment by marcingrzejszczak** [comment]
Also, we do already delete all contracts and mappings - https://github.com/spring-cloud/spring-cloud-contract/blob/v2.2.4.RELEASE/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/ContractProjectUpdater.java#L201 . Can you elaborate more on the use case please?

**Comment by ArjanSchouten** [comment]
I use version 2.2.4 at the moment. I have to look into the code you referred to a bit more to understand what happens in my case.

What sometimes happens:
1. I have contract `event-publish.groovy` in `src/test/resources/contracts/event-publish.groovy`
2. I run `./gradlew clean publishStubsToScm`
3. I rename `src/test/resources/contracts/event-publish.groovy` to `src/test/resources/contracts/command-publish.groovy`
4. I run `./gradlew clean publishStubsToScm`
5. In github repo configured in build.gradle I have both:
`META-INF/my.package/producer/version/contracts/consumer/messaging/event-publish.groovy` and 
`META-INF/my.package/producer/version/contracts/consumer/messaging/command-publish.groovy`

```
contracts {
    testFramework = 'JUNIT5'
    baseClassMappings {
        baseClassMapping(".*messaging.*", "my.package.contract.MessagingContractTestBase")
    }
    basePackageForTests = "my.package.contract"

    publishStubsToScm {
        contractDependency {
            stringNotation = "${project.group}:${project.name}:${project.version}"
        }
        contractRepository {
            repositoryUrl = "git://https://github.com/user/repo"
        }
        contractsMode = "REMOTE"
    }
}
```
So what I want is that `META-INF/my.package/producer/version/contracts/consumer/messaging/event-publish.groovy` is removed from the github repo.

**Comment by marcingrzejszczak** [comment]
Hmmmm that should work. Can you run this with DEBUG logs so that we can see why it's not working?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by keydon** [comment]
ah and if I go to the tmp dir (/tmp/git-contracts-1751461935888-0/)
and do `git status` there, I get a bunch of old contracts. thats my workaround right now, to push that stuff manually from time to time ;O
