### ISSUE TITLE
Response body should support matching 

### ISSUE THREAD

**Issue by dstepanov** [spring-cloud/spring-cloud-contract#150]
```
response {
   status 200
   body(value(stub("HELLO FROM STUB"), server(regex(".*"))))
}
```
Right now it generates:
```
response.statusCode == 200
and:
def responseBody = (response.body.asString())
responseBody == ".*"
```

**Comment by marcingrzejszczak** [comment]
meh... as a workaround maybe try `execute(...)` ?

**Comment by dstepanov** [comment]
Doesn't work either

**Comment by marcingrzejszczak** [comment]
Try with latest snapshots.

**Comment by dstepanov** [comment]
Will it work with 'execute(...)'?

17. 11. 2016 v 13:15, Marcin Grzejszczak <notifications@github.com>:

**Comment by marcingrzejszczak** [comment]
yes - I've added `execute` too

**Comment by marcingrzejszczak** [comment]
https://github.com/spring-cloud/spring-cloud-contract/commit/df80cc8f1fa004c818cc847b311670b087c47ecf#diff-e6aa1428b47294d77becb23ca25f402eR1668

**Comment by dstepanov** [comment]
Cool Thanks!
