### ISSUE TITLE
Spring Cloud Contract does not work together with Gradle nebula release plugin

### ISSUE THREAD

**Issue by athlan** [spring-cloud/spring-cloud-contract#1502]
**Describe the bug**
When Gradle project has both [nebula release plugin](https://github.com/nebula-plugins/nebula-release-plugin) and spring cloud contract plugin, version of some _jgit_ library clashes.

The error message is the following:
```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/spring-cloud-contract-nebula-example/spring-cloud-contract-nebula-example/build.gradle' line: 14

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.release', version: '6.3.3']
> Failed to apply plugin 'nebula.release'.
   > No signature of method: org.eclipse.jgit.internal.storage.file.FileRepository.getRef() is applicable for argument types: (String) values: [HEAD]
     Possible solutions: getAt(java.lang.String), getFS(), grep(), exactRef(java.lang.String), findRef(java.lang.String), getAllRefs()
```

- Gradle version: 6.6.1
- Spring cloud contract version: 2.2.4.RELEASE
- Spring boot plugin version: 2.3.3.RELEASE
(those 3 above get from spring initializr)
- Nebula release plugin version: 6.3.3

**Sample**
I've created sample repo to reproduce this issue. Code available under:
https://github.com/athlan/spring-cloud-contract-nebula-example

**Comment by marcingrzejszczak** [comment]
So apparently there's a mismatch between jgit in nebula and spring cloud contract. Interesting.

**Comment by athlan** [comment]
Yep. Looks like they uses newer one where API was broken:

Spring Cloud Contract - 5.5.1.201910021850-r
https://github.com/spring-cloud/spring-cloud-contract/blob/master/pom.xml#L45

Nebula Release: 5.7.0.202003110725-r
https://github.com/nebula-plugins/nebula-release-plugin/blob/master/build.gradle#L43

**Comment by athlan** [comment]
Ok never mind. I've checked the latest version, not 6.3.3. Referenced method was deprecated and later deleted from jgit.
Once bumped to newest nebula plugin (15.1.0 for today), they bumped jgit and it worked.

**Comment by athlan** [comment]
Ok never mind. I've checked the latest version, not 6.3.3. Referenced method was deprecated and later deleted from jgit.
Once bumped to newest nebula plugin (15.1.0 for today), they bumped jgit and it worked.
