### ISSUE TITLE
java.lang.IllegalStateException: Parsed JSON for LocalDateTime 

### ISSUE THREAD

**Issue by tillias** [spring-cloud/spring-cloud-contract#1515]
**Describe the bug**
Hello folks, I'm using  https://www.baeldung.com/spring-cloud-contract and

` <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-contract-maven-plugin</artifactId>
                <version>2.2.3.RELEASE</version>
`

When I look into generated tests there is following assertion

`assertThatJson(parsedJson).field("['createdOn']").isEqualTo("2020-09-23T12:45:55.216");`

If I configure base test as following:
```java
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.MOCK)
@DirtiesContext
@AutoConfigureMessageVerifier
public class ApiControllerTest {

    @Autowired
    private WebApplicationContext appContext;

    @Before
    public void setup() {
        RestAssuredMockMvc.webAppContextSetup(appContext);
```

then there is following failure:
`java.lang.IllegalStateException: Parsed JSON [{"createdOn":"2020-09-23T12:45:55.000000216"}] doesn't match the JSON path [$[?(@.['createdOn'] == '2020-09-23T12:45:55.216')]]`

If I configure base test as following:

```java
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.MOCK)
@DirtiesContext
@AutoConfigureMessageVerifier
public class ApiControllerTest {

    @Autowired
    private WebApplicationContext appContext;

    @Before
    public void setup() {
        StandaloneMockMvcBuilder standaloneMockMvcBuilder
                = MockMvcBuilders.standaloneSetup(controller);
        RestAssuredMockMvc.standaloneSetup(standaloneMockMvcBuilder);
```

then there is following failure:

`java.lang.IllegalStateException: Parsed JSON [{"createdOn":[2020,9,23,12,45,55,216]}] doesn't match the JSON path [$[?(@.['createdOn'] == '2020-09-23T12:45:55.216')]]`

Can you please advise how to make LocalDateTime working correctly? I'm currently using Java 8

**Comment by tillias** [comment]
Opened parallel in https://github.com/rest-assured/rest-assured/issues/1384
Not sure who is responsible

**Comment by marcingrzejszczak** [comment]
can you check that when you use `EXPLICIT` mode and you send a request to your app that was started on a port, then things are working fine?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
