### ISSUE TITLE
Problem to generate java test code for xml contract with attributes

### ISSUE THREAD

**Issue by RaymondZhuohui** [spring-cloud/spring-cloud-contract#1517]
We have a soap service which generate a response like this:

    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
       <SOAP-ENV:Header>
          <RsHeader xmlns="http://*******/****/****/******/schema">
             <MsgSeqId>48bf6b16-b059-41d2-a60f-d8d9304caff7</MsgSeqId>
             <SessionToken>*************</SessionToken>
             <SessionState>
                <StateInformation>
                   <Key>1234567890</Key>
                   <Value>transaction1</Value>
                </StateInformation>
                <StateInformation>
                   <Key>sessionId</Key>
                   <Value>***************</Value>
                </StateInformation>
             </SessionState>
          </RsHeader>
       </SOAP-ENV:Header>
       <SOAP-ENV:Body>
          <CompleteDepositRs xmlns="http://*******/****/****/******/schema">
             <TransactionId>1234567890</TransactionId>
             <TransactionStatus>
                <TransactionState>AUTHORISED</TransactionState>
             </TransactionStatus>
          </CompleteDepositRs>
       </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>

The generated java test code by spring cloud contract is like this:

        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/@xmlns:SOAP-ENV")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/@xmlns:SOAP-ENV")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/SOAP-ENV:Header/RsHeader/@xmlns")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/SOAP-ENV:Header/RsHeader/@xmlns")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/SOAP-ENV:Header/RsHeader/@xmlns")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/SOAP-ENV:Header/RsHeader/@xmlns")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/SOAP-ENV:Header/RsHeader/@xmlns")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/SOAP-ENV:Header/RsHeader/@xmlns")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/SOAP-ENV:Header/RsHeader/@xmlns")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/@xmlns:SOAP-ENV")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/@xmlns:SOAP-ENV")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/SOAP-ENV:Body/CompleteDepositRs/@xmlns")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/SOAP-ENV:Body/CompleteDepositRs/@xmlns")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/SOAP-ENV:Body/CompleteDepositRs/@xmlns")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/SOAP-ENV:Body/CompleteDepositRs/@xmlns")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/SOAP-ENV:Body/CompleteDepositRs/@xmlns")).isEqualTo("");
        assertThat(valueFromXPath(parsedXml, "/SOAP-ENV:Envelope/@xmlns:SOAP-ENV")).isEqualTo("");

All the values in isEqualTo() is empty. And it did not generate assertion code for some nodes, e.g. MsgSeqId.

Also, In version 2.2.2, we were able to use a workaround that we created matchers using path starting with "//", e.g. :

  matchers:
    body:
    - path: //RsHeader/MsgSeqId/text()
      type: by_equality

However, in 2.2.4 this is broken, the generated assertion code for the matcher is like this:

assertThat(valueFromXPath(parsedXml, "//RsHeader/MsgSeqId/text()")).isEqualTo("");

**Comment by vkochnev** [comment]
I've encountered the same issue with 3.0.0-M4. The reason is incorrect `XPath` being generated when element has namespace, but it is a default namespace (`xmlns` attribute is specified on the node itself or on it's parent). So `name == localName` and `namespaceURI != null`, in this case you cannot refer element like `/element`, only like `/*[name() = 'element']` or `/*[name() = 'element' and namespace-uri() = 'urn:example.com/Test']`. This issue breaks not only generated tests, but stubs also.
Looks like this was introduced with making `XPath`s `namespaceAware` in scope of gh-1446.
Will be glad if this will help to resolve this faster.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/pull/1590
