### ISSUE TITLE
AutoConfigureWireMock stopped working once I switched from spring-boot-starter-webflux to spring-boot-starter

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-contract#1519]
**Describe the bug**
Converted a multimodule Gradle project from using webflux (Netty server) to gRPC. Replaced `spring-boot-starter-webflux` with `spring-boot-starter`, and found that `AutoConfigureWireMock` doesn't start the server anymore.
```
Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
```
Looking into the code, I've not been able to find out why it'd need a web server. Tried `@Import(WireMockConfiguration::class)` to no avail.

Boot 2.3.4.RELEASE, Cloud Hoxton.SR6.

**Comment by marcingrzejszczak** [comment]
Interesting cause it should start with the WireMock's shaded Jetty. We need more information (snippets, full logs etc.) or better - a sample project. Can you provide those?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
