### ISSUE TITLE
Spring cloud contract with content type application/stream+json

### ISSUE THREAD

**Issue by ajeetbansal** [spring-cloud/spring-cloud-contract#1535]
**Describe the bug**
I am trying to test a Spring webflux based REST API that returns application/stream+json content type using spring cloud contract. I have defined the contract as follows. In the below sample, my API is returning two entities, but the tests generated by this contract is just asserting the presence of Entity1 in the actual response. Also the stub generated by this contract just return Entity1.

```
Contract.make {
description "should return all entities"
request{
    method GET()
    url("/api/v1/entities")
}
response {
    headers {
        header 'Content-Type': 'application/stream+json'
    }
    body(
            '''                       
                        {
                        "id" : "1",
                        "name" : "Entity1",
                        "nested_data" : {
                        "key1" : "value1"
                        }
                    },
                                                {
                        "id" : "2",
                        "name" : "Entity2",
                        "nested_data" : {
                        "key1" : "value1"
                        }
                    }
           '''
    )
    status 200
} 

```

**Comment by marcingrzejszczak** [comment]
```json
 {
                        "id" : "1",
                        "name" : "Entity1",
                        "nested_data" : {
                        "key1" : "value1"
                        }
                    },
                                                {
                        "id" : "2",
                        "name" : "Entity2",
                        "nested_data" : {
                        "key1" : "value1"
                        }
                    }
```

this is not a valid json.

**Comment by ajeetbansal** [comment]
Please note that the content type is application/stream+json ( not application/json). If we use application/stream+json content type then the REST API returns a stream of json just like I provided in the example. 

FYI, I also tried by specifying the json array representation in the cloud-contract, i.e.

`[
 {
                        "id" : "1",
                        "name" : "Entity1",
                        "nested_data" : {
                        "key1" : "value1"
                        }
                    },
                                                {
                        "id" : "2",
                        "name" : "Entity2",
                        "nested_data" : {
                        "key1" : "value1"
                        }
                    }
]`

 but in that case the generated test fails while running the test against the REST API that returns application/stream+json.

**Comment by marcingrzejszczak** [comment]
I don't think that WireMock supports stream really... Maybe that's why it doesn't work well. Can you file an issue in WireMock to add support for streams?

**Comment by tomakehurst** [comment]
@marcingrzejszczak my reading of this is that the response body is just a series of JSON documents delimited by commas, so WireMock shouldn't have any problem serving that as it doesn't care whether the body is valid JSON, XML or anything else.

Am I missing something?

**Comment by marcingrzejszczak** [comment]
I don't know if this is a good example of what I think we're talking about here but that's the closest I found - https://stackoverflow.com/questions/45635739/rest-streaming-json-output . When we're talking about streams I understand that Jetty would print out additional entries upon receiving them. So you don't have a finite e.g. 3 element array that is returned, it's an open connection to which you flush N number of entries.

Now coming back to the stub maybe I'm wrong however I think I saw people try it out with WireMock and streaming and that didn't work for some reason. If you're saying that that should work then most likely there's an issue with SC-contract. @ajeetbansal if you ignore the invalid test generation, just generate the stub - will it work on the consumer side?

**Comment by tomakehurst** [comment]
Agree WireMock can't (yet) hold the connection open and push a non-finite set of events down it, but for the purposes of testing I don't think that matters where you're testing a known, finite set of events.

**Comment by marcingrzejszczak** [comment]
Yeah that's what I thought too, however apparently setting that header makes jetty go crazy it seems :shrug:

**Comment by tomakehurst** [comment]
Seems to work fine with the Apache client:

```java
@Test
public void jsonStreaming() {
        final String body = "{\n" +
                "                        \"id\" : \"1\",\n" +
                "                        \"name\" : \"Entity1\",\n" +
                "                        \"nested_data\" : {\n" +
                "                        \"key1\" : \"value1\"\n" +
                "                        }\n" +
                "                    },\n" +
                "                                                {\n" +
                "                        \"id\" : \"2\",\n" +
                "                        \"name\" : \"Entity2\",\n" +
                "                        \"nested_data\" : {\n" +
                "                        \"key1\" : \"value1\"\n" +
                "                        }\n" +
                "                    }";

        wm.stubFor(get(urlPathEqualTo("/stream"))
                .willReturn(ok()
                        .withHeader("Content-Type", "application/stream+json")
                        .withBody(body)));

        WireMockResponse response = client.get("/stream"); // Apache client under the hood
        assertThat(response.statusCode(), is(200));
        assertThat(response.content(), is(body));
}
```

**Comment by marcingrzejszczak** [comment]
@ajeetbansal can you actually confirm that once the stub is created you can't properly consume the stream?

**Comment by ajeetbansal** [comment]
@marcingrzejszczak the stub just returns the first entity. In case of above example, it returns only the following
`{
                        "id" : "1",
                        "name" : "Entity1",
                        "nested_data" : {
                        "key1" : "value1"
                        }
                    }`

**Comment by marcingrzejszczak** [comment]
Can you show the wiremock stub?

**Comment by ajeetbansal** [comment]
[Uploading ccDemo-0.0.1-SNAPSHOT-stubs.jar…]()

Attaching the verifier stub jar. When I run it using the StubRunnerExecutor and try to issue GET using curl the behaviour is as follows:

Commmand: curl localhost:9001/api/v1/entities
Output:
{"id":"1","name":"Entity1","nested_data":{"key1":"value1"}}
