### ISSUE TITLE
Wiremock support for multiple requests

### ISSUE THREAD

**Issue by peterpivarnik** [spring-cloud/spring-cloud-contract#1565]
Wiremock currently supports sending more requests within one stub definition.
http://wiremock.org/docs/stubbing/
Here is definition of such json file:
```json
{
  "mappings": [
    {
      "request": {
        "method": "GET",
        "url": "/one"
      },
      "response": {
        "status": 200
      }
    },
    {
      "id": "8c5db8b0-2db4-4ad7-a99f-38c9b00da3f7",
      "request": {
        "url": "/two"
      },
      "response": {
        "status": 200,
        "body": "Body content"
      }
    }
  ],

  "importOptions": {
    "duplicatePolicy": "IGNORE",
    "deleteAllNotInImport": true
  }
}
```
Currently this is not supported by spring-cloud-contract-wiremock.
Is this feature planned?

**Comment by marcingrzejszczak** [comment]
Hi! We haven't considered it. Can you present a use case where from the point of view of creating a stub / generated tests this could be useful?

**Comment by peterpivarnik** [comment]
Well, I'm not sure if I understand your question. But I will try to explain by example.

I'm using spring-cloud-contract-wiremock in integration test of my application. This tested application calls other application which is mocked by wiremock.
So to test more scenarios I have to create more files with stubs like this:
stub1.json:
~~~
{
  "request": {
    "method": "GET",
    "url": "/profile/10"
  },
  "response": {
    "bodyFileName": "profile10.json",
    "headers": {
      "Content-Type": "application/json"
    },
    "status": 200
  }
}
~~~
stub2.json:
~~~
{
  "request": {
    "method": "GET",
    "url": "/profile/11"
  },
  "response": {
    "bodyFileName": "badRequest.json",
    "headers": {
      "Content-Type": "application/json"
    },
    "status": 400
  }
}
~~~
stub3.json:
~~~
{
  "request": {
    "method": "GET",
    "url": "/profile/12"
  },
  "response": {
    "bodyFileName": "internalServerError.json",
    "headers": {
      "Content-Type": "application/json"
    },
    "status": 500
  }
}
~~~
With bulk import I could have one file with all the definitions for this particular API in one file. 
This could make the integration tests much more readable and understandable for any new member of the team.
stubs.json:
~~~
{
  "mappings": [
    {
      "request": {
        "method": "GET",
        "url": "/profile/10"
      },
      "response": {
        "bodyFileName": "profile10.json",
        "headers": {
          "Content-Type": "application/json"
        },
        "status": 200
      }
    },
    {
      "request": {
        "method": "GET",
        "url": "/profile/11"
      },
      "response": {
        "bodyFileName": "badRequest.json",
        "headers": {
          "Content-Type": "application/json"
        },
        "status": 400
      }
    },
    {
      "request": {
        "method": "GET",
        "url": "/profile/12"
      },
      "response": {
        "bodyFileName": "internalServerError.json",
        "headers": {
          "Content-Type": "application/json"
        },
        "status": 500
      }
    }
  ]
}
~~~

**Comment by marcingrzejszczak** [comment]
If you're not using verifier but you're using Spring Cloud Contract WireMock them you can use that format cause we're using WireMock directly. I don't understand the problem really

**Comment by peterpivarnik** [comment]
I think I found the reason why it was not working for me.
I was using annotation AutoConfigureWireMock with **stubs**:
~~~
@AutoConfigureWireMock(port = 0, stubs = "file:src/integrationTest/resources")
~~~
With this only single stub can be registered, and you have to use single request for registering it.
But if you will use it with **files**:
~~~
@AutoConfigureWireMock(port = 0, files = "file:src/integrationTest/resources")
~~~
Then you can use single request and also bulk of requests for registering stubs.

Thanks for your time
