### ISSUE TITLE
Spring Cloud Contract build is sensitive to line endings

### ISSUE THREAD

**Issue by shanman190** [spring-cloud/spring-cloud-contract#1567]
At the moment, this would effect the **defaults** for Windows (`\r\n`) and Mac (`\r`) users with respect to file line endings. I'm going to continue to develop a list of the files that are sensitive to line endings, but starting out with I've found at least these from the SC-contract build itself:

Using:
```
./mvnw verify -Pfast
```
NOTE: then having to exclude projects via: `-pl '!spring-cloud-contract-verifier'` to continue onward. 

Classes (confirmed line ending issue):
```
org.springframework.cloud.contract.verifier.util.xml.XmlToXPathsConverterSpec (multi-line Groovy strings)
```

Classes (potential line ending issue):
```
org.springframework.cloud.contract.verifier.wiremock.DslToWireMockClientConverterSpec (surefire/test crashes with exit 0)
```

Modules (potential line ending issues):
```
:spring-cloud-contract-wiremock (surefire/test JVM terminates with no discernable output as to why; surefire ForkStarter exit 0)
:spring-cloud-contract-stub-runner (surefire/test; this one might be something small, but I'll do a little more digging)
    AetherStubDownloaderSpec.Should return credentials from settings_xml » Runtime
    AetherStubDownloaderSpec.Should use local repository from settings.xml » Runtime
    AetherStubDownloaderSpec.should throw an exception when artifact not found in local m2 » Runtime
    AetherStubDownloaderSpec.should throw an exception when local m2 gets replaced with a temp dir and a jar is not found in remote » Runtime
```

Since the code is specifically contained within this project, there's not really a sample to provide. Now of course another possible option to this puzzle would be to just guide users toward checking out the project using *nix (`\n`) line endings.

One other note specifically for Windows users is that even when checking out the project at the root directory, the user will need to enable `core.longPaths` in order to successfully checkout the project locally. Windows has a file path limit of 255 characters by default and with SC-contract this is hit pretty rapidly. This part specifically should probably just be a note in the README for contributing.

**Comment by ankurshukla10** [comment]
@marcingrzejszczak  what needs to be done, I'll be happy to help here.

**Comment by marcingrzejszczak** [comment]
> One other note specifically for Windows users is that even when checking out the project at the root directory, the user will need to enable core.longPaths in order to successfully checkout the project locally. Windows has a file path limit of 255 characters by default and with SC-contract this is hit pretty rapidly. This part specifically should probably just be a note in the README for contributing.

For branch `2.2.x` modify this file https://github.com/spring-cloud/spring-cloud-contract/blob/2.2.x/docs/src/main/asciidoc/_building.adoc by adding a section that enabling `core.longPaths` for Git (e.g. by running the command `git config --system core.longpaths true`) is necessary to build Spring Cloud Contract.

**Comment by ankurshukla10** [comment]
@marcingrzejszczak  just double-checking that for branch 2.2.x, I need to add a "note" in the _building.adoc file to let the users know 'if he/she is trying to build the Spring Cloud Contract on a windows machine then he/she should enable support for long paths in their git config by issuing a command `git config --system core.longpaths true`.
Am I right?

**Comment by shanman190** [comment]
It's that is specifically necessary to enable **before** you clone Spring Cloud Contract. :)

Not doing so results in a half checked out working directory/tree where git has no clue as to what is currently going on.

**Comment by marcingrzejszczak** [comment]
Yeah maybe not a note but maybe a section for Windows users

**Comment by ankurshukla10** [comment]
@shanman190 @marcingrzejszczak  Thank you. I am on it.

**Comment by ankurshukla10** [comment]
@marcingrzejszczak @shanman190   I have raised [pull-request](https://github.com/spring-cloud/spring-cloud-contract/pull/1575) for this. Please review and let me know your thoughts.

**Comment by shanman190** [comment]
So I don't think this is yet _fully_ complete, but how does it sound to break this up into two issues since I can't seem to reopen it? I did a not so great thing when I really mentioned two issues that both relate to Windows in one ticket. I probably should have just gone ahead and wrote up two originally.

As a reminder:
1) Clone options on Windows for core.longPaths (fixed)
2) Build (specifically tests it seems) is sensitive to line endings

Thoughts, @OlgaMaciaszek?
