### ISSUE TITLE
Generated Test has wrong escaping in regex

### ISSUE THREAD

**Issue by nekator** [spring-cloud/spring-cloud-contract#1569]
I wrote a contract using the groovy dsl. I added some dynamic values inside the response and provided a regex to validate the value in the test using the `value(consumer(...),producer(...))` syntax.

The whole expression is wrapped into a GString like this: `"${value(consumer(...), producer(...))}"`
This leads to double escaped backslashes inside the generated test.

sample contract:
```
import org.springframework.cloud.contract.spec.Contract


Contract.make {
    name('sample')
    request {
        urlPath("/")
        method GET()
    }
    response {
        status OK()
        headers {
            contentType(applicationJson())
        }
        body(
                id: "${value(consumer('1'), producer(regex('\\d+')))}"
        )
    }
}
```
generated test:
```
	@Test
	public void validate_sample() throws Exception {
		// given:
			MockMvcRequestSpecification request = given();


		// when:
			ResponseOptions response = given().spec(request)
					.get("/");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);
			assertThat(response.header("Content-Type")).matches("application/json.*");

		// and:
			DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			assertThatJson(parsedJson).field("['id']").matches("\\\\d+");
	}
```

This leads to the following exception:
`java.lang.IllegalStateException: Parsed JSON [{"id":"1"}] doesn't match the JSON path [$[?(@.['id'] =~ /\\d+/)]]`

In my opinion this should generate a valid regex because it is vaild groovy syntax. As a workaround i replaced ` "${value(consumer('1'), producer(regex('\\d+')))}"` with ` value(consumer('1'), producer(regex('\\d+')))`

This lead to `assertThatJson(parsedJson).field("['id']").matches("\\d+");` as generated test code

**Comment by marcingrzejszczak** [comment]
Which version of contract are you using?

**Comment by nekator** [comment]
> Which version of contract are you using?

2.2.0.RELEASE

**Comment by marcingrzejszczak** [comment]
Can you please update to the latest stable release and only then file an issue? Because there is a chance that we've already fixed the issue that you're reporting.

**Comment by nekator** [comment]
> Can you please update to the latest stable release and only then file an issue? Because there is a chance that we've already fixed the issue that you're reporting.

Okay. I will update an the report the results

**Comment by nekator** [comment]
Updated to 2.2.5.RELEASE with the same result.

**Comment by marcingrzejszczak** [comment]
Ok, so your workaround is actually the proper way to do it. You're passing to the body a map, not a string. So you should either do

```groovy
        body(
               "id: ${value(consumer('1'), producer(regex('\\d+')))}"
        )
```

or

```groovy

        body(
                id: value(consumer('1'), producer(regex('\\d+')))
        )
```

**Comment by nekator** [comment]
Okay so this is a correct behaviour and not a bug. 
Thanks for your fast reply and keep up the great work ;)

**Comment by marcingrzejszczak** [comment]
> Okay so this is a correct behaviour and not a bug.

Yup

> Thanks for your fast reply and keep up the great work ;)

No problem and thanks for the nice words :)
