### ISSUE TITLE
GeneratedTest class not extending correct contractPackageRegex class

### ISSUE THREAD

**Issue by rojagadeesh** [spring-cloud/spring-cloud-contract#1580]
Bug
In version 2.2.1, I'm using below baseClassMappings
<baseClassMapping>
  contractPackageRegex> .*com.UpdateFixedTermDepositEndPointV2_0_0.* <- /contractPackageRegex
  baseClassFQN>com.dbs.mdcm.v2_0_0.termdeposit.term_deposits_resource.UpdateFixedDepositsBaseContract 
</baseClassMapping>
<baseClassMapping>
  contractPackageRegex>.*FetchTermDepositsSummaryEndPointV1_0_0.*</contractPackageRegex>
   baseClassFQN>com.dbs.mdcm.termdeposit.term_deposits_resource.TermDepositsInquiryBaseContract</baseClassFQN>
</baseClassMapping>

After running generateTests task, class FetchTermDepositsSummaryEndPointV1_0_0Test not extending from appropriate class.  Is there any limitation to the contractPackageRegex

**Comment by marcingrzejszczak** [comment]
Please upgrade to the latest version and try again.

Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
