### ISSUE TITLE
spring-cloud-contract-wiremock 2.2.3.RELEASE and above breaks test context reloading when using different base classes

### ISSUE THREAD

**Issue by davidmelia** [spring-cloud/spring-cloud-contract#1586]
Hi,

I'm upgrading from Hoxton.SR4 to Hoxton.SR9 and my contract tests started to break.  I have a project to illustrate this https://github.com/davidmelia/spring-cloud-contract-wiremock-issue

I have figure out the issue is localised to the changes in 
```
		<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-contract-wiremock</artifactId>
				<!-- 				<version>2.2.2.RELEASE</version> WORKS -->
				<!-- 				<version>2.2.3.RELEASE</version> DOES NOT WORK -->				
				<version>2.2.5.RELEASE</version>
				<scope>test</scope>
		</dependency>   
```
where 2.2.2.RELEASE works fine but anything above this breaks my tests.

I am using the Wiremock API and have two base classes Dave1ContractBase and Dave2ContractBase. 

Thanks

**Comment by Tavark** [comment]
I don't now if its related, but we are facing an issue with Wiremock as well when updating from Hoxton.SR4 to a newer version. Our setup looks similar to yours.
I found out, that in our case during Wiremock bean creation "https-port" is being set to a random port, though we have explicitly configured.

`
@ActiveProfiles( profiles = { "test" } )
@AutoConfigureWireMock( port = 0 )
`

However, adding the following line to our application-test.yml fixed the issue. Seems like an odd workaround for me.
`
wiremock:
  server:
    https-port: -1
`

**Comment by davidmelia** [comment]
@marcingrzejszczak that's fixed it. Brilliant thanks 😊

**Comment by marcingrzejszczak** [comment]
Great, thanks for checking it out!
