### ISSUE TITLE
Dynamic port usage

### ISSUE THREAD

**Issue by Darkvater** [spring-cloud/spring-cloud-contract#1588]
**Is your feature request related to a problem? Please describe.**
Using spring-cloud-contract 2.2.5
I am confused as to the use of the "wiremock.server.dynamic-port" property. Setting it to true does not use a dynamic port at all, it just silences the warning about using fixed ports.

**Describe the solution you'd like**
One would expect this setting to start using dynamic ports, or if its only purpose is to silence the warning to give it a more descriptive name like 'wiremock.server.warn-about-fixed-ports" for example.
I do agree that random ports should be used as possible and also spring's zero-configuration so I would additionally suggest to change the default port in `AutoConfigureWireMock` to 0 instead of the fixed value of 8080.

**Describe alternatives you've considered**
To get random ports the only solution at the moment is `@AutConfigureWiremock(port = 0)`

**Comment by marcingrzejszczak** [comment]
This property is used by us internally. We set it to `true` once you set the `port=0` as you mentioned. Check the `WireMockApplicationListener` for more details.

**Comment by Darkvater** [comment]
Thanks for the quick reply, my question still stands:
- given that dynamic-port is internal, can it be hidden/removed from the config?
- AutoConfigureWiremock should by default use port 0

**Comment by marcingrzejszczak** [comment]
> given that dynamic-port is internal, can it be hidden/removed from the config?

it cannot but maybe we can add some javadocs on this.

> AutoConfigureWiremock should by default use port 0

we're aligned with the defaults of WireMock. WireMock does not start on a random port by default. It starts on 8080
