### ISSUE TITLE
Stubs mapping directory isn' t created in sub module

### ISSUE THREAD

**Issue by Alvise88** [spring-cloud/spring-cloud-contract#159]
If you have gradle multi project the verifier doesn' t create the mapping with Json folder. The workaround consists to change the stubs directory name.

**Comment by marcingrzejszczak** [comment]
Hi @Alvise88 . Do you think it would be possible for you to create a sample Github project to recreate that? Thanks a lot!

**Comment by yacekmm** [comment]
+1

Similar issue in my case: simple SpringBoot service. gradle task `generateWireMockClientStubs` is not executing since it iss marked as `UP-TO-DATE`. as a result, the `mappings` dir is not created.

Workaround: use --rerun-tasks on gradle build to force `UP-TO-DATE` tasks to run anyway

**Comment by marcingrzejszczak** [comment]
Do you have a sample project? It would help me speed things up with fixing this

**Comment by yacekmm** [comment]
nope, sorry. 

It occured in my production project. Worked for some time, then stopped just like that. I can't figure out what could happen. There were changes in codebase, but none of them touched CDC. Stubs are copied to the jar. Only json mappings are missing (the whole dir)

**Comment by marcingrzejszczak** [comment]
ok so if I have a multimodule Gradle project then this doesn't work? How do you apply the plugin?

**Comment by marcingrzejszczak** [comment]
Ok I've replicated that - https://github.com/marcingrzejszczak/sc-contract-159 . `./gradlew checkMappings` blows up :/
