### ISSUE TITLE
2.2.x build failure in spring-cloud-contract-pact

### ISSUE THREAD

**Issue by bono007** [spring-cloud/spring-cloud-contract#1592]
**Describe the bug**
The 2.2.x branch fails to build in the spring-cloud-contract-pact module with the following:
```
------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spring-cloud-contract-pact: Could not resolve dependencies for project org.springframework.cloud:spring-cloud-contract-pact:jar:2.2.6.BUILD-SNAPSHOT: Could not transfer artifact com.google.guava:guava:jar:30.1-jre from/to spring-plugins (https://repo.spring.io/plugins-release): Not authorized , ReasonPhrase: Unauthorized. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] 
```
At first I thought it was something hosed on my machine but I verified that Circle CI is seeing the same thing [here](https://app.circleci.com/pipelines/github/spring-cloud/spring-cloud-contract/1742/workflows/9d01b666-d1bd-4421-aa3c-c0e205e41d67/jobs/11769).
**Sample**
To reproduce, pull down the latest from 2.2.x  and run `./mvnw clean install`.

**Comment by marcingrzejszczak** [comment]
Should be fixed now
