### ISSUE TITLE
Not Found -> https://docs.spring.io/spring-cloud-contract/docs/3.0.0-SNAPSHOT/reference/htmlsingle/yml-schema.html 

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-contract#1593]
**Describe the bug**
In the official documentation:

3.1.4. Contract DSL in YAML
To see a schema of a YAML contract, visit the YML Schema page.

The link brings to this page:
https://docs.spring.io/spring-cloud-contract/docs/3.0.0-SNAPSHOT/reference/htmlsingle/yml-schema.html

Which returns a

Not Found

The requested URL /spring-cloud-contract/docs/3.0.0-SNAPSHOT/reference/htmlsingle/yml-schema.html was not found on this server.

Thank you

**Comment by marcingrzejszczak** [comment]
You'll have to check it out here https://docs.spring.io/spring-cloud-contract/docs/3.0.0-SNAPSHOT/reference/html/yml-schema.html . Apparently we don't support external files when doing a single page html

**Comment by patpatpat123** [comment]
Hello!

Many thanks for the link. Working fine.
Up to you to close this or not. Depending on you thinking if it can help some other using the single file view.

Thanks again!

**Comment by marcingrzejszczak** [comment]
I'm not closing it just yet. Maybe @Buzzardo has an idea what to do about this?

**Comment by Buzzardo** [comment]
The `htmlsingle` directory contains only one HTML file: the single file that is the reference guide. `link:yml-schema.html[YML Schema]` needs to point to the multi-file version, or we need to add all the HTML files to the `htmlsingle` directory.
