### ISSUE TITLE
Wrong link to the advanced docs

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#1594]
https://docs.spring.io/spring-cloud-contract/docs/3.0.0/reference/html/documentation-overview.html#advanced-topics points to `advanced.html.html`

https://docs.spring.io/spring-cloud-contract/docs/3.0.0/reference/html/project-features.html#features-whats-next doesn't point to `advanced.html`

the documentation code can be found under `docs/src/main/asciidoc`

**Comment by Utkarsh299-tech** [comment]
Hey @marcingrzejszczak! I would like to work on this issue. Can you please assign this to me?

**Comment by marcingrzejszczak** [comment]
There you go @Utkarsh299-tech :)

**Comment by Utkarsh299-tech** [comment]
Thanks, @marcingrzejszczak! I'm working on that.
