### ISSUE TITLE
Add multiple base test classes support

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#16]
Moved from https://github.com/Codearte/accurest/issues/205

**Comment by dhanaraj0** [comment]
Anyone lands here can have a look at 
https://cloud.spring.io/spring-cloud-contract/multi/multi__spring_cloud_contract_verifier_setup.html#gradle-different-base-classes

**Comment by nareshn842** [comment]
Hello Team,

Is this resolved. 

Is this allowed to define multiple packages for basePackageForTests and is multiple classes allowed for baseClassForTests.?

basePackageForTests = 'com.testcompany.testgroup.abc'
baseClassForTests = "com.testcompany.testgroup.abc.ApplicationTest"

Here I want to add multiple packages and classes for base package/class.

Can you please let me know.

Thanks,
Naresh

**Comment by marcingrzejszczak** [comment]
No, you have to use the regex based base class matching

**Comment by nareshn842** [comment]
@marcingrzejszczak  Hi , Can you please share some reference for regex base class matching.

**Comment by marcingrzejszczak** [comment]
It's in the documentation - https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/gradle-project.html#by-mapping and https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/maven-project.html#by-mapping

**Comment by nareshn842** [comment]
Thank you for the reply. Can you confirm to use this regex syntax, we need to use  spring cloud contract 3.0 version and Spring Boot version 2.4 please confirm .?

We are using boot 2.2.2 and contract version 2.1.1 . With this version its not compiling.

Thanks,
Naresh

**Comment by marcingrzejszczak** [comment]
This got fixed 5 years ago. Please double check what you're doing.
