### ISSUE TITLE
Use jsonPath style in contract DSL

### ISSUE THREAD

**Issue by ezraroi** [spring-cloud/spring-cloud-contract#160]
When i was writing normal controller tests to validate the my api is not broken i was writing things like this:
```java
.andExpect(jsonPath("$.fieldErrors", hasSize(1)))
            .andExpect(jsonPath("$.message", is("error.validation")))
            .andExpect(jsonPath("$.fieldErrors[0].field", is("cmdName")))
            .andExpect(jsonPath("$.fieldErrors[0].message", is("NotNull")));
```

Not that i moved to Spring-Cloud-Contracts, how can i achieve such thing in the DSL?

**Comment by marcingrzejszczak** [comment]
With the DSL currently the index based verification of the json is experimental (it's really hard to properly recurse over the json and build regex with index). You can try it out:

```
The support for the verification of size of JSON arrays is experimental. If you want to turn it on please provide the value of a system property spring.cloud.contract.verifier.assert.size equal to true. By default this feature is set to false. You can also provide the assertJsonSize property in the plugin configuration.
```
from https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_limitations

**Comment by ezraroi** [comment]
Cool, thanks for the super fast answer.. And how can I evaluate expression as 
```
jsonPath("$.fieldErrors[0].message", is("NotNull"))
```

**Comment by marcingrzejszczak** [comment]
Hmm I don't think that this is supported :/ But you can do (assuming that this is a response part)

```
Contract.make {
    response {
        [
            fieldErrors: [
                message: $(producer(execute('isNotNull($it)')), consumer("some message"))
            ]
        ]
    }
}
```

You need to have a `isNotNull(Object o)` method in your base class. You can also add a static import to some commons or sth and execute some static method. The `$it` thing will be converted to the jsonPath. In other words it will be converted to sth like this:

This is a part of a generated test

```
isNotNull(jsonPath("$.fieldErrors[*].message")
```

Something like that ;)

**Comment by ezraroi** [comment]
Cool... that was very useful. I think that the documentation is missing some details on json assertion

**Comment by marcingrzejszczak** [comment]
Why? It's written here - https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_executing_custom_methods_on_server_side

**Comment by ezraroi** [comment]
I meant not the part of the server method execution but the fact that I can write json on the right side of the filed name, like here:
```
fieldErrors: [
                message: $(producer(execute('isNotNull($it)')), consumer("some message"))
]
```

I was sure that i can only use value or $ there

**Comment by marcingrzejszczak** [comment]
hmm not sure that I get it so I'll just explain everything :P

this is Groovy notation (I write about it here - https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_contract_dsl and mention the Groovy JSON support docs - http://groovy-lang.org/json.html)

`$()` is a method that can have a producer / consumer thing (https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_what_is_this_value_consumer_producer) . As you mentioned you can name it `value(...)` too. And that's pretty much it I think :P
