### ISSUE TITLE
spring-cloud-contract-maven-plugin 3.0.0 - You haven't configured a MockMVC instance. You can do this statically

### ISSUE THREAD

**Issue by LoganDev99** [spring-cloud/spring-cloud-contract#1601]
Using start.spring.io with Spring Boot ```2.4.2``` with Web and Contract Verifier, which pulls in version ```3.0.0``` of the spring-cloud-contract-maven-plugin. Using this guide to learn Spring CDC. https://spring.io/guides/gs/contract-rest/

I'm getting this error even though I have ```standaloneSetup()``` configured. Bumping the plug-in down to version ```2.2.5.RELEASE``` works, but just curious what to do with version ```3.0.0```. Haven't found a guide for version ```3.0.0``` saying to do anything different.

```
You haven't configured a MockMVC instance. You can do this statically

RestAssuredMockMvc.mockMvc(..)
RestAssuredMockMvc.standaloneSetup(..);
RestAssuredMockMvc.webAppContextSetup(..);
```

**Sample**
With spring cloud version ```2020.0.0```
README has additional information.
https://github.com/LoganDev99/springcdc

**Comment by marcingrzejszczak** [comment]
Your base classes are using JUnit 4 imports - https://github.com/LoganDev99/springcdc/blob/master/src/test/java/com/example/cdc/BaseClass.java#L3 and the generated test is using JUnit 5 ones. Please change `@Before` to `@BeforeEach` and remove the `@RunWith` annotation.

**Comment by LoganDev99** [comment]
> Your base classes are using JUnit 4 imports - https://github.com/LoganDev99/springcdc/blob/master/src/test/java/com/example/cdc/BaseClass.java#L3 and the generated test is using JUnit 5 ones. Please change `@Before` to `@BeforeEach` and remove the `@RunWith` annotation.

Perfect, that was the issue.

To configure the framework used update your ```<testFramework>``` configuration.

JUnit 4 use ```JUNIT```
JUnit 5 use ```JUNIT5```

```
	<plugin>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-contract-maven-plugin</artifactId>
		<version>${spring-cloud-contract.version}</version>
		<extensions>true</extensions>
		<configuration>
			<testFramework>JUNIT</testFramework>
			<baseClassForTests>hello.BaseClass</baseClassForTests>
		</configuration>
	</plugin>
```

**Comment by marcingrzejszczak** [comment]
Updated the samples - https://github.com/spring-guides/gs-contract-rest/commit/43ecad96d887e41b733fbd6fd1a5a1f65c786229
