### ISSUE TITLE
Spring Cloud 2020.0.0 StubTigger no longer sends messages to channels

### ISSUE THREAD

**Issue by davidmelia** [spring-cloud/spring-cloud-contract#1603]
Please see https://github.com/davidmelia/spring-cloud-contract-streamlistener-consumer as reference

Is summary the above project works fine in Spring Cloud Hoxton SR9 / Boot 2.3.8.RELEASE but breaks when upgrading to Spring Cloud 2020.0.0 / Boot 2.4.1.

 I have a consumer for JSON and AVRO and I have 4 tests in ConsumerIntegartionTest

- testJsonFxRateEvent - simple test to send JSON payload to my consumer and check it's been received.
- testJsonFxRateEventViaSpringCloudContract - simple test to send JSON payload to my consumer via stub trigger and check it's been received
- testAvroFxRateEvent - simple test to send AVRO payload to my consumer and check it's been received.
- testAvroFxRateEventViaSpringCloudContract - simple test to send AVRO payload to my consumer via stub trigger and check it's been received

Spring Cloud Hoxton SR9 / Boot 2.3.8.RELEASE they all pass.
Spring Cloud 2020.0.0 / Boot 2.4.1 both testJsonFxRateEventViaSpringCloudContract and testAvroFxRateEventViaSpringCloudContract fail indiciating that the stub trigger is broken somewhere.

Any ideas?

Thanks

N.B I cannot upgrade to the new stream functional way of doing things due to another issue in spring cloud contract - https://github.com/spring-cloud/spring-cloud-contract/issues/1602 but interestingly if I upgrade my reference project here we get a different issue.

**Comment by marcingrzejszczak** [comment]
Please change this:

```xml
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-test-support</artifactId>
			<scope>test</scope>
		</dependency>
```

and use this:

```xml
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
			<type>test-jar</type>
			<scope>test</scope>
			<classifier>test-binder</classifier>
			<optional>true</optional>
		</dependency>
```

The former is deprecated and the latter works with the legacy, non functional stream approach too.

**Comment by davidmelia** [comment]
Sorry I assumed the new test binder was for the functional approach only. Thanks
