### ISSUE TITLE
Does current stub runner support wiremock's parameters?

### ISSUE THREAD

**Issue by namidairo777** [spring-cloud/spring-cloud-contract#1605]
Firstly, I am not sure this is already supported or not. 
So appreciate if someone can confirm it for me.  🙇‍♂️ 
(Couldn't find `question` type when issuing tickets)

## Question
Currently I am following [this guide](https://cloud.spring.io/spring-cloud-contract/reference/html/docker-project.html#docker-stubrunner-example) to run a container which reads my local maven contracts.
As far as I know, internally it runs wiremock server on a different port. 
But stub runner jar only supports these application properties [spring-cloud-contract/reference](https://cloud.spring.io/spring-cloud-contract/reference/html/appendix.html)
How can I customize the wiremock to use the parameters [Command line options](http://wiremock.org/docs/running-standalone/) ?
E.g. If I want to have `--no-request-journal` and `--disable-request-logging`, how can I achieve it?

I want to use this as mock server for some performance test, but current default setting will blow up heap and memory...

### My tests
```bash
docker run --rm -e "STUBRUNNER_IDS=com.xxx:1.0.0-SNAPSHOT:stubs:9876" -e "STUBRUNNER_STUBS_MODE=LOCAL" -v "${HOME}/.m2/:/root/.m2:ro" -p "8083:8083" -p "80:9876" /springcloud/spring-cloud-contract-stub-runner:2.2.5.RELEASE --entrypoint "java -Djava.security.egd=file:/dev/./urandom -jar /stub-runner-boot.jar --disable-request-logging --no-request-journal"
```

These data always exists... 😢 

- Request journal: access `http://localhost/__admin/requests`
- Request logs 
![image](https://user-images.githubusercontent.com/5969716/106151035-46d5da00-61bf-11eb-933f-fdb5a51824e1.png)

**Comment by marcingrzejszczak** [comment]
`--disable-request-logging --no-request-journal` those are not supported. You can disable logging by looking at this answer https://stackoverflow.com/questions/44460834/cant-turn-off-debug-logging-for-wiremock so theoretically you could set this

```
-e "LOGGING_LEVEL_COM_GITHUB_TOMAKEHURST_WIREMOCK=WARN\
-e "LOGGING_LEVEL_WIREMOCK_ORG=ERROR"\
-e "LOGGING_LEVEL_WIREMOCK=WARN"
```

I haven't tested it though so please double check if it's working.

**Comment by namidairo777** [comment]
@marcingrzejszczak 
Thanks for your reply. 
I also tried this way, but request journal still exists no matter of log level.
I generated stub mappings from contracts and used wiremock instead.

**Comment by namidairo777** [comment]
Thanks for looking into this question.
It would be much nicer if stub runner can easily configure wiremock settings as well~
I will close this issue
