### ISSUE TITLE
wiremock.reset-mappings-after-each-test does not work on nested class test

### ISSUE THREAD

**Issue by michaldo** [spring-cloud/spring-cloud-contract#1610]
Example: in given form the test pass
When nested class is uncommented, test fails
```
@SpringBootTest(properties = "wiremock.reset-mappings-after-each-test=true")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@AutoConfigureWireMock(port=0)
class WiremockApplicationTests {

	@Value("${wiremock.server.port}")
	String port;

	private WebTestClient webTestClient ;

	@BeforeEach
	void initWebtest() {
		webTestClient = WebTestClient.bindToServer()baseUrl("http://localhost:" + port).build();
	}

//	@Nested
//	class NestedClass {

		@Test
		@Order(1)
		void test200() {
			WireMock.stubFor(WireMock.get("/").willReturn(WireMock.aResponse().withStatus(200)));

			webTestClient.get().exchange().expectStatus().isOk();
		}


		@Test
		@Order(2)
		void test404() {
			webTestClient.get().exchange().expectStatus().isNotFound();
		}
//	}

```
'springCloudVersion', "2020.0.1"

**Comment by marcingrzejszczak** [comment]
I wonder if it's not related to Spring as such. In Contract we're leveraging the Spring's TestExecutionListener. If you run the tests with logs to DEBUG do you see any Contract logs being printed or the WireMockTestExecutionListener is not being called at all?

**Comment by michaldo** [comment]
On nested case I see the following:

> WireMockTestExecutionListener  : No @AutoConfigureWireMock annotation found on [class deleteme.wiremock.WiremockApplicationTests$NestedClass]. Skipping

**Comment by marcingrzejszczak** [comment]
Ah, so we should check for annotations also on the parent class too. We're not supporting nested classes for the time being then.

**Comment by bono007** [comment]
@marcingrzejszczak 

I started looking into this one. So far I have found that the [AnnotationUtils.findAnnotation](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/annotation/AnnotationUtils.java#L530) does not work in the nested case as it uses [SearchStrategy.TYPE_HIERARCHY](https://github.com/spring-projects/spring-framework/blob/5d70aaacef55185e92b0e465ffc7fbee5818bfaf/spring-core/src/main/java/org/springframework/core/annotation/MergedAnnotations.java#L475) and we need to use [SearchStrategy.TYPE_HIERARCHY_AND_ENCLOSING_CLASSES](https://github.com/spring-projects/spring-framework/blob/5d70aaacef55185e92b0e465ffc7fbee5818bfaf/spring-core/src/main/java/org/springframework/core/annotation/MergedAnnotations.java#L486). There is no current way to override the strategy in AnnotationUtils but this code does the trick to get past this first issue:

```java
private boolean annotationMissing(TestContext testContext) {
  Annotation annotation = MergedAnnotations
      .from(testContext.getTestClass(), MergedAnnotations.SearchStrategy.TYPE_HIERARCHY_AND_ENCLOSING_CLASSES,
          RepeatableContainers.none())
      .get(AutoConfigureWireMock.class).withNonMergedAttributes().synthesize(MergedAnnotation::isPresent)
      .orElse(null);
  ...
  
```

It still is not working as I am sure there are other pieces of code doing the same. I will get back to this sometime today but just wanted to drop some status.

**Comment by bono007** [comment]
> It still is not working as I am sure there are other pieces of code doing the same.

This was just a side effect of the way that my test was structured. The nested and outer had slightly different configs so the context was not being shared and wiremock port was different in nested class.
