### ISSUE TITLE
Allow specifying list of possible key values

### ISSUE THREAD

**Issue by christine-hundt-idealo** [spring-cloud/spring-cloud-contract#1619]
We are using version "2020.0.1 of spring-cloud-contract".
In our contract, we need to be able to restrict the possible key values to a defined list.
Like in:
```
body([
    manyKeys: [
        ($(anyOf("FIRST_KEY", "SECOND_KEY"))): "theValue"
    ]
])
```
This contract generates a test containing unresolved strings like "DslProperty":
```
.body("{\"manyKeys\":{\"DslProperty{\\nclientValue=^FIRST_KEY$|^SECOND_KEY$, \\n\tserverValue=FIRST_KEY}\":\"theValue\"}}");
```

We would like to have a test, that is only valid, when we send the keys "FIRST_KEY" or "SECOND_KEY".
We also considered to use a regex instead of `anyOf,` but it also fails.

Example project: [keyValidaion.zip](https://github.com/spring-cloud/spring-cloud-contract/files/6060417/keyValidaion.zip)

**Comment by marcingrzejszczak** [comment]
We have not considered having the regular expression applied for the key really. What you can do is the following

```groovy

["FIRST_KEY", "SECOND_KEY"].collect { String acceptedKey ->

  return Contract.make { 
    ...
       manyKeys: [
           (acceptedKey) : "theValue"
       ]
    ...
  }

}

```

that way you'll create an array of contracts.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by christine-hundt-idealo** [comment]
Sorry for waiting so long with the feedback!
I was hoping to be able to write a contract, as suggested in my initial comment, because of https://stackoverflow.com/questions/56851252/key-validation-in-spring-cloud-contract-tests. But this might have been misleading.

With your suggested idea of creating an array of contracts, I have two problems:

1. I can not make it work. This might be caused by a lack of groovy knowledge.
My complete contract looks like this:
```groovy
package contracts
["FIRST_KEY", "SECOND_KEY"].collect { String acceptedKey ->

    return Contract.make {
        request {
            headers {
                contentType(applicationJson())
            }
            method 'POST'
            urlPath('/anyPath')
            body([
                    manyKeys: [
                            (acceptedKey): "theValue"
                    ]
            ])
        }
        response {
            status 200
        }
    }
}
```
And I get the error:

`Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:3.0.1:generateTests (default-cli) on project keyvalidation: Execution default-cli of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:3.0.1:generateTests failed: groovy.lang.MissingPropertyException: No such property: Contract for class: contracts.keyValidation
`

2. More important: For our use-case, it should also be allowed to have multiple of the allowed keys in one request body. Eg.
```json
{ 
    "manyKeys": 
    {
        "FIRST_KEY": "firstValue",
        "SECOND_KEY": "secondValue",
        "MORE_KEYS": "moreValues"
    }
}
```

I see, that this kind of applying regular expressions might require bigger changes, eg. because this issue is still open: https://github.com/json-path/JsonPath/issues/439, but we would be very happy if it will possible to define such contracts in the future :-).

**Comment by marcingrzejszczak** [comment]
> Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:3.0.1:generateTests (default-cli) on project keyvalidation: Execution default-cli of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:3.0.1:generateTests failed: groovy.lang.MissingPropertyException: No such property: Contract for class: contracts.keyValidation 

You need to use fully qualified name or an import for `Contract`. In other words just add `import org.springframework.cloud.contract.spec.Contract` at the top

**Comment by christine-hundt-idealo** [comment]
Thank you, that works.
