### ISSUE TITLE
Contract stubs return incorrect response when the wiremock differs only by request body

### ISSUE THREAD

**Issue by alexsander55** [spring-cloud/spring-cloud-contract#1620]
When we have multiple contracts which differ only by the number of parameters passed in the request body, sometimes it returns back incorrect wiremock response.

We have multiple contracts defined in a groovy and they differ only by request body
The request body we pass is Array of Strings.

A sample contract is as below.
```
[
                Contract.make {
                                request {
                                                method('POST')
                                                headers {
                                                                contentType(applicationJson())
                                                }
                                                **body([["A"]])**
                                                **url("/test/find")**
                                }
                                response {
                                                status 200
                                                **body(file("response1.json"))**
                                                headers {
                                                                contentType(applicationJson())
                                                }
                                }
                },
                Contract.make {
                                request {
                                                method('POST')
                                                headers {
                                                                contentType(applicationJson())
                                                }
                                                **body(["A","B"])**
                                                **url("/test/find")**
                                }
                                response {
                                                status 200
                                                **body(file("response2.json"))**
                                                headers {
                                                                contentType(applicationJson())
                                                }
                                }
                }
]

```
Now when we use the above contract stub , then sometimes when we trigger request with request body of 2 ("A","B") the stub returns contract response with one value.

when we Request for **/test/find with param ["A","B"]** is triggered we get **response1** back instead of **response2**.

How the Contract stub is processed:

2021-03-04 11:51:53.498  INFO 24136 --- [qtp968796075-31] WireMock                                 : Request received:
**127.0.0.1 - POST /test/find**

Accept: [application/json]
Cache-Control: [no-cache]
User-Agent: [Apache-CXF/3.2.4]
Connection: [keep-alive]
Host: [localhost:9191]
Pragma: [no-cache]
Content-Length: [16]
Content-Type: [application/json]
**[ "A", "B" ]**

Matched response definition:
{
  "status" : 200,
  **"body" : "{\"DXB\":[{\"company_code\":\"one\"}]}",**
  "headers" : {
    "Content-Type" : "application/json"
  },
  "transformers" : [ "response-template" ]
}

Response:
HTTP/1.1 200
Content-Type: [application/json]
Matched-Stub-Id: [5f393074-0902-4f76-a934-02dd4f91e1ca]

How it should have processed:

2021-03-04 11:51:53.498  INFO 24136 --- [qtp968796075-31] WireMock                                 : Request received:
**127.0.0.1 - POST /test/find**

Accept: [application/json]
Cache-Control: [no-cache]
User-Agent: [Apache-CXF/3.2.4]
Connection: [keep-alive]
Host: [localhost:9191]
Pragma: [no-cache]
Content-Length: [16]
Content-Type: [application/json]
**[ "A", "B" ]**

Matched response definition:
{
  "status" : 200,
  **"body" : "{\"A\":[{\"company_code\":\"one\"}],\"B\":[{\"company_code\":\"two\"}]}",**
  "headers" : {
    "Content-Type" : "application/json"
  },
  "transformers" : [ "response-template" ]
}

Response:
HTTP/1.1 200
Content-Type: [application/json]
Matched-Stub-Id: [5f393074-0902-4f76-a934-02dd4f91e1ca]

**Comment by marcingrzejszczak** [comment]
Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by alexsander55** [comment]
Spring Cloud Vresion is Hoxton.SR1

Sample groovy file used in the stub is 
[Uploading sample.groovy…]()

The issue is not replicated always, out of 5 attempts to run the Contract test 1 attempt fails when it tries to match to incorrect contract

**Comment by marcingrzejszczak** [comment]
Please upgrade to the latest version and try again. Hoxton.SR1 is old. Also, please provide a sample that replicates the issue

**Comment by alexsander55** [comment]
I have sample of the groovy file handy with me


``
[
Contract.make {
	request {
		method('POST')
		headers {
						contentType(applicationJson())
		}
		**body([["A"]])**
		**url("/test/find")**
	}
	response {
		status 200
		**body(file("response1.json"))**
		headers {
						contentType(applicationJson())
		}
	}
},
Contract.make {
	request {
		method('POST')
		headers {
						contentType(applicationJson())
		}
		**body(["A","B"])**
		**url("/test/find")**
	}
	response {
		status 200
		**body(file("response2.json"))**
		headers {
						contentType(applicationJson())
		}
	}
}
]

**Comment by alexsander55** [comment]
I dont have the full applciation with me, but when we add the below groovy as a stub to service , then it fails once in a while 
[samplegroovy.zip](https://github.com/spring-cloud/spring-cloud-contract/files/6147486/samplegroovy.zip)

Will try with updated version and see if it picks.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
