### ISSUE TITLE
WireMockRestServiceServer#build() accepts POST method even if that wasn't specified in the JSON file.

### ISSUE THREAD

**Issue by schjan79** [spring-cloud/spring-cloud-contract#163]
The MockRestServiceServer created by the build method of class WireMockRetServiceServer responds to POST request even if the JSON specifies a GET end-point.

See the test in the attached patch.

[test_simplePutShouldFail.zip](https://github.com/spring-cloud/spring-cloud-contract/files/638002/test_simplePutShouldFail.zip)

**Comment by marcingrzejszczak** [comment]
@schjan79 Thanks a lot for uploading the patch - it was much easier to test this!!
