### ISSUE TITLE
Random https port in annotation AutoConfigureWireMock is broken

### ISSUE THREAD

**Issue by asgoth** [spring-cloud/spring-cloud-contract#1633]
**Describe the bug**

Using `@AutoConfigureWireMock` with a random https port (`httpsPort = 0`) does not work anymore. The starting server has the default 443 port.

The bug seems to be caused by the following if statement in `WireMockApplicationListener`:

```
	private void registerPort(ConfigurableEnvironment environment) {
		Integer httpPortProperty = environment.getProperty("wiremock.server.port", Integer.class);
		// If the httpPortProperty is not found it means the AutoConfigureWireMock hasn't
		// been initialised.
		if (httpPortProperty == null) {
			return;
		}
```
The workaround is to add `port = 0` too, e.g. `@AutoConfigureWireMock(port = 0, httpsPort = 0)`.

Versions used:

- Spring Boot BOM version: 2.4.4
- Spring Cloud BOM version: 2020.0.2
- Spring Cloud Contract version: 3.0.2

**Sample**

Just annotate a class with `@AutoConfigureWireMock(httpsPort = 0)`.

**Comment by marcingrzejszczak** [comment]
hey @asgoth are you willing to apply a fix to the 2.2.x branch?

**Comment by varpa89** [comment]
@marcingrzejszczak we need it in 2.2.x as well

**Comment by marcingrzejszczak** [comment]
Great! If anyone is interested in providing the fix then it would be great!

**Comment by GodwinMaravai** [comment]
Can somebody approve and merge the above fix.

**Comment by GodwinMaravai** [comment]
@marcingrzejszczak When this change will be released

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/fab8b99b3abfaa88e5d44042552e54bc570fdb36

**Comment by marcingrzejszczak** [comment]
Please check this milestone page https://github.com/spring-cloud/spring-cloud-release/milestone/102
