### ISSUE TITLE
issue with handling oneOf if value contains special symbols

### ISSUE THREAD

**Issue by nik-lazer** [spring-cloud/spring-cloud-contract#1635]
**Problem statement**
I have a contract, which has Enum in one field, and one of the values contains "+", e.g. "VAL+VAL".
full example here:
```
package contracts

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    name 'anyOf test'
    request {
        method 'POST'
        url ("hello")
        body(
                type: anyOf("VAL", "VAL+VAL")
        )
    }
    response {
        status OK()
    }
}
``` 
When I am trying to generate tests, I am getting an error:
`Execution default-convert of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:3.0.2:convert failed: java.lang.IllegalStateException: The generated value [VAL+VAL] doesn't match the pattern [^VAL$|^VAL+VAL$]`

**Sample**
The full sample can be found [here](https://github.com/nik-lazer/contract-verifier-issue/tree/master).

**Comment by marcingrzejszczak** [comment]
As a workaround you can use `regex` and write the `or` statement yourself

**Comment by nik-lazer** [comment]
> 
> 
> As a workaround you can use `regex` and write the `or` statement yourself

That's clear, and the workaround is available in [branch](https://github.com/nik-lazer/contract-verifier-issue/blob/fix/regex/src/test/resources/contracts/AnyOfCase.groovy)

**Comment by marcingrzejszczak** [comment]
Yup, that's why I marked this as a bug but wanted to provide a workaround so you're not blocked
