### ISSUE TITLE
Wiremocks replicates mapping files from custom stubs directory to default mappings location

### ISSUE THREAD

**Issue by jefferson-lima** [spring-cloud/spring-cloud-contract#1648]
**Describe the bug**
When using `@AutoConfigureWireMock` with a custom `stubs` directory, the mapping files from the custom location are copied to the default location

I have the following setup:

```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@EmbeddedKafka(topics = {"${kafka.topic-name.sms}", "${kafka.topic-name.email}"})
@Import({Application.class, Configuration.class})
@AutoConfigureWireMock(port = 0, stubs = "classpath:/stubs/e2e")
@AutoConfigureDataMongo
@ActiveProfiles("e2e")
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@interface E2EContext {}
```

My mapping files are under `src/test/resources/stubs/e2e`, and the default mappings directory `src/test/resources/mappings` is empty.

When I run my test using the `E2EContext`, the stubs are located and Wiremock works fine, except that the mapping files are copied from `src/test/resources/stubs/e2e` to `src/test/resources/mappings`.

**Comment by marcingrzejszczak** [comment]
I wonder if it's not a problem with WireMock as such. We're just registering the stubs... However, the WireMock's `StubMapping` has a field `shouldBePersisted`. If you set in your WireMock's JSON definition `"shouldBePersisted": false` then most likely the JSON file will not be persisted to the default location.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
