### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by markgargan** [spring-cloud/spring-cloud-contract#1652]
Hi folks, 

When trying to clone the repo I got filename too long when attempting to clone into c:/work. It's that windows filename length issue. Can you clone the repo on windows? 

Thanks,
Mark.

**Comment by TheCoffeeOfficial** [comment]
Hi!
Sure you can, you have to update your git configurations before trying to clone it.
Git configurations are stored in a "gitconfig" file that you can edit with a simple notepad.

On windows the file should be somewhere like "C:\Program Files\Git\mingw64\etc\gitconfig" but it depends on where you've installed the git.
If you use Sourcetree's or other application's internal git then the file path should look like "C:\Users\xy\AppData\Local\Atlassian\SourceTree\git_local\mingw32\etc\gitconfig"
Also, you should check if you can't find it.
"C:\Users\xy\.gitconfig"

To be able to clone files with a longer paths than 255 characters you have to add the following to your gitconfig.

[core]
	longpaths = true

if [core] already there then simply just add longpaths = true below it.
