### ISSUE TITLE
Enable CORS in stub-runner with stubrunner configurations

### ISSUE THREAD

**Issue by szatyinadam** [spring-cloud/spring-cloud-contract#1655]
In our project we use stub-runner to stub backend based on our contracts and the front-end team can develop independently using these stubs.
We use the springcloud/spring-cloud-contract-stub-runner Docker image to serve these stubs but we can not enable CORS globally in the stub runner.
Wiremock has a config for this (`.stubCorsEnabled(true)`), maybe stub-runner can support this as well.

Our preferred solution is a stubrunner config which can get from `${ADDITIONAL_OPTS}`, for example: `"--stubrunner.enableCors=true"`

**Comment by TheCoffeeOfficial** [comment]
This could be a standalone enhancement or the part of this https://github.com/spring-cloud/spring-cloud-contract/issues/1268

**Comment by marcingrzejszczak** [comment]
I like the idea behind #1268. Let's go with such an approach. Feel free to file a pr and I'll review it
