### ISSUE TITLE
Missing .yml file link in spring-cloud-contract documentation

### ISSUE THREAD

**Issue by anushyakkutty** [spring-cloud/spring-cloud-contract#1658]
2.6. XML Support for HTTP has a broken .yml file link :
 https://cloud.spring.io/spring-cloud-contract/reference/html/project-features.html#contract-dsl-xml

Checkout this screenshot : 
![image](https://user-images.githubusercontent.com/13326766/117660302-4a550600-b19d-11eb-8a5c-5699db5d9998.png)

**Comment by marcingrzejszczak** [comment]
Hey, thanks for the report. Are you willing to file a pr with a fix?
