### ISSUE TITLE
can't checkout repo on Windows, filenames too long

### ISSUE THREAD

**Issue by vincent-fuchs** [spring-cloud/spring-cloud-contract#166]
Hi,

I know this is a bit stupid, but just want to mention it in case you're not aware. .. the deeply nested folder structure on the repository makes it difficult to checkout the repository on Windows with its ridiculous length limit for filenames : my local repository where I clone stuff has reasonable length, 33 characters from D: to final slash, included. but when cloning the repo, I get this : 

Checking connectivity... done.

```
error: unable to create file spring-cloud-contract-tools/spring-cloud-contract-g
radle-plugin/src/test/resources/functionalTest/bootSimple/repository/mappings/sp
ring/cloud/twitter-places-analyzer/pairId/collerate_PlacesFrom_Tweet.groovy (Fil
ename too long)
error: unable to create file spring-cloud-contract-tools/spring-cloud-contract-g
radle-plugin/src/test/resources/functionalTest/bootSimple/src/test/groovy/org/sp
ringframework/cloud/contract/verifier/twitter/places/AcceptanceSpec.groovy (File
name too long)
error: unable to create file spring-cloud-contract-tools/spring-cloud-contract-g
radle-plugin/src/test/resources/functionalTest/bootSimple/src/test/groovy/org/sp
ringframework/cloud/contract/verifier/twitter/places/BaseMockMvcSpec.groovy (Fil
ename too long)
fatal: cannot create directory at 'spring-cloud-contract-tools/spring-cloud-cont
ract-gradle-plugin/src/test/resources/functionalTest/sampleJerseyProject/fraudDe
tectionService/src/main/java/org/springframework/cloud/frauddetection': Filename
 too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
```

actually, even when trying to checkout at the root of my drive (D:), I still one issue : 

```
Checking connectivity... done.
error: unable to create file tests/spring-cloud-contract-stub-runner-amqp/src/te
st/resources/m2repo/repository/org/springframework/cloud/contract/verifier/stubs
/amqp/spring-cloud-contract-amqp-test/0.4.0-SNAPSHOT/spring-cloud-contract-amqp-
test-0.4.0-SNAPSHOT-stubs.jar (Filename too long)
fatal: unable to checkout working tree
```

How come we store jars in the git repo  ?

**Comment by marcingrzejszczak** [comment]
It's not really unusual to store jars in git. I'm simulating downloading of jars from an external repo. Maybe try building it using cygwin or Ubuntu for Windows?

**Comment by marcingrzejszczak** [comment]
ping?

**Comment by vincent-fuchs** [comment]
sorry, I thought you would close the issue :-) I can't really try the options you're giving me, as this happens on my machine at the office, and I can't really install Ubuntu or cygwin on it

**Comment by marcingrzejszczak** [comment]
Sorry to hear that. We'll have to close this then cause trying to upgrade all folders will take a while :( Maybe we'll do that some day in the future
