### ISSUE TITLE
wiremock.server.portDynamic is unrelated to whether the port is dynamic or not

### ISSUE THREAD

**Issue by mjaggard** [spring-cloud/spring-cloud-contract#1660]
**Describe the bug**
There is a property which is used to determine whether to mark the context as dirty or not called `wiremock.server.portDynamic` however the property that actually decides is called `wiremock.server.port` and it's set to 0 to be dynamic - `portDynamic` is not accessible from the annotation.

Tested with 3.0.0

**Comment by mjaggard** [comment]
Now tested with 3.0.2 with the same issue. In addition, to prevent the context from being marked as dirty, I have to set `wiremock.server.portDynamic` to true as well as `wiremock.server.httpsPortDynamic` even though I'm not using HTTPS.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
