### ISSUE TITLE
Bump pact dependencies versions to 4.2.X

### ISSUE THREAD

**Issue by heroInCommunity** [spring-cloud/spring-cloud-contract#1661]
Starting from version 4.1 pact is using different schema for their maven dependencies,
like au.com.dius.pact.provider:spring:4.2.5, au.com.dius.pact.provider:junit5spring:4.2.5 etc.

The latest versions of Pact contain different improvements, i.e. Java LocalDate support.

**Comment by marcingrzejszczak** [comment]
Hi! Are you willing to file a pr with the improvement?

**Comment by marcingrzejszczak** [comment]
I think Pact 4.2 is Java 11 based so we can't merge it (I've already done it in one branch and then I had to revert my changes). https://github.com/spring-cloud/spring-cloud-contract/commit/90172436be6590732c2ec70a1e98ce6716fd3c11

**Comment by bastiandoetsch** [comment]
Ah, good to know.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/commit/d5a47e2514f42a039d6ac30df11136de5dd05425
