### ISSUE TITLE
TMS integration

### ISSUE THREAD

**Issue by Daemon2017** [spring-cloud/spring-cloud-contract#1669]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
Is there any way to send results of SCC tests with TMS (Adaptavist, HP ALM, Zephyr etc.)? 

It would be nice if there was a field "TmsId" in contracts, which content would transforn in content of "@TmsId" annotation, for example:
abc.yaml
```
description: >All required and optional fields are filled
name: User sends a correct request and receives an expected response
TmsId: MYPRJ-1298
request:
...
```
abc.java
```
	@Test
        @TmsId(value = "MYPRJ-1298")
	public void validate_User_sends_a_correct_request_and_receives_an_expected_response() throws Exception {
		// given:

```

With such annotation it would be easy to send test result to any TMS via listener.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by marcingrzejszczak** [comment]
We're not planning any such support out of the box.
