### ISSUE TITLE
Regression in number matcher with version SCC 3.0.3 and Spring Boot 2.5

### ISSUE THREAD

**Issue by camory** [spring-cloud/spring-cloud-contract#1670]
**Describe the bug**
When migrating to Spring Cloud Contract 3.0.3 and Spring Boot 2.5, tests using regex matchers like, `anyNumber()`, `anyPositiveInt()`, `anyInteger()` are failing with the following exception:
```
c.toomuchcoding.jsonassert.JsonAsserter  : Exception occurred while trying to match JSON Path [$[?(@.['value'] =~ /-?(\d+)/)]]

com.jayway.jsonpath.InvalidPathException: Failed to parse filter: [?(@.['value'] =~ /-?(\d+)/)], error on position: 18, char: /
	at com.jayway.jsonpath.internal.filter.FilterCompiler.compile(FilterCompiler.java:89) ~[json-path-2.5.0.jar:2.5.0]
	at com.jayway.jsonpath.internal.filter.FilterCompiler.compile(FilterCompiler.java:54) ~[json-path-2.5.0.jar:2.5.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readFilterToken(PathCompiler.java:461) ~[json-path-2.5.0.jar:2.5.0]
```
It seems the issue is related to the upgrade of `com.jayway.jsonpath:json-path` to the version **2.5.0**. If we force the downgrade to the version **2.4.0**, all the tests run successfully.

**Sample**
Here is a contract sample which is failing:
```groovy
package contracts

import org.springframework.cloud.contract.spec.Contract

import static org.springframework.cloud.contract.spec.internal.HttpStatus.OK
import static org.springframework.cloud.contract.spec.internal.MediaTypes.APPLICATION_JSON

Contract.make {
    description """
                Should match any Integer
                """
    request {
        method 'GET'
        url '/values'
        headers {
            contentType APPLICATION_JSON
        }
    }
    response {
        status OK
        headers {
            contentType APPLICATION_JSON
        }
        body([
                "value": anyInteger()
        ])
    }
}
```
Github Sample project reproducing the issue can be found here: https://github.com/camory/sb_2.5_scc_3.0.3_issue

**Comment by marcingrzejszczak** [comment]
Yeah we're aware if the json-path issue. We're waiting for the new json-path release to have it fixed.

**Comment by camory** [comment]
I have tested with version 0.6.1 of `jsonassert` but it 's still failing.
The version of `json-path` defined by `jsonassert` is overriden by the version defined by `spring-boot-starter-test` which is set to 2.5.0 and not 2.6.0. Do you know if Spring Boot 2.5.1 will upgrade to version 2.6.0

I have updated the test project accordingly.

Thanks for your work and your reactivity

**Comment by marcingrzejszczak** [comment]
I had a chat with @snicoll and they're not planning to upgrade that library. I guess you need to do an exclude :shrug:

**Comment by snicoll** [comment]
To put a bit more context, we're not going to upgrade to a new feature release of a third party library in a maintenance release of Spring Boot. Our [Support Policy](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#third-party-dependencies) is available on our wiki. You can override the version of json path in your project using the `json-path.property` and I would advise you to request that team to release a maintenance release for that issue. If they do a `2.5.1` we will upgrade asap.

**Comment by camory** [comment]
@snicoll , I will follow your advice and set the right version wiht the json-path property and in parallel request a maintenance release of `json-path` if it is possible.

Thanks again for your quick feed back and your time

**Comment by manuelnaranjo** [comment]
BTW 2.0.6 got released and it fixes things
