### ISSUE TITLE
Breaking changes of 3.x version (missing migration guide)

### ISSUE THREAD

**Issue by daggerok** [spring-cloud/spring-cloud-contract#1671]
**Describe the bug**

Hello, can you please point me where I can find some migration guide from 2.2.7.RELEASE to 3.0.0 versions?
Or maybe you can look on example I have prepared what's wrong wit hit and why I'm getting `Connection refused` error in `ContractVerifierTest.java:27` after 3.x migration?

**Sample**

Here I have prepared a PR with only version upgrade: https://github.com/daggerok/webflux-reactive-testing-example/pull/2

Thank you

---
Regards,
Maksim

**Comment by marcingrzejszczak** [comment]
JUnit5 is the default and you're mixing Junit4 and Junit5 imports https://github.com/daggerok/webflux-reactive-testing-example/blob/master/reservation-service/src/test/java/com/github/daggerok/contract/BaseClass.java#L7-L8

**Comment by daggerok** [comment]
@marcingrzejszczak 

Thanks a lot! I have migrated both contract maven plugin 2.x -> 3.x and junit 4 -> junit 5

https://github.com/daggerok/webflux-reactive-testing-example/commit/557b750185562de8f2cb22569d339bebed503821
