### ISSUE TITLE
JAR of current Snapshot 3.0.4 has no binary content

### ISSUE THREAD

**Issue by patrickheinzelmann** [spring-cloud/spring-cloud-contract#1674]
The build of Spring Cloud Kubernetes fails as the JAR of the current SNAPSHOT version has no content.

https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-contract-verifier/3.0.4-SNAPSHOT/spring-cloud-contract-verifier-3.0.4-20210620.073042-181.jar

```
{
  "errors" : [ {
    "status" : 500,
    "message" : "Could not process download request: Binary provider has no content for '1e75f60ca30425a4a91b89ac5ad635ae3701b66b'"
  } ]
}
```

**Comment by marcingrzejszczak** [comment]
There was an upgrade of repo.spring.io done and there were some issues that should be resolved now. Please try again.

**Comment by patrickheinzelmann** [comment]
@marcingrzejszczak The repo is still throwing 500 error.

**Comment by marcingrzejszczak** [comment]
Strange... I'm rerunning the build then
