### ISSUE TITLE
Spring boot compatibility table?

### ISSUE THREAD

**Issue by spicalous** [spring-cloud/spring-cloud-contract#1676]
**Describe the bug**

I am running:
- `spring-boot-starter-parent:2.3.11`
- `spring-cloud-starter-contract-stub-runner:3.0.2`

After writing a test with `@AutoConfigureWireMock(port = 0)`, I am getting exception:
```
java.lang.NoClassDefFoundError: org/springframework/test/context/TestContextAnnotationUtils
	at org.springframework.cloud.contract.wiremock.WireMockTestExecutionListener.annotationMissing(WireMockTestExecutionListener.java:96) ~[spring-cloud-contract-wiremock-3.0.2.jar:3.0.2]
```

This is because spring boot 2.3.x is using only `spring-test:jar:5.2.15.RELEASE` whereas `TestContextAnnotationUtils` was introduced only from `spring-test:jar:5.3.0`

Do we have compatibility mentioned anywhere in the docs? 

Happy to contribute in any way, please point me in the right direction

**Comment by marcingrzejszczak** [comment]
It's on the front page of the Spring Cloud homepage - https://spring.io/projects/spring-cloud . You have to use Boot 2.4 or 2.5

**Comment by spicalous** [comment]
Silly me, I was looking at the reference docs! Thanks!
