### ISSUE TITLE
Publish Stubs to SCM targeting a different branch

### ISSUE THREAD

**Issue by JeremyLoy** [spring-cloud/spring-cloud-contract#1679]
**Is your feature request related to a problem? Please describe.**
My organization has many rules surrounding the protection of the master branch. Unfortunately, it would be easier for us to publish stubs targeting a different branch, than it would be to relax the rules.

Also, there has been a recent push to replace `master` with `main` industry wide. Being able to do that through SCC would be nice.

**Describe the solution you'd like**
A `branch` property added to the `contracts.publishStubsToScm.contractRepository` section.

**Describe alternatives you've considered**
I can't think of anything thing else, except maybe adding it to the `repostoryUrl` property, but that would be less clear IMO.

**Additional context**
n/a

**Comment by marcingrzejszczak** [comment]
Please check this section of the documentation https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/maven-project.html#maven-pushing-stubs-to-scm about the Maven plugin and here https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/gradle-project.html#gradle-pushing-stubs-to-scm for the Gradle plugin. In general you can pass the `git.branch` property and that way you will change the branch to which you push your stubs. Check https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/appendix.html#additional-application-properties for more info about other properties.

**Comment by JeremyLoy** [comment]
@marcingrzejszczak thanks for the swift response. I saw that section, but did not realize there was a `git.branch` property. It worked well, we just needed to make the branch ourselves first.

Thank you!
