### ISSUE TITLE
Add the ability to configure Wiremock-extensions to AutoConfigureWireMock-annotation

### ISSUE THREAD

**Issue by Daemon2017** [spring-cloud/spring-cloud-contract#1684]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I often need to use asynchronous stubs and for that I use the ["Webhooks" extension](https://github.com/wiremock/wiremock-webhooks-extension) for WireMock like that:
```
        WireMockServer asyncWireMockServer;
        WireMockConfiguration wireMockConfiguration = wireMockConfig()
                .port(8082)
                .usingFilesUnderDirectory("src/test/resources/async")
                .extensions(new Webhooks())
                .notifier(new Slf4jNotifier(true));
        asyncWireMockServer = new WireMockServer(wireMockConfiguration);
        asyncWireMockServer.start();
```
Can you please add the ability to enable Wiremock-extensions via the AutoConfigureWireMock annotation? Something like that:
```
@AutoConfigureWireMock(port = 8082, stubs = "file:src/test/resources/async", extensions={new Webhooks(), new BodyTransformer()})
```

**Describe alternatives you've considered**

**Additional context**

**Comment by marcingrzejszczak** [comment]
You can already do that. Please read the docs here https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/advanced.html#customization-wiremock . The problem with that particular extension is that it's incompatible with the latest Wiremock verions.
