### ISSUE TITLE
Link to workshop-page in using.adoc is broken

### ISSUE THREAD

**Issue by fabapp2** [spring-cloud/spring-cloud-contract#1685]
[The Reference](https://cloud.spring.io/spring-cloud-contract/reference/html/using.html) links to the [workshop-page](https://cloud-samples.spring.io/spring-cloud-contract-samples/tutorials/contracts_on_the_producer_side.html) but the host `https://cloud-samples.spring.io` can't be resolved.

**Comment by nikpalyi** [comment]
Hi, the correct link could found from https://github.com/spring-cloud-samples/spring-cloud-contract-samples and the correct URL is: https://spring-cloud-samples.github.io/spring-cloud-contract-samples/workshops.html , cheers! NP

**Comment by marcingrzejszczak** [comment]
This https://cloud.spring.io/spring-cloud-contract/reference/html/using.html is a link to old docs. This is the link to the latest ones https://docs.spring.io/spring-cloud-contract/docs/
