### ISSUE TITLE
 spring-cloud-contract-verifier MockMvc requestParameters generation does not support parameters that need encoding

### ISSUE THREAD

**Issue by koslowskyj** [spring-cloud/spring-cloud-contract#170]
# Problem
Currently when using the groovy DSL and adding request parameters,

```

org.springframework.cloud.contract.spec.Contract.make {
  request {
    method 'GET'
    
    urlPath( '/somePath'){
    	queryParameters {
                                        parameter 'filter': 'hello'
                                        parameter 'filter2': 'world'
                                        parameter 'filter3': '{\\"___other___\\":\\"day\\"}'
		}
    }
    headers {
    	header('Accept': 'application/json;charset=UTF-8')
  	}
  }
response {
  status 200
  body("""
         [{
           "id":4
           //some more fields
          }]
  """)
  headers {
    header('Content-Type': 'application/json;charset=UTF-8')
  }
 }
}

```

something like this is generated:

```
ResponseOptions response = given().spec(request)
					.get("/somePath?filter=hello&filter2=world&filter3={\"___other___\":\"day\"}")
//this call leads to an exception because of the json that needs to be encoded which is not done when 
```

just appending it to the path.

while the javadoc of MockMvc states the following: 

> Perform a GET request to a path. Normally the path doesn't have to be fully-qualified e.g. you don't need to specify the path as http://localhost:8080/path. In this case it's enough to use /path.
>**Parameters:**
>path The path to send the request to.
>pathParams The path parameters. E.g. if path is "/book/{hotelId}/{roomNumber}" you can do get("/book/{hotelName}/{roomNumber}", "Hotels R Us", 22);.

# Solution
if something like this would be generated it would work.

```
//this would work and in the rest controller it would also arrive propperly decoded 
ResponseOptions response = given().spec(request)
					.get("/incomingFiles?filter={filter}&filter2={filter2}&filter3={filter3}","hello","world","{\"___other___\":\"day\"}");
```

# Question

**I already added a patch to the spring-cloud-contract-verifier project, but I wonder how to contribute this, should I just open a pull request?**

**Comment by marcingrzejszczak** [comment]
Yeah sure, please open a pull request and let's talk there :)

**Comment by koslowskyj** [comment]
see https://github.com/spring-cloud/spring-cloud-contract/pull/171

**Comment by marcingrzejszczak** [comment]
Thanks - BTW can you elaborate more on this

`//this is a hack for this test see also pluggable architecture test generator https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html`

**Comment by koslowskyj** [comment]
you can ignore or delete this (was a comment to myself when I was trying to play with the DSL), it is possible to "hack" the dsl by providing the correct strings and to bring an encoded queryParameter into the url string

so you could write something like this in the dsl

request {
    method 'GET'
    
    urlPath( '/someURL'){
parameter 'filter': '{json}", "{\\"___any___\\":\\"9999\\"} '
}
}

**Comment by marcingrzejszczak** [comment]
ah I get it... ok let's focus on fixing the bug :)

**Comment by koslowskyj** [comment]
solved in https://github.com/spring-cloud/spring-cloud-contract/pull/171
