### ISSUE TITLE
escaped json string get expanded to wrong asserts in verification test

### ISSUE THREAD

**Issue by Zane-XY** [spring-cloud/spring-cloud-contract#1701]
Given the contract definition

```groovy
  outputMessage {
        body(file('response.json'))
  }
```

response.json

```json
"payload": "{\"propsA\":\"valueA\",\"propsB\":\"valueB\"}"
```

The above contract generates multiple asserts

```java
assertThatJson(parsedJson).field("['payload']").field("['propsA']").isEqualTo("valueA");
assertThatJson(parsedJson).field("['payload']").field("['propsB']").isEqualTo("valueB");
```
The payload here is a json string, should be treated as String, but it wrongly treated as json object.

**Comment by marcingrzejszczak** [comment]
Can you provide content type to be application/json ? Also can you provide which version of contract you are using?

**Comment by Zane-XY** [comment]
@marcingrzejszczak 

this is for a message contract. Can I make content type to be application/json inside a outputMessage?

**Comment by marcingrzejszczak** [comment]
Yes. You can set it via `messageHeaders`

**Comment by Zane-XY** [comment]
I just tried, makes no difference

```json
outputMessage {
        ...
        headers {
            contentType(applicationJson())
        }
}
```
still generates 
```java
			assertThatJson(parsedJson).field("['payload']").field("['propsA']").isEqualTo("valueA");
			assertThatJson(parsedJson).field("['payload']").field("['propsB']").isEqualTo("valueB");
```

**Comment by marcingrzejszczak** [comment]
Meh, I'll have to look into that.
