### ISSUE TITLE
Multiple topics in Embeded Kafka cause error

### ISSUE THREAD

**Issue by Zane-XY** [spring-cloud/spring-cloud-contract#1702]
I saw similar bug has been reported [here](https://github.com/spring-cloud/spring-cloud-contract/issues/1308). 
It is closed by advising using kafka container without really solve the problem. 

If I specify more than one topics here, 
```java
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@AutoConfigureMessageVerifier
@EmbeddedKafka(partitions = 1, topics = {"topic1", "topic2"})
@ActiveProfiles("test")
public abstract class BaseClass  {...}
```

the @AutoConfigureMessageVerifier will throw an error

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.contract.verifier.messaging.MessageVerifier]: Factory method 'contractVerifierKafkaMessageExchange' threw exception; nested exception is java.lang.IllegalStateException: Failed to be assigned partitions from the embedded topics
```

**Comment by marcingrzejszczak** [comment]
I'd suggest to go with the tests getting ran against testcontainers and registering your own message sender / receiver - https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/main/producer_kafka_middleware

**Comment by Zane-XY** [comment]
@marcingrzejszczak yeah, looked into that. 
But I think it's not a matter of Embeded Kafka though. 
If I register my own sender/receiver. Embeded Kafka also works.

I think the problems lies in the following code, `kafkaProperties.getConsumer().getGroupId()` will return the same group id for all the topics, it will trigger a rebalance and cause the error.
make this `kafkaProperties.getConsumer().getGroupId()` read from configurable source or random can solve the issue.

```java
private Consumer prepareListener(EmbeddedKafkaBroker broker, String destination, KafkaProperties kafkaProperties) {
		Map<String, Object> consumerProperties = KafkaTestUtils
				.consumerProps(kafkaProperties.getConsumer().getGroupId(), "false", broker);
...
}
```

I haven't tested, but maybe create the topics via spring-kafka's @NewTopic may skip this issue.

**Comment by marcingrzejszczak** [comment]
But `kafkaProperties.getConsumer().getGroupId()` is configurable. Theoretically, you could type `spring.kafka.consumer.group-id=${random.int}` and it will create a random value?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
