### ISSUE TITLE
Cannot set replyTo property on request message in contract for RabbitMQ (Spring AMQP)

### ISSUE THREAD

**Issue by baranowskikamil** [spring-cloud/spring-cloud-contract#1706]
**Describe the bug**
Hi,

I'm trying to use Spring Cloud Contract with RabbitMQ and with method sendAndReceive from Spring AMQP. 
I hit the point when I'm trying to send request from contract but there is problem with replyTo message property. 

First I tried to set it via header `amqp_replyTo` but it couldn't figure out the replyTo property for request.  It's done in `org.springframework.amqp.rabbit.listener.adapter.AbstractAdaptableMessageListener` and it expected to set replyTo in request (which isn't done in Spring Cloud Contract (SpringAmqpStubMessages)). Then I found metadata, but it wouldn't fix. When I try to set it like this: 

```    metadata("amqp": [
            input: [
                    messageProperties: [
                            'replyTo': 'test.reply.queue'
                    ]
            ]
    ])
```

I got this error:
```
 at [Source: (byte[])"{"replyTo":"test.reply.queue","replyToAddress":{"exchangeName":"","routingKey":"test.reply.queue"}}"; line: 1, column: 49] (through reference chain: org.springframework.amqp.core.MessageProperties["replyToAddress"])
        at xxx.ContractVerifierTest.validate_sendAndReceiveContract(ContractVerifierTest.java:82)
``` 
It couldn't write Address as it doesn't have default constructor (if I understand it correctly). 

After it I tried to modify `SpringAmqpStubMessages#send` by adding this code: 
```		if (headers != null && headers.containsKey(AmqpHeaders.REPLY_TO)) {
			message.getMessageProperties().setReplyTo(header(headers, AmqpHeaders.REPLY_TO));
		}
```

It helped but I got next error: 

```

[ERROR] Failures: 
[ERROR]   ContractVerifierTest.validate_sendAndReceiveContract:86 
Wanted but not invoked:
rabbitTemplate.send(
    "test.reply.queue",
    <Capturing argument>,
    <Capturing argument>,
    <any>
);
-> at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.receive(SpringAmqpStubMessages.java:188)

```

At this point I'm completely lost. Is it possible to use Spring Cloud Contract to verifier "send and receive" with RabbitMQ? 

**Sample**

My contract looks like this:
```package contracts

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    label("sendAndReceiveEvent")
    input {
        messageFrom("test.provider.sendAndReceive.exchange")
        messageBody([
                requestId: '123'
        ])
        messageHeaders {
            header("amqp_replyTo", "test.reply.queue")
            header("amqp_receivedRoutingKey", "test.provider.sendAndReceive.queue")
            header("contentType", "application/json")
            header("correlationId", "31231231")
        }
    }
    outputMessage {
        sentTo('test.reply.queue')
        body('123')
        headers {
            header("correlationId", "31231231")
            header("contentType", "application/json")
        }
    }
}
```

Rabbit listener 
```
@RabbitListener(queues = "test.provider.sendAndReceive.queue")
    public String rabbitListener(SendAndReceiveRequest request, Message message) {
        return request.getRequestId().equals("123") ? "true" : "false";
    }
```

Example of consumer:
```
        String isValid = (String) rabbitTemplate.convertSendAndReceive(
                TEST_DIRECT_EXCHANGE,
                TEST_DIRECT_QUEUE,
                new SendAndReceiveRequest("123")
        );
```

**Comment by marcingrzejszczak** [comment]
Do you have a small sample that we could check out?

**Comment by baranowskikamil** [comment]
Added txt file with change I did in SpringAmqpStubMessages.java
[contract-testing-provider.zip](https://github.com/spring-cloud/spring-cloud-contract/files/7078206/contract-testing-provider.zip)

**Comment by baranowskikamil** [comment]
Is there any plan to fix it? Or any tips what we can do to fix it?

**Comment by marcingrzejszczak** [comment]
I didn't have time to look into that. Is it possible for you to not use the stubbed version of rabbitmq but to run rabbitmq in a container like presented here for producer https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/main/producer_rabbit_middleware and here for consumer https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/main/consumer_rabbit_middleware ? Most likely you'll have to merge the created sender beans into one (cause you want to do both send and receive).

**Comment by baranowskikamil** [comment]
Hi, I tried to use real rabbit instance as in provided examples. I finished with valid contract for sendAndReceive. Currently I stack on "consumer" side test. I would like to have test where I send message to rabbitMq and receive expected response (as in contract). It is simple for REST where I can setup stubRunner. How can I achieve it for rabbit?

**Comment by ysiuu** [comment]
Hi. The above pointers did not get us to a working solution :( Working sendAndReceive contracts would make it possible to avoid mixing HTTP next to AMQP for handling communication between services and keep using Spring Cloud Contract. Is there maybe another approach we can try to make it work?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
