### ISSUE TITLE
response body with text content type header still being verified using json matchers

### ISSUE THREAD

**Issue by regevbr** [spring-cloud/spring-cloud-contract#172]
Using response body as follows:

```
body '{"a":1}\n{"a":2}'
 headers {
            contentType(textPlain())
        }

```

Even though this is a non standard json, it still trys to convert the output of the endpoint to json and compare it to the "first" object stated. e.g.:

```
DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
assertThatJson(parsedJson).field("a").isEqualTo(1);
```

The reason for this use case is for endpoints that are performing streaming of new line seperated json objects.

**Comment by regevbr** [comment]
@marcingrzejszczak suggest the following workaround for now:
body($(consumer('{"a":1}\n{"a":2}'), producer(execute('checkThisOut($it,"{\"a\":1}\n{\"a\":2}")')))
which works for me

**Comment by marcingrzejszczak** [comment]
Done in https://github.com/spring-cloud/spring-cloud-contract/commit/c1b2fd4432209233cc5c4b3661cc498eba2bd589

**Comment by regevbr** [comment]
:star
