### ISSUE TITLE
Spring-cloud-contract tests aren't considered in jacoco sonarqube reports.

### ISSUE THREAD

**Issue by cygair** [spring-cloud/spring-cloud-contract#1726]
Dear all,

I'm coming here to find your help, since we're turning around for many days.

Our project si contract first, and we're using gradle. We've two repos :

- repo-contract
- repo-service

The service is a spring-boot rest service.
In the repo-contract we have ;

- Yaml contract
- groovy contracts
- BaseStubsClassTests.

_gradle clean compile_ is working perfectly.

In the repo-service, we're importing the repo-contract, and making tests with a BaseClassTest and building classes with openapigen.
Tests are correctly generated, and when doing a gradle clean build, contract tests are runs correctly. BUT ! Since there is an issue, the generated tests arn't included in the jacaco reports (I can't out jacoco, it's a company mandatories) and sonarqube.

We tried to include the BaseClassTest package  in jacoco/sonarqube gradle config, and the generated test class package, without any change ...

Our service include : 

src/main:
- mycompany/myservice/controller/controller.class

src/test:
- mycompany/myservice/cloudcontracttests/baseTests.class

Thank you for your return.

Cyril G.

**Comment by jamietanna** [comment]
On a Gradle repo I've tested this with, I've got the JaCoCo plugin applied, and have:

```groovy
plugins {
  id 'java'
  id 'jacoco'
}


jacocoTestReport {
  reports {
    xml.enabled true
  }
}
test.finalizedBy jacocoTestReport
```

And then running a `./gradlew clean contractTest` shows there's a JaCoCo exec file generated:

```
-rw-r--r--  1 jamie jamie 303711 Jan  6 16:11 contractTest.exec
```

**Comment by marcingrzejszczak** [comment]
So I guess we can close this
