### ISSUE TITLE
Add a possibility to use packageWithBaseClasses inside baseClassMappings

### ISSUE THREAD

**Issue by viniciustoni** [spring-cloud/spring-cloud-contract#1730]
Hello, 

I'm creating contract tests on my current project and I got into a situation which I have 2 different packages for my controllers:

- internal: All controllers that will be available only inside our VPN.
- external: All controllers that we want to expose to external clients.

We are using spring profile to determine which controllers the spring needs to expose for that particular instance.

So I would like to create our stubs on the same model as it's configured our controllers, with internal and external packages, but on  spring-cloud-contract-maven-plugin we can only add one _packageWithBaseClasses_ which makes sense, so one way that I was trying to configure the verify plugin to work this way, was to use _baseClassMappings_  for the package with "less" amount of controllers and _packageWithBaseClasses_ for the package with "more" controllers, but the problem is that all the time that we create a new contract test for controllers under _baseClassMappings_ I'll need to also add one entry on my pom, so the change for us to forget about it could be high.

So thinking on that, is there any change that we can add something similar to _packageWithBaseClasses_ inside _baseClassMappings_? Or a new configuration property which we can organize our stub/base test into packages?

I've create one project example on my own github: https://github.com/viniciustoni/scc-examples  (the pom with the conf is here: https://github.com/viniciustoni/scc-examples/blob/main/sales-products/pom.xml).

**Comment by marcingrzejszczak** [comment]
You can create all 3 possible configurations. Why the current configuration option is not correct?

**Comment by viniciustoni** [comment]
Hi @marcingrzejszczak , 

It was one of my first way to solve this problem, but I didn't find the proper configuration to "link" the contract folder with package folder, for example:
- For all controllers that are configured with local profile: get all contracts for path <MyGitRepo>/groupId/artifactId/versionId/internal and use all base class present on _packageWithBaseClasses_ = `com.vagai.salesproducts.controller.internal`
- For all controllers that are configured with external profile: get all contracts for path <MyGitRepo>/groupId/artifactId/versionId/external and use all base class present on _packageWithBaseClasses_ = `com.vagai.salesproducts.controller.external`

Also I tried on multi-configuration level with:

1. Created a contract structure folder where I can filter the contracts per "profile" via version(contractDependency.version);
2. Created a contract structure folder where I can filter the contracts per "profile" via artifactId(contractDependency.artifactId);

for both of them the problem that I had was that during download phase, from git, it's downloading correct from the first conf, but for the next configuration, with different version/artifactId instead of download it again it'll use the same files that from first conf, and on this case it'll not contains the proper contracts for that particular version.
To be honest if I can use via configuration where I can split those contracts via version or artifactId, for me will be the best case scenario, because on consumer tests I can also use the proper set of contracts that we want, for example app that has only access to one set of endpoint, will have the consumer test for the internal contracts. 

I also tried to add all the contracts on the same contractDependency, and then create 2 configuration divided by `<contractsPath>internal</contractsPath>` or `<contractsPath>external</contractsPath>` the problem with this one was that the generated code will add the contract path on Base class name, for example: public class ProductExternalControllerTest extends **External**ProductExternalControllerBase,  instead of only ProductExternalControllerBase.

If we want, I can send you some show case like video or we can have some call so I can show this case.

**Comment by marcingrzejszczak** [comment]
I don't understand why you're doing it like this but still, let me try to help you. There are 2 ways of solving this problem IMO.

You're using any form of base class providing to point the external and internal contracts to the same base class. That base class has 2 configurations in it - one for one spring profile and another for the other spring profile. You would have to toggle them on from the build I guess or somehow resolve it from the test name.

Another option is to just use the base class mapping to point all internals to 1 base class and all externals to another base class. Each of them has the `@ActiveProfiles` annotation on it one for internal the other for external.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by viniciustoni** [comment]
Well we are doing this basically due the architecture decision, so we can have all code base into one single module on maven, instead of one module for internal endpoints, one for eternal and one for shared code(there are some differences on the way that we are validating the request on each "type" of internal/external. Basically because that, in general if I had 2 separate module my life was going to be much more easier :D

Well with ActiveProfile could be one solution, I'll try to do that, actually I liked a lot the idea of use 2 different configuration(it was my first try to solve this issue, but I got into the problem described before, it's re-using the same contract download from git repo), is there a way that I can configure the framework in the way that it'll download the contract on all configurations and not only once and re-use it?

**Comment by viniciustoni** [comment]
So, just to give you a short feedback about one small test that I did, let me know if you agree with it, in case yes, I can close this ticket and create a new one with proper description:
Problem:
- I have a project which my contracts are on external repo on github
- On my app, I'll have N types of profile app with different contract between then - On my case 2 types, internal/external
- On contract repo, I'll have the contract into separate maven version, one per each profile
- On my plugin configuration I'll create under executions tag, One execution per profile, with proper configuration to get the contracts from the git repo with proper contractDependency, where the diff between then will be the packageWithBaseClasses plus version under contractDependency
- This conf is not working because the plugin is executing the files download only once, so it'll always get the same version for all configuration

Test that I did:
- Looking for the code, I've notice that we have this class: MavenContractsDownloader, that is downloading the contracts from GIT;
- On _downloadAndUnpackContractsIfRequired_ method There is a condition: **if (downloadedContractsDir != null && downloadedContractsDir.exists())** this condition will always reuse the first download that the plugin did;
- I've change it to **false** only for my test, to check if we execute the download all the time it'll work:
- RESULT: It worked fine, so in case we download the contracts for each configuration the plugin verifier will work fine for multiple **packageWithBaseClasses** or contractDependency version

So, my question is: Is there a way that we can use some parameter to force the download for all configuration instead of reuse it? 

I know that it's weird to have multiple contract test for producers, but it's a way that we can solve the issue in case more projects are using Spring profile to determine which "type" of "app" version they are starting instead of use maven module for it.

**Comment by marcingrzejszczak** [comment]
> So, my question is: Is there a way that we can use some parameter to force the download for all configuration instead of reuse it? If there is no way to do that, then I'll need to think in a way to do a workaround on it, I can use @ActiveProfile, but once I'll use this contracts on consumer side, I'll have issues with conflicts of contracts(same endpoint for both internal/external).

Theoretically you can try setting a property in Maven called (`CONTRACTS_DIRECTORY`), you could set it via a system property like this `-DCONTRACTS_DIRECTORY=` that will always return a new value (e.g. a temporary directory).

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
