### ISSUE TITLE
Multipart rejected error with wiremock when using 2.2.0.RELEASE

### ISSUE THREAD

**Issue by adeel718** [spring-cloud/spring-cloud-contract#1732]
**Describe the bug**
When upgrading spring-cloud-starter-contract-stub-runner from 2.1.5.RELEASE to 2.2.0.RELEASE getting test failures when uploading a file. Using wiremock to stub the file downloading part.

Error is "cause1":"wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found",
            "servlet":"com.github.tomakehurst.wiremock.servlet.WireMockHa... (649 bytes)]

**Comment by marcingrzejszczak** [comment]
Can you try with 2.2.8.RELEASE or preferably 3.0.4 ?

**Comment by adeel718** [comment]
That didn't work either @marcingrzejszczak

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
