### ISSUE TITLE
PactContractConverter ignores boolean fields in yaml during conversion to json

### ISSUE THREAD

**Issue by heroInCommunity** [spring-cloud/spring-cloud-contract#1736]
Having yaml like this:

    ...
    response:
      ...
      body:
        someBoolean: true
        someNumber: 1
        someString: "str"

Json file created by conversion using PactContractConverter has 'someBoolean' field missing, while other fields are present.

version 3.0.4 is used

**Comment by marcingrzejszczak** [comment]
PactConverter has been removed in Spring Cloud Contract 4.0.0 so we're not planning on doing additional work for it. We're working with the Pact Foundation to move the support to the foundation.
