### ISSUE TITLE
Unable to send Multipart/mixed Parts from Contract Groovy.

### ISSUE THREAD

**Issue by shankarthakur** [spring-cloud/spring-cloud-contract#1739]
Question :
I am new to Contract test development and I'm struggling with creating contract for multipart/mixed controller method, where data is read like this below:

```
StandardMultipartHttpServletRequest myrequest = new StandardMultipartHttpServletRequest(request);
        Collection<Part> requestParts = request.getParts()
```

In the Contract Groovy I am defining the request like this:
```
Contract.make {

    request {

        method 'POST'
        url '/test'
        headers {
            contentType 'multipart/mixed;boundary=AaB03x'
        }
        multipart([

                info : named(
                        name: value(consumer(regex(nonEmpty())), producer('filename1')),
                        content: value(consumer(regex(nonEmpty())), new ServerDslProperty(file('test.json')))),

                file2: named(
                        name: value(consumer(regex(nonEmpty())), producer('filename1')),
                        content: value(consumer(regex(nonEmpty())), new ServerDslProperty(fileAsBytes('testaudio.wav')))),
        ])

    }
    response {
        'status' 202
    }
}
```

Please help me with this issue. 
Thank you.

**Comment by marcingrzejszczak** [comment]
Here you have an example of multipart https://github.com/spring-cloud/spring-cloud-contract/blob/e73d6526bfb3240f9dc33d6afcf2be17e5383f49/samples/standalone/dsl/http-server/src/main/java/com/example/fraud/TestController.java#L61 and https://github.com/spring-cloud/spring-cloud-contract/blob/e73d6526bfb3240f9dc33d6afcf2be17e5383f49/samples/standalone/dsl/http-server/src/test/resources/contracts/multipart/shouldWorkForMultipartWithContentType.groovy and https://github.com/spring-cloud/spring-cloud-contract/blob/e73d6526bfb3240f9dc33d6afcf2be17e5383f49/samples/standalone/dsl/http-server/src/test/java/com/example/fraud/MultipartBase.java

**Comment by shankarthakur** [comment]
Thank you for your reply @marcingrzejszczak ,
Unfortunately, this example doesn't match our use case completely. In the example, @RequestPart annotation is used to read the parts. Whereas in our case, we are reading the request using the following method: 
```
StandardMultipartHttpServletRequest myrequest = new StandardMultipartHttpServletRequest(request);
Collection<Part> requestParts = request.getParts()
```
In this case, the getParts() method returns an empty collection.
Is there any method available using which we can get the parts when we use this getParts() method. Also, does our current method of sending the multipart data in the groovy script have any mistakes?
In fact @marcingrzejszczak .

**Comment by marcingrzejszczak** [comment]
Yes it does have minor. Let me update it.

```groovy
Contract.make {

    request {

        method 'POST'
        url '/test'
        headers {
            contentType 'multipart/mixed;boundary=AaB03x'
        }
        multipart([

                info : named(
                        name: value(consumer(regex(nonEmpty())), producer('filename1')),
                        content: value(consumer(regex(nonEmpty())), producer(file('test.json')))),

                file2: named(
                        name: value(consumer(regex(nonEmpty())), producer('filename1')),
                        content: value(consumer(regex(nonEmpty())), producer(fileAsBytes('testaudio.wav')))),
        ])

    }
    response {
        status 202
    }
}
```

You would have to prepare a simple Java, Maven sample for me to look into, otherwise it will be difficult to help.

**Comment by shankarthakur** [comment]
Please find the below git sample link: https://github.com/shankarthakur/Multipart_mixed/tree/main
@marcingrzejszczak

**Comment by shankarthakur** [comment]
@marcingrzejszczak  Please provide feedback.

**Comment by marcingrzejszczak** [comment]
If I fix the issue or start working on it you will see an update here. I don't have the time to start working on this ATM.

**Comment by shankarthakur** [comment]
@marcingrzejszczak , Do you know this is an issue in spring cloud contract , or do you mean you would invest some time to explore whether this is an issue or not.

**Comment by marcingrzejszczak** [comment]
Yes I would need to invest time to explore this at all.

**Comment by shankarthakur** [comment]
@marcingrzejszczak , Ack.

**Comment by shankarthakur** [comment]
@marcingrzejszczak Any update.

**Comment by marcingrzejszczak** [comment]
I will update you once anything is done, currently I don't have time to work on this issue. Please feel free to file a PR with a fix if you can spare time to fix this

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
