### ISSUE TITLE
Add given/providerStates part when generate a RequestResponsePact from a Contract

### ISSUE THREAD

**Issue by mathieu-amblard** [spring-cloud/spring-cloud-contract#1740]
I am using the `ToFileContractsTransformer` in version 3.0.4 to generate a PACT file from a Contract for HTTP as described in the reference documentation : https://docs.spring.io/spring-cloud-contract/docs/3.0.0/reference/htmlsingle/#how-to-generate-pact-from-scc.

My Contract looks like this :
```groovy
package com.test

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    description("""
Some description...
""")
    request {
       ...
    }
    response {
        ...
    }
}
```

The generate PACT file looks like this :
```json
{
    "provider": {
        "name": "..."
    },
    "consumer": {
        "name": "..."
    },
    "interactions": [
        {
            "description": "Some description",
            "request": {
                ...
            },
            "response": {
                ...
            }
        }
    ],
    "metadata": {
        "pactSpecification": {
            "version": "3.0.0"
        },
        "pact-jvm": {
            "version": "4.0.10"
        }
    }
}
```

Firstly, I would like to know if there is any reason to not have a `providerState` as it is done for the `MessagePact` here : https://github.com/spring-cloud/spring-cloud-contract/blob/90172436be6590732c2ec70a1e98ce6716fd3c11/spring-cloud-contract-tools/spring-cloud-contract-pact/src/main/java/org/springframework/cloud/contract/verifier/spec/pact/MessagePactCreator.java#L58 or if it is an oversight.

Secondly, if this is an oversight, is it possible to add it the same way, and with maybe an input field that take only a string :
```groovy
Contract.make {
    description("""
Some description...
""")
    input 'the initial state of the provider'
    request {
       ...
    }
    response {
        ...
    }
}
```
It seems that we only need to call the given method of the Pact DSL here : https://github.com/spring-cloud/spring-cloud-contract/blob/6d78e66c90cb4d032cf6774c2f80cd722ac8f675/spring-cloud-contract-tools/spring-cloud-contract-pact/src/main/java/org/springframework/cloud/contract/verifier/spec/pact/RequestResponsePactCreator.java#L112 and here : https://github.com/spring-cloud/spring-cloud-contract/blob/6d78e66c90cb4d032cf6774c2f80cd722ac8f675/spring-cloud-contract-tools/spring-cloud-contract-pact/src/main/java/org/springframework/cloud/contract/verifier/spec/pact/RequestResponsePactCreator.java#L141 if some input was set in the Contract.

Thanks in advance !

**Comment by marcingrzejszczak** [comment]
Are you willing to provide a PR ?

**Comment by mathieu-amblard** [comment]
> Are you willing to provide a PR ?

Yes, I will provide one asap.
