### ISSUE TITLE
Docs: Incomplete JUnit5 examples - use of `@Rule`

### ISSUE THREAD

**Issue by jamietanna** [spring-cloud/spring-cloud-contract#1746]
**Describe the bug**

In [the docs, 6.2 Setting up the Consumer](https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/using.html#flows-provider-non-spring-consumer), we see:

```java
@Rule
    public StubRunnerExtension stubRunnerExtension = new StubRunnerExtension()
            .downloadStub("com.example","artifact-id", "0.0.1")
            .repoRoot("git://git@github.com:spring-cloud-samples/spring-cloud-contract-nodejs-contracts-git.git")
            .stubsMode(StubRunnerProperties.StubsMode.REMOTE);
```

Which is not correct according to https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/75d347aae083a6267bd0d76774a3706172fbf2db/consumer_with_latest_3_0_features_gradle/src/test/java/com/example/GenerateStubsTest.java#L21-L26, which shows this should be:

```java
	@RegisterExtension
	static StubRunnerExtension rule = new StubRunnerExtension()
			.downloadStub("com.example","beer-api-producer-latest", "0.0.1-SNAPSHOT")
			.repoRoot("stubs://file://" + System.getenv("ROOT") + "/producer_with_latest_3_0_features_gradle/src/contractTest/resources/contracts/beer/in_progress")
			.stubsMode(StubRunnerProperties.StubsMode.REMOTE)
			.withGenerateStubs(true);
```

**Comment by jamietanna** [comment]
Thought I'd raise it for now in the meantime, but yeah I am certainly happy looking through and sorting it :smile:

**Comment by pk-218** [comment]
@marcingrzejszczak can I take up this issue?
I have been learning Spring and would like to contribute to its projects.

**Comment by marcingrzejszczak** [comment]
Oh absolutely, be my guest!
