### ISSUE TITLE
Stub runner boot not working in windows

### ISSUE THREAD

**Issue by javierminoglb** [spring-cloud/spring-cloud-contract#1751]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 
If you run the stub runner boot application with a path that contains a windows file separator you get a URISyntaxException

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

To reproduce download the dependency to your local maven repo:
```bash
/mvnw dependency:get -Dartifact=org.springframework.cloud:spring-cloud-contract-stub-runner-boot:3.0.4:jar
```
Run the stub runner with a windows file separator in the repository url:
```bash
java -jar ~/.m2/repository/org/springframework/cloud/spring-cloud-contract-stub-runner-boot/3.0.4/spring-cloud-contract-stub-runner-boot-3.0.4.jar --stubrunner.ids=com.example:demo --stubrunner.stubsMode=remote --stubrunner.cloud.stubbed.discovery.enabled=false --stubrunner.idsToServiceIds.demo=demo --stubrunner.generate-stubs=true --stubrunner.repositoryRoot="stubs://file:..\stubs"
```

**Comment by marcingrzejszczak** [comment]
Why do you need to use a file windows separator in the repository root? Also this gets mapped later to a Spring Resource where I guess you should be using the URL notation. Please read more about this here https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#resources
