### ISSUE TITLE
SpringBoot 3.0.0-M1 + SpringCloud 2022.0.0-M1 [ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-contract-verifier:jar is missing. 

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-contract#1752]
Hello Spring Cloud Contract Team,

Wanted to say thank you for this very cool project.
With the exciting releases of both SpringBoot 3.0.0-M1 and SpringCloud 2022.0.0-M1, I went ahead to bump the versions up.
https://spring.io/blog/2022/01/20/spring-boot-3-0-0-m1-is-now-available
https://spring.io/blog/2022/01/27/spring-cloud-2022-0-0-m1-codename-kilburn-has-been-released

While things worked perfectly fine on my SpringBoot 2.6.3 + Jubilee, the exact same code, with just the version change on the pom file to the new pair SpringBoot 3.0.0-M1 + SpringCloud 2022.0.0-M1, the following error is observed.

```
/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=abc -Dmaven.home=maven3 [...] -Didea.version=2021.3.1 clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-contract-verifier:jar is missing. @ line xx, column 21
 @ 
```

Spring Cloud Contract is an important part of our architecture. How to continue using this please?

If Spring Cloud Contract is not part of Spring Cloud 2022, what are the alternative, and how to "keep the features and behaviors" offered please?

Thank you

**Comment by marcingrzejszczak** [comment]
Spring cloud contract was not part of this milestone. It will be available for m2
