### ISSUE TITLE
Docs: single html/pdf for 3.1.0 is broken

### ISSUE THREAD

**Issue by gavvvr** [spring-cloud/spring-cloud-contract#1753]
For 3.1.0 you will see some ascciidoc-related stuff and no docs.:

https://docs.spring.io/spring-cloud-contract/docs/3.1.0/reference/htmlsingle/
https://docs.spring.io/spring-cloud-contract/docs/3.1.0/reference/pdf/index.pdf

For comparison 3.0.0 full html works just fine:
https://docs.spring.io/spring-cloud-contract/docs/3.0.0/reference/htmlsingle/

**Comment by marcingrzejszczak** [comment]
It seems that all of our single page docs are broken for all the cloud projects :grimacing:

**Comment by jonatan-ivanov** [comment]
It seems single page docs are published under <projectname>.html instead of index.html:
https://docs.spring.io/spring-cloud-contract/docs/3.1.0/reference/htmlsingle/spring-cloud-contract.html

**Comment by gavvvr** [comment]
Thanks for the link @jonatan-ivanov !
The source code snippet is broken in [8.6.3 section of 3.1.0 docs](https://docs.spring.io/spring-cloud-contract/docs/3.1.0/reference/htmlsingle/spring-cloud-contract.html#how-to-protocol-convention-producer-with-contracts-stored-locally).
Looks good [in 3.0.0](https://docs.spring.io/spring-cloud-contract/docs/3.0.0/reference/htmlsingle/#how-to-protocol-convention-producer-with-contracts-stored-locally)

**Comment by marcingrzejszczak** [comment]
I've built the documentation locally and it works well with all the versions. Let's see if the next release is better.
