### ISSUE TITLE
skipTests / maven.test.skip properties are not following the maven semantics

### ISSUE THREAD

**Issue by chicobento** [spring-cloud/spring-cloud-contract#1758]
**Describe the bug**

According with maven documentation at https://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-tests.html 

> You can also skip the tests via the command line by executing the following command:

    mvn install -DskipTests

> If you absolutely must, you can also use the maven.test.skip property to skip compiling the tests. maven.test.skip is honored by Surefire, Failsafe and the Compiler Plugin.

    mvn install -Dmaven.test.skip=true

So I'd expect that the code generation capabilities of this plugin should stay unaffected in case skipTests is used - and only affected by maven.test.skip property.

Same information can be found at maven compiler plugin docs: https://maven.apache.org/plugins/maven-compiler-plugin/testCompile-mojo.html#skip

> https://maven.apache.org/plugins/maven-compiler-plugin/testCompile-mojo.html#skip

However, the code generation MOJOs are taking skipTests in consideration before execution:
https://github.com/spring-cloud/spring-cloud-contract/blob/114524379e0fa6ec34c58b4bcdcc3510b0497915/spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/main/java/org/springframework/cloud/contract/maven/verifier/GenerateTestsMojo.java#L253

**Background**
On our CI we run maven at different stages. To improve efficiency, we run a compilation at the beginning so that we can limit the phases that we execute later on. Eg:

1. mvn install -DskipTests
2. mvn surefire:test

The contract test classes are not being picked up at the test stage because the -DskipTests at stage 1 is preventing the test code to be generated.

**Comment by marcingrzejszczak** [comment]
Makes sense, are you willing to make a fix for this? Since this is a breaking change that would be merged for 4.0.0.

**Comment by chicobento** [comment]
Will try to find sometime for providing a PR. When are you guys planning to release 4.0.0 ?

**Comment by chicobento** [comment]
If it doesnt get into 4.0.0 then we'll have to wait for 5.0.0

**Comment by spencergibb** [comment]
4.0 goes GA in november, but changes like this need to be in by the last milestone in September
