### ISSUE TITLE
Incorrect matching groovy to yml files started from capital letters

### ISSUE THREAD

**Issue by gadgadskiy** [spring-cloud/spring-cloud-contract#1761]
Hi guys. I faced a new issue after updating the spring-cloud-contract-parent from 2.2.7.RELEASE to 3.1.0 version.
After that, I have troubles with converting groovy to yml files (for generated contracts) in two cases:
- filename starts from the capital letter
- filename contains space(s)
For example, for a contract with a filename that starts from a capital letter, the yml file with filename starts from small letter will be generated, and this contract won't be found. In the previous version, this problem was absent.
Is this a new feature, and I should add validations to filenames, or is it a bug?

**Comment by marcingrzejszczak** [comment]
Sounds like a bug. Do you have a small sample that replicates this problem?

**Comment by gadgadskiy** [comment]
For example, I have a contract named ShouldSendPromo.groovy with the standard `Contract.make {...}` content.
I'm starting a build with generating producer tests on the service side. After it finished, two files appeared in an appropriate folder:
- ShouldSendPromo.yml (named with a capital letter as the groovy prototype)
- MessagingTest.java, which contains the following code:
```
// then:
ContractVerifierMessage response = contractVerifierMessage.receive("scheduler_kafka_topic",
        contract(this, "shouldSendPromo.yml"));
assertThat(response).isNotNull();
```
As the yml starting with the small letter is set there, it couldn't find such a file and failed.

**Comment by marcingrzejszczak** [comment]
I see, I think we never assumed that you would start a file with a capital letter (which was a fair assumption cause you don't typically name scripts / files like this), you're actually the first one to file such an issue. Is it a problem for you to rename the files?

**Comment by marcingrzejszczak** [comment]
I can mark this as a bug but the workaround is so simple that I can't put a lot of priority on this. If you're willing to provide a fix I'll be more than happy to take it.

**Comment by gadgadskiy** [comment]
Ok, I'll fix it by preventing pushing such files.
