### ISSUE TITLE
Support groovy 4

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-contract#1762]
Boot upgraded to groovy 4 https://github.com/spring-projects/spring-boot/commit/dd812a3f76ac27c6c91bab0e02ea08c58ecaddd1

Updated spock groovy 4 support here https://github.com/spring-projects/spring-boot/commit/a1e972ebaa63a3c935afd3bd9b8958c910961d4b

And temporarily removed rest assured here https://github.com/spring-projects/spring-boot/commit/568cd687af8ccb6119b97dd3083e5968b32a233b

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/commit/145cf4dd9e59c5d40151ef5e9e8ee82bfd4542d2
