### ISSUE TITLE
Groovy - referencing the request from response no result expected.

### ISSUE THREAD

**Issue by ernestorumo** [spring-cloud/spring-cloud-contract#1767]
In Groovy DSL, when referencing the request object from response , it responses with an array structure instead of an object. 
When I want an object structure, it responses with an array of objects. None of the cases are correct. Not complex request structure examples are showed on documentation.

    request_1
```
    {
        "origin": {
            "atribute_A": "foo",
            "atribute_B": "bar"
        }
    }
```
    response_1
``` 
 {
        "origin": [
            "foo",
            "bar"
        ]
    }
```
    request_2
```   
 {
            "origin": [
            {
                "atribute_A": "foo",
                "atribute_B": "bar"
            }]
        }
```
    response_2
```
 {
            "origin": [
            {
                "atribute_A": "foo",
                "atribute_B": "bar"
            }]
        }
```

version 3.1.0

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

Please [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by ernestorumo** [comment]
The behavior exposed is caused by the jsonPath expression, when it´s selected by ```$.origin.*``` always return an array, the correct way is ```$.origin```, without wildcard, for retrieve the original structure of property. Is not really an issue.

I´m very sorry for the noob mistake.
