### ISSUE TITLE
Spring Contract ignore test with message

### ISSUE THREAD

**Issue by arcioneo** [spring-cloud/spring-cloud-contract#1768]
With the following code:

```
Contract.make {
            ignored() 
            description "e"
               request {
                method 'POST'
                url '/api/login'
                headers {
                    contentType("application/json")
                }
                body($(execute("aMethod()")))
            }
            response {
                status 200
                headers {
                    contentType("application/json")
                }
            }
        }
```

The following code is generated:

```
@Test
@Ignore
public void someName(){}
```

Sonar complains asking for a description on the ignore method, something like:

```
@Test
**@Ignore("See Ticket #1234")**
public void testDoTheThing() {}
```

Can you guys update 'ignored()' method to receive also a message that will be shown at the Ignore annotation?

**Comment by marcingrzejszczak** [comment]
Is it the same problem with `@Disabled` for JUnit5 ?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
