### ISSUE TITLE
The test results are different in the server and local environment.

### ISSUE THREAD

**Issue by ricadro** [spring-cloud/spring-cloud-contract#1772]
First of all, contract is used for testing in the project. There is no error in the local test result. After uploading to the git server, there will be a request response json matching error in the maven building, resulting in the test failure. I want to know what's the reason.

**Comment by ricadro** [comment]
Even the local and server-generated test class and json files are consistent, but the test results are very different.

**Comment by ricadro** [comment]
When I upgraded the contract  version from 2.2.5 to 2.2.8, the local and server test results were consistent. Is this a bug in 2.2.5?

**Comment by marcingrzejszczak** [comment]
I don't really understand the problem however if the situation got resolved by upgrading the version by patch that means that most probably that was a bug

**Comment by ricadro** [comment]
When I submitted the new code, the same scene as before appeared again. I need help

**Comment by marcingrzejszczak** [comment]
Please upload a sample that reproduces the problem. Currently I don't understand what the problem reallocate is
