### ISSUE TITLE
WebFlux: Unsatisfied dependency expressed at test case execution

### ISSUE THREAD

**Issue by Vinayak-Mahadev** [spring-cloud/spring-cloud-contract#1781]
Hi Team,
 When executing test cases I'm getting below error. 

`-------------------------------------------------------------------------------
Test set: com.infy.ContractVerifierTest
-------------------------------------------------------------------------------
Tests run: 9, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 5.618 s <<< FAILURE! - in com.infy.ContractVerifierTest
validate_03_infybook_get  Time elapsed: 0.277 s  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.infy.controller.InfyBookController': Unsatisfied dependency expressed through field 'infyBookService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

validate_02_infybook_get  Time elapsed: 0.038 s  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.infy.controller.InfyBookController': Unsatisfied dependency expressed through field 'infyBookService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

validate_06_infybook_save  Time elapsed: 0.035 s  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.infy.controller.InfyBookController': Unsatisfied dependency expressed through field 'infyBookService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

validate_09_infybook_update  Time elapsed: 0.033 s  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.infy.controller.InfyBookController': Unsatisfied dependency expressed through field 'infyBookService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

validate_01_infybook_get_all  Time elapsed: 0.025 s  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.infy.controller.InfyBookController': Unsatisfied dependency expressed through field 'infyBookService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

validate_07_infybook_save  Time elapsed: 0.021 s  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.infy.controller.InfyBookController': Unsatisfied dependency expressed through field 'infyBookService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

validate_04_infybook_delete  Time elapsed: 0.024 s  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.infy.controller.InfyBookController': Unsatisfied dependency expressed through field 'infyBookService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

validate_05_infybook_delete  Time elapsed: 0.024 s  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.infy.controller.InfyBookController': Unsatisfied dependency expressed through field 'infyBookService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

validate_08_infybook_update  Time elapsed: 0.023 s  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.infy.controller.InfyBookController': Unsatisfied dependency expressed through field 'infyBookService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.infy.service.InfyBookService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

`

With the following code:

pom.xml
`<plugin>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-contract-maven-plugin</artifactId>
				<version>3.1.2</version>
				<extensions>true</extensions>
				<configuration>
					<testFramework>JUNIT5</testFramework>
					<baseClassForTests>com.infy.InfyBookTest</baseClassForTests>
					<testMode>WEBTESTCLIENT</testMode>
					
				</configuration>
			</plugin>`

base class:
`@SpringBootTest(classes = InfyBook02Application.class)
public class InfyBookTest 
{
	
	@Autowired
	protected InfyBookController infyBookController;
	
	
	@BeforeEach
	public void beforeEachTest() {
		RestAssuredWebTestClient.standaloneSetup(infyBookController);;
	}
}`

Controller:
`@RestController
@RequestMapping("/v1/infybook")
@Slf4j
public class InfyBookController 
{

	@Autowired
	private InfyBookService infyBookService;

	@GetMapping(path = "/book", produces = MediaType.APPLICATION_JSON_VALUE)@Operation(tags = "get", description = "get all book")
	public Flux<InfyBook> getAllBook()
	{
		return infyBookService.getAllBook().doOnComplete(() -> log.info("getAllBook service triggered"));
	}

	@GetMapping("/book/{bookId}")@Operation(tags = "get", description = "get book by Id")
	public Mono<ResponseEntity<InfyBook>> getBook(@PathVariable Long bookId)
	{
		return infyBookService.getBook(bookId)
				.doOnNext(book -> log.info("getBook by id service : " + book))
				.map(ResponseEntity::ok)
				.defaultIfEmpty(ResponseEntity.notFound().build());
	}

	@PostMapping("/book")@Operation(tags = "post", description = "save book")
	public Mono<ResponseEntity<InfyBook>> saveBook(@RequestBody InfyBook book)
	{
		return infyBookService.saveBook(book)
				.doOnNext(booktemp -> log.info("saveBook service : " + booktemp))
				.map(ResponseEntity::ok)
				.defaultIfEmpty(ResponseEntity.noContent().build());
	}

	@PutMapping("/book")@Operation(tags = "put", description = "update book by id")
	public Mono<ResponseEntity<InfyBook>> updateBook(@RequestBody InfyBook book)
	{
		return infyBookService.updateBook(book)
				.doOnNext(booktemp -> log.info("updateBook service : " + booktemp))
				.map(ResponseEntity::ok)
				.defaultIfEmpty(ResponseEntity.noContent().build());
	}

	@DeleteMapping("/book/{bookId}")@Operation(tags = "put", description = "delete book by id")
	public Mono<ResponseEntity<InfyBook>> deleteBook(@PathVariable Long bookId)
	{
		return infyBookService.deleteBook(bookId)
				.doOnNext(book -> log.info("deleteBook by id service : " + book))
				.map(ResponseEntity::ok)
				.defaultIfEmpty(ResponseEntity.notFound().build());
	}
}`

Contract file example:
`package contracts

import org.springframework.cloud.contract.spec.Contract

Contract.make {

	description "Get all infybook record"

	request {
		url "/v1/infybook/book"
		method GET()
	}

	response {
		status OK()
	}
}`

SOURCE CODE: [https://github.com/Vinayak-Mahadev/spring-contract/blob/main/spring.zip?raw=true](url)

**Comment by marcingrzejszczak** [comment]
Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

Apparently you don't have `No qualifying bean of type 'com.infy.service.InfyBookService` registered as bean.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Vinayak-Mahadev** [comment]
Thanks for the support. But still I'm facing same error, I uploaded source code here,

https://github.com/Vinayak-Mahadev/spring-contract/blob/main/spring.zip

**Comment by marcingrzejszczak** [comment]
I took your project and did the following. 

1) Changed your test base class not to set up the whole context since you're using standalone option from rest assured

```java
public class InfyBookTest
{
	protected InfyBookController infyBookController = new InfyBookController(new InfyBookService());
	
	@BeforeEach
	public void beforeEachTest() {
		RestAssuredWebTestClient.standaloneSetup(infyBookController);
	}
}

```

2) Modified the controller to be able to pass the service via the constructor. 

Some tests have passed, some didn't - I didn't have a single time the issue you got. Nor did I have it with what you initially had in your repo.
