### ISSUE TITLE
Spring Cloud Contract  Version compatibility issues

### ISSUE THREAD

**Issue by ricadro** [spring-cloud/spring-cloud-contract#1786]
When I upgraded the version of springboot from 2.3.12.RELEASE to 2.4.6, and the version of springcloud from Hoxton.SR9 to 2020.0.3, and ran the test again, casue: " xxx: nodename nor servname provided, or not known executing POST http://xxx " error, is this a version compatibility issue?

**Comment by marcingrzejszczak** [comment]
Please check the following compatiblity Matrix https://spring.io/projects/spring-cloud/ and douple check that your Boot versions are aligned with Spring Cloud ones.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
