### ISSUE TITLE
Documentation about Wiremock broken

### ISSUE THREAD

**Issue by epragtbeamtree** [spring-cloud/spring-cloud-contract#1793]
**Describe the bug**

See https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/project-features.html#features-wiremock. It seems like there should be a Java code sample, but the code block is empty:

<img width="996" alt="image" src="https://user-images.githubusercontent.com/91307175/172371739-21d60a6f-ed22-4d35-93b8-0c8e5f8568a3.png">

**Comment by pennstatephil** [comment]
When should we expect this change to be live on "current" documentation? I saw the 2022.0.0-M3 milestone was closed on June 15th, but I can't tell when that's going to be the "current" version.

**Comment by epragtbeamtree** [comment]
@pennstatephil I can't answer that question, but what I can tell you it's published here: https://docs.spring.io/spring-cloud-contract/docs/current-SNAPSHOT/reference/html/project-features.html#features-wiremock
