### ISSUE TITLE
I want to ignore specify field asserts in response body when generate test。

### ISSUE THREAD

**Issue by codingthought** [spring-cloud/spring-cloud-contract#1799]
I want to ignore specify field asserts in response body when generate test。

example：

```
Contract.make {
	request {
		method('PUT')
		headers {
			contentType(applicationJson())
		}
		body(file("request.json"))
		url("/1")
	}
	response {
		status OK()
		body(file("response.json"))
		headers {
			contentType(textPlain())
		}
	}
}
```
```
//response.json
{
"id":1,
...
"__description": {}
}
```
I want to ignore `__description` assert only when generate test

**Comment by marcingrzejszczak** [comment]
If you want to ignore it, then remove it from the contract

**Comment by codingthought** [comment]
I want use __description as contract fields comments. It's make contract read friendly for consumer, but need't verify.

**Comment by marcingrzejszczak** [comment]
The only way to achieve this is to remove it from the contract
