### ISSUE TITLE
replace RestAssuredMockMvc?

### ISSUE THREAD

**Issue by ffatghub** [spring-cloud/spring-cloud-contract#1804]
Hi all,

is it possible to replace RestAssuredMockMvc with a custom REST-assured API implementation. Specifically we would like to use  [swagger-coverage](https://github.com/viclovsky/swagger-coverage) in our groovy base test class in order to hook a filter like this one

RestAssured.given().filter(new SwaggerCoverageRestAssured())

thanks a lot
ciao

**Comment by marcingrzejszczak** [comment]
Can't you use the EXPLICIT mode and then on `RestAssured` call `filters` (https://github.com/rest-assured/rest-assured/blob/master/rest-assured/src/main/java/io/restassured/RestAssured.java#L506)?

**Comment by ffatghub** [comment]
Hi @marcingrzejszczak thank you. SpringCloud is new to me. Do you have a working testMode=EXPLICIT example?

**Comment by marcingrzejszczak** [comment]
Here you have an example of the EXPLICIT mode https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/project-features.html#features-context-paths and here https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/3.1.x/producer_webflux/pom.xml#L107
