### ISSUE TITLE
iso8601WithOffset generates invalid date

### ISSUE THREAD

**Issue by renatolean** [spring-cloud/spring-cloud-contract#1816]
**Describe the bug**
On version 3.1.3 and 3.1.4, at least for kotlin but maybe applicable to other languages, when using `org.springframework.cloud.contract.spec.internal.CommonDsl#getIso8601WithOffset`,
sometimes the generated outcome returns an invalid date.

**Sample**

Usage:

`"timestamp" to iso8601WithOffset`

Sometimes results in an invalid date, see examples:

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.Instant` from String "4848-06-31T06:46:40-03:11": Failed to deserialize java.time.Instant: (java.time.format.DateTimeParseException) Text '4848-06-31T06:46:40-03:11' could not be parsed at index 0
```
**There is no 31st June.**

other example:
```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.Instant` from String "9801-11-31T23:03:41Z": Failed to deserialize java.time.Instant: (java.time.format.DateTimeParseException) Text '9801-11-31T23:03:41Z' could not be parsed at index 0
```
**There is no 31st of November**

**Comment by marcingrzejszczak** [comment]
It's really hard to always create a proper date using a regex (what we're doing is in fact generating a text from a provided regular expression). If you know how to improve the regex so that this kind of problems don't happen - please help us out :)

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
