### ISSUE TITLE
Mixed Ascii doc grammar for code highlighting.

### ISSUE THREAD

**Issue by iamkyu** [spring-cloud/spring-cloud-contract#1817]
**Describe the bug**
Two grammar are mixed for code highlighting that I checked.
Example.
1. [src,Java]
2. [source,java, indent=0]

I think the first one doesn’t work.
Is there a reason why it is being used  this?

**Sample**
in  [spring-cloud-contract/getting-started.adoc at main · spring-cloud/spring-cloud-contract · GitHub](https://github.com/spring-cloud/spring-cloud-contract/blob/main/docs/src/main/asciidoc/getting-started.adoc)

`public class BaseTestClass`
Highlight not working with `[src,Java]`

`public class LoanApplicationServiceTests`
Highlight  working with `[source,java, indent=0]`

**Comment by marcingrzejszczak** [comment]
I guess that's a mistake, are you willing to file a PR to the 3.1.x branch?

**Comment by iamkyu** [comment]
@marcingrzejszczak ok, i will

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/pull/1820
