### ISSUE TITLE
ContractVerifierTest does not run the test

### ISSUE THREAD

**Issue by Thinkenterprise** [spring-cloud/spring-cloud-contract#1828]
I Use Spring Boot 2.7.x und Spring Cloud 2021.0.4. 

I have the follow contract: 

```
import org.springframework.cloud.contract.spec.Contract

Contract.make {
	description "should return 1 by id=101"

	request {
		url "/flights/count/101"
		method GET()
	}

	response {
		status OK()
		body (1)
	}
}

```

**The tests are generated and can be run from the Eclipse IDE**.

Here are my base test 

```java
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
public class BaseClass {
	
	@Autowired FlightController fligthController;
	
	@BeforeEach public void setup() {
		RestAssuredMockMvc.standaloneSetup(fligthController);

	}

}
``` 

```java
public class ContractVerifierTest extends BaseClass {

	@Test
	public void validate_get_count_flights_by_id() throws Exception {
		// given:
			MockMvcRequestSpecification request = given();


		// when:
			ResponseOptions response = given().spec(request)
					.get("/flights/count/101");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);

		// and:
			String responseBody = response.getBody().asString();
			assertThat(responseBody).isEqualTo("1");
	}

}
``` 

But ``mvn clean install`` didnt execute the test. 

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.thinkenterprise.ContractVerifierTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

Here the Plugin Definition 

```xml
<plugin>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-contract-maven-plugin</artifactId>
		<extensions>true</extensions>
		<version>3.1.4</version>
		<configuration>
			<baseClassForTests>com.thinkenterprise.BaseClass</baseClassForTests>
		</configuration>
</plugin>
```

Are there any settings missing?

**Comment by marcingrzejszczak** [comment]
Maybe you're using junit4 instead of junit5? We do have tests that prove that this is working fine

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
