### ISSUE TITLE
Configure Local Maven Repository 

### ISSUE THREAD

**Issue by KonradEichstaedt** [spring-cloud/spring-cloud-contract#184]
Hi All, 

I'am using the spring-cloud-contract but I failed to run local StubRunner Tests. The Reason is because my local maven repository isn't in the default home directory. I configured another localtion on my windows system but the stubrunner will always use the default homedirectory\m.\repository

How can I configure the Stubrunner local maven repository?

**Comment by marcingrzejszczak** [comment]
That's a very good question ;) It's enough to pass the `maven.repo.local` system property to your application and it will pick a different location.

**Comment by KonradEichstaedt** [comment]
Many Thanks for support and the great framework ...

Best regards 

Konrad

**Comment by marcingrzejszczak** [comment]
Thank you so much for your kind words :D I'm really happy that you're enjoying it :)
