### ISSUE TITLE
Error with spring-cloud-contract-wiremock after Spring Boot 3 upgrade

### ISSUE THREAD

**Issue by linusnorton** [spring-cloud/spring-cloud-contract#1851]
**Describe the bug**
Using spring-cloud-contract-wiremock 3.1.5 with Spring Boot 3 fails to compile with: 

```
java.lang.NoClassDefFoundError: org/springframework/util/SocketUtils
	at org.springframework.cloud.contract.wiremock.WireMockApplicationListener.registerPropertySourceForDynamicEntries(WireMockApplicationListener.java:97) 
```

**Comment by marcingrzejszczak** [comment]
Spring Cloud Contract 4.x is the one that works with Spring Boot 3. The ga release of that is scheduled for 14/12. Until then please check out our RC releases.
