### ISSUE TITLE
What happened to 3.1.x StubRunner functionality - e.g. getMessageFrom() - in main?

### ISSUE THREAD

**Issue by cer** [spring-cloud/spring-cloud-contract#1852]
I've not been able to find the latest version of this in main:

https://github.com/spring-cloud/spring-cloud-contract/blob/d364b5d29e07d58141b7aa05a50fbb1463aa7e07/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/jms/StubRunnerJmsConfiguration.java#L69

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-contract/wiki/Spring-Cloud-Contract-4.0-Migration-Guide
