### ISSUE TITLE
self consumed messsage not sent to test queue after upgrading to v3.1.5 (only 1 subscriber)

### ISSUE THREAD

**Issue by emreavsar** [spring-cloud/spring-cloud-contract#1856]
**Describe the bug**
- Cloud contracts on provider side for messages
- testing according to this page https://cloud.spring.io/spring-cloud-contract/reference/html/project-features.html#features-messaging-integrations
- @AutoConfigureMessageVerifier used in base classes
- upgraded from v3.0.2 to v.3.1.5 (same behaviour with 3.1.4 as well)
- the message is also self consumed by the producer (to scale via messaging middleware)

Generated test will fail due to message != null assertion fails.

When removing the self listening to that message, it works like a charm.

**Sample**
- setup producing of a message with spring cloud stream (functional binding instead of annotations)
- write cloud contract producer test for it
- configure your application to also listen to this (write a simple echo listener and bind it with a Consumer<String>)
- re-run your cloud contract test (this should fail now)

Ps: the message is consumed by another app as well, hence not a cloud contract for the producing app itself (which would not make sense)

**Comment by marcingrzejszczak** [comment]
Can you upload a sample so that we can check it out?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
