### ISSUE TITLE
Add integration with JVM Test Suite Gradle plugin

### ISSUE THREAD

**Issue by a-glapinski** [spring-cloud/spring-cloud-contract#1863]
**Is your feature request related to a problem? Please describe.**
I would like to the `contractTest` source set and tasks be registered as test suite as per [The JVM Test Suite Plugin
](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html). Unfortunately, I cannot achieve that:

```kotlin
// build.gradle.kts
testing {
    suites {
        val contractTest by registering(JvmTestSuite::class) {
            useJUnitJupiter()
        }
    }
}
```
```
Could not create domain object 'contractTest' (JvmTestSuite)
> Could not create an instance of type org.gradle.api.plugins.jvm.internal.DefaultJvmTestSuite.
   > Cannot add a SourceSet with name 'contractTest' as a SourceSet with that name already exists.
```

`by getting(JvmTestSuite::class)` doesn't work as well since `contractTest` isn't registered as test suite:
```
TestSuite with name 'contractTest' not found.
```

**Describe the solution you'd like**
I would like Spring Cloud Contract Gradle plugin to integrate with JVM Test Suite plugin and register its `contractTest` source set, task etc. using JVM Test Suite plugin, for `contractTest` JVM test suite to be registered.

**Comment by shanman190** [comment]
@marcingrzejszczak, this should be pretty doable. I'll see if I can't get around to it later this week.
