### ISSUE TITLE
AutoConfigureHttpClient RestTemplate with InterceptingClientHttpRequestFactory

### ISSUE THREAD

**Issue by nkolosnjaji** [spring-cloud/spring-cloud-contract#1868]
**Is your feature request related to a problem? Please describe.**
If user defines RestTemplate with interceptor (built with RestTemplateBuilder and HttpComponentsClientHttpRequestFactory), _@AutoConfigureHttpClient_ will not setup "relaxed SSL validation". This is because restTemplate.getRequestFactory() will return wrapper of InterceptingClientHttpRequestFactory. 

**Describe the solution you'd like**
_@AutoConfigureHttpClient_  will check also InterceptingClientHttpRequestFactory if it's wrapping instance of HttpComponentsClientHttpRequestFactory.class

I can submit PR.

**Comment by nkolosnjaji** [comment]
"_@AutoConfigureHttpClient_" is part of spring-cloud-contract-wiremock which is importing WireMockRestTemplateConfiguration. It would be nice if RestTemplateBuilder is already configured with SSL relaxed validation when used in combination with RestTemplate interceptors.

RestTemplate with interceptors will not configure this, as per this code:

https://github.com/spring-cloud/spring-cloud-contract/blob/v4.0.1/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockRestTemplateConfiguration.java#L51

and 

https://github.com/spring-projects/spring-framework/blob/v6.0.4/spring-web/src/main/java/org/springframework/http/client/support/InterceptingHttpAccessor.java#L105

**Comment by marcingrzejszczak** [comment]
I think I need more sleep - I've completely forgotten about that class. Yes, definitely we're interested in this PR.

**Comment by nkolosnjaji** [comment]
I will create PR this days, thanks a lot!
