### ISSUE TITLE
Do not generate original directory OR tell Stub Runner to use yml instead of groovy contracts

### ISSUE THREAD

**Issue by rroehrig** [spring-cloud/spring-cloud-contract#1872]
**Is your feature request related to a problem? Please describe.**
We want to write custom verifiers as described in "Spring Cloud Contract customization".
As described in the documentation we use the convertToYaml flag in order to generate the contracts in yaml instead of groovy.
However, when we use the stub runner, it picks up the groovy contracts which are in the jar in the original directory.

**Describe the solution you'd like**
We hope we don't miss the right properties but we can neither find an option to not generate the original directory nor tell the stub runner to use the yaml files instead of the groovy files.

**Describe alternatives you've considered**
* Either do not generate the original directory
* Or tell the stub runner which contract format to use

**Additional context**
Jar structure:
groupId/artifactid/version/contracts --> contains the yaml contracts
groupId/artifactid/version/original --> contains the groovy contracts

**Comment by marcingrzejszczak** [comment]
Why is `original` folder even picked? Is it because it's on the classpath?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
