### ISSUE TITLE
FilenotFoundException

### ISSUE THREAD

**Issue by smfaizalkhan** [spring-cloud/spring-cloud-contract#1880]
**Describe the bug**
Spring Cloud Contract generates message verifier test from Groovy to YAML

**Sample**
 In the producer side, I have written a Groovy test with Contract.make and specify the input and outputMessage like below.

       package contracts

                 org.springframework.cloud.contract.spec.Contract.make {
                      description 'Some Description'
                      label 'some_label'
                        input {
                        messageFrom('activemq:queue:tracker.queue.in')
                        messageBody([
                            name: $(anyNonBlankString()),
                            instanceId: $(anyNonBlankString()),
                            gameSessionId: $(anyNonBlankString())
                        ])
                        messageHeaders {
                          header('JMSType', 'WeeklyQuestCommand')
                        }
                            }
                            outputMessage {
                              sentTo('activemq:queue:tracker.queue.out')
                              body([
                                name: $(anyNonBlankString()),
                                instanceId: $(anyNonBlankString()),
                                gameSessionId: $(anyNonBlankString())
                              ])
                              headers {
                                header('JMSType', 'WeeklyQuestCommand')
                              }
                            }
                          
                          }

And my Base class

            package com.gamesys.sampletrackerapp;
            
            import org.springframework.boot.test.context.SpringBootTest;
            import org.springframework.cloud.contract.verifier.messaging.boot.AutoConfigureMessageVerifier;
            
            @SpringBootTest
            @AutoConfigureMessageVerifier
            public class TrackerBase {
            }

The mvn command generates test class and yaml file with contract 

	// when:
			contractVerifierMessaging.send(inputMessage, "activemq:queue:tracker.queue.in",
					contract(this, "tracker_weekly_quest_confirmed_event.yml"));

		// then:
			ContractVerifierMessage response = contractVerifierMessaging.receive("activemq:queue:tracker.queue.out",
					contract(this, "tracker_weekly_quest_confirmed_event.yml"));
					
					
When the test is run ,i get FileNotFoundException

java.lang.IllegalStateException: java.io.FileNotFoundException: com/gamesys/sampletrackerapp/tracker-weekly-quest-confirmed-event.yml

pom.xml as below

       <dependencyManagement>
      <dependencies>
        
        <dependency>
          <groupId>org.apache.camel.springboot</groupId>
          <artifactId>camel-spring-boot-bom</artifactId>
          <version>3.20.0</version>
          <type>pom</type>
          <scope>import</scope>
        </dependency>
        
        <dependency>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-dependencies</artifactId>
          <version>2020.0.6</version>
          <type>pom</type>
          <scope>import</scope>
        </dependency>
  
      </dependencies>
    </dependencyManagement>

      <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-contract-verifier</artifactId>
      <version>3.0.2</version>
      <scope>test</scope>
    </dependency>

      <plugin>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-contract-maven-plugin</artifactId>
        <version>3.0.2</version>
        <extensions>true</extensions>
        <configuration>
          <baseClassForTests>com.gamesys.sampletrackerapp.TrackerBase</baseClassForTests>
        </configuration>
      </plugin>
      
      
      
 Reported on stackoverflow
 https://stackoverflow.com/questions/73147104/spring-cloud-contract-generates-message-verifier-test-from-groovy-to-yaml

**Comment by smfaizalkhan** [comment]
@marcingrzejszczak  ,please advice on whats the issue and how to address it

**Comment by marcingrzejszczak** [comment]
Can you show your generated test resources  and the generated test sources folder?

**Comment by marcingrzejszczak** [comment]
Does this work from the command line? When doesn't it work?

**Comment by smfaizalkhan** [comment]
@marcingrzejszczak 
I tried removing that line of "contract with files " and it is working 

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/22238550/228751227-6da68f94-c3dd-4fe8-b809-8d4373107f92.png">

Y is the groovy files copied to generated resources and test source folders ? and referred in the code ?

**Comment by smfaizalkhan** [comment]
@marcingrzejszczak 
I was able to overcome the issue by placing the file in the classpath


<img width="1399" alt="image" src="https://user-images.githubusercontent.com/22238550/228760653-46921813-6c05-4d58-b40d-7f04b68b08cf.png">


As the error is java.lang.IllegalStateException: java.io.FileNotFoundException: c**om/gamesys/sampletrackerapp/tracker-weekly-quest-confirmed-event.yml**

I think the issue may be the file sud be in the classpath ,so it is accesible by Class.getResource()

So the file i think sud be copied to classpath as,ur tot's please

**Comment by smfaizalkhan** [comment]
@marcingrzejszczak  ,i have changed my contract to be  "_" so generated file is also with. "_".But i think the generated file sud take the same format as given in the contract.. ur tots :)

**Comment by marcingrzejszczak** [comment]
Is this still a problem? It would be great to have a project that replicates this issue

**Comment by smfaizalkhan** [comment]
@marcingrzejszczak
