### ISSUE TITLE
Is it possible to produce a Groovy DSL script from an OpenAPI specification generated in JSON format

### ISSUE THREAD

**Issue by GurushanthGowdar** [spring-cloud/spring-cloud-contract#1881]
Hi,
Is there a method, plugin, or dependency that can be used to transform an OpenAPI Specification produced in JSON format to a Groovy contract?

**Comment by GurushanthGowdar** [comment]
Thank you for your response, @marcingrzejszczak. Although it's feasible to utilize the OpenAPI specification as the contract directly, we need the contracts to be in Groovy format. Hence, we are striving to generate Groovy contracts automatically. I'll attempt to produce the contracts in Groovy by utilizing the dependency and method mentioned above.

**Comment by marcingrzejszczak** [comment]
Check this class https://github.com/spring-cloud/spring-cloud-contract/blob/6fd4280d12a5186eb2a009eb018b8c0943baf85d/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/ToFileContractsTransformer.java and this one https://github.com/spring-cloud/spring-cloud-contract/blob/main/spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/java/org/springframework/cloud/contract/verifier/wiremock/WireMockToDslConverter.java . The latter can convert a Wiremock Json to a Groovy contract. You could write sth similar.

**Comment by GurushanthGowdar** [comment]
Hi @marcingrzejszczak ,Could you provide more details on the process of generating a Groovy contract from an OpenAPI generated JSON specification file? I am feeling uncertain about the steps I need to take, and I would appreciate it if you could elaborate on them.
