### ISSUE TITLE
Is it possible to use the spring-cloud-contract-oa3 with the OpenApi Specification in JSON format 

### ISSUE THREAD

**Issue by GurushanthGowdar** [spring-cloud/spring-cloud-contract#1884]
Hello @marcingrzejszczak, I was wondering if it's feasible to employ spring-cloud-contract-oa3 with an OpenAPI specification that's in JSON format. While looking at the examples, I noticed that all the specification files were in YAML, and I couldn't find any that were in JSON.

**Comment by marcingrzejszczak** [comment]
Why are you asking these question in this project? Please ask these question in the `spring-cloud-contract-oa3` project

**Comment by GurushanthGowdar** [comment]
okay @marcingrzejszczak  thank you for the response .
