### ISSUE TITLE
Spring Cloud Contract and two services that are both producers and consumers

### ISSUE THREAD

**Issue by smfaizalkhan** [spring-cloud/spring-cloud-contract#1889]
**Spring Cloud Contract and two services that are both producers and consumers**
With Event Sourcing, both services are producers and consumers. So I have both services generating stubs for the other service to consume

After browsing i came with the same issue in stackoverflow

https://stackoverflow.com/questions/50546972/spring-cloud-contract-and-two-services-that-are-both-producers-and-consumers
As it was in 2018 and so any updates 

@marcingrzejszczak  has asked to raise it  . any updates ?

**Comment by smfaizalkhan** [comment]
@marcingrzejszczak  ,please advice on whats the issue and how to address it

**Comment by marcingrzejszczak** [comment]
You can use the 2 features, generating stubs at runtime https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/project-features.html#features-stub-runner-generate-stubs-at-runtime and marking contracts as `in progress` https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/howto.html#how-to-mark-contract-in-progress . That way you're unblocking each others work until first stubs get published.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
