### ISSUE TITLE
I'm having trouble running the StubRunner Docker image that takes Groovy contracts as input, generates stubs, and starts a StubRunner server.

### ISSUE THREAD

**Issue by GurushanthGowdar** [spring-cloud/spring-cloud-contract#1893]
I am attempting to utilize the springcloud/spring-cloud-contract-stub-runner:4.0.1 Docker image to generate stubs at runtime from a Groovy contract and start a WireMock stubRunner server on a specified port. I am encountering an issue with stub generation at runtime. Specifically, the stubRunner is producing a "No Stubs found on the classpath" error because the stubs are not being generated.

Command I am Running :
```
docker run  --rm -e "STUBRUNNER_IDS=User-Management:user-management-services:+:stubs:8212" -e "STUBRUNNER_REPOSITORY_ROOT=stubs://file:///home/guru/Projects/Contracts/MyContracts" -e "STUBRUNNER_GENERATE_STUBS=true" -e "STUBRUNNER_STUBS_MODE=local" -p "8212:8212" -p "9876:9876" springcloud/spring-cloud-contract-stub-runner:4.0.1 
```

My question is whether it is possible to generate stubs at runtime using the StubRunner Docker image. I have previously accomplished this task using the StubRunner JAR on my local machine. If it is possible, what modifications do I need to make to the above command?

**Comment by marcingrzejszczak** [comment]
I'm not seeing you attach the contracts as a volume in your docker image. Please check an example here https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/docker-project.html#docker-stubrunner-example

**Comment by GurushanthGowdar** [comment]
Hi @marcingrzejszczak, thank you for your reply. I was able to solve my issue by mounting my local path to the StubRunner container path. However, I have a question - is there a way for the StubRunner image to automatically pick up any changes made to the contracts file and re-run to give updated results?

**Comment by marcingrzejszczak** [comment]
No, you have to run it each time from scratch
