### ISSUE TITLE
Wrong exception message in YamlToContracts

### ISSUE THREAD

**Issue by broeser** [spring-cloud/spring-cloud-contract#1894]
**Describe the bug**
Spring Cloud Contract 3.1.6
When the IllegalStateException is thrown while converting Yaml to Contracts, the relativePath is not logged.
Reason is, that the "-character is escaped via \" in line 851 here: 
https://github.com/spring-cloud/spring-cloud-contract/blob/5f14f230d15e04b07498a45bdec4490d78c590b1/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/converter/YamlToContracts.java

**Comment by marcingrzejszczak** [comment]
Ah indeed. Are you willing to file a PR to the 3.1.x branch? I would merge it forward to main then
