### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by stevenvanophem** [spring-cloud/spring-cloud-contract#1899]
The link in the documentation under https://docs.spring.io/spring-cloud-contract/docs/3.0.0-SNAPSHOT/reference/htmlsingle/#contract-yml seems to be broken (404).

**Comment by marcingrzejszczak** [comment]
It's there https://docs.spring.io/spring-cloud-contract/docs/current-SNAPSHOT/reference/html/yml-schema.html
