### ISSUE TITLE
Lack of support of XML in generated Spock tests

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#19]
_From @marcingrzejszczak on May 13, 2015 19:33_

_Copied from original issue: Codearte/accurest#69_

**Comment by marcingrzejszczak** [comment]
XML Assert is ready https://github.com/marcingrzejszczak/xmlassert . We're waiting for @tomakehurst to add XPath support for WireMock. In the meantime we can support everything but regexs

**Comment by tomakehurst** [comment]
I promise I haven't forgotten!

**Comment by marcingrzejszczak** [comment]
It's been a long time since this issue was set and nobody was asking for it so let's close it for now.
