### ISSUE TITLE
Spring cloud contract is unable to use for an application written using Kotlin

### ISSUE THREAD

**Issue by pexa-ushanib** [spring-cloud/spring-cloud-contract#1904]
**Is your feature request related to a problem?** I tried to use spring cloud contract verifier for an application written in Kotlin (Spring boot), but the autogenerated class is unable to identify the Base test class written in Kotlin

**Describe the solution you'd like**
Can we have improve the spring cloud contract verifier to support Kotlin written applications and tests? 

**Describe alternatives you've considered**
I might have a look at Pact flow - Still in progress

**Additional context**
I tried even by writing the tests in Java, but it is unable to start the server because the application is written in Kotlin.

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

You have an example written in Kotlin here https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/main/producer_kotlin_ftw

**Comment by pexa-ushanib** [comment]
Hi Please find below,

I have given xx.xx.xx.xx for package.


`extra["springCloudVersion"] = "2022.0.1"`


```
package xx.xx.xx.xx.producer

import io.kotest.core.spec.style.DescribeSpec
import xx.xx.xx.xx.util.TestUtil
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.web.servlet.MockMvc
import org.springframework.test.web.servlet.get

@AutoConfigureMockMvc
@SpringBootTest
class BaseContractTest(
    var mockMvc: MockMvc
) : DescribeSpec({
    describe("Health API - Ok Request (200) scenario ") {
        it("when system is healthy") {
            val expectedResponse = """{
                                   "healthy": true,
                                   "dependencies": [
                                       {
                                          "name": "Postgres",
                                          "healthy": true
                                       }  
                                   ]}"""

            mockMvc.get("${TestUtil.API_BASE_PATH}/health") {
            }.andExpect {
                status { isOk() }
                content { json(expectedResponse, true) }
            }
        }
    }
})
```


Above is my BaseContracttest class. In the auto generated CntractVerfier test class it is unable to import the above class.
It says,
```
error: cannot find symbol
import xx.xx.xx.xx.BaseContractTest;
                                                      ^
```
The generated test resource will be in java which is unable to import the kotlin bass class


<img width="542" alt="image" src="https://github.com/spring-cloud/spring-cloud-contract/assets/101084829/3637903f-37cd-41e2-b704-56f94078dd01">

**Comment by pexa-ushanib** [comment]
hi @marcingrzejszczak Could you have a look at this? 
Thanks

**Comment by pexa-ushanib** [comment]
Hi @marcingrzejszczak gentle reminder on this. We are trying to finalise the use of Spring cloud in our project. Appreciate if you can provide some inputs which can help us if this support is available or planned to have in future, or if we are doing something wrong.

**Comment by pexa-ushanib** [comment]
Any update on this? 
Thanks

**Comment by marcingrzejszczak** [comment]
I've given you a link with a working version. Have you checked it out?

**Comment by pexa-ushanib** [comment]
@marcingrzejszczak Thanks for the sample. The example you have given is using rest controllers. Our code is using open API spec. Have you got a sample done using open api spec which uses the spring cloud contract?
