### ISSUE TITLE
"Iterative mode does not support scenarios" error 

### ISSUE THREAD

**Issue by Sshviq** [spring-cloud/spring-cloud-contract#1906]
I try create 'Stateful contracts' (https://cloud.spring.io/spring-cloud-static/spring-cloud-contract/2.2.1.RELEASE/reference/html/project-features.html#contract-stateful-contracts) but the next error appears:

`**Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.1.RELEASE:convert (default-convert) on project ...: Execution default-convert of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.1.RELEASE:convert failed: java.lang.IllegalStateException: Iterative mode does not support scenarios. Use -DContractFileScanner.useRecursive=true** `

 <spring-cloud-contract.version>2.1.1.RELEASE</spring-cloud-contract.version>

Contracts structure:
```
producer_name\
  src\
   main\
        resources\
             contracts\
                consumer_name\
                  rest\
                     1_login.groovy
                     2_logout.groovy
```

**Comment by marcingrzejszczak** [comment]
You're using spring cloud contract in version 2.2.x which is not supported anymore (check this page for more information https://spring.io/projects/spring-cloud-contract#support ). Please upgrade to the latest version.
