### ISSUE TITLE
[Documentation] Broken links for server-side code and client-code in spring-cloud-contract reference documentation

### ISSUE THREAD

**Issue by prithvitewatia** [spring-cloud/spring-cloud-contract#1907]
The current reference document version (4.0.3) has broken link for server-side code and client side code.

The link for section is provided here [Section links](https://docs.spring.io/spring-cloud-contract/docs/4.0.3/reference/html/getting-started.html#getting-started-cdc)

These screenshot of breaking links is attached.

For breaking server-side code

<img width="1440" alt="Screenshot 2023-05-29 at 7 54 24 PM" src="https://github.com/spring-cloud/spring-cloud-contract/assets/42640176/01e4e0f3-90f2-4692-8028-e4d0f8df8d66">

For breaking client side code

<img width="1440" alt="Screenshot 2023-05-29 at 7 55 02 PM" src="https://github.com/spring-cloud/spring-cloud-contract/assets/42640176/c8ede0b3-b60f-441c-9483-82465b92b374">

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/961b1195298911e43258ff7e0f6cd1cbbdb58fd9
