### ISSUE TITLE
Add an option to download contracts from Pact Broker

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#191]
We can plug in downloading the contracts via the Pact Broker. Here we have an example of how to override stub downloading https://github.com/spring-cloud/spring-cloud-contract/blob/master/tests/spring-cloud-contract-stub-runner-moco/src/test/groovy/org/springframework/cloud/contract/stubrunner/provider/moco/ClasspathStubProvider.groovy and here is the Pact Loader https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-junit/src/main/java/au/com/dius/pact/provider/junit/loader/PactBrokerLoader.java#L53

**Comment by marcingrzejszczak** [comment]
There are some docs on how to run it
https://github.com/bethesque/pact_broker#to-have-a-play-around-on-your-local-machine
docker would probably be a more reproducible option
there’s a docker example here, but it assumes postgres, and you probably want sqlite/h2 or something https://github.com/DiUS/pact_broker-docker

via @Fitzoh

**Comment by cah-andrewfitzgerald** [comment]
Here's a simple example dockerfile I've been using locally:
https://github.com/Fitzoh/pact_broker/commit/cb9c9bac708911a8713365e2edc43e9727890bb3
