### ISSUE TITLE
No logs from WireMock

### ISSUE THREAD

**Issue by bartoliniii** [spring-cloud/spring-cloud-contract#1916]
Hello!
I'm using the latest version of Spring Cloud Contract (4.0.3) with Spring Boot 3.1.0 with slf4j-api 2.0.7 with log4j 2.19.0.
I have a very simple stub runner run by annotation (@AutoConfigureStubRunner), with embedded wiremock run on random port and it works pretty well, but I can't see any logs from WireMock.

According to [this](https://cloud.spring.io/spring-cloud-contract/reference/html/howto.html#how-to-debug-wiremock) article is should work out of the box, but it doesn't in my case.

I debugged a little and I found that the reason is that wiremock-jre8-standalone uses its own copy of slf4j classes prefixed with wiremock package (e.g. wiremock.org.slf4j.Logger) so my log configuration can't work with it and finally NOPLogger from wiremock.org.slf4j package is used.

I didn't find any way to make logger working. I even tried to replace wiremock-jre8-standalone and use a standard wiremock-jre8, but it is not possible - some classes e.g. HandlebarsTemplateProcessor uses repacked dependencies from standalone version of wiremock.

Did I miss something?
Is there any way to make it working?

**Comment by copbint** [comment]
I have come across this issue too, and can't find solution.

**Comment by marcingrzejszczak** [comment]
Do you have a small project that replicates this issue?

**Comment by tgeens** [comment]
```
@SpringBootTest
@AutoConfigureWireMock(port = 0)
@AutoConfigureWebTestClient
public class AutoConfigureWireMockApplicationTests {

    @Autowired
    WireMockServer wireMockServer;

    @Test
    public void testLogging() {
        wireMockServer.stubFor(get(urlEqualTo("/test"))
                .willReturn(ok("Hello World!")));

        var result = WebClient.create()
                .get().uri("http://localhost:{port}/test", wireMockServer.port())
                .exchangeToMono(response -> response.bodyToMono(String.class))
                .block();

        assertThat(result).isEqualTo("Hello World!");
    }
}
```

Trying this (in my webflux project) gives 0 wiremock logging.

Stepping through with my debugger, I end up in `Slf4jNotifier` and `verbose` is true, but `logging.isInfoEnabled()` and `logging.isErrorEnabled()` returns `false`.

I tried setting `logging.level.WireMock=DEBUG` etc, but that gives the same result.

**Comment by tgeens** [comment]
As a workaround, I switched to the `ConsoleNotifier` and this does work:
```
    @Bean
    WireMockConfigurationCustomizer optionsCustomizer() {
        return config -> config.notifier(new ConsoleNotifier(true));
    }
```

That reduces this problem to a slf4j/logback config issue? :thinking:

**Comment by adamsmith118** [comment]
> That reduces the logging-problem to a slf4j/logback config issue? 🤔

Presumably it's using `NOPLogger`, which wouldn't write anything...
