### ISSUE TITLE
Not working messageFrom in messaging tests

### ISSUE THREAD

**Issue by bartoliniii** [spring-cloud/spring-cloud-contract#1917]
In my tests, I cannot use `messageFrom` in `input` section as it is described ([in documentation](https://cloud.spring.io/spring-cloud-contract/reference/html/project-features.html#contract-dsl-output-triggered-message)). I don't even see such field in [Input class](https://github.com/spring-cloud/spring-cloud-contract/blob/abbd78e6774165126205000890b1486f5f9db6f1/specs/spring-cloud-contract-spec-java/src/main/java/org/springframework/cloud/contract/spec/internal/Input.java#L30)

Example contract definition:
```
package contracts

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    input {
        // there are no messageFrom, body and messageHeaders in Input class
        messageFrom('some-input-queue')
        body([
                intputField: "exampleValue"
        ])
        messageHeaders {
            header('contentType', applicationJson())
        }
    }
    outputMessage {
        sentTo("some-output-queue")

        body([
                outputField: "value"
        ])
    }
}
```

Is it still supported?

The approach with messages [triggered by method/label](https://cloud.spring.io/spring-cloud-contract/reference/html/project-features.html#contract-dsl-output-triggered-method) is working great in my case.

**Comment by marcingrzejszczak** [comment]
No, it was removed in 4.0 https://github.com/spring-cloud/spring-cloud-contract/wiki/Spring-Cloud-Contract-4.0-Migration-Guide#leave-only-code-input-triggers-and-output-message-type

**Comment by bartoliniii** [comment]
Oh I see, I have to admit it seemed very promising to me for the situation where there is input-queue/output-queue, and  we could model the tests the same way as we do for REST services and keep contracts on the (real) provider side (defined the same way as for REST services).

Without that, we have to treat these two queues separately, but in fact they are not separated

**Comment by bartoliniii** [comment]
@marcingrzejszczak I see you've already closed the issue, but I wonder if the documentation shouldn't be updated in this issue, to prevent the confusion I experienced?

**Comment by marcingrzejszczak** [comment]
@bartoliniii is there any mention of that property in the documentation?

> And last question - is there any chance to restore the functionality from the issue? Because it seems to be still valid, and I see in some issues, that people really did use it.

Nope, we're not planning to add it back

**Comment by bartoliniii** [comment]
Yes, I've linked it in first post ([this link](https://cloud.spring.io/spring-cloud-contract/reference/html/project-features.html#contract-dsl-output-triggered-message))

**Comment by marcingrzejszczak** [comment]
That's the deprecated documentation. The current one is here https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/

**Comment by bartoliniii** [comment]
Ohh, thanks!
