### ISSUE TITLE
Update messaging DSL documentation

### ISSUE THREAD

**Issue by adamleantech** [spring-cloud/spring-cloud-contract#1940]
Upgrading from spring cloud contract 3.x to 4.x leaves messaging tests broken because support for messageFrom, messageBody and messageHeaders have been removed.  The documentation has not been updated to reflect this and the commit message for the change that caused it doesn't reference any issue so it's not clear why this change was made.

See [here](https://cloud.spring.io/spring-cloud-contract/reference/html/project-features.html#contract-dsl-output-triggered-message)

and [here](https://github.com/spring-cloud/spring-cloud-contract/commit/1999066c5af7af2692b2897fc9ca70215534e3cc#diff-076e476a46352b39334287cc982263dac60dc2971254bb0bc6036f355d5cfa06)

**Comment by marcingrzejszczak** [comment]
This is not our current documention. You can find the most recent ones here https://docs.spring.io/spring-cloud-contract/docs/
