### ISSUE TITLE
WireMockTestExecutionListener blocks any other before test actions

### ISSUE THREAD

**Issue by Fadelis** [spring-cloud/spring-cloud-contract#1995]
**Describe the bug**
The `WireMockTestExecutionListener` in the `beforeTestClass` checks whether the application context is not broken by calling `testContext.getApplicationContext();`, which blocks all other actions until the application context is initialised. In turn this makes any other before actions (ie. BeforeAll annotated methods) to be run after the whole application context is initialized and it may be to late for these methods (ie. test container setup methods). This is called even when the test class doesn't have any wiremock configuration setup.
 So probably it could be improved by having a different if condition order - `if (annotationMissing(testContext) || wireMockConfigurationMissing(testContext) || applicationContextBroken(testContext))` and by checking whether the context is actually available via `testContext.hasApplicationContext` in the `applicationContextBroken` method, as there shouldn't be a need to see if it's broken when it's not there yet?

**Comment by marcingrzejszczak** [comment]
That's not good. Are you willing to file a PR (I guess against 3.1.x branch)? Is there an option to write a test for this?

**Comment by Fadelis** [comment]
@marcingrzejszczak Yes, I could make a PR and look into whether it's possible to write a test for it.

**Comment by marcingrzejszczak** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-contract/pull/1996

Thank you @Fadelis for your contribution!
