### ISSUE TITLE
Add feature to generate JAXRS controllers based on contract DSL

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#20]
_From @jkubrynski on May 12, 2015 11:13_

_Copied from original issue: Codearte/accurest#65_

**Comment by marcingrzejszczak** [comment]
The work required to do this (with all the endpoint stubbing, pojo creation) is not worth the results. We're dropping this.

**Comment by jkubrynski** [comment]
The main problem with model creation is that based on JSON's it could be only "stringly" typed which makes it useless in strongly typed language.
