### ISSUE TITLE
Stating a body field as anyBoolean fails as it tries to compare strings

### ISSUE THREAD

**Issue by regevbr** [spring-cloud/spring-cloud-contract#201]
Using
`response {
        status 200
        body([
            first: $(anyBoolean())
        ]
}`

Will produce 
`assertThatJson(parsedJson).field("first").isEqualTo("(true|false)");`
Which fails as it performs string comparsion.
The fix should be probably soomething of the sort
` assertThat(parsedJson.read("$.first", String.class)).matches("(true|false)");`

**Comment by marcingrzejszczak** [comment]
Ha! I know why you have this exception... The naming is bad from my side but I needed to be backward compatible.

There are methods coming from `RegexPatterns` and they just give you Strings.  There's a bunch of methods coming from `PatternValueDslProperty`. The latter are giving you proper values.

```
        T anyAlphaUnicode()
	T anyNumber()
	T aBoolean() 
	T anyIpAddress()
	T anyHostname()
	T anyEmail()
	T anyUrl()
	T anyUuid()
	T anyDate()
	T anyDateTime()
	T anyTime()
```

Run this again with `aBoolean()` and it will work. I can't use `anyBoolean()` cause the name is taken and the change would be backward incompatible.

**Comment by marcingrzejszczak** [comment]
Ping @regevbr ?

**Comment by regevbr** [comment]
Will check and let you know

**Comment by regevbr** [comment]
Works perfectly, thanks!

**Comment by marcingrzejszczak** [comment]
No problem!
