### ISSUE TITLE
Another format file not getting referenced from groovy file

### ISSUE THREAD

**Issue by tadlakha9** [spring-cloud/spring-cloud-contract#2018]
**Describe the bug**
while executing 'generateClientStubs' task, `txt` format file are not getting referenced inside `groovy` file with **4.0.3** version whereas working fine with **4.0.2** version

**Sample**,
In our application, we are referring a `txt` file from within the `groovy` contract file, but after the use of 4.0.3 tag, txt file are not getting transferred with groovy files from `contractTest -> resources -> contracts folder` because of which our 'generateClientStubs' task is failing which require the `txt` file as well.

![image](https://github.com/spring-cloud/spring-cloud-contract/assets/51110539/a176e66e-c757-4e9f-b2d5-d00f7cd7903c)

**Comment by marcingrzejszczak** [comment]
@shanman190 do you think it's sth related to the Gradle plugin changes?

**Comment by marcingrzejszczak** [comment]
@tadlakha9 do you observe the same problem with Maven or you don't have an option to verify that easily?

**Comment by shanman190** [comment]
@tadlakha9, would you be able to provide a reproducible sample that we could try out as well?

@marcingrzejszczak, from a process standpoint the `copyContracts` task copies everything from the source contract directory into the `build/stubs/META-INF/${project.group}/${project.name}/${project.version}/contracts`. From there the `generateClientStubs` is telling the generation process to use that directory from the output of the `copyContracts` task. So everything that exists within the original contracts folder should be immediately available for the `generateClientStubs` task without doing anything extra at all. I'm not immediately seeing a way in which it would ever not be there if it was in the original source directory to begin with. The only case that I can come up with as a potential is if the new contracts folder is used, but the file is in the old contracts folder. We default the plugin internally to attempt to see if the new folder exists, but if it doesn't then fallback to the old folder and log a deprecation warning. If the new folder _does_ exist, then _everything_ must exist there for the processes to complete successfully.

**Comment by tadlakha9** [comment]
> u think it's sth related t

**Comment by tadlakha9** [comment]
> @shanman190 do you think it's sth related to the Gradle plugin changes?

No, i don't think its related to gradle plugin change, because it was working fine with 7.6.1 version with our microservices

**Comment by tadlakha9** [comment]
While debugging, we observe that we are getting below exception

Gradle does not know how file 'build\stubs\META-INF\service-token-validator-commons-test\5.2.0-alpha1\contracts\tokenType.txt' was created (output property 'copiedContractsFolder'). Task output caching requires exclusive access to output paths to guarantee correctness (i.e. multiple tasks are not allowed to produce output in the same location).

It is getting conflicting with gradle task.

but this issue we start getting with 4.0.3 version and not with 4.0.2 version

**Comment by tadlakha9** [comment]
Thanks for quick support. 

We had analyzed the issue is because of gradle cache, we were calling same task twice which leads to an errors.

Thanks again.
