### ISSUE TITLE
Execution default-generateStubs of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:3.1.3:generateStubs failed: An API incompatibility was encountered while executing org.springframework.cloud:spring-cloud-contract-maven-plugin:3.1.3:generateStubs: java.lang.NoSuchMethodError: org.codehaus.plexus.util.DirectoryScanner.setFilenameComparator(Ljava/util/Comparator;)V

### ISSUE THREAD

**Issue by reddykmr** [spring-cloud/spring-cloud-contract#2027]
I have uplifted my application from Spring boot 2.5.7 to 3.1.2  along with that spring cloud stub runner and spring cloud contract contract verifier dependencies also uplifted to latest version
Spring cloud contract maven plugin we are using 3.1.3 ( not only this versions with above version also having same issue), which giving 
the issue ( my earlier version is 3.0.2)

plugin configuration

      <plugin>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-contract-maven-plugin</artifactId>
        <version>3.1.3</version>
        <extensions>true</extensions>
        <configuration>
          <baseClassForTests>com.example.TestClass</baseClassForTests>
        </configuration>
      </plugin>
	  
Exception stacktrace

Caused by: java.lang.NoSuchMethodError: org.codehaus.plexus.util.DirectoryScanner.setFilenameComparator(Ljava/util/Comparator;)V
	at org.codehaus.plexus.components.io.resources.PlexusIoFileResourceCollection.getResources(PlexusIoFileResourceCollection.java:250)
	at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:561)
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:221)
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:199)
	at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:1063)
	at org.springframework.cloud.contract.maven.verifier.GenerateStubsMojo.createStubJar(GenerateStubsMojo.java:147)
	at org.springframework.cloud.contract.maven.verifier.GenerateStubsMojo.execute(GenerateStubsMojo.java:127)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 30 more

Even i added the pleuxs-utils dependency explicitly, still giving same exception

can you please help on this issue

thanks

**Comment by reddykmr** [comment]
Hi Team, can you please help me ASAP on the above issue

**Comment by spencergibb** [comment]
Contract 3.1.x is not compatible with boot 3.1.x. See https://github.com/spring-cloud/spring-cloud-release/wiki/Supported-Versions#supported-releases

**Comment by reddykmr** [comment]
ok thanks for info
after using of 4.0.3 spring cloud contract with spring boot 3.1.2 and JDK17 we facing warning issue, can you please help how to solve it and what are the modifications required in POM
[WARNING] Could not transfer metadata org.slf4j:slf4j-api/maven-metadata.xml from/to spring-releases (https://repo.spring.io/release): authentication failed for https://repo.spring.io/release/org/slf4j/slf4j-api/maven-metadata.xml, status: 401 Unauthorized
[WARNING] Could not transfer metadata org.slf4j:slf4j-api/maven-metadata.xml from/to maven-restlet (https://maven.restlet.org): transfer failed for https://maven.restlet.org/org/slf4j/slf4j-api/maven-metadata.xml
[WARNING] org.slf4j:slf4j-api/maven-metadata.xmlfailed to transfer from https://repo.spring.io/release during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of spring-releases has elapsed or updates are forced. Original error: Could not transfer metadata org.slf4j:slf4j-api/maven-metadata.xml from/to spring-releases (https://repo.spring.io/release): authentication failed for https://repo.spring.io/release/org/slf4j/slf4j-api/maven-metadata.xml, status: 401 Unauthorized
[WARNING] org.slf4j:slf4j-api/maven-metadata.xmlfailed to transfer from https://maven.restlet.org during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of maven-restlet has elapsed or updates are forced. Original error: Could not transfer metadata org.slf4j:slf4j-api/maven-metadata.xml from/to maven-restlet (https://maven.restlet.org): transfer failed for https://maven.restlet.org/org/slf4j/slf4j-api/maven-metadata.xml
[WARNING] Could not transfer metadata org.slf4j:slf4j-api/maven-metadata.xml from/to apache.snapshots (https://repository.apache.org/snapshots): transfer failed for https://repository.apache.org/snapshots/org/slf4j/slf4j-api/maven-metadata.xml
[WARNING] org.slf4j:slf4j-api/maven-metadata.xmlfailed to transfer from https://repo.spring.io/release during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of spring-releases has elapsed or updates are forced. Original error: Could not transfer metadata org.slf4j:slf4j-api/maven-metadata.xml from/to spring-releases (https://repo.spring.io/release): authentication failed for https://repo.spring.io/release/org/slf4j/slf4j-api/maven-metadata.xml, status: 401 Unauthorized
[WARNING] org.slf4j:slf4j-api/maven-metadata.xmlfailed to transfer from https://maven.restlet.org during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of maven-restlet has elapsed or updates are forced. Original error: Could not transfer metadata org.slf4j:slf4j-api/maven-metadata.xml from/to maven-restlet (https://maven.restlet.org): transfer failed for https://maven.restlet.org/org/slf4j/slf4j-api/maven-metadata.xml
[WARNING] org.slf4j:slf4j-api/maven-metadata.xmlfailed to transfer from https://repo.spring.io/release during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of spring-releases has elapsed or updates are forced. Original error: Could not transfer metadata org.slf4j:slf4j-api/maven-metadata.xml from/to spring-releases (https://repo.spring.io/release): authentication failed for https://repo.spring.io/release/org/slf4j/slf4j-api/maven-metadata.xml, status: 401 Unauthorized
[WARNING] org.slf4j:slf4j-api/maven-metadata.xmlfailed to transfer from https://maven.restlet.org during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of maven-restlet has elapsed or updates are forced. Original error: Could not transfer metadata org.slf4j:slf4j-api/maven-metadata.xml from/to maven-restlet (https://maven.restlet.org): transfer failed for https://maven.restlet.org/org/slf4j/slf4j-api/maven-metadata.xml

**Comment by spencergibb** [comment]
Don't use repo.spring.io/release use maven Central

**Comment by reddykmr** [comment]
I have used below configuration, still facing the issue 
example:
  <repositories>
  <repository>
    <id>central</id>
    <name>Maven Central</name>
    <layout>default</layout>
    <url>https://repo1.maven.org/maven2</url>
    <snapshots>
    <enabled>false</enabled>
    </snapshots>
  </repository>
</repositories>

**Comment by reddykmr** [comment]
we are unable to solve the issue and one more thing when we run the client side contracts(yaml) expected Producer contract not executing,
Could you please provide the latest configuration of producer contracts in yaml

**Comment by marcingrzejszczak** [comment]
I don't understand this issue. Can you go to start.spring.io and generate a spring cloud contract project? You will see how a well created project looks like and try applying it in your project.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
