### ISSUE TITLE
spring-cloud-contract-gradle-plugin 4.0.4 Groovy dependencies resolution issues with Groovy 4.0.15

### ISSUE THREAD

**Issue by LukasSmrcka** [spring-cloud/spring-cloud-contract#2034]
I was upgrading my Groovy from version 3 to version 4 and the plugin spring-cloud-contract-gradle-plugin had issues when building the app with Groovy 4.0.15. It was allways breaking with the version 4.0.15 on dependency resolution. I see in maven central there are dependencies of plugin version 4.0.4 on the Groovy 4.0.0. To fix the 4.0.15 I had to adjust resolution strategy in the gradle file like this:

``` 
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if ((details.requested.group == 'org.codehaus.groovy' || details.requested.group == 'org.apache.groovy') && details.requested.name != 'groovy-bom') {
            details.useTarget group: 'org.apache.groovy', name: details.requested.name, version: '4.0.15'
        }
    }
}
```

After adding of this the resolution started to work. But it seems to me it should be working without such adjustments.

**Comment by marcingrzejszczak** [comment]
fixed by https://github.com/spring-cloud/spring-cloud-contract/commit/95998b4d57af968d0731206a8f96c862d3cd2ad3
