### ISSUE TITLE
Release 3.1.9 to keep spring-cloud-contract-wiremock with spring-cloud-gateway?

### ISSUE THREAD

**Issue by ilgrosso** [spring-cloud/spring-cloud-contract#2037]
Would it be possible to keep the release train aligned with [spring-cloud-gateway](https://github.com/spring-cloud/spring-cloud-gateway)?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ilgrosso** [comment]
Sorry for late reply.

At [Apache Syncope](https://github.com/apache/syncope) we are basing one of the components on Spring Cloud Gateway; the related tests are using Spring Cloud Contract WireMock.

For such a reason, we tend to keep their release versions in sync but, when you compare

* https://github.com/spring-cloud/spring-cloud-gateway/tags
* https://github.com/spring-cloud/spring-cloud-contract/tags 

you can notice that there is no counterpart under https://github.com/spring-cloud/spring-cloud-contract/tags for https://github.com/spring-cloud/spring-cloud-gateway/releases/tag/v3.1.9

**Comment by marcingrzejszczak** [comment]
I don't understand. Use the release trains where we're showing which versions are working together https://github.com/spring-cloud/spring-cloud-release/

**Comment by ilgrosso** [comment]
I see https://github.com/spring-cloud/spring-cloud-contract/releases/tag/v3.1.9 now, thank you!
