### ISSUE TITLE
testMatchers byType is not working with minOcurrences(0) and maxOcurrences(0)

### ISSUE THREAD

**Issue by julio-martin** [spring-cloud/spring-cloud-contract#204]
```
testMatchers {           jsonPath('$.items', byType{             maxOccurrence(0)           })         }
```

It creates only next assert:
```
assertThat((Object) parsedJson.read("$.items")).isInstanceOf(java.util.List.class)
```

**Comment by marcingrzejszczak** [comment]
LOL - I love Groovy, and the Groovy Truth (http://groovy-lang.org/semantics.html#Groovy-Truth) but most likely here it's a lie ;) I have a condition in the code where I wanted to check if min occurrence or max occurrence took place. So I used Groovy Truth

```
if (it.minTypeOccurrence() || it.maxTypeOccurrence() ) {
						// build the assertion
					} else {
						checkType(bb, it, elementFromBody)
					}
```

for Integers the condition will be false if Integer is `null` or .... `0` :D
