### ISSUE TITLE
Wrong response matched when using queryParameters

### ISSUE THREAD

**Issue by jakub-bochenski** [spring-cloud/spring-cloud-contract#2042]
Given 2 contract definitions

```
Contract.make {
    request {
        method GET()
        urlPath "/v1.0/users?%24filter=identities%2Fany%28c%3Ac%2FissuerAssignedId+eq+%27Besmart1%21%2Bss_only%40example.com%27+and+c%2Fissuer+eq+%27exampletest.onmicrosoft.com%27%29&%24select=extension_e7a978dca46f4594ade3a4eb7258f667_internal%2Cidentities%2CsignInActivity"
    }
```
and
```
    Contract.make {
        request {
            method GET()
            urlPath("/v1.0/users") {
                queryParameters {
                    parameter '$filter': $(consumer(regex('identities/any\\(c:c/issuerAssignedId eq \'[^@]+@example\\.com\' and c/issuer eq \'exampletest\\.onmicrosoft\\.com\'\\)')))
                }
            }
        }
```

When I send a request `GET /v1.0/users?%24filter=identities%2Fany%28c%3Ac%2FissuerAssignedId+eq+%27Besmart1%21%2Bss_only%40smartassistant.com%27+and+c%2Fissuer+eq+%27zoovutest.onmicrosoft.com%27%29&%24select=extension_e7a978dca46f4594ade3a4eb7258f667_internal%2Cidentities%2CsignInActivity` it is matched by the second contract, and not the first.

**The second contract should not match, as it doesn't have the `$select` query parameter at all.**

As a workaround adding this to the second contract seems to prevent it from matching:
```

                    parameter '$select': ''
```

**Comment by marcingrzejszczak** [comment]
I don't think this is our fault, we delegate work to WireMock and it requires to set the parameter as you've described it. Do you think we should document that?

**Comment by jakub-bochenski** [comment]
> I don't think this is our fault, we delegate work to WireMock and it requires to set the parameter as you've described it.

Using the `queryParameters` closure seems to result in different behavior than specifying the query inside `url`. 
I think it would be nice to document how/why it causes different beheviour in WM

>   parameter '$select': ''

Setting parameter to empty string to mean "not present" is not obvious, so I'd also point it out in docs

**Comment by jakub-bochenski** [comment]
hey @marcingrzejszczak I still don't understand exactly why the closure vs string result in different behavior. 
Could you point me to what different WM constructs those are using?

**Comment by jakub-bochenski** [comment]
I mean using the string seems to imply exact match, contrary to cfeefcd910c7748286178c14287843085a2971d4

**Comment by marcingrzejszczak** [comment]
https://wiremock.org/docs/request-matching/#url-matching , you can either match directly the url or make WM parse the query parameters and check if concrete query params are present. If you're using the query params and they are not defined at all it means that we don't care if they are there.
