### ISSUE TITLE
AutoConfigureWireMock Not Auto Configuring

### ISSUE THREAD

**Issue by welsh** [spring-cloud/spring-cloud-contract#2051]
**Describe the bug**
When using `@AutoConfigureWireMock(port = 5678)` with Spring Boot 3.2 and Cloud RC 2023.0.0-RC1, it still defaults to `8080` for its default port rather than using what is provided.

Unsure if this is something introduced with Spring Boot or Cloud but if I go back to Boot 3.1.6 and Cloud 2022.0.4 then it works.

**Sample**
Here is a sample project: https://github.com/welsh/spring-cloud-wiremock-issue

You can see the `WiremockApplicationAnnotationTest` test fails because it cannot connect to `5678` but is successful with `8080`.

There also is `WiremockApplicationImportTest` that uses a `WireMockConfigurationCustomizer` to set the port to `5678` which is successful for both test cases.

You can also swap to the `boot_3_1` branch which confirms the working behaviour on the older branch where all the tests pass.

**Comment by spencergibb** [comment]
Duplicates #2035. Will be available in 2023.0.0 soon

**Comment by welsh** [comment]
> Duplicates #2035. Will be available in 2023.0.0 soon

Thanks! Think I missed the duplicate when I checked the Spring Cloud Contract issues cause it was already closed.
