### ISSUE TITLE
MediaTypes are missing the json/HATEOAS type + all media types with + in them are invalid as + is a regex char

### ISSUE THREAD

**Issue by regevbr** [spring-cloud/spring-cloud-contract#206]

**Comment by marcingrzejszczak** [comment]
Can you show some examples? You should be able to provide arbitrary content types without any issues.

**Comment by regevbr** [comment]
Ineed you can pass your own string and that is what I did, but thought it will be nice to have it build in.
Also, all the ones using '+' will fail so if you use:

`response {
        headers {
            contentType(applicationAtomXml())
        }
    }`
It iwll be transformed to 
`assertThat(response.header("Content-Type")).matches("application/atom+xml.*");`

Which wil fail

**Comment by marcingrzejszczak** [comment]
Good to know cause that's a bug. Could you please add some tests in your PR to ensure that we don't have any regressions?

**Comment by regevbr** [comment]
Sure. Will do later tonight

**Comment by regevbr** [comment]
Seems like the issue was fixed in 1.0.3...
