### ISSUE TITLE
Missing 4.1.0 docker release. 

### ISSUE THREAD

**Issue by elysrivero99** [spring-cloud/spring-cloud-contract#2073]
I was upgrading my project to use Spring Cloud Contract 4.1.0 but in some other services (non java) I'm using [spring-cloud-contract-stub-runner](https://hub.docker.com/r/springcloud/spring-cloud-contract-stub-runner/tags) to perform all tests. 

I'm not seeing the tag 4.1.0. It is intentional? Or was missing when you performed the release?

Thanks in advanced!

**Comment by marcingrzejszczak** [comment]
Yikes! I'm pushing them as we speak.

**Comment by marcingrzejszczak** [comment]
Done!

https://hub.docker.com/layers/springcloud/spring-cloud-contract-stub-runner/4.1.0/images/sha256-6de8eefad28c6b97bb0d6cae001cc02f2990a7138f2f381522c5558bab7a2341?context=explore

https://hub.docker.com/layers/springcloud/spring-cloud-contract/4.1.0/images/sha256-c9044fe7db6393dc3572dbe7d5b3a3bff8f699284f085dc33bd2e5a096da23b5?context=explore
