### ISSUE TITLE
wiremock.server.port is always defaulting to 8080

### ISSUE THREAD

**Issue by mohamed-asfour** [spring-cloud/spring-cloud-contract#2074]
**Describe the bug**

It seems that the change provided in this [bug](https://github.com/spring-cloud/spring-cloud-contract/issues/1920) led to undesired behaviour by defaulting the server port always to 8080 after setting it once to a random port.

This block replaces the `wiremock.server.port` property even if it has been already set
```java
else {
			Map<String, Object> source = getWireMockSource(environment);
			source.put("wiremock.server.port", 8080);
			if (log.isDebugEnabled()) {
				log.debug("Registered WireMock server port property to the default <8080> value");
			}
		}
```
could you please be kind and have a look on this issue?

*affected Version*:  3.1.9

Thanks in Advance

**Comment by svetlana-nikitina** [comment]
@marcingrzejszczak thanks a lot for fixing, waiting for release 
is the milestone correct though?

**Comment by marcingrzejszczak** [comment]
Argh, it's not, thanks for checking
