### ISSUE TITLE
Add feature to generate Spring controllers based on contract DSL

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#21]
_From @jkubrynski on May 12, 2015 11:13_

_Copied from original issue: Codearte/accurest#64_

**Comment by KrzysiekT** [comment]
Wow.

**Comment by marcingrzejszczak** [comment]
The work required to do this (with all the endpoint stubbing, pojo creation) is not worth the results. We're dropping this.
