### ISSUE TITLE
Camel Kafka fails to read messages unless run twice

### ISSUE THREAD

**Issue by javiersvg** [spring-cloud/spring-cloud-contract#2107]
As a developer
I want to create a tests that reads messages from a kafka topic using camel
So that I can validate services that communicate using kafka

Expected:
SCC should be able to execute a test that validates that a message is written to a kafka topic

Actual:
The test fails because SCC is unable to read the message from kafka the first time is run

I have created the following repo with an example of the bug:
https://github.com/javiersvg/scc-camel-kafka-bug-demo

I am trying to debug the issue without luck so far, but in case it helps it seems that the first message that is being read by camel from Kafka is flagged as read despite never being passed to the EventDrivenPollingConsumer class.
This might be a camel issue but it could also be a problem in the way SCC is using camel, but I am not sure yet.

**Comment by marcingrzejszczak** [comment]
Can you create an example that doesn't use SCC, only camel and where you can confirm that you can read it properly? That way we can exclude SCC being the culprit (or confirm that)

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
