### ISSUE TITLE
wrapValueWithQuotes throws NullPointer when value is null (Cannot invoke "Object.toString()" because "value" is null)

### ISSUE THREAD

**Issue by fireplace009** [spring-cloud/spring-cloud-contract#2117]
Java 21
`<spring-cloud-contract.version>4.1.3</spring-cloud-contract.version>`

**Describe the bug**

When running the maven plugin, my `contract.yaml` has a `bodyFromFile` value. 
This file is a `.json` containing (amongst other things) an array with values. 
One of these value can be `null` 

**Sample**

```json
{
  "rows": [
    {
      "values": [
        "2023-10-19 08:39:55",
        "B",
        "N",
        "",
        "100",
        "01",
        1,
        1369,
        "100",
        null,
        null,
        null
      ],
  ]
}
```

In the class `DelegatingJsonVerifiable` this method:

```java
    private static String wrapValueWithQuotes(Object value) {
        return value instanceof String ? "\"" + stringWithEscapedQuotes(value) + "\"" : value.toString();
    }
```

does not take into account that the value can be null - (value instanceof String is false => value.toString throws NPE

**Comment by fireplace009** [comment]
Awesome !!! Thank you

**Comment by marcingrzejszczak** [comment]
Thank you for filing the issue :)
