### ISSUE TITLE
Question: AetherFactories local repository

### ISSUE THREAD

**Issue by juagonzalez** [spring-cloud/spring-cloud-contract#214]
In AetherFactories.class exist a method that set the local repository with a hardcode string for .m2/repository. 

>     private static String localRepositoryDirectory() {
        return System.getProperty("maven.repo.local", System.getProperty("user.home") + "/.m2/repository");
    }

Actually i have a custom setting for maven and my repo is in c:/.m2, when i try to get my server's stubs it fail because the stubs doesn't exist in that repo. 

Is there any way to change that?

**Comment by marcingrzejszczak** [comment]
As you can see it's not hardcoded - you can override it by passing to your tests a system property `maven.repo.local` that will point to a proper place. That thing to the right is the default if you don't have the property set

**Comment by juagonzalez** [comment]
oh thanks so much! i'll try it
