### ISSUE TITLE
wiremock.server.port proprety is 0 if used random port

### ISSUE THREAD

**Issue by yukatan** [spring-cloud/spring-cloud-contract#225]
I' m running a test with this configuration:

```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@RunWith(SpringRunner.class)
@AutoConfigureWireMock(port = 0)
@ActiveProfiles("test")
```
I can see that the wiremock is starting in a random port, but when I try to bind the port with the property wiremock.server.port the property has always the value 0. 

I'm using spring cloud Candem.SR4

is this expected behaviour?? how can I bind the random port??

if I use 

`@AutoConfigureWireMock(port = 9999)
`
I can see the wiremock.server.port populated correctly

**Comment by marcingrzejszczak** [comment]
I'm sorry but I can't replicate this.

```
@RunWith(SpringRunner.class)
@SpringBootTest(classes=WiremockTestsApplication.class, properties="app.baseUrl=http://localhost:${wiremock.server.port}", webEnvironment=WebEnvironment.RANDOM_PORT)
@DirtiesContext
@AutoConfigureWireMock(port=0)
// Default stubs work at classpath:/mappings
public class AutoConfigureWireMockAutoStubsApplicationTests {

	@Autowired
	private Service service;

	@Value("${wiremock.server.port}")
	private Integer port;

	@Test
	public void contextLoads() throws Exception {
		assertThat(this.service.go()).isEqualTo("Hello World");
		assertThat(this.port).isGreaterThan(0);
	}

}
```

This works fine. Can you upload your sample somewhere?

**Comment by yukatan** [comment]
your example works until I add the config server starter as dependency

  ```
 <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-config</artifactId>
  </dependency>
```

even if configuration in config server is empty or even if it doesn't connect to config server ${wiremock.server.port} is 0

**Comment by marcingrzejszczak** [comment]
hmm and what if you call it like this:

````
@RunWith(SpringRunner.class)
@SpringBootTest(classes=WiremockTestsApplication.class, properties="app.baseUrl=http://localhost:${wiremock.server.port}", webEnvironment=WebEnvironment.RANDOM_PORT)
@DirtiesContext
@AutoConfigureWireMock(port=0)
// Default stubs work at classpath:/mappings
public class AutoConfigureWireMockAutoStubsApplicationTests {

	@Autowired
	private Service service;

	@Autowired
	private Environment env;

	@Test
	public void contextLoads() throws Exception {
		assertThat(this.service.go()).isEqualTo("Hello World");
		assertThat(this.env.getProperty("wiremock.server.port")).isGreaterThan(0);
	}

}
```

Maybe property resolution is done in this case too early or sth...

**Comment by yukatan** [comment]
this.env.getProperty("wiremock.server.port") is always 0

**Comment by marcingrzejszczak** [comment]
Ok so for now the only workaround that comes to my mind is to disable the autoconfiguration of the config server client for these tests. I'll try to analyze what's wrong with this in the meantime.

**Comment by yukatan** [comment]
just to let you know
I added "spring.cloud.config.enabled: false" to bootstrap.yml and configuration is disabled but the problem is still there. I think just to add the dependency creates the bug.

**Comment by marcingrzejszczak** [comment]
That's really unfortunate. Thanks for the hint!

**Comment by dsyer** [comment]
It's a problem with the boot strap context in spring-cloud-commons. I'll see if we can work around it here.

**Comment by mjaggard** [comment]
This still doesn't work for me:

```
    @Configuration
    public static class WiremockServerConfiguration {
        @Primary
        @Bean
        public Config config(Config prev, WireMockConfiguration wireMockConfiguration, @Value("${wiremock.server.port}") int port) {
            port = wireMockConfiguration.isRunning() ? port : 2000;
            log.info("Wiremock started on port {}", port);
            return ....
        }
    }
```

This prints "Wiremock started on port 0"

**Comment by marcingrzejszczak** [comment]
The port is adjusted later in `WireMockConfiguration`'s `@PostConstruct`. You're checking it too early.

**Comment by mjaggard** [comment]
How do I get it later? I need to be able to create my Config bean to be
injected into the application during the creation process because the app
reads the value in a constructor.

**Comment by marcingrzejszczak** [comment]
You have no other choice than to either 

- ensure your code runs after the WireMockConfiguration happens
- resolve the port at runtime
- allow a setter based injection of the port for the sake of tests (e.g. add a package scope setter and call it in your test)

any other ideas @dsyer ?

**Comment by mjaggard** [comment]
Could you make the method `org.springframework.cloud.contract.wiremock.WireMockConfiguration.httpPort` public so that I can access it in my bean creation?

**Comment by marcingrzejszczak** [comment]
But you shouldn't depend on our `WireMockConfiguration`... You shouldn't inject our configuration classes into your beans.

**Comment by mjaggard** [comment]
But what I *should* inject is the port number and that's not working sure surely injecting the configuration is better than nothing?

**Comment by marcingrzejszczak** [comment]
I have given you other options that you can consider

**Comment by mjaggard** [comment]
I think I am running this after the WireMockConfiguration has happened - at least I am getting `isRunning()` returning true.

```
    @Configuration
    public static class WiremockServerConfiguration {
        @Primary
        @Bean
        @SneakyThrows
        public Config config(Config prev, WireMockConfiguration wireMockConfiguration, @Value("${wiremock.server.port}") int port, Environment environment) {
            log.info("Port from env {}", environment.getProperty("wiremock.server.port"));
            var method = WireMockConfiguration.class.getDeclaredMethod("httpPort");
            method.setAccessible(true);
            Object portTest = method.invoke(wireMockConfiguration);
            log.info("Port from method {}", portTest);
            log.info("Port from @Value {}", port);
            return ...
    }
}
```

Prints out:
Port from env 0
Port from method 58011
Port from @Value 0

Also, the environment never ends up containing the correct value. I've tried injecting `Environment` into my test and even after setting up my wiremock stubs successfully, I still get `0` as the value of wiremock.server.port.

I'll just use the nasty reflection for now, it's only test code 👎

**Comment by mjaggard** [comment]
> The port is adjusted later in `WireMockConfiguration`'s `@PostConstruct`. You're checking it too early.

I can't see any code in `WireMockConfiguration` that does this?
