### ISSUE TITLE
Concatenation in a header value with an execute() fails

### ISSUE THREAD

**Issue by pfrank13** [spring-cloud/spring-cloud-contract#231]
This is minor but figured I'd log it.  When trying to use the header portion of the DSL I tried
```groovy
header('Authorization', 'Bearer ' + execute('authToken()'))
```
results in Java code that looks like
```java
.header("Authorization", "Bearer authToken()");
```
If you remove the String concatenation and push it into the method being called it works as expected
DSL
```groovy
header('Authorization', execute('authToken()'))
```
results in correct Java code that looks like
```java
.header("Authorization", authToken());
```

**Comment by marcingrzejszczak** [comment]
Yeah, that makes sense and is kind of expected. I'll have to update the docs that you can't do such things as concatenation when using execute. From the implementation point of view it's just doing a toString on the ExecutionProperty which is the name of the command to run. Sorry for the inconvenience :/
