### ISSUE TITLE
Improve support for arrays in body

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#24]
_From @mzielinski on April 10, 2016 11:1_

Assume that we have below response from server

```
{
   "exp": 2459982033,
   "user_name": "admin",
   "authorities": [
       "ROLE_ADMIN"
   ],
   "client_id": "ui",
   "scope": [
       "read",
       "write"
   ]
}
```

I would like to check wheather scope array is not empty. I do not care about specific values. Currently I am not able to do it. For sure we should improve support for arrays in body, maybe this task will be a good place to think about it.

_Copied from original issue: Codearte/accurest#217_

**Comment by marcingrzejszczak** [comment]
Right now you can do it with a method on the server side.

**Comment by Fitzoh** [comment]
[pact-jvm](https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit)
handles that example something like this:
`eachLike("authorities", stringType())`
With the ability to specify min/max number of values like this:
`minArrayLike("authorities", 1, stringType())`
`maxArrayLike("authorities", 5, stringType())`

See link at top of comment for docs or [this link](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonBody.java) for source

**Comment by marcingrzejszczak** [comment]
This is can be fixed via - https://github.com/spring-cloud/spring-cloud-contract/issues/185 . You can provide a manual check of stuff via the matchers
