### ISSUE TITLE
Checking the internal structure of response arrays 

### ISSUE THREAD

**Issue by chundt** [spring-cloud/spring-cloud-contract#240]
While using spring cloud contract for testing our API returning an array of json objects, I have two issues/questions.
1. When my contract contains:
```
response {     
    status 200     
    body([
                 [             
                    name : "ben",
                     age : 33 
                ],
                 [ 
                     name : "mary",
                      age : 8         
                ]
    ])
    headers { 
        contentType(applicationJsonUtf8()) 
    }
 }
```
in the generated test the following json is correctly tolerated:
```
[
    {
        "name" : "ben", 
        "age" : 33 
    },
    {
        "name" : "mary", 
    	"age" : 8
     }
]
```

but also this is allowed: (mixed up values)
```
[
    {
        "name" : "ben", 
        "age" : 8
    },
    {
        "name" : "mary", 
    	"age" : 33
     }
]
```
I see, that this is due to the fact that the generated test only contains assertions like:
```
assertThatJson(parsedJson).array().contains("name").isEqualTo(„ben“); 
assertThatJson(parsedJson).array().contains("age").isEqualTo(33);
 assertThatJson(parsedJson).array().contains("name").isEqualTo(„mary“); 
assertThatJson(parsedJson).array().contains("age").isEqualTo(8);
```
Is there a possibility to check that the values are correctly grouped in the json objects contained in the array?

2. A more serious problem occurred to me, when we changed our (WIP-) API in order to support paging.
After the change the API returned:
```
{
"content": [
    {
        "name" : "ben", 
        "age" : 33 
    },
    {
        "name" : "mary", 
    	"age" : 8
     }
],
"totalPages": 1,
"totalElements": 1,
"last": true,
"size": 20,
"number": 0,
"first": true,
"numberOfElements": 1
}
```
As this change is **NOT downwards compatible** the test should break, but the generated assertions (see above) seem to ignore the depth level of the array. Thus, the test is still green. 
As our motivation to use spring cloud contract for testing the interaction of our micro services to have breaking tests in such a case, I really like to have an option to define that in the contract.

**Comment by marcingrzejszczak** [comment]
The best option will be to use the `testMatchers` section. Then you can do any sort of combination in the way you please. You can use regex or execute via a command and check a concrete ordering. Read more about this here - http://cloud.spring.io/spring-cloud-static/spring-cloud-contract/1.0.3.RELEASE/#_dynamic_properties_in_matchers_sections

**Comment by marcingrzejszczak** [comment]
Another option is to turn on the experimental feature of creating tests with order assertion - http://cloud.spring.io/spring-cloud-static/spring-cloud-contract/1.0.3.RELEASE/#_limitations_2  . You can set a system property `spring.cloud.contract.verifier.assert.size=true` and see if that helps.

**Comment by chundt** [comment]
Thank you for the fast response! I will try to use the `testMatchers`, but I would really love to have automatically generated assertions for the internal array structure :-).

By the way: when I use `testMatchers` AND a pattern for the response body, then unfortunately, I do not get any assertions generated from the body pattern.

**Comment by marcingrzejszczak** [comment]
Yeah that's deliberate. You can use either of those. If you use `testMatchers` then you have to control fully the assertion process.

If you want the internal structure to be checked try the size assertion check. But it's an experimental feature. 

JSON is such a terrible structure that it's very difficult to ensure in an automated fashion that proper JSON paths will be generated. So if the experimental feature will not work for you then you'll have to write the response assertions yourself :(

**Comment by chundt** [comment]
When setting the system property `spring.cloud.contract.verifier.assert.size=true`, I see no difference in the generated test. 
But setting `<assertJsonSize>true</assertJsonSize>` in the plugin configuration helps. 
The only difference in generated tests is, that now the size is checked automatically. Is this right or should there be any additional assertions?

**Comment by marcingrzejszczak** [comment]
`spring.cloud.contract.verifier.assert.size=true` this should be set in the surefire plugin. Good that you found the `<assertJsonSize>true</assertJsonSize>` cause I've forgotten about it :P 

Yeah the size should be checked but I thought that I implemented an experimental check of index but most likely I only wanted to do it and haven't done it. So actually you don't have any other option than to do a manual check :/

Or you can file a PR to add support for indexed checks :D

**Comment by chundt** [comment]
Thank you for your help and the discussion! I look forward for the future enhancements of your project, and maybe, if I have the time, think about a PR :-).

**Comment by marcingrzejszczak** [comment]
No problem :) 

Will definitely try to think about making this better. For now you'll have to go with the manual check though.
