### ISSUE TITLE
spring-cloud-contract - consumer with Feign Clients

### ISSUE THREAD

**Issue by blackOcean** [spring-cloud/spring-cloud-contract#242]
Using Spring Cloud with Netflix OSS.

Config-service and eureka is up. Now I installed my producer locally at port 8090. Consumer using Feign clients to call producer to get some data. Now I am getting 500 error. It is showing that URL not found. The closest match is /ping.  I believe Feign client is unable to mock, it is somehow trying to connect with eureka not from the locally installed producer. Can you help me on it.

**Comment by marcingrzejszczak** [comment]
`/ping` and `/health` are two endpoints that we mock by default. In your case it seems that the stubs were properly set up and you've managed to shoot a request at the stubbed WireMock endpoint. Most likely your request is wrong. You're missing headers / body or sth. Can you show your stub and how you're sending your request?

**Comment by marcingrzejszczak** [comment]
Ping @blackOcean ?

**Comment by marcingrzejszczak** [comment]
Cloding due to inactivity
