### ISSUE TITLE
Extend the DSL with new Client and Server pattern DslProperty creation methods

### ISSUE THREAD

**Issue by pfrank13** [spring-cloud/spring-cloud-contract#245]
When doing some work on my own I came up with a few primitives I think would be generally useful to people at large.  Specifically

1. anyIso8601DateTimeWithTimeZone: adds the Z and +0:00 style endings to a date with optional millisecond precision
2. anyNotEmptyOrWhitespaceString: Anything that is "" or " " will fail
3. enumOf(String...): useful for enumerated values in an API, currencies, languages etc.

I've got no horse in the naming fight, I tend to name verbosely which isn't popular with many people, other suggestions appreciated.

Pull Request forthcoming, I needed a gh issue number to create a proper branch and check messages

**Comment by marcingrzejszczak** [comment]
Hi @pfrank13 ! Great job!

Ensure that any commits are done to a PR for branch `1.0.x` . We're merging then everything from `1.0.x` to master.

As for naming maybe let's go with

```
anyIso8601WithOffset 
anyNonEmptyString
anyOf(...)
```

WDYT? BTW I'm not an expert on naming ;) @Fitzoh maybe you have an opinion on this? :)

**Comment by Fitzoh** [comment]
I like your suggestions @marcingrzejszczak , but I think `anyNonEmptyString` is a little different from `anyNotEmptyOrWhitespaceString`.

Should probably be two options, `anyNonEmptyString` (would allow `' '`) and `anyNonBlankString` (would not allow `' '`).

[isEmpty](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isEmpty-java.lang.CharSequence-)
[isBlank](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isBlank-java.lang.CharSequence-)

**Comment by marcingrzejszczak** [comment]
Oh yeah I've forgotten about the blank method. Obviously you're right. My dementia is getting more severe than I thought.

**Comment by marcingrzejszczak** [comment]
Congrats @pfrank13 on your PR :D

**Comment by pfrank13** [comment]
@marcingrzejszczak Thank you sir :)
