### ISSUE TITLE
Uses local repository instead of failing with invalid artifactory credentials

### ISSUE THREAD

**Issue by mogronalol** [spring-cloud/spring-cloud-contract#248]
Earlier today I was struggling to get the stubrunner to load my latest stubs from artifactory:

`io.specto:my-service:+:stubs:8082`

I've now found out that this was because I'd added the wrong username and password by accident. 

Expected outcome:
An immediate failure when authentication is not successful

Actual outcome:
Loads the latest stubs from your local cache which may be out of date

If I hard code the version number:

`io.specto:my-service:31:stubs:8082`

Then I get a failure if it's not local.

In otherwords, if you're explicit about working online then I think it makes more sense to always fail it can't authenticate with the repository, to negate any confusion about the latest stubs not being the latest.

**Comment by marcingrzejszczak** [comment]
Do you have any stacktrace with the exception where sc-contract tried to log in and failed?

**Comment by marcingrzejszczak** [comment]
ping @mogronalol ?

**Comment by marcingrzejszczak** [comment]
Ah so we swallow the original exception! Cool that's what I was looking for. Thanks for the stacktrace
