### ISSUE TITLE
Helpful classes to create custom test generator

### ISSUE THREAD

**Issue by jerckov** [spring-cloud/spring-cloud-contract#254]
In package `org.springframework.cloud.contract.verifier.builder` there are some classes and mechanisms that could be helpful for create custom test generator f.e. `BlockBuilder.class`. Maybe there should be some abstraction with helper methods to make creating custom test generator simpler?

**Comment by marcingrzejszczak** [comment]
After some discussions with @jerckov it turned out that the only class that is useful is the `BlockBuilder`. We'll make it public for `1.1.x`
