### ISSUE TITLE
Contract generation for old applications

### ISSUE THREAD

**Issue by ozersenturk** [spring-cloud/spring-cloud-contract#256]
Hi there,

We have a spring mvc application that is written quite a while ago. It does not contain any tests. Is there an easy way to generate SCC groovy contracts from mvc mappings for this application? It has hundreds of endpoints and it is currently not possible to write all the contracts manually.

Best regards.

Özer

**Comment by marcingrzejszczak** [comment]
You can use RestDocs with sc contract. The contracts and stubs can be automatically created for you from your tests.

**Comment by ozersenturk** [comment]
Yes, I know that. However, the application does not have any tests :) I just wanted to learn if it is possible to generate contracts from mvc mappings :) (as an initial setup for consumer driven contracts)

**Comment by marcingrzejszczak** [comment]
Wow if your application has no tests then indeed you have a problem :P there is no way to generate contracts from mappings. That's because we need a request reply scenario, not a schema

**Comment by ozersenturk** [comment]
Ok :) I just tried my luck :)
