### ISSUE TITLE
iso8601WithOffset generated test code incorrectly .isEqualTo as opposed to .matches

### ISSUE THREAD

**Issue by pfrank13** [spring-cloud/spring-cloud-contract#257]
When using the iso8601WithOffset in the context of these 2 tests: [JaxRsClientMethodBuilderSpec](https://github.com/spring-cloud/spring-cloud-contract/blob/4d895da4fbb86c338dd65c1ccb70dddff5932a34/spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientMethodBuilderSpec.groovy#L1051) and [MockMvcMethodBodyBuilderSpec](https://github.com/spring-cloud/spring-cloud-contract/blob/4d895da4fbb86c338dd65c1ccb70dddff5932a34/spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderSpec.groovy#L1951) the assertion generates with a .matches properly.

However, it seems that isn't the case when the verifier plugin itself generates the code.

```java
assertThatJson(parsedJson).field("iso8601WithOffset").isEqualTo("([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\\.\\d{3})?(Z|[+-][01]\\d:[0-5]\\d)");
```

it generates a .isEqualTo which of course fails.

Steps to Reproduce:
1. git clone https://github.com/pfrank13/plugin-dependency-scc.git
2. git checkout iso_8601_with_offset_bug
3. ./mvnw clean install -Pextending && ./mvnw clean install
observe the stack trace and check out the ExampleTest that is generated

As an aside, I personally haven't figured out a good way to step through the code during code generation so I'm tracing by eye for the most part, any help with debugging would be greatly appreciated as well.  Thanks!

**Comment by pfrank13** [comment]
Looks like I can use org.springframework.cloud.contract.maven.verifier.PluginIT in spring-cloud-contract-tools/spring-cloud-contract-maven-plugin to test.

**Comment by marcingrzejszczak** [comment]
Try using the unit test cause it is really slow

**Comment by pfrank13** [comment]
Just wanted to update the bug with where I'm at.  I still can't reproduce this bug inside of the Spring Cloud Contract project.  The code generation works fine, correctly producing a .matches() for the regex.  In projects that use the verifier plugin this isn't the case however.  To make sure I'm actually using code I think I am I custom compiled SCC with a logging statement so I could ensure the maven plugin being used was the one just built and it is, and the bug is still present so this doesn't appear to be me doing something stupid with my pom declaration or the like.  At this point I'm sort of stuck =)

**Comment by marcingrzejszczak** [comment]
I'll take a look at this next week I promise :)

**Comment by marcingrzejszczak** [comment]
I couldn't replicate it - https://github.com/pfrank13/plugin-dependency-scc/pull/1 . I've migrated to snapshots to make `url` work and I updated the response to make the tests pass

**Comment by pfrank13** [comment]
Okay so after your pull request into the master for my repo I added back a date with offset and it passes, which is fantastic. But here is where I'm sort of confused the branch iso_8601_with_offset_bug, which was the one to demo the bug, still fails and I updated the contract dependencies to 1.0.5.BUILD-SNAPSHOT.  According to the effective pom from my repo's master should be the same so what gives?  That's super weird to me.  On the plus it appears I'm not crazy and I indeed could't reproduce the bug in the SCC code =)

**Comment by marcingrzejszczak** [comment]
Remember that in the plugin you have to explicitly provide the version. It might be resolved improperly.

**Comment by pfrank13** [comment]
Oh I was super cognizant of that, shit I went so far as to add log messages to make sure I was using what I thought I was, so it's got the version declared on it as well.

**Comment by marcingrzejszczak** [comment]
Ok so I'm closing this one? :P

**Comment by pfrank13** [comment]
Hahaha, yeah looks good to me.  The best bugs are the one's that aren't bugs.  Thanks for looking into it, sorry to waste your time =)

**Comment by marcingrzejszczak** [comment]
No problem :)
