### ISSUE TITLE
basePackageForTests can be configured automatically based on baseClassForTests package

### ISSUE THREAD

**Issue by jkubrynski** [spring-cloud/spring-cloud-contract#260]
Currently we need to set it directly in the pom.xml configuration. Automatic behavior will be much more useful

**Comment by marcingrzejszczak** [comment]
What exactly do you have in mind. Can you provide an example?

**Comment by jkubrynski** [comment]
With the configuration as the one below, default package for generated tests is ```org.springframework.cloud.contract.verifier.tests```
```
<configuration>
  <baseClassForTests>com.kubrynski.web.AbstractContractTest</baseClassForTests>
  <testFramework>JUNIT</testFramework>
</configuration>
```

Maybe it would be better to use ```com.kubrynski.web``` as it can be determined based on the ```baseClassForTests``` property

**Comment by marcingrzejszczak** [comment]
The flow for setting the generated tests package name will look like this:

- pick `basePackageForTests`
- if `basePackageForTests` wasn't set pick the package from `baseClassForTests`
- if `baseClassForTests` wasn't set pick `packageWithBaseClasses`
- if nothing got set pick the default `org.springframework.cloud.contract.verifier.tests`

**Comment by marcingrzejszczak** [comment]
I don't see the code. Can you upload it in a readable manner?

**Comment by cszhangwenhua** [comment]
With the configuration as the one below, default package for generated tests is org.springframework.cloud.contract.verifier.tests and   com.fantasy.contract.generate
in com.fantasy.contract.generate packege, ContractVerifierTest extends ContractVerifierBase
in org.springframework.cloud.contract.verifier.tests package, ContractVerifierTest has no super class,why?
```                        
                        <configuration>
                            <contractsWorkOffline>true</contractsWorkOffline>
                            <contractsDirectory>
                                src/test/resources/contracts
                            </contractsDirectory>
                            <baseClassForTests>
                                com.fantasy.ContractVerifierBase
                            </baseClassForTests>
                            <!-- Provide the base class for your auto-generated tests -->
                            <basePackageForTests>
                                com.fantasy.contract.generate
                            </basePackageForTests>


                        </configuration>

**Comment by marcingrzejszczak** [comment]
I'll look into it - thanks

**Comment by cszhangwenhua** [comment]
<groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-contract-maven-plugin</artifactId>
                <version>1.2.3.RELEASE</version>
                
                ****

sorry，change <extensions>true</extensions> to <extensions>false</extensions>，it will ok。
