### ISSUE TITLE
Add sample scenarios to showcase how stateful behaviour works

### ISSUE THREAD

**Issue by diegobe** [spring-cloud/spring-cloud-contract#273]
This issue is for adding same examples about how to add [scenarios](https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_scenarios) in a producers repo.

**Comment by marcingrzejszczak** [comment]
WIP here - https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/adding_scenarios

**Comment by diegobe** [comment]
I like the example, very difficult to forget the states 🍺! It is great to see this working. As I mentioned there is an appetite to use it.

Did u try to reset the states by calling the url scenarios/reset  ?

**Comment by marcingrzejszczak** [comment]
What can I say - such things happen in life in exactly that hmm scenario? :P

No I haven't. We don't actually allow this OOB. You'd have to find the port and shoot at `/__admin/scenarios/reset` but that will work since we would be calling WireMock directly.

I haven't yet had the time to write the consumer side. I'll finish this tomorrow. I'll also add a javadoc that you need a stateful "backend" to the test. That's why I've set up a Spring context that is shared between the tests.

**Comment by marcingrzejszczak** [comment]
Done in https://github.com/spring-cloud-samples/spring-cloud-contract-samples/commit/5aefab1b3257e9082cff7c55db2dea8bad7ecc33

Producer side ;)

```java
RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = WebEnvironment.MOCK)
@AutoConfigureMockMvc
@AutoConfigureJsonTesters
@AutoConfigureStubRunner(workOffline = true, ids = "com.example:beer-api-producer-with-scenario:+:stubs:8090")
@DirtiesContext
public class BeerControllerTest extends AbstractTest {

	@Autowired MockMvc mockMvc;
	@Autowired BeerController beerController;

	@Before
	public void setupPort() {
		beerController.port = 8090;
	}

	@Test public void should_eventually_get_completely_wasted() throws Exception {
		sendARequestAndExpectStatuses(SOBER, TIPSY);
		sendARequestAndExpectStatuses(TIPSY, DRUNK);
		sendARequestAndExpectStatuses(DRUNK, WASTED);
	}

	private void sendARequestAndExpectStatuses(DrunkLevel previousStatus, DrunkLevel currentStatus) throws Exception {
		mockMvc.perform(MockMvcRequestBuilders.post("/wasted")
				.contentType(MediaType.APPLICATION_JSON)
				.content(json.write(new Person("marcin")).getJson()))
				.andExpect(status().isOk())
				.andExpect(content().json("{\"previousStatus\":\"" + previousStatus.name() +
						"\",\"currentStatus\":\"" + currentStatus.name() + "\"}"));
	}
}
```

**Comment by diegobe** [comment]
It looks good! Thanks for adding this in!
