### ISSUE TITLE
Introduce explicit mode of stub downloading

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#287]
Currently we have a combination of `workOffline`, `repositoryRoot`

- `workOffline:true`, `repositoryRoot:null` - pick from local maven repo
- `workOffline:false`, `repositoryRoot:sth` - download from maven repo
- `workOffline:false`, `repositoryRoot:null` - pick from classpath

for version `1.2.0` we could consider a Spring Boot Test style of explicitly providing an option. `Local`, `Classpath`, `Maven` or sth like that.

**Comment by hsdmiranda** [comment]
Currently we are using gradle and the dependencies are downloaded to another folder that is not in the .m2/repository. Is there a way it could work offline from a local gradle repository?

**Comment by marcingrzejszczak** [comment]
I think that you can change the `repositoryRoot` to point to the directory. I wonder if Aether can even work with the Gradle cache. I doubt that it would work. You can however add the dependency as a test dependency and pick it up from classpath.

**Comment by vicusbass** [comment]
Would be useful to have `workOffline` as being prioritary: i.e. 
`workOffline:true`, `repositoryRoot:sth` - ignore the repositoryRoot and pick from local maven repo
