### ISSUE TITLE
Spring REST Docs integration: contracts contain unnecessary host entry

### ISSUE THREAD

**Issue by tkopczynski** [spring-cloud/spring-cloud-contract#290]
Contracts that are generated from Spring REST Docs tests contain unnecessary host and port information. In both the URL match and headers. This leads to problems when actually using this contract in tests.

See here: http://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_generating_contracts_using_restdocs

**Comment by marcingrzejszczak** [comment]
Done in https://github.com/spring-cloud/spring-cloud-contract/commit/ec65d1b69f8783b51e3760e9106828b83e67b08b

**Comment by tkopczynski** [comment]
This is a different issue actually, it needs code changes - removing the host from the URL that lands in the contract generated with Spring rest docs

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/commit/3d23964dca42ab8633b6998393ab8087599cc31a
