### ISSUE TITLE
documentRoot should have a default documented property

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-contract#293]
If a test wants to use `@AutoConfigureStubRunner` and let the infrastructure download the stubs, a `documentRoot` attribute must be provided.

This attribute can be externalized using a user-defined property (see [this example](https://github.com/spring-cloud-samples/github-analytics/blob/0b29b502cfbc03eaba6da13ad8d4deab2177cbc9/src/test/java/org/springframework/github/AnalyticsApplicationTests.java#L27)) but that requires to define a property expression in the annotation.

It would be much better if a default property exists and was transparently used if no value is set in the annotation. This allows to define such infrastructure outside of the code as one would expect.

Concretely, a `spring.cloud.contract.stub.repositories` property can be defined (and metadata added to it so that IDE can provide assistance). If no `documentRoot` is set, the value of that property would be used by default. If this property is set, the usual behaviour happens if `documentRoot` is set.

This would allow you to write something like:

```java
@AutoConfigureStubRunner(ids = "com.example.github:github-webhook")
```

and 

```properties
spring.cloud.contract.stub.repositories=https://example.com/repo
```

**Comment by marcingrzejszczak** [comment]
We already do that via `stubrunner.ids` or `stubrunner.repositoryRoot`

**Comment by snicoll** [comment]
Is there a plan to reconsider those variable names? They do not align well with the rest of the ecosystem IMO

**Comment by marcingrzejszczak** [comment]
Yeah I'll create a new issue for that. We might consider doing that but I think that it should be done in 2 releases or sth like that. First deprecating them in the next major one and then removing in the subsequent one.
