### ISSUE TITLE
Documentation: user guide could benefit from a concrete example of byCommand assertions

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-contract#299]
There is an example there already, but the implementation of the Java method `assertThatValueIsANumber()` is never shown, so it's hard for the user to know how to write it. In particular it's not obvious what type the argument has (`JSONObject`? `String`?).

**Comment by WhyINeedToFillUsername** [comment]
In my opinion, this is still an issue. The implementation of assertThatValueIsANumber() is still not shown - should it be written in the test base java class, the groovy file, the generated test source, or in the separate library with shared resources? There should be a hint about this.

**Comment by marcingrzejszczak** [comment]
@WhyINeedToFillUsername hopefully this (https://github.com/spring-cloud/spring-cloud-contract/commit/1c0d4e56cf6739f652468c8abda1b02f5aa4f4c5) better addresses the issue

**Comment by marcingrzejszczak** [comment]
The generated test class is already there above that snippet
