### ISSUE TITLE
Generated tests fail in version 1.1.0.RELEASE

### ISSUE THREAD

**Issue by Gonzo17** [spring-cloud/spring-cloud-contract#305]
Hey guys,

I'm new to Spring Cloud Contracts and have been working through the tutorial. I've been using version 1.0.4.RELEASE to get it all working. After that I updated my dependency to 1.0.5.RELEASE, which worked fine, and then to 1.1.0.RELEASE, which lets the generated tests fail.

Reason for that is a changed static import for 'assertThat'. 

In 1.0.5.RELEASE:
`import static org.assertj.core.api.Assertions.assertThat;`

In 1.1.0.RELEASE: 
`import static org.springframework.cloud.contract.verifier.assertion.SpringCloudContractAssertions.assertThat;`

Error log:
`[ERROR] ***/target/generated-test-sources/contracts/org/springframework/cloud/contract/verifier/tests/ContractVerifierTest.java:[12,68] package org.springframework.cloud.contract.verifier.assertion does not exist`
`[ERROR] ***/target/generated-test-sources/contracts/org/springframework/cloud/contract/verifier/tests/ContractVerifierTest.java:[12,1] static import only from classes and interfaces
`

So obviously the new generated test references a class that doesn't exist. The specific dependency where `SpringCloudContractAssertions` should be is `spring-cloud-contract-verifier`. In both cases Maven gets the version 1.0.1.RELEASE, which explains why the new class isn't available. I assume, that the Spring dependency plugin is resolving the versions, so I wonder why it gives me version 1.0.1.RELEASE for this component even though a couple of newer versions are available. **

The relevant parts of my pom.xml:
```
	<properties>
		<spring-cloud.version>Camden.SR2</spring-cloud.version>
		<spring-cloud-contract.version>1.1.0.RELEASE</spring-cloud-contract.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-hateoas</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-feign</artifactId>
		</dependency>

		<!-- Test -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-contract-verifier</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>


	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-contract-maven-plugin</artifactId>
				<version>${spring-cloud-contract.version}</version>
				<extensions>true</extensions>
				<configuration>
					<baseClassForTests>SomeClass</baseClassForTests>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

** Maybe this issue explains why the artifact is not used in higher versions: https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-contract-verifier
However, I have no clue how the calculation of the usage is done, so this is just another guess.

**Comment by marcingrzejszczak** [comment]
The class does exist https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/assertion/SpringCloudContractAssertions.java . You're doing sth wrong. Please check out the with examples of setting up the project (https://github.com/spring-cloud-samples/spring-cloud-contract-samples). Or publish the project somewhere so that I can check it out

**Comment by marcingrzejszczak** [comment]
Ah I see what you're doing wrong. You're using a `Camden` release train with a `Dalston` version of Spring CLoud Contract. Just update to `Dalston` and it will work fine.

**Comment by Gonzo17** [comment]
Got it! You're right, I didn't realize that mismatch. Thank you for the help 😃
