### ISSUE TITLE
Unable to generate dynamic request body

### ISSUE THREAD

**Issue by rytighe** [spring-cloud/spring-cloud-contract#313]
I'm trying to have the body of my request populate as the result of a method call, and am using the following in my contract:

`body( 
     $(producer(execute('method123()')))
)`

The generated test code then contains:

`RequestSpecification request = given()
     .header("redacted", "redacted")
     .header("Content-Type", "application/json")
     .body("{\"executionCommand\":\"method123()\"}");`, 

which doesn't actually invoke the referenced method.  Including something similar in the response body works perfectly.  Am I missing something?

**Comment by marcingrzejszczak** [comment]
For sure you need to pass sth on the `consumer` side cause otherwise, the stub will not know how to match the request. I'll check out tomorrow if you can actually provide the whole body for tests from a method (I don't remember anyone wanting that until now)

**Comment by rytighe** [comment]
Thanks for following up.  I'm inclined to think this is a bug - a somewhat similar use case is generating dynamic header values (https://github.com/spring-cloud/spring-cloud-contract/issues/111), which I've confirmed works locally.

**Comment by marcingrzejszczak** [comment]
Most likely so. That's pretty unusual but definitely should be possible to be done.
