### ISSUE TITLE
Cannot define messaging contracts for queues whose messages are consumed in raw format

### ISSUE THREAD

**Issue by lnhrdt** [spring-cloud/spring-cloud-contract#331]
With Streams configured in raw mode:

```
spring.cloud.stream.default.consumer.headerMode: raw
```

And a consumer ready to receive the raw message body:

```java
@Component
@EnableBinding(Topics.class)
public class SomeListener {

    private final Logger logger = LoggerFactory.getLogger(SomeListener.class);

    @StreamListener(Topics.EVENTS)
    public void receive(byte[] message) throws IOException {
        String messageString = new String(message);
        Message messageObject = new ObjectMapper().readValue(messageString, Message.class);
        logger.info(messageString);
    }
}
```

I do not believe there is a way to define the contract body:

```groovy
package contracts.claims.messaging

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    label 'sends_text_message'

    outputMessage {
        sentTo("events")

        body("{\"message\": \"hello\"}".getBytes()) // This does not work
        headers {
            header("contentType", applicationJsonUtf8())
        }
    }
}
```

We're taking this approach to have easier control over deserialization error handling.

**Comment by marcingrzejszczak** [comment]
Hi @lnhrdt . I think that with latest Stream `2.0.0` release, and this commit https://github.com/spring-cloud/spring-cloud-contract/commit/9abc2b39e1208213c24c413ee80154302eab5dcf we're always sending arrays of bytes. Can you double check it on your side that this is the case? In other words, you don't have to write ` body("{\"message\": \"hello\"}".getBytes())`. Just write ` body('''{"message": "hello"}''')`. We will convert it to bytes anyways.

**Comment by lnhrdt** [comment]
Hey @marcingrzejszczak, thanks for the followup! It's been a while since I've used Spring Cloud Contract so I don't have an active project to double check this for you on. We can close this issue if you like and the next time I'm using Spring Cloud Contract with messaging I'll let you know how it goes.

**Comment by marcingrzejszczak** [comment]
Ok! I'll close it for now
