### ISSUE TITLE
Generated producer tests don't compile with messaging header regex patterns

### ISSUE THREAD

**Issue by mtthwcmpbll** [spring-cloud/spring-cloud-contract#336]
We've got a contract defined with some basic messaging body that also expects to have a particular header value.  Here's out contract:

```
org.springframework.cloud.contract.spec.Contract.make {
    label 'trigger_event'

    input {
        triggeredBy('requesIsCalled()')
    }

    outputMessage {
        sentTo 'topic.rateablequote'
        headers {
            header('processId', value(producer(regex('[0-9]+')), consumer('123')))
        }
        body([
            eventId: value(producer(regex('[0-9]+')), consumer('1'))
        ])
    }
}
```

In this case, we'd like to use the client stubs to test this by generating messages with the `processId` header set to `123`, but we don't care what the producer is generating as long as it matches our expected pattern.  This contract generates a producer test with the following matcher line:

```
assertThat(response.getHeader("processId")).matches("[0-9]+");
```

Running the test throws an exception when it can't find a `matches()` method on the base providing `assertThat()`:

```
MessagingTest.java:29: error: cannot find symbol
                        assertThat(response.getHeader("processId")).matches("[0-9]+");
                                                                   ^
  symbol:   method matches(String)
  location: class AbstractObjectAssert<CAP#1,Object>
  where CAP#1 is a fresh type-variable:
    CAP#1 extends AbstractObjectAssert<CAP#1,Object> from capture of ?
1 error
startup failed:
Compilation failed; see the compiler error output for details.

1 error

:compileTestGroovy FAILED
```

This is using Spring Cloud Contract version 1.1.1

**Comment by marcingrzejszczak** [comment]
Can you please check out version `1.1.2.BUILD-SNAPSHOT` ? From what I see the problem should have already been fixed
