### ISSUE TITLE
Contracts path cannot be overriden

### ISSUE THREAD

**Issue by vicusbass** [spring-cloud/spring-cloud-contract#338]
When providing a custom location for contracts, the default location is used instead
E.g. When running the following command
`mvn org.springframework.cloud:spring-cloud-contract-maven-plugin:convert -DcontractsDirectory=/tmp` 
the default location is used: `${basedir}/src/test/resources/contracts"`

Providing a custom location is important for external contracts or for particular maven modules configuration
Using **_1.1.1.RELEASE_** version

**Comment by marcingrzejszczak** [comment]
Assuming we have the following directory structure

```
.
...
├── pom.xml
├── producer
...
```

Remember to run this in the following way:

```
./mvnw org.springframework.cloud:spring-cloud-contract-maven-plugin:convert -Dspring.cloud.contract.verifier.contractsDirectory=/home/marcin/repo/spring-cloud-contract-samples/producer/src/test/resources/contracts -f producer/pom.xml
```

That way you will run the `convert` step from the root of the project but for the child module (`producer`) module in this case
