### ISSUE TITLE
Gradle plugin incorrectly caching SNAPSHOT versions of contracts

### ISSUE THREAD

**Issue by reillylm** [spring-cloud/spring-cloud-contract#343]
In `GradleContractsDownloader`, we [cache downloaded contracts](https://github.com/spring-cloud/spring-cloud-contract/blob/7be2d8dad5a5b5652db8bb90b7c0bb9373782deb/spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/GradleContractsDownloader.groovy#L41) based off the GAV coordinates (`groupId:artifactId:version:classifier`) of the artifact, but this doesn't account for the changing nature of `SNAPSHOT` versions.

I think we could have an option to skip caching altogether as a field in one of the extension blocks, or perhaps just explicitly handle `SNAPSHOT` versions.

**Comment by marcingrzejszczak** [comment]
Hmm and what if you apply the `--refresh-dependencies` - doesn't it help? Or do you mean that the problem is in how we use Aether as such?

**Comment by reillylm** [comment]
Just tested `--refresh-dependencies`-- no dice. I think that flag affects only gradle's out-of-the-box dependency management, but we're caching directly from the plugin in `GradleContractsDownloader` (I don't think we even go through Aether if there's a cache hit).

If you stop the gradle daemon with `--stop` then the cache will be cleared and we'll redownload the contracts through Aether, but that's kind of a destructive workaround.
