### ISSUE TITLE
Improve document with migration from 1.0.X to 1.1.0 for spring-cloud-contracts

### ISSUE THREAD

**Issue by bookerT303** [spring-cloud/spring-cloud-contract#350]
We have been using spring-cloud-contracts and have @AutoConfigureWireMocks and WireMocks that read the stubs.  With the reorganization of stubs in 1.1.0 it was far simpler to keep the same structure as 1.0.X

And while we could make it work changing:
```
@AutoConfigureWireMock(stubs = "classpath:/customer-stubs/mappings", port = 8084)
```
to
```
@AutoConfigureWireMock(stubs = "classpath:customer-stubs/META-INF/travel.components/customer-contract/1.0.2-SNAPSHOT/mappings/", port = 8084)
```
That hard coding of the version in the classpath was going to be an issue with constant maintenance every time the version changed..

So to keep the structure of the stubs the same and minimize the impact of upgrading we
use this gradle task
```
task copyStubs(type: Copy, dependsOn: 'generateWireMockClientStubs') {
//    Preserve directory structure from 1.0.X of spring-cloud-contracts
    from "${project.buildDir}/resources/main/customer-stubs/META-INF/${project.group}/${project.name}/${project.version}"
    into "${project.buildDir}/resources/main/customer-stubs"

}
```

So it might be nice to offer that as an option in the document.

**Comment by marcingrzejszczak** [comment]
There you go https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_new_structure_of_generated_stubs :)
