### ISSUE TITLE
unable  to send File( with Xml content) in a Body of request of a Contract 

### ISSUE THREAD

**Issue by svijetha78** [spring-cloud/spring-cloud-contract#351]
Contract.make {
            name: 'First Time Register Ecore'
            request {
                method 'PUT'
                urlPath(SEARCH_REGISTER_URL)
                headers {
                    header 'X-INFA-USER-NAME', value(producer("dummy"), consumer(optional(regex('\\w+'))))
                    header 'X-INFA-USER-ID', value(producer("dummy"), consumer(optional(regex('\\w+'))))
                    header 'X-INFA-ORG-ID', value(producer("dummy"), consumer(optional(regex('\\w+'))))
                    contentType(applicationXml())            
                }
              body(value(                     
                        consumer("${getStaticFileContent('__files/searchFiles/mdm-search-metamodel_v1.ecore')}")
                )) 
			}		
			   response { 
				status 204 
				                
                }
         
        }

**Comment by marcingrzejszczak** [comment]
I'm sorry but I can't read anything from what you typed in above...

The other thing is that we currently don't support XML at all.

**Comment by svijetha78** [comment]
Question is : can we send xml File in request Body of the contract .

**Comment by marcingrzejszczak** [comment]
Nope, currently, you can't.
