### ISSUE TITLE
incorrect absent() in stubs

### ISSUE THREAD

**Issue by eBeyond** [spring-cloud/spring-cloud-contract#353]
The mapping from contract-files (groovydsl) to wiremock-stubs doesn't work as expected: (in case of absent())

Given:
```
    request {
        method 'GET'
        urlPath( '/some/path/*')
        headers {
            header('''Authentication''', absent())
        }
    }
```
Should result in  (wiremock-doc)
```
  "request" : {
    "urlPath" : "/some/path/*",
    "method" : "GET",
    "headers" : {
      **"Authentication" : {
        "absent" : "true"
      }**
    }
  },
```
But results in:
```
  "request" : {
    "urlPath" : "/some/path/*",
    "method" : "GET",
    "headers" : {
      **"Authentication" : {
        "equalTo" : "true"
      }**
    }
  },
```

**Comment by marcingrzejszczak** [comment]
As a workaround IMO you should just remove that header ATM since it's not required. Or is it the case that it MUST NOT be there?

**Comment by eBeyond** [comment]
Currently it doesn't have any impact on my project. I've restructured the contracts to load the catch-all contract as the last one (priority: 10000).

**Comment by marcingrzejszczak** [comment]
Ok, that's good. I understand that the tests are properly generated?

**Comment by eBeyond** [comment]
Yes, there is no problem I've seen (except this one above).

**Comment by eBeyond** [comment]
By the way: is there any positive pendant to absent() for example exists()? Or do I have to use some kind of regex?

**Comment by marcingrzejszczak** [comment]
You can use the `nonBlank()` pattern from `RegexPatterns`.
