### ISSUE TITLE
Response contains optional complex objects

### ISSUE THREAD

**Issue by rytighe** [spring-cloud/spring-cloud-contract#354]
Including basic optional elements works fine, like:

```
body([
  "status":$(optional(regex("[1-8]")))
])
```

But can I include optional complex objects, like:

```
body([
  "data":{
    $(optional(regex(number()))),
    ...
  }
])
```

If so, how to do so is unclear to me.  Thanks for your help.

**Comment by marcingrzejszczak** [comment]
I don't understand the question. Yes, you can put whatever you want in the `$(...)`. It has to compile and be available on both sides (consumer and the producer).

**Comment by rytighe** [comment]
Trying something like:
```
body([
  "eSignData":$(optional(
    "name":$(optional("Full Name")),
    "browserInformation":$(optional("Chrome"))
  ))
])
```
Leads to compilation errors: 
```
Caused by: java.lang.IllegalArgumentException: Failed to serialize object of type: class java.util.LinkedHashMap
```

**Comment by marcingrzejszczak** [comment]
What are you trying to achieve? Your code is wrong. Why are you writing `$(optional(...))` everywhere?

**Comment by marcingrzejszczak** [comment]
Not everything can be `optional(...)`. Only a primitive value can be an `optional` one. What `optional` does is that adds a regular expression to define an optional presence of a value.

**Comment by rytighe** [comment]
Unfortunately the response object model is defined as such:
```
SubmittedDraftCase {
authorizedUsersList (Array[string], optional),
created (string, optional),
draftStatus (string, optional) = ['1', '2', '3', '4', '5', '6', '7', '8'],
eSignData (EsignData, optional),
id (integer, optional),
operationalizedReceiptNumber (string, optional),
request (Form, optional),
submitedOn (string, optional),
valid (boolean, optional)
}
```
If the short answer is that the complex objects in the response can't be marked as optional, I'll accept that and keep going down another route.

**Comment by marcingrzejszczak** [comment]
If something is optional just do not put it in the contracts? If that answer doesn't satisfy you then indeed complex structures cannot be defined as optional.

**Comment by rytighe** [comment]
Understoon.  Thank you for your feedback.

**Comment by marcingrzejszczak** [comment]
No problem!

**Comment by vishalevooq** [comment]
Lets assume an example, 
```java
class Person{
  Address homeAddress;
  Optional<Address> officeAddress;
}
class Address{
  String postalCode;
}
```
How do we define a contract where home address is required and postal code must be present inside it. 
Whereas officeAddress is optional, but if present then postalCode should be not null.

**Comment by ltuch** [comment]
I was looking at a similar issue recently where I would like to model optional request fields (non primitive).

The API I am looking at has multiple non-primitive optional fields, and when certain optional request fields are provided then certain optional fields are conditionally returned by the API.

This seems difficult to model in Spring Cloud Contract. I can see a few options and each of which has some downsides.

1. Do not include the optional features in the contract. The downside of this is that the contract covers less. If there are a large number of optional fields, then the contracts aren't that expressive as they cover a small number of fields.
2. Create additional contract scenarios which cover the optional fields. The problem with this approach is that you can end up with a large number of contracts scenarios (just for the success cases) and this has a few downsides:
- multiple contract scenarios can match a request - then you need to use something like priorities to preference one contract over another one.
- if there are multiple scenarios there can be duplication between the scenarios which isn't ideal.
