### ISSUE TITLE
Very long response body

### ISSUE THREAD

**Issue by mlem** [spring-cloud/spring-cloud-contract#357]
Hi,

in my case I've got a an issue with the length of the body.
I'm trying to load more then 65k characters into body and groovy seems to have troubles with it (I hope it is a groovy limitaion and not a natural limitaion of some other system)

```
[ERROR] Exception occurred while trying to evaluate the contract at path [/home/martin/development/.../some_contract_with_very_long_body.groovy]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/home/martin/development/.../some_contract_with_very_long_body.groovy: 26: String too long. The given string is 349896 Unicode code units long, but only a maximum of 65535 is allowed.
 @ line 26, column 14.
           body('''
                ^

```

I was trying to load the body from a json file, but I can't get it to work.
Do you have some hint for me?
```

        body(
                this.getClass().getResource("/some_long_body.json").text
)

```

**Comment by marcingrzejszczak** [comment]
Currently, we don't support such long bodies. That's because on both sides of the communication (client & server) you would need to provide that file. It can come in the stubs jar but the problem is that we don't add the files from the JAR to the classpath when you download stubs at runtime. 

I'm thinking of a workaround though. You could add the stub to the classpath manually https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_classpath_scanning . Then you'll have the files on the classpath. However, you would have to provide the proper path as it is set in the jar. OTOH if you do that it will fail on the producer side. 

Anyways let's start with that.  Can you publish your project somewhere so I can play around with it?

**Comment by mlem** [comment]
Wow, thanks for that timy response.
My project is confidential. I'll try to setup an example project for that one on github.
I'll notify you whenever it's ready.

On the classpath thing: I was hoping to put it right next to the contracts, so I don't have to setup a different jar file....
But probably it will not be included into the stubs.jar unless I reconfigure the spring-cloud-contract-maven-plugin.

**Comment by marcingrzejszczak** [comment]
> I'll notify you whenever it's ready.

Sure - take your time. I could set it up myself but I think it would be better to see exactly what you have so that I can try to fix your concrete scenario.

> But probably it will not be included into the stubs.jar unless I reconfigure the spring-cloud-contract-maven-plugin.

That would exactly be the problem.

**Comment by mlem** [comment]
here you go:
https://github.com/mlem/spring-cloud-contract-issue-reproducer

In the meanwhile I'll see how to reduce the response to fit into 65k.

**Comment by marcingrzejszczak** [comment]
@mlem I've tested it locally but you can also give it a try. 

```
git clone https://github.com/spring-cloud/spring-cloud-contract.git
cd spring-cloud-contract
git checkout issues_#357_file_reference
./mvnw clean install -DskipTests -Pfast -T 8
```

That way you'll install `1.2.0.BUILD-SNAPSHOT` locally together with the new feature. Here is the PR https://github.com/spring-cloud/spring-cloud-contract/pull/360/files . Here you have an example of a contract and file reference - https://github.com/spring-cloud/spring-cloud-contract/tree/21dc23285dac8bc6cd97a48823df67a57f3c99d2/spring-cloud-contract-verifier/src/test/resources/classpath

**Comment by marcingrzejszczak** [comment]
Actually I've decided to merge that ;) Just use the latest snapshots.

**Comment by mlem** [comment]
WOW. that was fast!
thanks.
I've tried it with my repo: https://github.com/mlem/spring-cloud-contract-issue-reproducer/tree/master/src/test/resources/contracts/longresponse
it works now! Thanks!
I will give a try on our product.

**Comment by marcingrzejszczak** [comment]
Awesome! Please give it a try. I had to play with classpaths to make this work and maybe I haven't thought about something :/
