### ISSUE TITLE
in an array the last object is not allowed to have an empty array

### ISSUE THREAD

**Issue by mlem** [spring-cloud/spring-cloud-contract#361]
Hi,

I'm getting an exception, if there is a json structure with an element with an empty array.

```
[INFO] --- spring-cloud-contract-maven-plugin:1.2.0.BUILD-SNAPSHOT:generateTests (default-generateTests) @ spring-cloud-contract-issue-reproducer ---
[INFO] Generating server tests source code for Spring Cloud Contract Verifier contract verification
[INFO] Will use contracts provided in the folder [/home/martin/development/git/spring-cloud-contract-issue-reproducer/src/test/resources/contracts/parsingproblem]
[INFO] Directory with contract is present at [/home/martin/development/git/spring-cloud-contract-issue-reproducer/src/test/resources/contracts/parsingproblem]
[INFO] Test Source directory: /home/martin/development/git/spring-cloud-contract-issue-reproducer/target/generated-test-sources/contracts added.
[INFO] Using null as base class for test classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.367 s
[INFO] Finished at: 2017-07-19T13:23:17+02:00
[INFO] Final Memory: 37M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:1.2.0.BUILD-SNAPSHOT:generateTests (default-generateTests) on project spring-cloud-contract-issue-reproducer: Execution default-generateTests of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:1.2.0.BUILD-SNAPSHOT:generateTests failed: Parsed JSON [{"node":{"id":7268,"children":[{"id":7269,"children":[],"references":[{"id":7284}]},{"id":7274,"children":[],"references":[]}],"references":[]}}] with the JSON path [$.['node'].['children'][*].['references'][*]] is not empty! -> [Help 1]

```

I will post here the sample soon

is there any way to ignore the emptiness on generation?

**Comment by marcingrzejszczak** [comment]
Can you paste your contract?

**Comment by mlem** [comment]
https://github.com/mlem/spring-cloud-contract-issue-reproducer, second issue

```
org.springframework.cloud.contract.spec.Contract.make {
    request { // (1)
        method 'PUT' // (2)
        url '/fraudcheck' // (3)
        body([ // (4)
               clientId  : $(regex('[0-9]{10}')),
               loanAmount: 99999
        ])
        headers { // (5)
            contentType('application/vnd.fraud.v1+json')
        }
    }
    response { // (6)
        status 200 // (7)
        body( [
                node       : [
                        id             : 7268,
                        children           : [
                                [
                                        id             : 7269,
                                        children           : [],
                                        references: [
                                                [
                                                        id: 7284
                                                ]
                                        ]
                                ],
                                [
                                        id             : 7274,
                                        children           : [],
                                        references: []
                                ]
                        ],
                        references: []
                ]

        ]
        )
        headers { // (9)
            contentType('application/vnd.fraud.v1+json')
        }
    }
}
```

**Comment by marcingrzejszczak** [comment]
Ok I know why... That's because we use the following JSON Path

`$.['node'].['children'][*].['references'][*]` 

That `[*]` means that we assume that there will be _ANY_ entry that matches that JSON Path. In your case you have mutually exclusive values. One `references` array is empty and one is not. I guess your only way is to go with an additional `testMatchers` section and manually rule out the empty arrays.

**Comment by mlem** [comment]
thanks for that hint.
fixed by adding 
```

        testMatchers {
            jsonPath("\$.['node'].['children'][*].['references'].[*]",byType { minOccurrence(0) })
        }
```
to response in contract

**Comment by marcingrzejszczak** [comment]
Yup that's a good approach!

**Comment by mlem** [comment]
one more thing.
such a response structure still delivers a wrong test:
`
			assertThatJson(parsedJson).field("['node']").array("['children']").array("['references']").isEmpty();
`
This test ist correct for the second child, but not for the first one. so my tests are breaking.
Do I need to add for each child a testmatcher? So if there are 6 children, I need to add six times a testmatcher or how does it map?

**Comment by marcingrzejszczak** [comment]
So when you're using a test matcher it will delete all automatically created tests. So if you manually want to test an array `$.a.b` that has `c` and `d` elements, then when you create a test matcher for `$.a.b`, then you'll have to create the matching for `c` and `d` yourself.

Remember that doing `[*]` will go through all elements of the array. That's why you have to be careful how you do matching by yourself. With such a matching

```
            jsonPath("\$.['node'].['children'][*].['references'].[*]",byType { minOccurrence(0) })
```

you'll have to do a test matcher for every single child. Or you can call `byCommand` and do the assertion in the code.

**Comment by mlem** [comment]
I've got the matcher wrong.
It was something like this:
` jsonPath("\$.['node'].['children'][*].['references'][*]",byType { minOccurrence(0) })`

I shoud've done 
` jsonPath("\$.['node'].['children'][*].['references']",byType { minOccurrence(0) })`
or easier:
` jsonPath("\$.node.children[*].references",byType { minOccurrence(0) })`

With such testMatchers it doesn't generate `isEmpty` checks anymore
