### ISSUE TITLE
Use Spring CLI to run stubs locally

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#37]
For the case where the consumer wants to prototype the API it would be good for them to immediately install and run stubs from the contracts.

E.g. installing

```
spring cloud contract install /Users/path/to/contracts/ 'groupid.a.b.c' 'artifactid.d.e.f' '1.0.0.BUILD-SNAPSHOT'
```

E.g. running

```
spring cloud contract run /Users/path/to/contracts/ 'groupid.a.b.c' 'artifactid.d.e.f' '1.0.0.BUILD-SNAPSHOT'
```

**Comment by jkubrynski** [comment]
Currently you can run stubs using maven, even if you don't have pom.xml:
```
cd /tmp
mvn spring-cloud-contract-verifier:run -Dstubs="groupid.a.b.c"
```

**Comment by marcingrzejszczak** [comment]
It would be really awesome also to use `spring cloud cli` to download stub runner boot and pass some parameters to it

**Comment by simonzhong1985** [comment]
@jkubrynski  when I run "mvn spring-cloud-contract-verifier:run -Dstubs="groupid.a.b.c"" under such folder where there is no pom.xml and no contracts. Although the goal is successful, I found such log "Launching StubRunner with contracts from c:\empty_folder" and "Started stub server for project **** on port -1". as you see the port is -1, I can't access the stub runner via -1 port. Could you give me some suggestion to run stub runner via mvn?

**Comment by marcingrzejszczak** [comment]
Can you show how your contracts look like?

**Comment by simonzhong1985** [comment]
@marcingrzejszczak  Does it mean it is necessary to run "mvn spring-cloud-contract-verifier:run " under such folder it has to contain contracts?

**Comment by jkubrynski** [comment]
@simonzhong1985 it's exactly how it works but you need to use a different property. As documented [here](https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract-maven-plugin/run-mojo.html) you should pass `-Dspring.cloud.contract.verifier.stubs=com.aaa:bb`

**Comment by simonzhong1985** [comment]
@jkubrynski  thanks for your answer. It works, Now I can download stubs by -Dspring.cloud.contract.verifier.stubs=com.aaa:bb. However, It does not work by -Dspring.cloud.contract.verifier.http.port to run wiremock on assigned port.

**Comment by marcingrzejszczak** [comment]
You should pass the port in the ids `-Dspring.cloud.contract.verifier.stubs=com.aaa:bb:+:stubs:1234`. That way you'll rnu the stubs groupid `com.aaa`, artifact id `bb` , version `+` - latest, classifier `stubs`, port `1234`

**Comment by simonzhong1985** [comment]
@marcingrzejszczak  thanks. It works as I expect. Thanks again.

**Comment by simonzhong1985** [comment]
@marcingrzejszczak  Is there any update about using spring cli to run stub?

**Comment by marcingrzejszczak** [comment]
Yeah, thanks for trying it out. Thanks to you, we've got these things that popped up - https://github.com/spring-cloud/spring-cloud-contract/issues/340 and https://github.com/spring-cloud/spring-cloud-contract/issues/341 

As for the update - I haven't done any work on the spring cli. Come to think of it maybe we should stick to maven since we already have some implementation there. It's easier to download and install maven instead of installing spring cli + the cloud extension.

**Comment by marcingrzejszczak** [comment]
I think we should add the Stub Runner application to the Spring Cloud CLI project. The rest should be done via Maven

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-cli/pull/65

**Comment by GurushanthGowdar** [comment]
Hi @marcingrzejszczak  @jkubrynski ,
if I run the ` mvn spring-cloud-contract-verifier:run -Dspring.cloud.contract.verifier.stubs=com.example:SCC_producer:+:stubs:8080`

In a directory which does not have any pom.xml file I am facing the issue of the plugin.
        
_No plugin found for prefix 'spring-cloud-contract-verifier' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/gurushantha.rg/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1_
