### ISSUE TITLE
Add to the docs / readme that Jersey sample is for non boot apps

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#370]
https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/test/resources/functionalTest/sampleJerseyProject/fraudDetectionService/src/test/java/org/springframework/cloud/MvcTest.java 

we should write that this sample is an example of playing around with Jetty when you have no Spring Boot. In addition we should add a sample in spring-cloud-contract-samples of Spring Boot + JaxRS

**Comment by baraths84** [comment]
@marcingrzejszczak is there any sample which you could refer me for - spring-cloud-contract with  Spring Boot + JaxRS.Thanks

**Comment by marcingrzejszczak** [comment]
Not that I'm aware of right now. Although if that's a spring boot app that should be pretty straightforward. You can set up the plugin in EXPLICIT mode and pass the whole WebAppContext to RestAssured.

**Comment by marcingrzejszczak** [comment]
The currently suggested approach is to use the EXPLICIT mode for generating contracts.

Plugin

```
<plugin>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-contract-maven-plugin</artifactId>
				<version>${version}</version>
				<extensions>true</extensions>
				<configuration>
					<testMode>EXPLICIT</testMode>
					<!--...->
				</configuration>
			</plugin>
```

or

```
contracts {
		testMode = 'EXPLICIT'
		// ...
}
```
add some contracts and the base class:

```java
import io.restassured.RestAssured;
import org.junit.Before;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.web.server.LocalServerPort
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.context.WebApplicationContext;

@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT, classes = SomeConfig.class, properties="some=property")
public abstract class BaseTestClass {

	@LocalServerPort
	int port;

	@Before
	public void setup() {
		RestAssured.baseURI = "http://localhost:" + this.port;
	}
}
```

that way all of your requests will be really sent to your application (instead of via mock mvc).

IMPORTANT: Notice the `io.restassured.RestAssured` import and not the mock mvc one.
