### ISSUE TITLE
Spring Cloud Contract Example with JAX-RS and Spring Boot

### ISSUE THREAD

**Issue by dollarhand** [spring-cloud/spring-cloud-contract#375]
Hi,
Can we have a spring-cloud-contract example with JAX-RS and Spring Boot application.

**Comment by dollarhand** [comment]
I am able to get the Spring-cloud-contract working with JAX-RS 2.0.

**Comment by marcingrzejszczak** [comment]
That's awesome! Can you write how you did that? Post an example somewhere so that others can also use it?

**Comment by dollarhand** [comment]
Sure I will write down the example and share it. Nothing fancy though just use the @SpringBootTest to start the actual web server and load the spring boot context to load all the Jersey resources.

**Comment by AjitDas** [comment]
@dollarhand could you please share the details how did you do this, it would be great if you can put a sample project in git or if you can put some important code snippets here please

**Comment by baraths84** [comment]
@dollarhand can you please share details on the same. I am stuck on the same.

**Comment by dollarhand** [comment]
@AjitDas / @baraths84 can you please share the exact problem you are getting, not sure till when I  might be able to put in that code sample :)
