### ISSUE TITLE
Add automated support for consumer contracts

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#38]
Consumers could publish their expectations (contracts to a repo). If a consumer (let's call him `barClient`) wants a server (groupid : `a.b.c`, artifactid: `fooServer`) to behave in a certain manner he could push the contract to  some Git repository (e.g. under the folder `/a/b/c/fooServer/barClient-expectations`) or publish the jar (e.g. `a.b.c:barClient:fooServer-expectations-stubs`).

Then the server side could provide the URL of the repo or switch to JAR based approach to download the contracts / find the proper folder (e.g. `groupId/artifactId`) and generate the tests for those expectations. Only after the tests pass can the server publish its stubs. Also if your tests fail you will know ultimately which consumer you break.

cc @olivergierke

**Comment by dsyer** [comment]
I think the storage and retrieval of contracts is an implementation detail, so git and jars are two valid choices. We already use jars and maven repositories for contracts, so I would think it might be better to stick with that if we do an initial implementation of this approach. These ones are published by the consumers, so maybe the naming convention would be different - I guess a consumer would have to put all of its contracts for all producers in one jar/repo, so there needs to be some structure within the archive.
