### ISSUE TITLE
Does Spring Cloud Contract support Chinese in contract  definition?

### ISSUE THREAD

**Issue by pastel001** [spring-cloud/spring-cloud-contract#385]
My contract response definition contains Chinese like this.
description is Chinese
``` 
response {
        status 200
        body("""
            {
                "code": 91015,
                "description": "订单已失效",
                "lastUpdateTime": "0",
                "payload": null
            }
        """)
    }
```
and the generated mapping json like this
```
"response" : {
    "status" : 200,
    "body" : "{\"code\":91015,\"description\":\"\\u8ba2\\u5355\\u5df2\\u5931\\u6548\",\"lastUpdateTime\":\"0\",\"payload\":null}",
    "transformers" : [ "response-template" ]
  }
```
the description is not in chinese
So,when i acess this stub  i get the uncode as response,not the Chinese defined in contract.
So,i want to know how to set the encoding for contract file? dose it can set utf-8 encoding ?
Thank you

**Comment by marcingrzejszczak** [comment]
Hi again :)

In the main issue - https://github.com/spring-cloud-samples/spring-cloud-contract-samples/issues/17 I asked you about the following:

> Also provide more information - do the generated tests also get improperly created? Please provide the contract version, your project setup and the whole contract.

Do you think you could provide these values?

**Comment by Pastel001** [comment]
The tests generated,and description also show as unicode like this
```
DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
assertThatJson(parsedJson).field("['code']").isEqualTo(91015);
assertThatJson(parsedJson).field("['description']").isEqualTo("\u8BA2\u5355\u5DF2\u5931\u6548");
assertThatJson(parsedJson).field("['payload']").isNull();
assertThatJson(parsedJson).field("['lastUpdateTime']").isEqualTo("0");
```
spring cloud contract version is 1.1.2.BUILD-SNAPSHOT.
the whole contract is like this
```
org.springframework.cloud.contract.spec.Contract.make {
    description("""
       订单无效返回失败
    """)
    request {
        method PUT()
        url "/api/command/1"

        headers {
            contentType(applicationJson())
        }
        body(
                phoneNo: 111222333,
                orderId: 123456789)
    }
    response {
        status 200
        body("""
            {
                "code": 91015,
                "description": "订单已失效",
                "lastUpdateTime": "0",
                "payload": null
            }
        """)
    }
}
```
Thank you.

**Comment by Pastel001** [comment]
@marcingrzejszczak，hi，i have provide the info you need,what else do i need to support,thank you

**Comment by marcingrzejszczak** [comment]
I'll try to check this out as soon as possible, please be patient :)

**Comment by marcingrzejszczak** [comment]
@Pastel001 the output is perfectly valid... If you check this website https://mothereff.in/js-escapes#1%7B%22code%22%3A91015%2C%22description%22%3A%22%E8%AE%A2%E5%8D%95%E5%B7%B2%E5%A4%B1%E6%95%88%22%2C%22lastUpdateTime%22%3A%220%22%2C%22payload%22%3Anull%7D you'll see that the text is escaped. 

You check out this answer on StackOverflow https://stackoverflow.com/questions/9806246/switch-off-utf-escaping-in-jsonbuilder for more information.

**Comment by Pastel001** [comment]
it says that it is the unicode string escape sequences,and it equals with the string. 
Infact i want the Chinese can normally show, when i access the stub in the web browser

**Comment by mario45211** [comment]
Bump - I'm struggling with similar problem, where request's body contains chars beyond ASCII table...


Contract in Kotlin DSL:
```kotlin
contract {
        name = "abc"
        request {
            url = url(ENDPOINT)
            method = GET
        }
        response {
            status = OK
            body = body(
                mapOf(
                    "message" to "Nieprawidłowy parametr"
                )
            )
        }
    }
```
and generated test class has:
```java
assertThatJson(parsedJson).field("['message']").isEqualTo("Nieprawid\u0139\u201Aowy parametr");
```

Is there any know workaround to disable escaping UTF-8 chars ?

**Comment by marcingrzejszczak** [comment]
Is your kotlin file utf-8 encoded?

**Comment by mario45211** [comment]
Yes, it is, but I must apologize, because my test works perfectly now. I don't know what exactly I was doing wrong, but I doubly checked now (my station and CI server's result) and all tests are green (I probably work too long with this code...)

Thank you for your response
