### ISSUE TITLE
Using testMatchers in DSL other than byRegex adds unsolicited isEmpty check for an array

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [spring-cloud/spring-cloud-contract#391]
I have a contract:
```
Contract.make {
            final int size = 2
            final int page = 1

            request {
                name "Get list of items"
                method 'GET'
                urlPath '/item/foo?size=' + size + '&page=' + page
                headers {
                    header "accept", accept
                }
            }
            response {
                status 200
                body("""
                    {
                        "total": "${regex('\\d+')}",
                        "page": {
                            "size": "${size}",
                            "num": "${page}"
                        },
                        "items": [
                            {
                                "id": "${anyNonBlankString()}"
                                "description": "${anyNonBlankString()}"
                            }
                        ]
                    }
                """)
                testMatchers {
                    // check there is the classification element with content_group element containing any key with any value
                    jsonPath('$.items[*].classification.CONTENT_GROUPS[*]', byRegex('.+'))
                    jsonPath('$.items[*]', byType{minOccurrence(2); maxOccurrence(2)})
//                    jsonPath('$.items[*]', byCommand('myFoo($it)'))
                }
                headers {
                    header "content-type", contentType
                }
            }
        }
```
When I add the testMatcher `jsonPath(..., byRegex)`, the generated tests are ok. But adding the `jsonPath(..., byType or byCommand)` adds an unsolicited check
`assertThatJson(parsedJson).array("['items']").isEmpty();`
to the generated test source. This test fails, since the items array is obviously not empty.

Version 1.1.2.RELEASE.

**Comment by marcingrzejszczak** [comment]
Can you also paste the generated test?

**Comment by marcingrzejszczak** [comment]
Also why are you mixing both the `testMatchers` and setting some dynamic values inside the array of `items`? The tests matchers will remove any manual checks that you've done in the response body. Another thing is that it's discouraged to use dynamic entries inside a multiline GString. Try doing the same with a Groovy map notation and check if things are working in a better way.

**Comment by WhyINeedToFillUsername** [comment]
Sure. Here it is, with a pointer to the unwanted line:
```
package org.springframework.cloud.contract.verifier.tests;
import ...
public class FooTest extends FooBase {
	@Test
	public void validate_get_list_of_items() throws Exception {
		// given:
			RequestSpecification request = given()
					.header("accept", "application/...json");

		// when:
			Response response = given().spec(request)
					.get("/item/foo?size=2&page=1");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);
			assertThat(response.header("content-type")).isEqualTo("application/...json;charset=UTF-8");
		// and:
			DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			assertThatJson(parsedJson).field("['page']").field("['size']").isEqualTo("2");
			assertThatJson(parsedJson).field("['total']").matches("\\d+");
		===>	assertThatJson(parsedJson).array("['items']").isEmpty();
			assertThatJson(parsedJson).field("['page']").field("['num']").isEqualTo("1");
		// and:
			assertThat(parsedJson.read("$.items[*].classification.CONTENT_GROUPS[*]", java.util.Collection.class)).allElementsMatch(".+");
			assertThat((Object) parsedJson.read("$.items[*]")).isInstanceOf(java.util.List.class);
			assertThat(parsedJson.read("$.items[*]", java.util.Collection.class)).hasFlattenedSizeBetween(2, 2);
	}
}
```

**Comment by WhyINeedToFillUsername** [comment]
I am not using the Groovy map notation, as it is easier to copy and paste the JSON from our REST API and add the code I want it to check.
I added the testMatchers because I need to test both the structure of the response with checking the values (for a regex) and check the amount of values in the response items array.

**Comment by WhyINeedToFillUsername** [comment]
And it is the full contract, I am sorry I forgot to delete the variable "accept", I omitted the rest of the file for privacy reasons. You can just delete the headers from request and response.

**Comment by marcingrzejszczak** [comment]
Please provide concrete values over here

```
{
                                "id": "${anyNonBlankString()}"
                                "description": "${anyNonBlankString()}"
                            }
```

e.g.

```
{
                                "id": "1"
                                "description": "2"
                            }
```

and then things should be working. What you wrote makes no sense since the `testMatchers` take precedence over any matching inside the body that the matchers are checking. That means that whatever you put there will be ignored. Since you put sth it broke some other piece of code in Spring Cloud Contract. Once you set the fixed values ping me back if things are working

**Comment by WhyINeedToFillUsername** [comment]
Ok, I have tried what you suggested. First I should say I have a feeling I don't use the contracts properly. Currently we are only using them for testing the responses of our REST API, so that's why I have things like "id: $anyNonBlankStr", explicit mode in pom.xml and we don't generate the stubs.

From what I understand, the body() part in the contract with JSON is for specifying the response of the stubs and the testMatchers for verifying the response.

So, I tried as you suggested, but it still generates the isEmpty() check.

The contract:
```
package contracts.items
import org.springframework.cloud.contract.spec.Contract

Contract.make {
    request {
        name "ISSUE 391"
        method 'GET'
        urlPath '/item/factsheet?size=2&page=1'
        headers {header "accept", "application/...json"}
    }
    response {
        status 200
        body("""
                    {
                        "items": [
                            {
                                "id": "35309",
                                "title": "lorem ipsum"
                            }
                        ]
                    }
                """)
        testMatchers {
            jsonPath('$.items[*].id', byRegex(nonBlank()))
            jsonPath('$.items[*].title', byRegex(nonBlank()))
            jsonPath('$.items[*]', byType { minOccurrence(2); maxOccurrence(2) })
        }
        headers {header "content-type", "application/...json;charset=UTF-8"}
    }
}
```

And the generated test:
```
@Test
public void validate_ISSUE_391() throws Exception {
	// given:
		RequestSpecification request = given()
				.header("accept", "application/...json");

	// when:
		Response response = given().spec(request)
				.get("/item/foo?size=2&page=1");

	// then:
		assertThat(response.statusCode()).isEqualTo(200);
		assertThat(response.header("content-type")).isEqualTo("application/...json;charset=UTF-8");
	// and:
		DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
		assertThatJson(parsedJson).array("['items']").isEmpty();
	// and:
		assertThat(parsedJson.read("$.items[*].id", java.util.Collection.class)).allElementsMatch(".*(\\S+|\\R).*|!^\\R*$");
		assertThat(parsedJson.read("$.items[*].title", java.util.Collection.class)).allElementsMatch(".*(\\S+|\\R).*|!^\\R*$");
		assertThat((Object) parsedJson.read("$.items[*]")).isInstanceOf(java.util.List.class);
		assertThat(parsedJson.read("$.items[*]", java.util.Collection.class)).hasFlattenedSizeBetween(2, 2);
}
```

It does work when I use the Groovy map notation in the contract:
```
...
body([
	"items": [
		"id"   : "35309",
		"title": "lorem ipsum"
	]
])
...
```
(the generated source is the same as above, minus the line `assertThatJson(parsedJson).array("['items']").isEmpty();`).

Is that ok? I would expect the line not to be generated in the first example as well.

**Comment by marcingrzejszczak** [comment]
That's interesting... So you found the bug! As a workaround please use the Groovy Map notation and I'll look into what the problem might be with the JSON approach.

**Comment by WhyINeedToFillUsername** [comment]
Ok, thanks!

**Comment by subhashybose** [comment]
while implementing Spring Cloud Contract for Integration Testing of Micro Services, i have defined a Contract in Groovy, and compared the expected JSON response by hard coding the values in a .json file. Everything works. But, if i do want to validate dynamically without having a static json response, i found a way but i need to get the dynamic json response into a string variable from the response of a Restful endpoint invocation. Please help.

import org.springframework.cloud.contract.spec.Contract

Contract.make {

request {

method 'GET'
url '/micro-service/90640454'
headers {
    header 'Content-Type': 'application/json;charset=UTF-8'
}
} response {

status 200
headers {
    header 'Content-Type': 'application/json;charset=UTF-8'
}
-- how can i get the actual_response here
body (file('expected_response.json'))
}

**Comment by subhashybose** [comment]
Marcin Grzejszczak... any idea on this please...

**Comment by marcingrzejszczak** [comment]
I completely don't understand what you want to achieve and I don't know why you're commenting on a random issue with completely irrelevant information. Please file a stackoverflow question or ask on the gitter chat

**Comment by subhashybose** [comment]
I have already created a new question, but as i do not see any quick
responses... i thought i could post it in somewhat related post. sorry for
the confusion.
below is the link to my post.
https://stackoverflow.com/questions/53857831/how-can-i-get-print-the-json-response-from-a-restful-service-call-in-groovy-with
this is related to implementation of spring cloud contract with groovy.
please help.

**Comment by marcingrzejszczak** [comment]
Please do not cross post.

**Comment by subhashybose** [comment]
Sure, can you please respond as I need to resolve this sooner, appreciate
your help.

Thanks

**Comment by marcingrzejszczak** [comment]
The question has already been answered. Please do not comment in this closed one.
