### ISSUE TITLE
Documentation: unclear information on checking the size of a collection using byType() testMatcher

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [spring-cloud/spring-cloud-contract#393]
From doc:

> byType() - the value taken from the response via the provided JSON Path needs to be of the same type as the type defined in the body of the response in the contract. byType can take a closure where you can set minOccurrence and maxOccurrence. That way you can assert on the size of the collection.

I would assume the check will be for the size of the collection (e.g. size of an ArrayList), but the generated tests use `hasFlattenedSizeBetween(lowerBound, higherBound)`.

I suggest you add that to the documentation ("This check the size of the flattened collection. To check the size of unflattened collection, e.g. an ArrayList, use a custom method via `byCommand` testMatcher.").

**Comment by marcingrzejszczak** [comment]
Are you willing to file a PR with the fix? If that's the case could you please file the PR against `1.1.x` branch and I'll merge it to `master` and `2.0.x`

**Comment by WhyINeedToFillUsername** [comment]
Ok, I'll try.

**Comment by WhyINeedToFillUsername** [comment]
https://github.com/spring-cloud/spring-cloud-contract/pull/394
