### ISSUE TITLE
a question about BaseClass config in the pom of producer

### ISSUE THREAD

**Issue by Pastel001** [spring-cloud/spring-cloud-contract#396]
env：
spring cloud contract version is 1.1.2.BUILD-SNAPSHOT.
question:
My contract is under the package com.example.he.rest.vehicle
When i config my baseClassMappings use regex ".*rest\\.vehicle.*" ,like this
```
                    <baseClassMappings>
                        <baseClassMapping>
                            <contractPackageRegex>.*rest\.vehicle.*</contractPackageRegex>
                            <baseClassFQN>com.example.VehicleRestBase</baseClassFQN>
                        </baseClassMapping>
                    </baseClassMappings>
``` 
the generated test dont have the code which extends the  base class VehicleRestBase 
I want to know how to exact match the the dot in the baseClassMappings setting?

**Comment by marcingrzejszczak** [comment]
Please check this section of the documentation http://cloud.spring.io/spring-cloud-static/Dalston.SR2/#_different_base_classes_for_contracts_2 and this example (https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/44c383a2e712890a286331ddf3b55826ea658ba1/producer_with_external_contracts/pom.xml) .

**Comment by Pastel001** [comment]
Yes，i know how to set the base class.
if i ues the regex like this ".*rest.*vehicle.*, the the generated test will extends the base class VehicleRestBase.
i just want to know why i cant use ".*rest\.vehicle.*" to exact match the dot?

**Comment by marcingrzejszczak** [comment]
Hmm maybe it's the matter of XML ? Try setting `&#92;` instead of `\`

**Comment by Pastel001** [comment]
set it like this 
```
  <contractPackageRegex>.*rest&#92;.vehicle.*</contractPackageRegex>
```
it does not work,still have no extends code

**Comment by marcingrzejszczak** [comment]
ok then and what if you change the `.` to `\\.` ?

**Comment by Pastel001** [comment]
not work too
i have try a lot of case, all not work but use ".*"
it is not exact match the dot,but it is to match all
infact it can meet most of scense

**Comment by marcingrzejszczak** [comment]
The string there is treated like a normal regular expression. I didn't check this myself but I guess it's pretty safe for you to use `.` .

**Comment by Pastel001** [comment]
yes,i will use ```.*``` instead.
Thank you
