### ISSUE TITLE
Use wiremock-standalone instead of "ambient" server

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-contract#397]
Recent versions of Wiremock relocate Jetty in the "standalone" jar, so it wouldn't clash with anything on the classpath in Spring Boot any more. We could probably remove a bunch of code in Spring Cloud Contract Wiremock if we use that as a dependency.

**Comment by marcingrzejszczak** [comment]
Related to https://github.com/spring-cloud/spring-cloud-contract/issues/146 ?

**Comment by dsyer** [comment]
It would make #146 redundant.
