### ISSUE TITLE
java.lang.ClassCastException in WireMockRestTemplateConfiguration

### ISSUE THREAD

**Issue by mnovoseltsev** [spring-cloud/spring-cloud-contract#399]
Hi Guys,

I have started using spring-cloud-contract-wiremock and I have spotted following issue.

Given:
Ordered with higher than lowest precedence RestTemplateCustomizer that adds interceptor to RestTemplate;
test with `@AutoConfigureHttpClient` or `@AutoConfigureWireMock` annotation

When:
`org.springframework.cloud.contract.wiremock.WireMockRestTemplateConfiguration#restTemplateCustomizer` invoked

Then:
Following exception thrown:

```
> java.lang.ClassCastException: org.springframework.http.client.InterceptingClientHttpRequestFactory cannot be cast to org.springframework.http.client.HttpComponentsClientHttpRequestFactory
> 
> 	at org.springframework.cloud.contract.wiremock.WireMockRestTemplateConfiguration$1.customize(WireMockRestTemplateConfiguration.java:47)
```

Issue related to the fact that if at least any interceptor added to `RestTemplate` then `RestTemplate` -> `org.springframework.http.client.support.InterceptingHttpAccessor#getRequestFactory` method returns wrapped request factory -> `org.springframework.http.client.InterceptingClientHttpRequestFactory`. But `org.springframework.cloud.contract.wiremock.WireMockRestTemplateConfiguration#restTemplateCustomizer` expects `org.springframework.http.client.HttpComponentsClientHttpRequestFactory` and casts without any checking:

```java
			@Override
			public void customize(RestTemplate restTemplate) {
				HttpComponentsClientHttpRequestFactory factory = (HttpComponentsClientHttpRequestFactory) restTemplate
						.getRequestFactory();
				factory.setHttpClient(createSslHttpClient());
			}
```

You can find demo project here -> https://github.com/mnovoseltsev/spring-contract-wiremock-issue-demo

**Comment by marcingrzejszczak** [comment]
Thanks, @mnovoseltsev for this great issue description. Thanks to this I could very easily replicate the problem and fix it in no time. Great job!

**Comment by mnovoseltsev** [comment]
Hi @marcingrzejszczak , not at all. I always glad to help. I have one more interesting case, I think I will post it nearest time.

**Comment by mnovoseltsev** [comment]
Hi @marcingrzejszczak , I was thinking about this a bit and found out that maybe it would be a good idea to remove `@AutoConfigureHttpClient` annotation from `@AutoConfigureWireMock` one? Currently this is going out of the box and it might spoil someone configs by overriding HttpClient. For example if we want to have custom http client with let's say disabled cookie management, then in some cases it may be overridden by \@AutoConfigureHttpClient rest template customizer. What do you think ? For sure here is also a possibility to use junit rules, but it will not allow to share wiremock server instance between test suits.

**Comment by marcingrzejszczak** [comment]
@mnovoseltsev maybe let's start a new issue and discuss it there? Could you create one please?

**Comment by mnovoseltsev** [comment]
@marcingrzejszczak FYI -> here it is https://github.com/spring-cloud/spring-cloud-contract/issues/413

**Comment by marcingrzejszczak** [comment]
Thanks!
