### ISSUE TITLE
Input message verification from consumer side

### ISSUE THREAD

**Issue by shankaryeshala-vce** [spring-cloud/spring-cloud-contract#400]
Do we have a way to test the input message contract from consumer side if producer changes input message body.

We use only stubTrigger.trigger("label"); to test from consumer side but how does consumer know that if the producer changes input message contract? Consumer test case seems to be passing for me always even producer changes input contract.

**Comment by marcingrzejszczak** [comment]
You have asked this question already on Stackoverflow (https://stackoverflow.com/questions/45973309/spring-cloud-contract-testing-input-message-validation/45973781?noredirect=1#comment78918509_45973781), please don't cross post
