### ISSUE TITLE
Bug in the spring-cloud-contract-gradle-plugin v1.1.3.RELEASE

### ISSUE THREAD

**Issue by chris-masterdev** [spring-cloud/spring-cloud-contract#402]
Hello,
I'm using the spring-cloud-contract on a gradle project and I aim to generate a contract for an async web-service.

Here are the dependencies I use.

```
dependencies {
        ...
        classpath "org.springframework.cloud:spring-cloud-contract-gradle-plugin:1.1.3.RELEASE"
}
apply plugin: 'spring-cloud-contract'

dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-contract-dependencies:1.1.3.RELEASE'
    }
}
```

I can have the plugin generate the contract tests using the async() method from the groovy DSL, but it seems that the `fixedDelayMilliseconds()` DSL method does not work as I would expect.

Here is my groovy contract file.

```
...
response {
        status 200
        async()
        fixedDelayMilliseconds(10000)
        body([
...
```

And here is the generated test.
...

```
// when:
			ResponseOptions response = given().spec(request)
					.when().async()
					.post(...
```

The plugin does not make use of the `fixedDelayMilliseconds(10000)` and does not add the expected `.timeout(10000)` in the generated unit test code.

So my test fails with a timeout error : "...  throws

```
 java.util.concurrent.ExecutionException,java.lang.InterruptedException] was not set during the specified timeToWait=1000"
```

If I add the `.timeout(10000)` in the unit test code myself then the test passes.

Would you please take a look at that issue in the gradle plugin as it seems there is a bug there ?

**Comment by marcingrzejszczak** [comment]
Thanks for the issue! I've updated your text with proper formatting. Thanks a lot for the extensive description. I actually think that the bug is there also for the Maven plugin. With the data you've provided it should be easy to reproduce!

**Comment by marcingrzejszczak** [comment]
The fix works currently only for the RestAssured based communication. So JaxRs case won't work.

**Comment by chris-masterdev** [comment]
Thank you!

**Comment by marcingrzejszczak** [comment]
No problem, could you test the snapshots in your spare time?

**Comment by chris-masterdev** [comment]
I could make sure it does work now when using both the gradle and maven plugins with version 1.1.4.BUILD-SNAPSHOT.
Good job! Thanks again!
