### ISSUE TITLE
Support for Pact v3

### ISSUE THREAD

**Issue by eschnou** [spring-cloud/spring-cloud-contract#406]
Current implementation supports the Pact v2 format, using pact-jvm 2.4.18. There is however a newer format that introduces additional features such as new matcher format, new query parameters format and matching on query parameters.

https://github.com/pact-foundation/pact-specification/blob/version-3/README.md

I'm in particular interested in using matchers on query parameters. For example being able to write:

```
"matchingRules": {
  "query": {
    "id": {
        "matchers": [
          { "match": "regex", "value": "[0-9]{5}" }
        ]
    }
  }
}
```

Pact v3 is already supported by latest pact-jvm. I've tried to simply update the pact-jvm field to another version but it seems this is not sufficient. Is there a way to support Pact v3 or does it also require code changes in spring-cloud-contract ?

**Comment by marcingrzejszczak** [comment]
That's a very interesting issue! Thanks for filing it... So we already support query parameters from what I see (https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-tools/spring-cloud-contract-spec-pact/src/main/groovy/org/springframework/cloud/contract/verifier/spec/pact/PactContractConverter.groovy#L61) but not with matchers. It seems that it will require not change of the code but actually introducting new one if Pact v3 is not compatible with Pact v2 (or is it?).

So what you should do in my opinion is to write your own support for Pactv3 and file a PR back to Spring Cloud Contract :) Thanks to the pluggable architecture (http://cloud.spring.io/spring-cloud-static/Dalston.SR3/#_custom_contract_converter) you don't have to wait for me to implement anything and you can do it yourself. What I suggest is to copy the class and the test, modify it to the Pact v3 format and it's enough for you to create a file in `src/main/resources/META-INF/spring.factories` with your class (https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-tools/spring-cloud-contract-spec-pact/src/main/resources/META-INF/spring.factories#L1-L2) . Then once you have the JAR on the classpath it will be automatically picked up.

**Comment by eschnou** [comment]
Thanks Marcin! I'll have a look at implementing the V3 support as you suggest.

**Comment by marcingrzejszczak** [comment]
Any luck? @eschnou ? :)

**Comment by TYsewyn** [comment]
@spencergibb @marcingrzejszczak I'm currently trying to upgrade Pact to version 3.5.13.
A lot has changed over time. Will keep you guys posted on the status of the upgrade!

**Comment by marcingrzejszczak** [comment]
great! @TYsewyn  please keep us posted

**Comment by TYsewyn** [comment]
PR to track the implementation can be found here: #569!

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/pull/569
