### ISSUE TITLE
Use array instead of CSV string for list of stubs to run

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-contract#41]

**Comment by dsyer** [comment]
Fixed ac873f9

**Comment by marcingrzejszczak** [comment]
Remember that there was an option to pass the list as a system prop. That's
why I didn't implement that as a list from the beginning

**Comment by dsyer** [comment]
I think that should still work in a Boot app (even though I think it's a bad idea to encourage it). I only changed the behaviour there.
