### ISSUE TITLE
Http Client override issue

### ISSUE THREAD

**Issue by mnovoseltsev** [spring-cloud/spring-cloud-contract#413]
Hi Guys,

I was thinking about `org.springframework.cloud.contract.wiremock.WireMockRestTemplateConfiguration#restTemplateCustomizer` a bit and found out that maybe it would be a good idea to remove `@AutoConfigureHttpClient` annotation from `@AutoConfigureWireMock` one? Currently this is going out of the box and it might spoil someone configs by overriding HttpClient. For example if we want to have custom http client with let's say disabled cookie management, then in some cases it may be overridden in tests by `@AutoConfigureHttpClient` rest template customizer. What do you think ? For sure there is also a possibility to use junit rules, but it will not allow to share wiremock server instance between test suits.

P.S: I am not quite familiar with whole Spring-Cloud-Contract infra, so maybe I do not see full picture and why `@AutoConfigureHttpClient` might be important to have bound to `@AutoConfigureWireMock`. Also would be nice to discuss the reason of having integration tests using https.

You can find example test here -> https://github.com/mnovoseltsev/spring-contract-wiremock-issue-demo/blob/master/src/test/java/spring/contract/wiremock/issue/demo/HttpClientOverrideTest.groovy

**Comment by marcingrzejszczak** [comment]
@mnovoseltsev it took some time but with `2.0.0` you'll be able to set the `wiremock.rest-template-ssl-enabled: false` and the customizer will not be applied

**Comment by mnovoseltsev** [comment]
@marcingrzejszczak Great, thanks
