### ISSUE TITLE
Contract converted to Pact v2 are not valid

### ISSUE THREAD

**Issue by eschnou** [spring-cloud/spring-cloud-contract#414]
In the current [Pact V2 specification](https://github.com/pact-foundation/pact-specification/tree/version-2), matchers on body must be expressed with a json path starting with `$.body`. For example:

```
"matchingRules": {
    "$.body[0][*].id": {
        "regex": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
    }
}
```

In the current implementation, the **body** string is omitted, as seen in the [test example](https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-tools/spring-cloud-contract-spec-pact/src/test/groovy/org/springframework/cloud/contract/verifier/spec/pact/PactContractConverterSpec.groovy#L179):

```
"matchingRules": {
    "$[0][*].id": {
        "match": "regex",
        "regex": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
 }
```

**Comment by marcingrzejszczak** [comment]
Lame mistake, sorry about that :/

**Comment by eschnou** [comment]
That was quick :-) No worries, probably an easy fix. One of the issue is that there is no formal specification of Pact. It would be helpful if they had a json-schema of the Pact spec. I'v however not seen such a document yet.

**Comment by marcingrzejszczak** [comment]
I agree - I had a very difficult time analyzing their code. Anyways like you said the fix will be quick :)
