### ISSUE TITLE
Getting errorCode 404 in response when requesting URL in encoded form

### ISSUE THREAD

**Issue by p03sinha** [spring-cloud/spring-cloud-contract#416]
I have created a service stub which contains following contract:

```
{
 "uuid" : "518fb81c-6356-444d-8029-0b1e9b539a28",
 "request" : {
 "urlPath" : "api/v11.0/ingressv2dm/metadata/?_filter=%5B%7B%22eClass%22%3A%7B%22name%22%3A%22TenantModel%22%7D%2C%22features%22%3A%5B%22guid%22%5D%7D%5D",
 "method" : "GET",
 "headers" : {
 "X-INFA-USER-NAME" : 
{ "matches" : "(\\w+)?" } 
,
 "X-INFA-USER-ID" : 
{ "matches" : "(\\w+)?" } 
,
 "X-INFA-ORG-ID" : 
{ "equalTo" : "ingressv2dm" } 
,
 "Content-Type" : 
{ "matches" : "application/json.*" } 
}
 },
 "response" : {
 "status" : 200,
 "body" : "
{\"eClass\":\"http://informatica.com/mdm/v2/Core#//TenantModel\",\"guid\":\"datamodel.demo.party\"} 
"
 }
 }
```

When try to access the url `api/v11.0/ingressv2dm/metadata/?_filter=%5B%7B%22eClass%22%3A%7B%22name%22%3A%22TenantModel%22%7D%2C%22features%22%3A%5B%22guid%22%5D%7D%5D`, it says "The requested resource is not available." and errorCode=404

1. Is the encoded URL in contract sub supported? How could I resolve this?

**Comment by marcingrzejszczak** [comment]
Have you added all the headers to the request too? Can you show the curl command that you use to access this resource?

**Comment by p03sinha** [comment]
Invoked GET api with the following details:

URI: http://10.75.141.46:33124/api/v11.0/ingressv2dm/metadata/?_filter=%5B%7B%22eClass%22%3A%7B%22name%22%3A%22TenantModel%22%7D%2C%22features%22%3A%5B%22guid%22%5D%7D%5D
Headers: X-INFA-USER-NAME:dummy
		 X-INFA-USER-ID:dummy
		 X-INFA-ORG-ID:ingressv2dm

**Comment by marcingrzejszczak** [comment]
You're missing content type...

**Comment by p03sinha** [comment]
![getapiresponse](https://user-images.githubusercontent.com/14883548/30106751-22021aee-931a-11e7-9005-ae913f81d6bd.png)

Refer the attached image for header details.

**Comment by marcingrzejszczak** [comment]
How do you run these stubs? Can you try with the latest snapshots Edgware (1.2.0 version of contract) snapshots? You will get a lot of WireMock's info logs to help see why it's not able to match the request

**Comment by p03sinha** [comment]
Thanks for the reply. Will try this.

**Comment by marcingrzejszczak** [comment]
Any luck @p03sinha ?

**Comment by marcingrzejszczak** [comment]
Closing due to inacticity
