### ISSUE TITLE
How to deal with the MAVEN version problem

### ISSUE THREAD

**Issue by earayu** [spring-cloud/spring-cloud-contract#418]
My company is using maven version of 3.0.5 in jekins. For spring-cloud-contract-maven-plugin, it requires maven version of 3.2.5。 

How Can I Use spring-cloud-contract if my maven version is below 3.2.5。 
Should I change the <prerequisites><maven>3.0.5</maven></prerequisites> and re-compile it myself?
Or there's a better solution?

Thanks.

**Comment by marcingrzejszczak** [comment]
The best solution is to bump Maven. You shouldn't be using such an old version.

If you can't bump the plugin version just use the Maven Wrapper (https://github.com/takari/maven-wrapper) and then your project will control the Maven version.

If you can't do it either your last resort is to alter the source code to lower the maven plugin version prerequisite but I have no idea if that won't affect the features.
