### ISSUE TITLE
Can we use different URL Matching Patterns (f.e. urlPattern)?

### ISSUE THREAD

**Issue by ryandegruyter** [spring-cloud/spring-cloud-contract#419]
Related: https://github.com/spring-cloud/spring-cloud-contract/issues/22

We were looking for a way to define optional URL Request parameters. But with queryParameters you can only define optional values, and not optional elements:

For example:
```
========
CONTRACT
========
Contract.make {
    request {
        method 'GET'
        urlPath('/v1/sessions/search',) {
            queryParameters {
                parameter 'environment': $(optional(regex(nonEmpty())))
            }
        }
    }
    response {...}
}


=====
STUB
=====
{
  "request": {
    "urlPattern": "/v1/sessions/search",
    "method": "GET",
    "queryParameters": {
      "environment": {
        "matches": "(.+)?"
      }
    },
    "response": {...}
}
```

The query parameter **value** is optional, 
but you still need to provide the query parameter **name** for the url to match.

A solution would be to use URL Request matching
http://wiremock.org/docs/request-matching/#url-matching
Wiremock supports a variety of url matchers.

Correct me if I'm wrong but I believe Spring Cloud Contracts only supports url() and urlPath().
Is it possible to define regex patterns in our groovy contracts for the request URL?

For example:
```
========
CONTRACT
========
Contract.make {
    request {
        method 'GET'
        urlPattern('/v1/sessions/search(.+)?')
    }
    response {...}
}


=====
STUB
=====
{
  "request": {
    "urlPattern": "/v1/sessions/search(.+)?",
    "method": "GET",
    "queryParameters": {
      "environment": {
        "matches": "(.+)?"
      }
    },
    "response": {...}
}

**Comment by marcingrzejszczak** [comment]
Yeah, you can do it via `urlPattern` with a regular expression. You can also create 2 different contracts (which I think is a more descriptive approach). One with and one without the query parameter. IF you check out the docs you will see examples of regular expressions in the URL (https://cloud.spring.io/spring-cloud-contract/multi/multi__contract_dsl.html#_regular_expressions)

**Comment by ryandegruyter** [comment]
Oh wow, sorry I completely missed that in the docs. Thanks for the quick reply! I'll try it out :)

And yes, multi contracts is also a good idea 👍
