### ISSUE TITLE
Spring 5 and WebTestClient support

### ISSUE THREAD

**Issue by YumingHe** [spring-cloud/spring-cloud-contract#422]
Hi,

Spring 5 uses WebClient (instead of RestTemplate) for async web request, which MockMVC does not support. It will be great if we can add support for WebTestClient in the generated tests in place of MockMVC for Spring 5.

Thanks,
Peter

**Comment by marcingrzejszczak** [comment]
Hi @YumingHe . So, as a workaround, to work with Spring 5 you'd have to turn on the `EXPLICIT` mode. That way you don't use the mocked API.

**Comment by SystemOutPrint** [comment]
Do you want add some documents or samples?
