### ISSUE TITLE
False positive in consumer tests on required missing header (matching multiple contracts)

### ISSUE THREAD

**Issue by alefr** [spring-cloud/spring-cloud-contract#424]
Hi,

We have the case where we have two different outcomes on the producer side depending on a header that gets passed in.

A simplified sample with two contracts:

With consumer header
```
org.springframework.cloud.contract.spec.Contract.make {
    request {
        method 'POST'
        url '/distributionchannel'
        headers {[
                    header("consumer", $(regex('[a-z0-9]{10}')))
        ]}
        body([...])
    }
    response {
        status 201
        headers { ... }
        body([...])
    }
}
```

Without consumer header
```
org.springframework.cloud.contract.spec.Contract.make {
    request {
        method 'POST'
        url '/distributionchannel'
        headers {[
        ]}
        body([...])
    }
    response {
        status 400
        headers { ... }
        body([...])
    }
}
```

The problem is that on the consumer side a request with the _consumer_ header matches both requests as it doesn't care if it's there or not when missing in the generated wiremock file.

Is there any way to do this?

I found this: #353 
and tried to produce the following contract:

Without consumer header
```
org.springframework.cloud.contract.spec.Contract.make {
    request {
        method 'POST'
        url '/distributionchannel'
        headers {[
            header("consumer", absent())))
        ]}
        body([...])
    }
    response {
        status 400
        headers { ... }
        body([...])
    }
}
```
The problem is that now the producer side doesn't verify correctly as "true" is placed as consumer header value (on the producer side, the consumer side does works fine if I force it through the producer side).

Am I using absent() correcly, or is there any other way of achieving what I'm aiming for?
Is there a guide to the actual DSL used for contracts? I haven't found one and is currently scavenging the source code for clues :)

Thanks

**Comment by marcingrzejszczak** [comment]
You can check out the `priority` method (http://cloud.spring.io/spring-cloud-static/Dalston.SR3/#_http_top_level_elements) . You have 2 contracts. One is a set of the other. It's up to you to define that the less concrete one (without a header) has a higher value of the `priority` e.g. `priority(10)` whereas the more concrete one (with header) has a lower value of the `priority` e.g. `priority(5)`. That way when a request arrives and 2 stubs are matching, then WireMock will pick the one with the lower value of the priority.

**Comment by alefr** [comment]
Thanks for Quick response,
Yes, I found that as well and figured that this will probably solve our case, so that we'll be able to move on.

But if that's the case I interpret it as there is no way of marking the header as truely absent on both producer and consumer side?

I mean it works for us now as we can match against another contract, but if we only had one and wanted to put absent on both producer and consumer side, it wouldn't pass validation with absent()?

**Comment by marcingrzejszczak** [comment]
Just don't put the value in the contract. Why do you want to ensure that the header is there? 

If you must ensure that the header is absent, you can actually make it the other way round. Create a contract with the header and ensure that the return status code is invalid or sth.

Also you can try to use the `matchers` section with max occurrence `0` (http://cloud.spring.io/spring-cloud-static/Dalston.SR3/#_dynamic_properties_in_matchers_sections)

**Comment by alefr** [comment]
If I don't put the value in the contract, we will have a match on the consumer side when the header is present in the call (which we don't want).

A problem with the priority approach is that I need to know and get a dependency between my contracts (maybe that's inevitable), but as we are different teams (a few consumers and us as a producer) working on the contracts and someone were to remove one of the contracts, we would get a match in wiremock on the consumer side which we don't want.

I'm fairly new to CDC as a whole and spring-cloud-contract in general and maybe I'm reasoning about this the wrong way. But the way I see it is that if I put `absent()` in the contract header and it gets matched on the consumer side only if the header is actually absent, shouldn't that be the case on the producer side as well?
As it is right now it produces a test with has the header value "true" for the header marked as absent.

Thanks, I will have a look at the matchers section.

**Comment by marcingrzejszczak** [comment]
> If I don't put the value in the contract, we will have a match on the consumer side when the header is present in the call (which we don't want).

I don't understand this requirement to ensure that the header is not there. If you put priorities then you create 2 contracts. One has the header (higher priority) resulting in 4xx status, one doesn't (lower priority) resulting in 2xx status. Either it's as simple as that or I don't understand sth.

> A problem with the priority approach is that I need to know and get a dependency between my contracts (maybe that's inevitable)

IMO it's inevitable (maybe we could an analysis of contracts and produce a warning but that would be very hard to do). WireMock (the HTTP server stub) has two matching contracts and needs to pick one. You can't skip it.

> But the way I see it is that if I put absent() in the contract header and it gets matched on the consumer side only if the header is actually absent, shouldn't that be the case on the producer side as well?

`absent()` means that the *value is absent*. Not that the header is absent. 

If you want to ensure that the whole header is absent you should try with matchers IMO.

**Comment by alefr** [comment]
> I don't understand this requirement to ensure that the header is not there. If you put priorities then you create 2 contracts. One has the header (higher priority) resulting in 4xx status, one doesn't (lower priority) resulting in 2xx status. Either it's as simple as that or I don't understand sth.

Yes, using priorities is fine in our case as it solves the initial problem (hadn't found priorities when I first posted). If it was possible to solve it without priorities it would be a better solution as we see it (as explained earlier), but if it doesn't exist, then that is the way we will go.

> IMO it's inevitable (maybe we could an analysis of contracts and produce a warning but that would be very hard to do). WireMock (the HTTP server stub) has two matching contracts and needs to pick one. You can't skip it.

See the answer above. It is true that if there is two matching wiremock cases than we need to use priorities. But if it didn't generate two cases that both matches then that would have been a better path (I explain a little but more about this below regarding `absent()`).

> absent() means that the value is absent. Not that the header is absent.

Ah, of course, that makes sense as it's in the value field. That's a bad on my side.

But even if that's the case a missing valute on the producer side would generate a test case that passes a producer test. Right now it produces a header value with "true" on the producer which doesn't conform to our consumer stub that sets the header to absent: true

This might only be in our case but if `absent()`didn't put any value in the header on the producer side it would do what we expect it to as it's handled the same way as a completely missing header.

Of course that would mean producing tests for completely missing header as well but that's a separate case and we're fine using priorities for that if it's the only way to go.

**Comment by marcingrzejszczak** [comment]
I think that the priorities are the way to go. Do you think we can close this issue then?

**Comment by alefr** [comment]
Yes, we can close it, but just to understand better:

Is there a reason that `absent()` produces a value in the header with **true**. Doesn't this create a missmatch between the generated test on the producer side and the generated stub (wiremock file) on the consumer side?

**Comment by marcingrzejszczak** [comment]
> Is there a reason that absent() produces a value in the header with true

I don't understand this statement. Where do you have the `true` value? Can you paste that piece of code that produces `true` ?

**Comment by alefr** [comment]
If I have this contract:
```
package contracts.mytest

import org.springframework.cloud.contract.spec.Contract

org.springframework.cloud.contract.spec.Contract.make {
	request {
		method 'GET'
		url '/mytest'
		headers {
			header('myheader', absent())
		}
	}
	response {
		status 200
	}
}
```
Then the generated test case on the producer side looks like:

```
@Test
public void validate_shouldReturnHeader() throws Exception {
	// given:
		MockMvcRequestSpecification request = given()
				.header("myheader", "true");
		// when:
		ResponseOptions response = given().spec(request)
				.get("/mytest");
		// then:
		assertThat(response.statusCode()).isEqualTo(200);
}
```

Which means that the header value of _myheader_ isn't really absent?

**Comment by marcingrzejszczak** [comment]
That actually looks like a bug. Can you show the stub?

**Comment by alefr** [comment]
Ah, ok, I thought it was by design and there was something I was missing.

Yes, the stub looks like:
```
{
  "id" : "9e1d403c-abfa-4b09-bff5-ebb0e67991ef",
  "request" : {
    "url" : "/mytest",
    "method" : "GET",
    "headers" : {
      "myheader" : {
        "absent" : true
      }
    }
  },
  "response" : {
    "status" : 200,
    "transformers" : [ "response-template" ]
  },
  "uuid" : "9e1d403c-abfa-4b09-bff5-ebb0e67991ef"
}
```
So the stub looks like expected and thus the reason for the missmatch between producer and consumer.
