### ISSUE TITLE
Wrong parsing of execute command

### ISSUE THREAD

**Issue by adamkrol93** [spring-cloud/spring-cloud-contract#428]
I have following contract definition
```Contract.make {
    request {
        method 'GET'
        urlPath(...)
    }
    response {
        status 200
        headers {
            header 'Content-Type': value(test(regex('application/json(;.*)?')), stub('application/json;charset=UTF-8'))
        }
        body(
                orderResponses: [[
                                         ...
                                         creationDate         : execute('currentDate("yyyy-MM-ddTHH:mm:ssZ")')
                                          ...
                                 ],
                                 [
                                         ...
                                         creationDate         : execute('currentDate("yyyy-MM-ddTHH:mm:ssZ")'),
                                         ...
                                 ]]
        )
        testMatchers {
            jsonPath('$.orderResponses', byType())
        }
    }
}
```

When requesting response from correct endpoint i get response as follows 
````
{"orderResponses":[{...
"creationDate":{"executionCommand":"currentDate(\"yy-MM-ddTHH:mm:ssZ\")"}
...]}
```

**Comment by marcingrzejszczak** [comment]
You are not wrapping the execute in `$(...)` or `$(value(...))`. You have to also provide the `consumer` part when working with `execute`. Please read the documentation on how to use the `execute(...)` method - http://cloud.spring.io/spring-cloud-static/Dalston.SR3/#_executing_custom_methods_on_server_side

**Comment by adamkrol93** [comment]
Wraping in $ does not work either.
```
$(stub(execute('currentDate("yyyy-MM-ddTHH:mm:ssZ")')), test("2017-09-28T12:25:00Z"))
```

Still returns 

```
"creationDate":{"executionCommand":"currentDate(\"yyyy-MM-ddTHH:mm:ssZ\")"}
```

**Comment by marcingrzejszczak** [comment]
Please read the documentation carefully. Check out the heading title 

http://cloud.spring.io/spring-cloud-static/Dalston.SR3/#_executing_custom_methods_on_server_side

_Executing custom methods on_ **server side**

You are trying to execute a custom method for the stub. If you want the stub to contain the current date just type

`$(stub(new Date().format("yyyy-MM-ddTHH:mm:ssZ")), test("2017-09-28T12:25:00Z"))`

**Comment by marcingrzejszczak** [comment]
There's currently no way to do that. Your contract tests should not depend on the value of that date.
