### ISSUE TITLE
Wiremock exclusions in BOM breaks clients of the BOM that are using Wiremock

### ISSUE THREAD

**Issue by greenbird-chr** [spring-cloud/spring-cloud-contract#432]
Clients of the cloud-contract BOM that depends on Wiremocks default dependencies to httpclient, jetty etc. breaks when importing the cloud-contract BOM since those dependencies are excluded in dependency management there.

I do not know if those exclusions are left over from the Wiremock 1.x dependency where they were needed or if cloud-contract actually needs them. If they are needed it would be better if cloud-contract added those exclusions where the Wiremock dependencies are used internally to avoid affecting clients of the BOM.

**Comment by dsyer** [comment]
Which version of Spring Cloud Contract are you using? The jetty etc. dependencies actually come from Spring Boot, so you shouldn't see anything from here.

If you switch to 1.3.x (not yet GA) we aren't using that wiremock library (we use the standalone version which doesn't depend on jetty etc.).

Do you have a simple sample app you can share?

**Comment by greenbird-chr** [comment]
Sorry. Forgot to say: version 2.0.0.M2
The exclusions in the BOM can be seen here:
https://github.com/spring-cloud/spring-cloud-contract/blob/v2.0.0.M2/spring-cloud-contract-dependencies/pom.xml

**Comment by dsyer** [comment]
Not there in snapshots: https://github.com/spring-cloud/spring-cloud-contract/blob/2.0.x/spring-cloud-contract-dependencies/pom.xml

**Comment by greenbird-chr** [comment]
Ok. Thanks.
