### ISSUE TITLE
generate Wiremock proxy stub out of a contract

### ISSUE THREAD

**Issue by wizison** [spring-cloud/spring-cloud-contract#433]
currently we are working on some new parts for our API and we want use the Wiremock proxy functionality, but unfortunately that will not work.

we want to generate a stub which looks like this:
`
{
  "priority": 10000,
  "request": {
    "method": "GET",
    "urlPattern": "/restapi/.*"
  },
  "response": {
    "proxyBaseUrl" : "http://10.10.10.10/restapi"
  }
}
`

our goal is to stub the new things for our apps and use the old things (auth key exchange, user key exchange, etc.) of the current dev system.

is there a way to get this behavior with a contract?

**Comment by marcingrzejszczak** [comment]
Currently, there's no way to achieve this out of the box on the producer side. You'd have to override the way stubs are generated. 

What you can do however is to use `@AutoConfigureWireMock` and create that particular stub only on the consumer side (http://cloud.spring.io/spring-cloud-static/Dalston.SR3/#_spring_cloud_contract_wiremock). That way you'll manually start a WireMock instance in the way you want with the `proxy`. You won't have it tested against the producer.

**Comment by wizison** [comment]
this works fine for the test. 

but when I use the StubRunnerServer (@EnableStubRunnerServer Annotation on the SpringBootApplication class), this stub is still missing. I tried it with json and javacode mapping in the consumer and the producer module (where the other contract stubs are located), but the proxy stub is never included in the StubRunnerServer.

do we have any chance to get the proxy stub started with the stubrunner?

our app developers should use the fat jar for developing against the new api stuff.

**Comment by marcingrzejszczak** [comment]
Ok, now I understand... What you can do is that on the producer side, after the stubs are generated, and before they are packaged in a jar, you will create that one stub you mentioned and place it in the output directory. That way the standard sc-contract mechanism will still package the stub in the JAR. The problem I see is that it's an untested stub - but I understand that you know what you're doing :)

**Comment by wizison** [comment]
sounds great! will try that and post my results later :)

thanks a lot.

**Comment by marcingrzejszczak** [comment]
Ok! I'll close the issue then

**Comment by wizison** [comment]
it works fine!

i use the maven-resources-plugin to copy the resources before the jar is packaged. thanks a lot!

looks like:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <executions>
        <execution>
            <id>copy-resource-one</id>
            <phase>prepare-package</phase>
            <goals>
                <goal>copy-resources</goal>
            </goals>
            <configuration>
                <outputDirectory>${basedir}/target/stubs/META-INF/someinternalstuff/mappings/</outputDirectory>
                <resources>
                    <resource>
                        <directory>src/test/resources/mappings/</directory>
                        <includes>
                            <include>**/proxy_*.json</include>
                        </includes>
                    </resource>
                </resources>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by marcingrzejszczak** [comment]
That's how I would do it too. Glad that it works for you!
