### ISSUE TITLE
-DskipTests still calls the generate test classes

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#44]
When we're skipping tests we don't want to generate and compile any test classes

**Comment by dsyer** [comment]
Probably to fix this we'll need the user to type `-DskipTests=true` (then you can de-activate a profile or something).

**Comment by marcingrzejszczak** [comment]
nah - we're doing that regardless unfortunately. I have a fix ready though

**Comment by marcingrzejszczak** [comment]
Fixed in https://github.com/spring-cloud/spring-cloud-contract/commit/7b99b1c8d582790cd4a3d5f0e42c86a4236752d5
