### ISSUE TITLE
Cannot test simple string JSON responses

### ISSUE THREAD

**Issue by laffuste** [spring-cloud/spring-cloud-contract#443]
This has been already [raised in stackoverflow](https://stackoverflow.com/questions/45916752/spring-cloud-contract-how-to-test-simple-string-response).

Apparently, the only way to test simple strings is to change the content type of the response to `"plain/text"`. However, simple strings are [valid JSON](https://stackoverflow.com/a/24805020/1297812). In most cases it won't be acceptable to change the content type only for those responses returning single strings and thus the test/contract has to be skipped.

**Comment by laffuste** [comment]
Hi,

Would it be possible to schedule this bugfix for 1.2.*?

Thanks!

**Comment by marcingrzejszczak** [comment]
Isn't it there in the latest release? If not then i doubt that we will make another sr of dalston so i guess you'll need to upgrade
