### ISSUE TITLE
Regex patterns not working as expected

### ISSUE THREAD

**Issue by krisztak** [spring-cloud/spring-cloud-contract#449]
When using anyNonEmptyString() or anyNonBlankString() invalid regex pattern is generated.

Groovy contract
```
id : $(anyNonEmptyString())
```

Error log 
```
Expecting:
 "7vdh2fqrbht89384r4cu049rb3vh511exwfjdqx93g6y7y62q98jyt5j4m61g3vc"
to match pattern:
 "[Ss]+"

```

**Comment by vasilesmartup** [comment]
This affects only the headers responses in contracts. Works fine when in body, e.g. `versionId : $(p(anyNonEmptyString()), c('invalidxxxx')),`

**Comment by marcingrzejszczak** [comment]
@vasilesmartup can you show an exact contract that is broken? I can't seem to replicate this

**Comment by marcingrzejszczak** [comment]
Ping @vasilesmartup ?

**Comment by krisztak** [comment]
Hi,

When we use theese methods in request headers or query params as in the example below, it does not get translated into a matcher properly.

In the contract:
```
  queryParameters{
               parameter duration: $(
                       consumer(anyNumber()),
                       producer(1))}
        }
        ```

In the generated mappings :

```
 "queryParameters" : {
      "duration" : {
        "equalTo" : "org.springframework.cloud.contract.spec.internal.ClientDslProperty(DslProperty(clientValue:-?\\d*(\\.\\d+)?, serverValue:1236855402))"
      }
    }
    ```
I am not sure if we are using it wrong, or there is a problem. Please let us know.

I can confirm that when using them in the request/respons body it works as expected.

**Comment by marcingrzejszczak** [comment]
Could you please format the code? https://help.github.com/articles/basic-writing-and-formatting-syntax/

**Comment by vasilesmartup** [comment]
The following contract is producing unexpected values for the headers.
```
package contracts.web

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    request {
        method 'PUT'
        urlPath($(
                consumer(regex('/v1/communities/(.+)/channels/[0-9]+')),
                producer('/v1/communities/contract/channels/1')))

        headers {
            contentType(applicationJson())
            header("X-Smartup-Test",
                    $(
                            consumer(anyNonEmptyString()),
                            producer(1)))
        }
        body()
    }
    response {
        status 204
    }
}
```
Here's the generated mapping```

{
  "id" : "e68e079d-ba53-4963-9e9a-c14a8cc9f6a5",
  "request" : {
    "urlPathPattern" : "/v1/communities/(.+)/channels/[0-9]+",
    "method" : "PUT",
    "headers" : {
      "Content-Type" : {
        "matches" : "application/json.*"
      },
      **"X-Smartup-Test" : {
        "equalTo" : "org.springframework.cloud.contract.spec.internal.ClientDslProperty(DslProperty(clientValue:[\\S\\s]+, serverValue:FKXHVYLRAIJLVGOTQNUA))"
      }**
  },
  "response" : {
    "status" : 204,
    "transformers" : [ "response-template" ]
  },
  "uuid" : "e68e079d-ba53-4963-9e9a-c14a8cc9f6a5"
}
```

**Comment by marcingrzejszczak** [comment]
You're misusing the regular expressions. If you could use the ones prefixed with `anyNonEmptyString()` if they are set as the only present values. Since you provide the consumer and the producer side, you should use the patterns coming from the `RegexPatterns` class. 

Such a contract

```groovy
org.springframework.cloud.contract.spec.Contract.make {
				request {
					method 'GET'
					urlPath($(
							consumer(regex('/v1/communities/(.+)/channels/[0-9]+')),
							producer('/v1/communities/contract/channels/1')))
			
					headers {
						header("X-Smartup-Test",
								$(
										consumer(regex(nonEmpty())),
										producer(1)))
					}
				}
				response {
					status 204
				}
			}
```

gives you such a stub

```json
{
		"request" : {
		"urlPathPattern" : "/v1/communities/(.+)/channels/[0-9]+",
		"method" : "GET",
		"headers" : {
		  "X-Smartup-Test" : {
			"matches" : "[\\S\\s]+"
		  }
		}
	  },
	  "response" : {
		"status" : 204
	  }
	  }
```
