### ISSUE TITLE
Allow parametrization of generated contract names

### ISSUE THREAD

**Issue by HaAlex** [spring-cloud/spring-cloud-contract#452]
In Spring Rest Docs you can parameterize the output directories by using for example {methodName}. 

```
@Before
public void setUp() {
    this.mockMvc = MockMvcBuilders.webAppContextSetup(this.context)
            .apply(documentationConfiguration(this.restDocumentation))
            .alwaysDo(document("{method-name}/{step}/"))
            .build();
}
```

But when using also Spring Cloud Contract in the same test, the generated contract file name will be: {methodName}.groovy.
Is there a possibility to get for example MyTest.groovy instead, without hard-coding the name?

Thank you.

**Comment by marcingrzejszczak** [comment]
Please read the docs 

- how to rename the `json` file http://cloud.spring.io/spring-cloud-static/Dalston.SR4/multi/multi__spring_cloud_contract_wiremock.html#_generating_stubs_using_restdocs
- how to rename the contract file http://cloud.spring.io/spring-cloud-static/Dalston.SR4/multi/multi__spring_cloud_contract_wiremock.html#_generating_contracts_using_restdocs

**Comment by HaAlex** [comment]
Thanks for your answer. Unfortunately this is not answering my question. Maybe the question was not clear enough.

**My example test looks like:**

```
    public void myTest() {
        mockMvc.perform(get(URL_TO_MY_SERVICE, FOO)).andExpect(status().isOk())
                .andDo(MockMvcRestDocumentation.document("{methodName}", SpringCloudContractRestDocs.dslContract()));
    }
```

**What files I get generated**

- {methodName}.groovy
- myTest.json

**What I expect to get**

- myTest.groovy
- myTest.json

The documentation only shows me the possibility to write:
```
    public void myTest() {
        mockMvc.perform(get(URL_TO_MY_SERVICE, FOO)).andExpect(status().isOk())
                .andDo(MockMvcRestDocumentation.document("myTest", SpringCloudContractRestDocs.dslContract()));
    }
```

**Comment by marcingrzejszczak** [comment]
Ok, now I understand. That's more than probable that it's not currently supported. I'll mark this issue as an enhancement. For now, unfortunately, you have to hardcode the method name.

**Comment by HaAlex** [comment]
Ok thanks for your quick response. :)
