### ISSUE TITLE
Configuration for generateTests in execution tag is ignored

### ISSUE THREAD

**Issue by lmonkiewicz** [spring-cloud/spring-cloud-contract#453]
I'm trying to configure multiple contract dependencies, with separate configurations. I'm trying to achieve this by using multiple executions in the plugin configuration.

But the moment I put configuration inside execution section it gets ignored and no tests are generated.

Examples can be found at:
POM with execution (not working): https://github.com/lmonkiewicz/spring-cloud-contracts-playground/blob/doesntGenerateTests/server/pom.xml

POW without execution (working): https://github.com/lmonkiewicz/spring-cloud-contracts-playground/blob/generatesTests/server/pom.xml

The commented out part in both cases is a configuration that I want to achieve.

Is it a bug, or I'm doing something wrong?

**Comment by marcingrzejszczak** [comment]
That looks like a bug. @mariuszs can you try checking it out?

**Comment by marcingrzejszczak** [comment]
Hey @lmonkiewicz is this still a problem with the latest snapshots?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
