### ISSUE TITLE
Add to @AutoConfigureStubRunner stubs option

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#46]
You could provide in the annotation on the tests which stubs you would like to have downloaded

**Comment by dsyer** [comment]
The best way to do this is the refactor `StubRunnerProperties` and pull all the `Stubs` properties up into the top level (there's no need for them to be nested anyway). Then we can simply add `@PropertyMapping("stubrunner")` to the `@AutoConfigureStubRunner` annotation.
