### ISSUE TITLE
I am unable to use regular expression nor use the predefined regular expression. Could you please help

### ISSUE THREAD

**Issue by sushmasrikrishna2579** [spring-cloud/spring-cloud-contract#464]
#In my contract i have to validate few attribute where its value changes at run time, say example , address ID which is an integer value. I tried using the below, but unable to crack

\$(p(anynumber()), c("238"))
$(consumer(238'), producer(regex('[0-9]{3}$'))),
$(consumer(238'), producer(regex('[0-9]{3}'))),
value(consumer(238'), producer(regex('[0-9]{3}$'))),
value(consumer(238'), producer(regex('[0-9]{3}'))),

**Comment by marcingrzejszczak** [comment]
You have provided very little information. You have to validate that values on the consumer side or the producer side? You have a dynamic value in the response or the request? In the test or the stub? Which version of sc contract are you using? Can you provide the sample contract?

**Comment by sushmasrikrishna2579** [comment]
Hi Marcin,

Thanks for your reply. I am trying to validate the values in the response
from the producer side . Here is the same contract. There are few
attributes whose value changes dynamically. E.g addressId and ownerId

package contracts

import org.springframework.cloud.contract.spec.Contract

Contract.make {

    request {
        method 'POST'
        url '/app/crm/address/customer'
        body([
        consumerId: 52

    ])
    headers {
            header('Content-Type', 'application/json')
            header('domain','la')
         }


    }

    response {
        status 200
        body([
        "validationList":null,
        "errorResponse": null,
                "status": "success",
        addresses: ["""
              {
              "addressId":127
              "addrStreet1": null,
            "addrStreet2": null,
            "addrCity": null,
            "addrZip": null,
            "addrHouseCode": null,
            "addrAttn": null,
            "addrCountry": null,
            "addrZipFour": null,
            "addressType": "ADDRESS",
            "createdBy": null,
            "creadtedOn": null,
            "updatedBy": null,
            "updatedOn": null,
            "transactionId": null,
            "ownerId":value(consumer(238), producer(regex('[0-9]{3}'))),
            "state": null,
            "customerId": 52
   }
   """
    ]
    ] )
        headers {
            contentType(applicationJson())
        }
    }}

Regards,
Sushma

**Comment by marcingrzejszczak** [comment]
You are putting text `value(...,...)` in the multiline String. You have to use `${...}` Groovy String interpolation. It should look like this `"ownerId":${value(consumer(238), producer(regex('[0-9]{3}')))},`

Please read more about it here http://groovy-lang.org/syntax.html#_string_interpolation and http://groovy-lang.org/json.html

**Comment by sushmasrikrishna2579** [comment]
Hi Marcin,

Thanks for your reply

As suggested I used Groovy String interpolation in my contracts. Still i
have issues building the application , getting compilation error something
like this.

I have attached the contract for your reference.

C:\Ngen\ngen-address-gateway\build\generated-test-sources\contracts\org\springfr
amework\cloud\contract\verifier\tests\ContractVerifierTest.java:205: error:
clas
s, interface, or enum expected
        }

Sorry to bother you .

Regards,
Sushma

**Comment by sushmasrikrishna2579** [comment]
Hi Marcin,

Thanks for your reply

As suggested I used Groovy String interpolation in my contracts. Still i
have issues building the application , getting compilation error something
like this.

I have attached the contract for your reference.

C:\Ngen\ngen-address-gateway\build\generated-test-sources\
contracts\org\springfr
amework\cloud\contract\verifier\tests\ContractVerifierTest.java:205: error:
clas
s, interface, or enum expected
        }

Sorry to bother you .

Regards,
Sushma

**Comment by marcingrzejszczak** [comment]
Neither have you attracted the contract not have you attached the generated test

**Comment by sushmasrikrishna2579** [comment]
Sorry for the same.

package contracts

import org.springframework.cloud.contract.spec.Contract

Contract.make {

    request {
        method 'POST'
        url '/app/crm/address/customer'
        body([
        consumerId: 52

    ])
    headers {
            header('Content-Type', 'application/json')
            header('domain','la')
         }


    }

    response {
        status 200
        body([

        "validationList":null,
        "errorResponse": null,
                "status": "success",
        addresses: ["""
          {
              "addressId":${value(consumer(401),
producer(regex('[0-9]+')))},
              "addrStreet1": null,
            "addrStreet2": null,
            "addrCity": null,
            "addrZip": null,
            "addrHouseCode": null,
            "addrAttn": null,
            "addrCountry": null,
            "addrZipFour": null,
            "addressType": "ADDRESS",
            "createdBy": null,
            "creadtedOn": null,
            "updatedBy": null,
            "updatedOn": null,
            "transactionId": null,
            "ownerId":${value(consumer(401), producer(regex('[0-9]+')))},
            "state": null,
            "customerId": 52
   }
   """
    ]

    ] )
        headers {
            contentType(applicationJson())
        }
    }}

**Comment by sushmasrikrishna2579** [comment]
Marcin,

This is the version we are using

springContractVerifierVersion=1.1.4.RELEASE

Regards,
Sushma

**Comment by marcingrzejszczak** [comment]
You can't mix the map notation and the string notation of the body. Please pick one

**Comment by sushmasrikrishna2579** [comment]
Hi Marcin,

Thanks for your reply. I am tester and not sure what exactly the terms Map
Notation and String Notation mean. Any example to refer, please share it.

Regards,
Sushma

**Comment by marcingrzejszczak** [comment]
Please read the documentation of spring Cloud contract and the provided links of groovy language.
