### ISSUE TITLE
Options are not passed to StubRunnerRule

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#466]

**Comment by jorgeviana** [comment]
Hi, you sent me some instructions today via email for me to try to debug the problem. Would it be possible to put them here as I usually don't have access to my work email at home. Thanks.

**Comment by marcingrzejszczak** [comment]
I've fixed the problem. Tomorrow I'll release it in version 1.3.1. The system props will work and there will be additional props
