### ISSUE TITLE
anyNumber in dsl generate String numbers in json

### ISSUE THREAD

**Issue by hatzhang** [spring-cloud/spring-cloud-contract#468]
full contract, full stub and the generated test are uploaded. 
[web.zip](https://github.com/spring-cloud/spring-cloud-contract/files/1501586/web.zip)

**Comment by marcingrzejszczak** [comment]
Could you please upload it as a github project? It will be much easier to collaborate. Thanks!

**Comment by hatzhang** [comment]
[uploaded here!!](https://github.com/hatzhang/anynumer)

**Comment by marcingrzejszczak** [comment]
The example you've presented (BTW I couldn't run it cause you were missing base class for the generated test and production code...) 

Having such code

```java
@SpringBootApplication
public class AnynumberApplication {

	public static void main(String[] args) {
		SpringApplication.run(AnynumberApplication.class, args);
	}
}

@RestController
class Controller {
	@RequestMapping(value = "/simple/", produces = MediaType.APPLICATION_JSON_VALUE)
	String foo() {
		return "{ \"number\": 123 }";
	}
}
```

such a base class

```
public class BaseClass {

	@Before
	public void setup() {
		RestAssuredMockMvc.standaloneSetup(new Controller());
	}
}
```

such a contract

```groovy

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    request {
        method "GET"
        url  value(regex('/simple/[a-z]*'))
    }
    response { // (6)
        status 200 // (7)
        body(
                number: anyNumber()
        )
        headers { // (9)
            contentType('application/json')
        }
    }
}


```

such a generated test

```
public class ContractVerifierTest extends BaseClass {

	@Test
	public void validate_simple() throws Exception {
		// given:
			MockMvcRequestSpecification request = given();

		// when:
			ResponseOptions response = given().spec(request)
					.get("/simple/");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);
			assertThat(response.header("Content-Type")).matches("application/json.*");
		// and:
			DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			assertThatJson(parsedJson).field("['number']").matches("-?\\d*(\\.\\d+)?");
	}

}
```

Doesn't generate any String numbers. However, it doesn't assert the types ( I guess that's what you mean...).  So this test passes if the response json is 

```json
{ "number": 123 }
```

and

```json
{ "number": "123" }
```

which is a bug. I'll try to address it in branch `2.0.x` (I'll bump jsonassert and add a feature to check types)

**Comment by marcingrzejszczak** [comment]
Can you @hatzhang confirm that my understanding is correct?

**Comment by hatzhang** [comment]
I want the stub boot application to return Number type value when the value is defined in contract using anyNumber。

After run generateStubs, the following mapping was generated:
`    {
  "id" : "e89105e8-808f-40d9-9d92-32f2b8ba6457",
  "request" : {
    "urlPattern" : "/simple/[a-z]*",
    "method" : "GET"
  },
  "response" : {
    "status" : 200,
    "body" : "{\"number\":\"-1207046272\"}",
    "headers" : {
      "Content-Type" : "application/json"
    },
    "transformers" : [ "response-template" ]
  },
  "uuid" : "e89105e8-808f-40d9-9d92-32f2b8ba6457"
}`
but i think the body part should be like this:
` "{\"number\":-1207046272}"`

**Comment by marcingrzejszczak** [comment]
Oh so in the generated stub the problem's there too... Thanks for clearing this up for me!

**Comment by hatzhang** [comment]
i have some other concerns about this:  

1. i think contract dsl should support all json native types
2. there may be need for String type number
3. wonder what happens when defining "anynumber"(or regx) in restdoc, then use that to generate dsl, then to mapping.

**Comment by vkrams** [comment]
I have noticed a similar problem in 1.1.3 and 1.2.1 
My expected response in groovy will be like this for one of the field. When I run the build it passes.
`"id"           : $(anyNumber())`
Now I will change the field name in the expected response. When I run the build it passes, which seems to be a bug for me. The bug might be in your anyNumber regular expression.
`"ids"           : $(anyNumber())`
Again I have changed the expected response as shown below and the build fails noting the field ids doesn't exist.
`"ids"           : $(regex('^\\d+\\.?\\d*$'))`

Just give a try in the project given by @hatzhang

**Comment by marcingrzejszczak** [comment]
@hatzhang @vkrams - thanks for the feedback. That's really valuable and will help to get around this!

**Comment by metaphor** [comment]
@marcingrzejszczak will this fix also applied to 1.2.x cause we have a bunch of projects using this version.

**Comment by marcingrzejszczak** [comment]
I haven't yet done this :/ I think that a workaround would be to manually provide a concrete value for the consumer e.g. `$(p(regex(number())), c(123))`

**Comment by axelhodler** [comment]
Somewhat related:

```
        body([
            coordinate: [
                lat: 48.5,
                lng: 9.5
            ]
        ])
```

leads to

```json
{"coordinate":{"lng":"9.5","lat":"48.5"}}
```

instead of

```json
{"coordinate":{"lng":9.5,"lat":48.5}}
```

so instead of `9.5` we have `"9.5"`
