### ISSUE TITLE
Number pattern allows empty value

### ISSUE THREAD

**Issue by JohannesDorn** [spring-cloud/spring-cloud-contract#471]
Creating a test of

`
test(
    [
        [
             "price" : regex(number())
        ]
    ]
)
`

accepts empty values. This leads to generated tests that do not assert the correctness of field names.

Suppose we test this against a JSON like this one:

`
[
  {
	"priceFoo": 123
 }
]
`

A test will be generated:

`assertThatJson(parsedJson).array().contains("['price']").matches("-?\\d*(\\.\\d+)?");`

This test will not fail for any wrong field names for "price" as the regex accepts empty values.
Is this intended? If so, how can I write a test that fails for wrong field names?

**Comment by marcingrzejszczak** [comment]
Nope. That's not intended. As a workaround please use regex(...) and write a valid regex. You can also try filing the PR to fix the regex ;)

**Comment by JohannesDorn** [comment]
I've created a pull request but the tests fail for some reason.

Unfortunately, I am in a network environment where I can't build the change locally.
Can you have a look at what's wrong?

**Comment by marcingrzejszczak** [comment]
Yeah you broke 11 tests ;) https://circleci.com/gh/spring-cloud/spring-cloud-contract/2826?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by JohannesDorn** [comment]
I've fixed the test failures
