### ISSUE TITLE
Slice Testing with just the Autoconfigurations related to stubrunner loaded in

### ISSUE THREAD

**Issue by bijukunjummen** [spring-cloud/spring-cloud-contract#473]
As a consumer of a service with stubs published, it would be great to load up only the spring configuration and components related to stub runner without needing to load up the entire application context. For a complex app with its own set of auto-configurations and with external database dependencies, loading up an entire context is difficult.

Just to provide a little more context, a consumer test looks like this:

```java
@RunWith(SpringRunner::class)
@SpringBootTest
@AutoConfigureStubRunner(ids = arrayOf("samples.contract:sample-producer:+:stubs"), workOffline = true)
class PassThroughContractTest {
```

The `@SpringBootTest` annotation causes the entire boot application context along with any auto-configurations to be loaded up which is costly for na app with likely external dependencies.

Junit rule works well as a substitute. It would be great to have a more Spring Boot native solution also.

Here is the project where I was trying it out - https://github.com/bijukunjummen/s-c-contract-sample

**Comment by bijukunjummen** [comment]
I will try and send you a PR @marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/pull/496
