### ISSUE TITLE
Bump WireMock to 2.12

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#477]

**Comment by gunayus** [comment]
Is this the one that needs to be upgraded to 2.12 

      <dependency>
        <groupId>com.github.tomakehurst</groupId>
        <artifactId>wiremock-standalone</artifactId>
        <version>2.11.0</version>
      </dependency>

**Comment by marcingrzejszczak** [comment]
Yeah, I've just bumped it.

**Comment by gunayus** [comment]
good job, 

I will pick an other issue then :)
