### ISSUE TITLE
Why not add @FixMethodOrder(MethodSorters.NAME_ASCENDING) in Junit Test source if it is not SCENARIO?

### ISSUE THREAD

**Issue by siodoon** [spring-cloud/spring-cloud-contract#480]
About spring-cloud-contract-verifier, at org.springframework.cloud.contract.verifier.builder.JavaTestGenerator.groovy. If groovy file name is not start with 0-9_, Junit test java class is generated has no  
`@FixMethodOrder(MethodSorters.NAME_ASCENDING)`. I think you can add configuration parameter to change test running order or change the following code 👍 

```
if (isScenarioClass(listOfFiles)) {
	**clazz.addImport(configProperties.targetFramework.getOrderAnnotationImport())
	clazz.addClassLevelAnnotation(configProperties.targetFramework.getOrderAnnotation()**)
}
```
to:

```
clazz.addImport(configProperties.targetFramework.getOrderAnnotationImport())
clazz.addClassLevelAnnotation(configProperties.targetFramework.getOrderAnnotation())
```

That is, whatever it is SCENARIO(stateful contract) or stateless contract, junit test should have  `@FixMethodOrder(MethodSorters.NAME_ASCENDING)`.
You know, Junit test order default is compare two name's hashcode, but this hashcode is changable and not predictable . Junit doc said:

```
 /**
     * Sorts the test methods in a deterministic, but not predictable, order
     */
    DEFAULT(MethodSorter.DEFAULT);
```

Why do I propose to do like the above?
i.e, for one microservice: there are 4 rest api, insert, update, get, delete. You know, one groovy is permitted to include one method,  But update, get and delete depend on insert operation. As a stub, it does not need to have state. So groovy file name can't start with 0-9_(not SCENARIO)

**Comment by marcingrzejszczak** [comment]
Can you explain what problem are you trying to solve?

**Comment by siodoon** [comment]
i.e, for one microservice: there are 4 rest api, insert, update, get, delete. You know, one groovy is permitted to include one method, But update, get and delete depend on insert operation. That is Unit test has before-after order. For a stub, it will be invoked by other services and does not need to have state. So groovy file name can't start with 0-9_(not SCENARIO)

**Comment by marcingrzejszczak** [comment]
> But update, get and delete depend on insert operation.

they depend in your business logic, not the contract one. Contract tests don't care about this.

> For a stub, it will be invoked by other services and does not need to have state. So groovy file name can't start with 0-9_(not SCENARIO)

I don't understand what you're writing. Yes, you don't need a state. Yes, it can't start with 0-9. Now, what is the problem?

**Comment by siodoon** [comment]
Yes, you're right. Contract does not care about business logic. I think contract includes at least 2 goals, one is  unit test itself and another is used by other services.  My case is unit test need have state, but contract is used by other service is stateless. 
At your code, if contract is stateful, junit test is run according to unit test method name ascending. Otherwise junit test is run according to other order.

**Comment by marcingrzejszczak** [comment]
Unit test doesn't need a real state. You can (should) mock it out.

I don't see any value in adding these annotations. But you can implement your own solution (since the sc-contract implementation is pluggable (http://cloud.spring.io/spring-cloud-static/Edgware.RELEASE/multi/multi__using_the_pluggable_architecture.html)

**Comment by siodoon** [comment]
Junit test code with stateful contract has annotation @FixMethodOrder(MethodSorters.NAME_ASCENDING), why does stateless contract have no this annotation? If stateless contract have this annotation as well, what is consequence?

**Comment by marcingrzejszczak** [comment]
There's no reason for it to have it. It solves no problem.

If you don't think that makes sense, as I said, you can implement your own way of generating tests and add these annotations.

**Comment by siodoon** [comment]
Thanks for your quick reply. I'm new to spring cloud contract. Document I can search is not too much. As a developer, I think how to code always has some reasons, so I want to know why it is.

**Comment by marcingrzejszczak** [comment]
> Document I can search is not too much

I don't understand this statement. The documentation is not good enough? Is it missing sth?

> As a developer, I think how to code always has some reasons, so I want to know why it is.

I've explained the reasons. There's no reason to add this annotation. The order shouldn't matter. If it does, use scenarios.
