### ISSUE TITLE
About Custom Test Generator

### ISSUE THREAD

**Issue by siodoon** [spring-cloud/spring-cloud-contract#481]
According to http://cloud.spring.io/spring-cloud-static/Edgware.RELEASE/multi/multi__using_the_pluggable_architecture.html#_using_the_custom_test_generator, 89.2 Using the Custom Test Generator. I implemented SingleTestGenerator, but ClassBuilder is @PackageScope. I can't use it. 
Can you provide an example about how to using the custom test generator, especially how to construct java test class?

**Comment by marcingrzejszczak** [comment]
Yeah, I think that's a mistake. For now, just copy the code to your codebase. I'll open this class for `2.0.0`

**Comment by marcingrzejszczak** [comment]
I was thinking about this... What's your use case? Do you want to generate the JVM based tests but in a different way?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
