### ISSUE TITLE
External Contract Workflow 

### ISSUE THREAD

**Issue by angusoid** [spring-cloud/spring-cloud-contract#485]
I wanted to get a confirmation on workflow with external contracts. I've already talked with Marcin via mail about this topic. For the sake of documentation I will describe the external workflow here and will expect to get some confirmation here as well. 

_Note:_
I am interested in figuring the complete workflow, especially concerning feature branches on respectful consumer/producer branches and their life cycle in this "contract" based environment. 

```
X - Contract Repository 
Y - Some Service Repository (A)
Z - Some Service Repository (B)

A - User
B - User
```

**Sequence 0.**
- Y and Z services have no communication channels or contracts yet. 
- User A is maintainer of service Y. 
- User B is maintainer of service Z.
- User A knows that service Z  holds data of his interest.
- User A gives a heads up to user B about his intentions.

**Sequence 1.** 
- User A creates a local feature branch for contract X, and writes contract proposal.
- While doing so, he also creates local feature branch for service Y and writes consumer tests. (working offline). 
- User A finishes implementation and submits a PR for contract X. 
- User A notifies user B that he should satisfy the other side of contract (producer).
- User A local feature branch for service Y is on hold. 

**Sequence 2.** 
- User B creates a local feature  branch for service Z and writes producer part of contract. (offline mode). 
- User B can merge contract PR. 
- User B local feature branch for service Z is on hold. 

**Sequence 3.**
- CI Builds contract master branch and releases artifact to Nexus/Artifactory.
- Both User A and B  update their local feature branches to work online. 
- Both User A and B  submit a PR for their respectful service feature branches. 
- CI Builds PR's and verifies working contracts.
- Branches are merged into master

_*Some observations:*_ 
- When creating contract PR, consumer can use some tagging to notify producer about his part of work.
- Consumer/Producers submit their PR in an online mode, its questionable if they ever submit PR with offline mode setup (this might break the CI build that builds PR). 
- Some steps are optional, if consumer ends up being the owner of producer service he could write implementation as well. 
- Obviously we are missing some steps such as reviewing and possibility that initial contract has to be adjusted due to some limitations.

**Comment by angusoid** [comment]
Just wanted to ask additional question related to the workflow mentioned above:

When we are switching to online mode the producer is responsible for providing producer stubs? (Sounds dope) 

If that is the case, the consumer has to wait for producer's branch to be merged (and stubs artifact released). And only then the consumer can switch to work in online mode.

CI builds Contracts repo (pushes contracts.jar) 
&darr;
Producer Switches Online (pulls contracts.jar)
&darr;
CI builds producers stubs (push producer-service-version-stubs.jar) 
&darr;
Consumer Switches Online  (pulls producer-service-version-stubs.jar)

**Comment by marcingrzejszczak** [comment]
> When we are switching to online mode the producer is responsible for providing producer stubs? 

You switch online once the stubs got already uploaded (otherwise your stuff will never work)

> If that is the case, the consumer has to wait for producer's branch to be merged (and stubs artifact released). And only then the consumer can switch to work in online mode.

Yes

**Comment by ionescuv** [comment]
> > If that is the case, the consumer has to wait for producer's branch to be merged (and stubs artifact released). And only then the consumer can switch to work in online mode.
> 
> Yes

Hi Marcin,

I'm also interested in how we can avoid blocking the consumer in "offline mode" until the stubs artifact has been released.
When using a common contract repository, could the stubrunner be configured to start different producer-stubs on different ports(if the stubs are all in a single repo)?

Also, what would be the reasons to NOT hold the contracts in the consumer repository? (Other than releasing the consumer without being sure the producer supports the contract)

Thanks

**Comment by marcingrzejszczak** [comment]
> When using a common contract repository, could the stubrunner be configured to start different producer-stubs on different ports(if the stubs are all in a single repo)?

contract != stubs. All contracts lay in a single repo. Stubs are uploaded by each producer separately. Stubs are not in the single repo.

> Also, what would be the reasons to NOT hold the contracts in the consumer repository? (Other than releasing the consumer without being sure the producer supports the contract)

Because you validate the contracts against the producer not the consumer. IMO it makes absolutely no sense to hold the contracts with the consumer. On the producer side, to generate tests, how many consumers will you point to? You might even not know who's using you.

**Comment by yuranos** [comment]
@marcingrzejszczak , we can though hold them with the consumer, right? Verifier and maven plugin can be added on Consumer side. I can even see some info on that in the spec.
Incidentally, I don't fully understand the reason to have stub/wiremock properties exposed via plugins(`stubs`, `httpPort`, etc.). Is it for cases on Consumer side when `@AutoConfigureStubRunner` is not an option?

**Comment by marcingrzejszczak** [comment]
> @marcingrzejszczak , we can hold them with the consumer though, right? Verifier and maven plugin can be added on Consumer side. I can even see some info on that in the spec.

like I said, previously. IMO that's a wrong idea.

>  I don't fully understand the reason to have stub/wiremock properties exposed via plugins(stubs, httpPort, etc.). Is it for cases on Consumer side when @AutoConfigureStubRunner is not an option?

That's when you want to run the stubs manually without a project.

**Comment by marcingrzejszczak** [comment]
Will be done via https://github.com/spring-cloud/spring-cloud-contract/pull/1157
