### ISSUE TITLE
matching criteria for contracts when there is a better matching

### ISSUE THREAD

**Issue by jorgeviana** [spring-cloud/spring-cloud-contract#486]
Version tried: 1.1.4.RELEASE

If I have a file with two contracts which the only difference is the number of headers, see bellow (I've omitted some fields for brevity).

```
[
Contract.make {
  method 'POST'
  url 'some url'
  headers {
    header 'a': 'some value'
    header 'b': 'some value'
  }
},
Contract.make {
  method 'POST'
  url 'some url'
  headers {
    header 'a': 'some value'
  }
}
]
```

And I make a request 'to the stubs' passing both headers, then it will match the contract with only one header.

Is this a bug or normal behaviour? Is there a way to make SCC match on all the fields passed?

**Comment by marcingrzejszczak** [comment]
It's normal. One contract is a subset of the other. You should add the priority method to both. The first one should have a higher priority which means a lower number e.g. priority(1) and the other priority(5)

**Comment by jorgeviana** [comment]
My bad, the search criteria I used in Google didn't led me to the right answer. Also don't remember to see this "priority" when I was reading documentation. Thanks for answering.

**Comment by marcingrzejszczak** [comment]
No problem. It's here - http://cloud.spring.io/spring-cloud-static/Edgware.RELEASE/single/spring-cloud.html#contract-dsl-http-top-level-elements
