### ISSUE TITLE
JUnit 5 support

### ISSUE THREAD

**Issue by jntakpe** [spring-cloud/spring-cloud-contract#489]
Currently Spring cloud contract supports JUnit 4 and Spock. It would be nice to have Junit 5 too

**Comment by thekalinga** [comment]
As of now, spring natively supports junit5 via `SpringExtension`?

Appreciate if you can share with us if you have some timelines on this

**Comment by marcingrzejszczak** [comment]
I don't have a timeline on this, sorry. Be my guest to provide a contribution.

**Comment by yuranos** [comment]
@marcingrzejszczak , I'm very muh interested to help, but I'm not sure I understand the scope. If all we are talking about, as an initial integration at least, is substituting Runners with Extension and maybe improve assertions a bit, I can do that.
If something more intricate, like replacements for JUnit 4 rules is required in the future, it can be added later.
What do you make of it?

**Comment by OlgaMaciaszek** [comment]
Hello, I'm already working on it, along with some refactoring of Java test classes generation. Will get it done by the end of May.

**Comment by yuranos** [comment]
Hi, @OlgaMaciaszek. Please keep in mind that fixed method order is not yet supported for JUnit 5.
See: https://github.com/junit-team/junit5/issues/13

**Comment by hemeroc** [comment]
@OlgaMaciaszek any news on your progress

**Comment by OlgaMaciaszek** [comment]
Hello, I'm really sorry. Some things have come up and I haven't managed to finish it. Will get it done during the weekend.

**Comment by OlgaMaciaszek** [comment]
Hello. I've worked on it, it have realised the old approach had to be refactored first before adding new stuff. Need a few more days. Will post here when it's done.

**Comment by OlgaMaciaszek** [comment]
I have submitted the PR. Waiting for review. Once again, sorry for the delay.

https://github.com/spring-cloud/spring-cloud-contract/pull/690

**Comment by handriamanantena** [comment]
I was just wondering if this feature was available for 2.1.0.M1?

**Comment by marcingrzejszczak** [comment]
If you click on the commit (https://github.com/spring-cloud/spring-cloud-contract/commit/b48d50edcc4cd59faae5796c764b45dbd035676b) to the top you see the `2.1.0.M1` tag. It should be there.
