### ISSUE TITLE
using String in jsonPath in WireMockRestDocs results in faulty groovy contract file

### ISSUE THREAD

**Issue by HaVonTe1** [spring-cloud/spring-cloud-contract#494]
When you try to use Strings in jsonPath to generate testMatchers in your contract file, it results in groovy compile errors:

Example:
```
        this.mockMvc.perform(post("/example")
            .content(objectMapper.writeValueAsString(messagebody))
            .contentType(MediaType.APPLICATION_JSON_UTF8)
            .accept(MediaType.APPLICATION_JSON_UTF8))
            .andExpect(status().isAccepted())
            .andExpect(content().json(objectMapper.writeValueAsString(response)))
            .andDo(WireMockRestDocs.verify()
                .jsonPath("$[?(@.exampleNumber >= 0 && @.exampleNumber < "+Integer.MAX_VALUE+")]")
                .jsonPath("$[?(@.exampleEnum in ['AUTO','CUSTOMER','EMPLOYEE'])]")
                .contentType(MediaType.valueOf("application/json"))
                .stub("my-remote-service-stub"))
            .andDo(
                document("example",
                    preprocessRequest(prettyPrint()),
                    preprocessResponse(prettyPrint()),
                    SlmSpringCloudContractRestDocs.dslContract()))
            .andDo(
                document("example",
                    preprocessRequest(prettyPrint()),
                    preprocessResponse(prettyPrint()),
                    requestFields(
                        fieldWithPath("exampleNumber").description("An example number field"),
                        fieldWithPath("exampleEnum").description("An example enum field")
                    )
                    ));

Generated my-remote-service-stub.groovy:

```
    Contract.make {
        request {
            method 'POST'
            url '/communication/api/v1/topic/complain'
            body('''
                {
      "exampleNumber" : 1,
      "exampleEnum" : "AUTO"
    }
            ''')
            headers {
                header('''Content-Type''', '''application/json;charset=UTF-8''')
                header('''Accept''', '''application/json;charset=UTF-8''')
            }
        }
        response {
            status 202
            body('''
            {
      "id" : 42
    }
            ''')
            headers {
                header('''Content-Type''', '''application/json;charset=UTF-8''')
            }
            testMatchers {
                jsonPath('$[?(@.exampleNumber >= 0 && @.exampleNumber < 2147483647)]', byType())
                jsonPath('$[?(@.exampleEnum in ['AUTO','CUSTOMER','EMPLOYEE'])]', byType())

            }
        }
    }
```
The Problem is the single quotation mark in "jsonPath".
This would work:
     jsonPath('''$[?(@.exampleEnum in ['AUTO','CUSTOMER','EMPLOYEE'])]''', byType())

**Comment by HaVonTe1** [comment]
I wanted to switch from Dalston to Edgware. But sadly your bugfix was only merged to 1.1.5 which is in Dalston. But noch in 1.2.x which comes with Edgware. Is there a chance to merge this bugfix to the 1.2.x branch too?

**Comment by marcingrzejszczak** [comment]
We always merge branches. You can see that in branch `1.2.x` the change is also present https://github.com/spring-cloud/spring-cloud-contract/blob/1.2.x/spring-cloud-contract-wiremock/src/main/resources/org/springframework/restdocs/templates/default-dsl-contract-only.snippet#L37 .

**Comment by HaVonTe1** [comment]
veeeery strange. I will check again. But I guess I just missed a "gradle clean" or something....
