### ISSUE TITLE
[gradle plugin] Mismatch between stubs jar directory structure and Ant pattern to search for contracts

### ISSUE THREAD

**Issue by reillylm** [spring-cloud/spring-cloud-contract#495]
In the Gradle plugin, when we generate a standalone stubs jar with the `copyContracts` and `verifierStubsJar` tasks, we package it with a dot-separated `groupid`, as it appears in the `project`'s `group` field:
https://github.com/spring-cloud/spring-cloud-contract/blob/f586cf298d5f6a25b0c4d9237ec7989b4c00123c/spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/OutputFolderBuilder.groovy#L14-L19
However, when we download that stubs artifact from a Maven repository, using the plugin and leaving the `contractsPath` property blank in the `ContractVerifierExtension` block, we're searching for a slash-separated `groupid`:
https://github.com/spring-cloud/spring-cloud-contract/blob/c354bffafbd37ad1da4d80294521445420634bf4/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/ContractDownloader.java#L63-L65
So, for a standalone stubs project with Maven coordinates like `com.xyz:standalone:0.2.0`, and an app that uses these stubs called `app`, we end up with something like:

```
12:06:25.806 [INFO] [org.springframework.cloud.contract.stubrunner.AetherStubDownloader] Resolved artifact [com.xyz:standalone:jar:stubs:0.2.0] to /Users/user/.m2/repository/com/xyz/standalone/0.2.0/standalone-0.2.0-stubs.jar
12:06:25.809 [INFO] [org.springframework.cloud.contract.stubrunner.AetherStubDownloader] Unpacking stub from JAR [URI: file:/Users/user/.m2/repository/com/xyz/standalone/0.2.0/standalone-0.2.0-stubs.jar]
12:06:25.825 [INFO] [org.springframework.cloud.contract.stubrunner.AetherStubDownloader] Unpacked file to [/var/folders/cr/w6r5svsj7bqc5p3qjgx89rtxl3hv0q/T/contracts6252887730850203514]
12:06:25.826 [INFO] [org.springframework.cloud.contract.stubrunner.ContractDownloader] Will pick a pattern from group id and artifact id
12:06:25.826 [INFO] [org.springframework.cloud.contract.stubrunner.ContractDownloader] Pattern to pick contracts equals [^/var/folders/cr/w6r5svsj7bqc5p3qjgx89rtxl3hv0q/T/contracts6252887730850203514(/)?.*com/xyz/app/.*$]
12:06:25.826 [INFO] [org.springframework.cloud.contract.stubrunner.ContractDownloader] Ant Pattern to pick files equals [**/com/xyz/app/**/]
12:06:25.830 [INFO] [org.gradle.api.Project] Downloading and unpacking files from [/var/folders/cr/w6r5svsj7bqc5p3qjgx89rtxl3hv0q/T/contracts6252887730850203514] to [/Users/user/dev/app/build/stubs/META-INF/com.xyz/app/0.2.0.0dabd3c/contracts]. The inclusion ant pattern is [**/com/xyz/app/**/*.*]
```
Does the plugin need to be updated to slash-separate the `groupid` when we package the stubs jar?

**Comment by marcingrzejszczak** [comment]
By standalone you mean the jar that contains all the contracts?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by soudmaijer** [comment]
@marcingrzejszczak Indeed a jar that only includes the contracts and mappings. For maven this works just fine, but in gradle it does not work.
