### ISSUE TITLE
[question] Support Spring Data REST Repositories

### ISSUE THREAD

**Issue by stoetti** [spring-cloud/spring-cloud-contract#499]
Hey!

I am currently evaluating if we should use Spring Cloud Contract for our Project, therefore I followed the simple samples which worked fine. Now I tried the first contract for our "real world" Api, which is based on Spring Data REST to avoid writing too much boilerplate-code.

Unfortunately I cannot get the Contract-Verifier Test running cause this Line does not create the necessary endpoint
`RestAssuredMockMvc.standaloneSetup(someAutowiredRepository);`

Question: Is there a special support or How-To when it comes to Spring Cloud Contract <=> Spring Data REST?

**Comment by marcingrzejszczak** [comment]
No wonder... I think you should try to setup the normal context (via `@SpringBootTest`) and then call `RestAssuredMockMvc.webAppContextSetup()`. You can check it out here - https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/master/producer/src/test/java/com/example/intoxication/BeerIntoxicationBase.java#L23-L32

**Comment by stoetti** [comment]
That did it, thanks for the quick and helpful reply.
