### ISSUE TITLE
Extend priority information about what the higher priority means

### ISSUE THREAD

**Issue by jkubrynski** [spring-cloud/spring-cloud-contract#508]
The current description in the javadoc is misleading

	 * You can set the level of priority of this contract. If there are two contracts
	 * mapped for example to the same endpoint, then the one with greater priority should
	 * take precedence

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/b745d9a7e38c0ecaef96f3050206a63c7f98b55a
