### ISSUE TITLE
Type Matcher on `$.body` from Pact is not evaluated as expected

### ISSUE THREAD

**Issue by thombergs** [spring-cloud/spring-cloud-contract#511]
When defining a type matching rule on the whole body in a pact file, it is not translated into a spring cloud contract matcher as expected.

**Pact matching rule:**
```json 
"body": {
  "firstName": "Zaphod",
  "lastName": "Beeblebrox"
 },
"matchingRules": {
  "$.body": {
    "match": "type"
  }
}
```

**Expected Behavior**:
Pact evaluates the above matcher as "all elements of the body should have the same type as defined above". So in our case, there should be two fields `firstName` and `lastName` each with a value of type `String`. 

**Actual Behavior**:
Error as reported in issue #509.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/bea0d4f78d44150f7348623b21b4afae51ab50b5
