### ISSUE TITLE
Enhancement - allow StubDownloader to keep unpacked files instead of always deleteing them

### ISSUE THREAD

**Issue by tomaszc** [spring-cloud/spring-cloud-contract#512]
Hi!

I would like to sometimes see what stubs were downloaded, unpacked and used for StubRunner initialization by a StubDownloader. Right now they are always deleted. 

I know it is possible to get WireMock configuration providing configuration property

> stubrunner.mappings-output-folder=./build/tmp/wiremock

Still I think that it would be useful to be able to inspect whole package which was downloaded and used as an input for:

- better validation
- being able to run WireMock manually with stubbed provider outside of the integration tests for whatever reasons

IMO it would be useful to have some configuration property like 'delete-stubs-after-test' with default value set to true.

**Comment by tomaszc** [comment]
I found the cause of always-delete feature [here](https://github.com/spring-cloud/spring-cloud-contract/blob/74b843d76b8ef8f0bec9c30a709ef3df88b62726/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/ClasspathStubProvider.java#L78).

**Comment by marcingrzejszczak** [comment]
That looks like a good idea. Thanks for the feedback!
