### ISSUE TITLE
contract file names with special chars lead to compile errors in generated tests

### ISSUE THREAD

**Issue by thombergs** [spring-cloud/spring-cloud-contract#518]
If a contract file name contains a character that is invalid in a Java method name (like '-') the generated test will have a compile error since the name of the contract file is taken as a method name without converting invalid characters.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/pull/519

**Comment by marcingrzejszczak** [comment]
Argh this has broken the scenarios. I need to add a special case support.

**Comment by marcingrzejszczak** [comment]
Numbers are valid for method names. They shouldn't be escaped
