### ISSUE TITLE
Gradle Plugin creates Producer Tests though the project is actually a Consumer

### ISSUE THREAD

**Issue by thombergs** [spring-cloud/spring-cloud-contract#520]
When running `gradlew build` the `spring-cloud-contract-gradle-plugin` currently runs all of these tasks:

* `generateClientStubs`: 
   transforms input DSL contracts into wiremock JSON stubs in the **consumer** build
* `verifierStubsJar`: 
   generates a JAR file containing a runnable application stubbing the API in the **consumer** build
* `generateContractTests`: 
   generate unit tests verifying in the **provider** build

When I'm trying to just create the wiremock stubs on the consumer side, the producer-verifying unit tests are automatically created as well (and failing, because I'm actually in the gradle project of the consumer and thus have not configured them!). 

I see no (documented) way to run only the consumer-relevant gradle tasks or only the producer-relevant gradle tasks. Other than using the `-x` flag in the gradle console to exclude the tasks I don't want, but that's not a clean way.

I would expect either 
* a flag "I'm a consumer build" or "I'm a producer build" in the `contracts` configuration so that only the consumer- or producer-relevant tasks are executed on `build` or, even better
* that the plugin does not hook into the `build` task at all, letting the developer add `build.dependsOn' himself, and thus choose which tasks to run

**Comment by marcingrzejszczak** [comment]
If you're a consumer you shouldn't be using the plugin

**Comment by thombergs** [comment]
What are the `generateClientStubs` and `generateWireMockClientStubs` tasks for then? I successfully created a consumer build using those stubs to verify the consumer code against the contract (having to use `-x generateContractTests` to exclude the producer tests) 

Also, the reference says that it's OK that way ;)
http://cloud.spring.io/spring-cloud-contract/single/spring-cloud-contract.html#gradle-consumer

**Comment by marcingrzejszczak** [comment]
They generate client stubs, meaning stubs FOR a client.

I need to update that part of the docs then cause they are misleading. The idea in that part is that *if you're not using stub runner, then you have to create the stubs somehow*.

**Comment by thombergs** [comment]
But it makes perfect sense to create those wiremock stubs in the consumer build. This way you can directly test your client code against them and you have validated that the consumer obeys the contract even before involving the producer at all. Then you can be sure that you gave a valid contract to the producer.

Otherwise, the consumer potentially publishes a contract to the provider and the consumer code doesn't match the contract, and you have to go an extra round with another version of the contract.

So, I would call it a feature to be able to use the verifier plugin in a consumer build :).

**Comment by marcingrzejszczak** [comment]
> But it makes perfect sense to create those wiremock stubs in the consumer build. This way you can directly test your client code against them and you have validated that the consumer obeys the contract even before involving the producer at all. Then you can be sure that you gave a valid contract to the producer.

So what you should do is to go to the producer's code and call the wiremock stub generation and installation from that code. I think I describe the process here - http://cloud.spring.io/spring-cloud-static/Edgware.RELEASE/multi/multi__spring_cloud_contract_verifier_introduction.html#_step_by_step_guide_to_consumer_driven_contracts_cdc

> Otherwise, the consumer potentially publishes a contract to the provider that doesn't match the consumer code, and you have to go an extra round with another version of the contract.

That's why you have the stubrunner's offline mode flag (or LOCAL stubsmode in 2.0.0)

> So, I would call it a feature to be able to use the verifier plugin in a consumer build :).

That is a feature but one that should be used via stub runner :)

**Comment by thombergs** [comment]
OK, I think I understand the `workOffline` flag now :). 

It's a bit hard to gather from the manual, though. When I find the time, I'll make some suggestions.

**Comment by marcingrzejszczak** [comment]
Sorry to hear that. We're trying our best to make the manual as good as possible. There are also videos, guides and tutorials. If you have any suggestion to improve it - please be my guest.
