### ISSUE TITLE
regex(nonBlank()) in contract can generate compilation breaking characters

### ISSUE THREAD

**Issue by AIElemental** [spring-cloud/spring-cloud-contract#521]
(intially started here https://stackoverflow.com/questions/48265832/spring-cloud-contract-regexnonblank-generates-control-symbols/48266804#48266804)
in spring cloud contract I used regex(nonBlank()) to cover possible unicode characters in input.
But sometimes regex(nonBlank()) generates characters like \u0008 that break the compilation of generated java classes. That makes nonBlank() kind of unusable and unreliable, so i believe it is a bug(). 
Could you please help? (used scc version is 1.0.5-RELEASE)
Example contract:
```
package contracts.api
import org.springframework.cloud.contract.spec.Contract
Contract.make {
  request {
    method 'GET'
    urlPath('/v1/users') {
      queryParameters {
        parameter 'userId': value(regex(nonBlank()))
      }
    }
  }
  response {
    status 200
  }
}
```

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/4e08f77996b60b9ee3d33b5454b749614818cc36
