### ISSUE TITLE
Unexpected behaviour when using regex() in url

### ISSUE THREAD

**Issue by bart-blommaerts** [spring-cloud/spring-cloud-contract#525]
On version: 1.2.1.RELEASE

This works fine

        Contract.make {
            request {
                method 'PUT'
                url $(consumer('/path/microservice/v1/resources/123'), producer('/microservice/v1/resources/123'))
                headers {
                    // cut for brevity
                }
            }
            response {
                status 200
            }
        }

This however doesn't:

      Contract.make {
            request {
                method 'PUT'
                url $(consumer(regex('/path/microservice/v1/resources/[a-zA-Z0-9]{3}')), producer('/microservice/v1/resources/123'))
                headers {
                    // cut for brevity
                }
            }
            response {
                status 200
            }
        }

It returns this assertion error:

    assert value ==~ pattern
       |     |   |
       |     |   /path/microservice/v1/resources/[a-zA-Z0-9]{3}
       |     false
       /microservice/v1/resources/123

When I change to contract to (and adapt my RestContoller accordingly):

    Contract.make {
        request {
            method 'PUT'
            url $(consumer(regex('/path/microservice/v1/resources/[a-zA-Z0-9]{3}')), producer('/path/microservice/v1/resources/123'))
            headers {
                // cut for brevity
            }
        }
        response {
            status 200
        }
    }

It works again, proving the regex works correctly.

"path" is added by an API Gateway between producer and my consumer. I have little control over it.
I removed parts of the contract, to focus on the regex.

**Comment by marcingrzejszczak** [comment]
I mean it works exactly as it should. What happens here is fully expected.

You provide a regex `/path/...`. Your concrete implementation of the regex doesn't contain `/path` which means that it's not matching the regex. That's why we're breaking your test generation.

You can pass the regex like `[/path]+` and it should work.

**Comment by bart-blommaerts** [comment]
Thanks a lot Marcin for your quick response. That makes a lot of sense.
Just for future reference:

`[/path]+` doesn't work (one or more). `[/path]*` works (zero or more).

**Comment by marcingrzejszczak** [comment]
Ah true, I mixed the regex. Sorry about that :)
