### ISSUE TITLE
Support for Spring Reactive Web (Webflux)

### ISSUE THREAD

**Issue by markus1189** [spring-cloud/spring-cloud-contract#529]
### Question:

How can I use Spring Cloud Contracts together with the new Spring Web Reactive?

I have a Controller that returns a `Mono<SomePojo>` and a contract for that service testing a simple GET request to it.

1) If I only add
```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
    </dependency>
```

and run it via `mvn test`, then the test fails with
```
java.lang.NoClassDefFoundError: org/springframework/web/servlet/DispatcherServlet
```

2) When I also include the `spring-boot-starter-web`, it fails with

```
java.lang.AssertionError:                                                                  
                                                                                   
Expecting actual not to be null 
```

during the contract test.

**Comment by marcingrzejszczak** [comment]
Yeah, you can. You have to add the `web` bit in your tests and use the `EXPLICIT` mode of generating tests. That way you will send a real request to your application. Example is here (http://cloud.spring.io/spring-cloud-static/Edgware.SR1/single/spring-cloud.html#_working_with_context_paths)

**Comment by markus1189** [comment]
@marcingrzejszczak Yes that did it. Thanks!
