### ISSUE TITLE
Sample producer project with wiremock extension

### ISSUE THREAD

**Issue by paulvitic** [spring-cloud/spring-cloud-contract#533]
Question

I am trying to find a sample producer side setup to add wiremock extension to the packaged stub. The scenario is that I would like to provide a dynamic current date to consumer in the stubbed response. I think the only way to do this is to add a wiremock extension. However I could not find any producer project that provides a sample to achieve this.

Thank you.

**Comment by marcingrzejszczak** [comment]
There is no standalone sample but if you go through the documentation you can find a section related to it, with a test - https://cloud.spring.io/spring-cloud-static/Edgware.SR1/single/spring-cloud.html#_registering_your_own_wiremock_extension

**Comment by paulvitic** [comment]
Thank you for reply. I have actually seen this part of the documentation. However it is not very clear to me how I package the sample TestWireMockExtensions.groovy and META-INF/spring.factories declaration. Do I place them in the producer project together with the groovy contracts under my test/resources/contracts folder? Do I need to add any configuration to spring-cloud-contract maven plugin so that these resources are packaged together in the stub Jar?
Or do I place these artifact at the consumer side project classpath?

**Comment by marcingrzejszczak** [comment]
You create a separate project that contains the following structure:

```
src/main/java/com/example/transformer/MyTransformer.java
src/main/resources/META-INF/spring.factories
```

In `spring.factories` you define 

```
org.springframework.cloud.contract.verifier.dsl.wiremock.WireMockExtensions=\
com.example.MyTransfomer
```

Your `MyTransformer` would look sth like this:

```java
package com.example.transformer

import com.github.tomakehurst.wiremock.extension.Extension;
import org.springframework.cloud.contract.verifier.dsl.wiremock.DefaultResponseTransformer;

/**
 * Extension that registers the default transformer and the custom one
 */
class MyTransformer implements WireMockExtensions {
	@Override
	List<Extension> extensions() {
		return Arrays.asList(
				new DefaultResponseTransformer(),
				new CustomExtension()
		);
	}
}

// This class would be your extension
class CustomExtension implements Extension {

	@Override
	String getName() {
		return "foo-transformer";
	}
}
```

A Jar created from this project should be shared between all the projects that use the stubs. You need it on the producer side (in the maven plugin's classpath) to generate proper stubs and you need to have it on the consumer side for WireMock to understand what the extension means.

**Comment by paulvitic** [comment]
Thank you. It is clear now. Would it be a good idea to have a feature request so that instead of depending on a separate library, the extensions are packaged in a fat stub jar?

**Comment by marcingrzejszczak** [comment]
That wouldn't work for the users that use Stub Runner to download the jars. Also, you need to pass some additional code to make this work. I think it should be up to the user to do this. If you want to achieve it you can actually hook in, in (AFAIR) `process-test-resources` phase and copy whatever you need into `target/stubs/` directory. There's already `META-INF` there so you would have to copy `spring.factories` there, and you would have to pass your additional, compliled, transformer related code too. Then the stub jar generation task would generate the stub jar for you, together with your classes. But it sounds like a custom thing to do.
