### ISSUE TITLE
Differ NotNull and NotBlank

### ISSUE THREAD

**Issue by joaocolling** [spring-cloud/spring-cloud-contract#534]
Hello! 
I have a Conversation with Marcin Grzejszczak on Gitter.

I need to separate the behavior of consumer when pass null when pass blank.

On RFC of Json ([here](https://tools.ietf.org/html/rfc7159#section-1)) says it's possible null on fields. 

> JSON can represent four primitive types (strings, numbers, booleans,
   and null) and two structured types (objects and arrays).

For me notNull it's different than notBlank or notEmpty, because i really want know if is really null, but in contract i can't do this or at least not able to do this.

Appreciate your attention.
João Paulo Colling

**Comment by marcingrzejszczak** [comment]
The problem is related to this: http://wiremock.org/docs/request-matching/ 

> Deems a match if the attribute value is valid JSON and matches the JSON Path expression supplied. A JSON body will be considered to match a path expression if the expression returns either a non-null single value (string, integer etc.), or a non-empty object or array.

we can't use JSON Path to make a regex on a `null` value. If you provide a json path then automatically it should pick a `non-null` value.

Have you tested either of `notBlank` or `notEmpty` against a null value? It shouldn't get picked.

**Comment by marcingrzejszczak** [comment]
Ping @joaocolling ?

**Comment by joaocolling** [comment]
So, I can't differ because WM request matching consider null as blank or empty value. 
Ok Marcin! No problem.
Thank you for your attention!

**Comment by marcingrzejszczak** [comment]
No problem!
