### ISSUE TITLE
BigDecimal format causes exception in generated test

### ISSUE THREAD

**Issue by eginwong** [spring-cloud/spring-cloud-contract#537]
Bug Report:

`1.2.2.Release`

I have a large bigdecimal in my contract DSL:

For example:

```
"largeNum": 55534673.56,
```

But when the generated test runs, I get the following error:
`java.lang.RuntimeException: com.jayway.jsonpath.InvalidPathException: Expected character: )`

And the line that it fails on is:

```
     assertThatJson(parsedJson).array().contains("['largeNum']").isEqualTo(55534673.56);
```

For smaller bigdecimals, everything is as expected.

**Comment by marcingrzejszczak** [comment]
It's a bug in json assert that got fixed via - https://github.com/marcingrzejszczak/jsonassert/issues/19 . Waiting for sync to central and will bump the version in sc-contract.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/83e304008e3f746ccaad97c6051bbf47555d278a
