### ISSUE TITLE
Change default layout of stubs jar files

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-contract#54]
I think the current layout is too flat, since once a jar is unpacked or inserted on a classpath there is no way to tell the origin of the contracts and mappings. My proposal is `/META-INF/[mappings,contracts]/<groupId>/<artifactId>/<version>/*` instead of `/[mappings,contracts]/*`. Note that WireMock already knows natively how to register stubs from a directory containing `/mappings/**` (that's why we want that at the top of the path).

P.S. I know we don't add stubs to any classpath in the stub runner, but it's a jar file in a Maven repo, so it's easy to do, and could be used to run Wiremock "manually" without the stub runner.

**Comment by dsyer** [comment]
Actually, I might have talked my self into `/META-INF/<groupId>/<artifactId>/<version>/[mappings,contracts]/*` because you would want to run stubs from a different service on a different port, typically, so the `/mappings` directories need to be segregated.

**Comment by marcingrzejszczak** [comment]
On the other hand WireMock won't be default pick this location. But we're going to build a solution that will pick up those locations so it doesn't matter at the end.

**Comment by marcingrzejszczak** [comment]
This is crucial to be done cause when using the DSL based solution all mappings for different applications end up in the same folder. We can't tell which mappings belong to which service.
