### ISSUE TITLE
Use "request.body" instead of "this" in YAML templates

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-contract#540]
Wiremock supports response templates like

```
{{jsonPath request.body '$.outer.inner'}}
```

so when we use 

```
{{{ jsonpath this '$.name' }}}
```

it's a bit confusing (even if it works somehow).

Also, the different spelling of the helper method is confusing (`jsonPath` vs. `jsonpath`), as is the triple handlebar (no escapes, apparently - why is it necessary?).

**Comment by marcingrzejszczak** [comment]
> no escapes, apparently - why is it necessary?

We're using handlebars for code too, so we didn't want it to be escaped. Apparently, WireMock didn't care in the stubs or at runtime.

**Comment by marcingrzejszczak** [comment]
I've started work on this but it's not as simple as I thought it would be. That's why I'm putting into backlog since fixing this will give us no real benefits other than the syntax change.

**Comment by mmatecki** [comment]
Hi,
`jsonpath this '$.x'` is not working with wiremock 2.18.0. I have to change it to `jsonPath request.body '$.x'` manually.
Please, could you put somewhere in that issue Wiremock's version, generated jsons work properly with?

**Comment by marcingrzejszczak** [comment]
All of our tests are executed against WireMock 2.18 so most likely you did something wrong (or we have a bug that I'm not familiar with). Can you create a sample that replicates the problem?

**Comment by mmatecki** [comment]
Here's the demo: https://github.com/mmatecki/scv-jsonpath-issue
I think that I could create the new issue as this one I have is not related to the YAML. Let me know if you want to track this in the separate issue so I'll create one.

**Comment by marcingrzejszczak** [comment]
Ah! Of course it won't work in the way you presented cause the default, standalone WireMock instance doesn't have our transformer. There's no way that it would work.

**Comment by marcingrzejszczak** [comment]
BTW I don't understand why would `{{...}}` work in the first place. 

Having such a stub definition. 

```json
{
  "id" : "51b077b3-2bfd-40d5-abe6-fe104a447fa7",
  "request" : {
    "urlPath" : "/api/v1/xxxx",
    "method" : "POST",
    "headers" : {
      "Authorization" : {
        "equalTo" : "secret2"
      }
    },
    "queryParameters" : {
      "foo" : {
        "equalTo" : "bar2"
      }
    },
    "cookies" : {
      "foo" : {
        "equalTo" : "bar"
      }
    },
    "bodyPatterns" : [ {
      "matchesJsonPath" : "$[?(@.['baz'] == 5)]"
    }, {
      "matchesJsonPath" : "$[?(@.['foo'] == 'bar')]"
    } ]
  },
  "response" : {
    "status" : 200,
    "body" : "{\"authorization\":\"{{request.headers.Authorization.[0]}}\",\"path\":\"{{request.path}}\",\"responseBaz\":{{jsonPath request.body '$.baz'}} ,\"param\":\"{{request.query.foo.[0]}}\",\"pathIndex\":\"{{request.path.[1]}}\",\"responseBaz2\":\"Bla bla {{jsonPath request.body '$.foo'}} bla bla\",\"responseFoo\":\"{{jsonPath request.body '$.foo'}}\",\"authorization2\":\"{{request.headers.Authorization.[1]}}\",\"fullBody\":\"{{{request.body}}}\",\"url\":\"{{request.url}}\",\"paramIndex\":\"{{request.query.foo.[1]}}\"}",
    "headers" : {
      "Authorization" : "{{request.headers.Authorization.[0]}};foo"
    },
    "transformers" : [ "response-template", "foo-transformer" ]
  },
  "uuid" : "51b077b3-2bfd-40d5-abe6-fe104a447fa7"
}
```

When I send it to WireMock and CURL

```
$ curl -X POST --header "Authorization: secret2" --data '{"baz":5, "foo": "bar"}' --cookie "foo=bar" http://localhost:8080/api/v1/xxxx\?foo\=bar2
```

I get

```json
{"authorization":"secret2","path":"/api/v1/xxxx","responseBaz":5 ,"param":"bar2","pathIndex":"v1","responseBaz2":"Bla bla bar bla bla","responseFoo":"bar","authorization2":"","fullBody":"{"baz":5, "foo": "bar"}","url":"/api/v1/xxxx?foo&#x3D;bar2","paramIndex":""}
```

As you can see the URL is broken. In order to ensure that the data is NOT escaped to HTML (it is escaped by Handlebars when you do `{{}}`) you have to use `{{{ }}}`

**Comment by marcingrzejszczak** [comment]
Yeah... RTFM (http://wiremock.org/docs/response-templating/)

```
request.body - Request body text (avoid for non-text bodies)
```

That's the reason why...

**Comment by marcingrzejszczak** [comment]
Ok, with latest snapshots you will be able to produce WireMock JSON stubs. I've invested time to make those changes backward compatible.
