### ISSUE TITLE
Custom method not referenced in generated test code

### ISSUE THREAD

**Issue by paulvitic** [spring-cloud/spring-cloud-contract#541]
Question

I am trying to use custom method for a multipart parameter value as follows
```groovy
request {
        method 'POST'
        url('/some/url')
        multipart(
                username: $(
                        c('someusername'),
                        p(execute('getUsername()'))),
                password: 'tester'
        )
    }
```

However the generated test code does not refer to the custom method but inserts the method name as literal string

```java
MockMvcRequestSpecification request = given()
					.param("username", "getUsername()")
					.param("password", "tester");
```

Could you please advise what I am doing wrong

**Comment by marcingrzejszczak** [comment]
I don't think we support this for multipart, that's why. Which apparently is a bug.
