### ISSUE TITLE
Question, should we do contract test in each microservice? 

### ISSUE THREAD

**Issue by jeven2016** [spring-cloud/spring-cloud-contract#544]
Hi team,
    Thanks for sharing such  awesome opensource project, and we plan to do contract test in our project after a meeting.  But I have a question on the best practices, should we do contract test in each microservice

Say we have threse microservices:
A --> B --> C
should we do contract test in all of them?  is any best practices for reference?

Thanks  : )

**Comment by marcingrzejszczak** [comment]
Thank you for the kind words.

The answer is that in most cases yes, you should test all of them. However if B is a technical service (like Zuul) you should follow these guidelines: https://github.com/spring-cloud/spring-cloud-contract/issues/450
