### ISSUE TITLE
Maven local repository configuration for stub runner

### ISSUE THREAD

**Issue by pivotal-radojko-drcelic** [spring-cloud/spring-cloud-contract#552]
If maven `settings.xml` is in {somewhere}/conf (or some other custom location) then `@AutoConfigureStubRunner` with `workOffline=true` is scanning  `~/.m2` looking for settings.xml and since we don’t have one there, it falls back to looking for local repository under `~/.m2/reposotory` !!! We are using `spring-cloud-contract-stub-runner` `1.2.3.RELEASE`. Does `@AutoConfigureStubRunner` scans only `~/.m2` looking for `settings.xml` and disregards custom maven configurations?

**Comment by marcingrzejszczak** [comment]
The code that is responsible for reading `settings.xml` is here https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/AetherFactories.java#L68-L73 .

All 3 system properties that can override the location are

```
private static final String MAVEN_LOCAL_REPOSITORY_LOCATION = "maven.repo.local";
	private static final String MAVEN_USER_SETTINGS_LOCATION = "org.apache.maven.user-settings";
	private static final String MAVEN_GLOBAL_SETTINGS_LOCATION = "org.apache.maven.global-settings";
```

Let's ensure that the documentation clearly states how to override these values. Also, most likely, each user has an environment variable, not a system property.
