### ISSUE TITLE
Incorrect reference to workOffline in Quick Start docs

### ISSUE THREAD

**Issue by benwatson528** [spring-cloud/spring-cloud-contract#553]
In the Quick Start section of https://cloud.spring.io/spring-cloud-contract/, `workOffline` is mentioned in the second-from-last code block and the paragraph of text immediately below that. However `workOffline` is not a valid argument to the `AutoConfigureStubRunner` annotation, at least for the Spring Cloud Contract version used by default in the Quick Start (2.0.0 M6).

I believe it should instead use `stubsMode = StubRunnerProperties.StubsMode.LOCAL`.

**Comment by marcingrzejszczak** [comment]
The property will change in 2.0.0. In the aforementioned page we reference a latest GA version. Anyways thanks for reminding about this
