### ISSUE TITLE
Question - any way to leverage existing JSON-schema definitions in spring cloud contract?

### ISSUE THREAD

**Issue by retrocode** [spring-cloud/spring-cloud-contract#557]
We have many existing JSON-schema definitions that we currently use to establish contracts between service consumers and producers. We would also like to use Spring Cloud Contract but are somewhat reluctant to have to re-implement our message body responses in the contract DSL (either Groovy or YAML). Is there any way to achieve this?

**Comment by marcingrzejszczak** [comment]
> JSON-schema definitions

contracts are not schemas. If you want to reuse whatever you have in your company and you can generate usage scenarios out of it, it's enough for you to use your own converter as described in the documentation - https://cloud.spring.io/spring-cloud-static/Edgware.SR2/multi/multi__using_the_pluggable_architecture.html#_custom_contract_converter

**Comment by retrocode** [comment]
Thanks, I get contracts are not schemas - but in our case schemas are a representation of the response body structure. 
At the end of the day we need to create a org.springframework.cloud.contract.spec.Contract with a response.body. Using the DSL we'd be creating this body structure to essentially match the structure of the schema (which can contain hierarchical elements and get quite complicated)

**Comment by marcingrzejszczak** [comment]
So with a converter you could just pass the piece of your schema as a String representation of the body.
