### ISSUE TITLE
Add configuration such that stubrunner cloud related properties are available in spring-configuration-metadata.json

### ISSUE THREAD

**Issue by thekalinga** [spring-cloud/spring-cloud-contract#566]
# Enhancement

Currently spring-cloud-contract-stubrunner autogenerated `spring-configuration-metadata.json` does not have any configuration w.r.t `stubrunner.cloud.enabled`, `stubrunner.cloud.ribbon.enabled`, `stubrunner.stream.enabled` & others.

Since these are not available in `spring-configuration-metadata.json`, IDEs cannot suggest these cloud related properties in their suggestions when editing configuration files. Please add these properties to `spring-configuration-metadata.json` either via `additional-spring-configuration-metadata.json` or via `@ConfigurationProperties`

Refer [here](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#configuration-metadata-additional-metadata) for more details

**Comment by marcingrzejszczak** [comment]
Thanks for reminding how to do that ;)

Can you provide a list of missing properties? That will be much easier for us to set them. Also feel free to create the beans as a pr :)

**Comment by thekalinga** [comment]
@marcingrzejszczak 

Looks like you have accessed a large number of these properties via `@Value` instead of `@ConfigurationProperties` (eg. `StubRunnerSpringCloudAutoConfiguration`)

I can see that `spring.factories` are set to

```properties
# Auto Configuration
org.springframework.cloud.contract.stubrunner.spring.AutoConfigureStubRunner=\
org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration,\
org.springframework.cloud.contract.stubrunner.spring.cloud.StubRunnerSpringCloudAutoConfiguration,\
org.springframework.cloud.contract.stubrunner.spring.cloud.ribbon.StubRunnerRibbonAutoConfiguration,\
org.springframework.cloud.contract.stubrunner.messaging.stream.StubRunnerStreamConfiguration,\
org.springframework.cloud.contract.stubrunner.messaging.integration.StubRunnerIntegrationConfiguration,\
org.springframework.cloud.contract.stubrunner.spring.cloud.zookeeper.StubRunnerSpringCloudZookeeperAutoConfiguration,\
org.springframework.cloud.contract.stubrunner.spring.cloud.eureka.StubRunnerSpringCloudEurekaAutoConfiguration,\
org.springframework.cloud.contract.stubrunner.spring.cloud.consul.StubRunnerSpringCloudConsulAutoConfiguration,\
org.springframework.cloud.contract.stubrunner.messaging.StubRunnerStreamsIntegrationAutoConfiguration
```

So my understanding is that all these properties in each of the `*AutoConfiguration` classes that are accessed via `@Value` (or) `@ConditionalOnProperty` should be included in `additional-spring-configuration-metadata.json`

(or)

Change the code to use `@ConfigurationProperties` instead of `@Value` so that the generated `spring-configuration-metadata.json` would automatically contain new properties. Also,  `@ConfigurationProperties` gives additional advantage of validation during binding

**Comment by thekalinga** [comment]
Here are the properties I could find

```
stubrunner.cloud.consul.enabled
stubrunner.cloud.enabled
stubrunner.cloud.delegate.enabled
stubrunner.cloud.stubbed.discovery.enabled
stubrunner.cloud.ribbon.enabled
stubrunner.cloud.zookeeper.enabled
stubrunner.integration.enabled
stubrunner.stream.enabled
```

Please note that these are exhaustive list. If you are the owner of the project, you might have better context of whether any properties are missing or not

**Comment by marcingrzejszczak** [comment]
Your assumption is correct (both how to fix it and the ownership). Thanks for at least part of the list, I'll try to look into it.
