### ISSUE TITLE
Add a convenience mechanism to get stub runner port

### ISSUE THREAD

**Issue by shanman190** [spring-cloud/spring-cloud-contract#573]
It would be nice to have a helper mechanism to acquire the stub runner port of a given producer. Thinking in a similar fashion to the [LocalServerPort](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/server/LocalServerPort.java) from Spring Boot. Maybe an API that looks something like:

```
@StubRunnerPort("beer-api-producer")
private int beerApiProducerPort
```

Using the [BeerControllerTest](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/master/consumer/src/test/java/com/example/BeerControllerTest.java) as the basis for the example.

**Comment by marcingrzejszczak** [comment]
You can already user the property that allows you to access that prop, right? But maybe an additional annotation can be useful

**Comment by shanman190** [comment]
@marcingrzejszczak, absolutely true. We talked about it a little bit at SpringOne this last year. It was more a convenience, readability type of thing than anything.

**Comment by marcingrzejszczak** [comment]
Stub Runner Spring registers environment variables in the following manner
for every registered WireMock server. Example for Stub Runner ids
 `com.example:foo`, `com.example:bar`.

- `stubrunner.runningstubs.foo.port`
- `stubrunner.runningstubs.com.example.foo.port`
- `stubrunner.runningstubs.bar.port`
- `stubrunner.runningstubs.com.example.bar.port`

Which you can reference in your code.

You can also use the `@StubRunnerPort` annotation to inject the port of a running stub.
Value of the annotation can be the `groupid.artifactid` or just the `artifactid`. Example for Stub Runner ids
`com.example:foo`, `com.example:bar`.

```java
@StubRunnerPort("foo")
int fooPort;
@StubRunnerPort("com.example:bar")
int barPort;
```
