### ISSUE TITLE
Add support for built in HTTP status response codes

### ISSUE THREAD

**Issue by thekalinga** [spring-cloud/spring-cloud-contract#575]
Type: Enhancement

Currently we have to type response codes manually such as 200, 403, e.t.c as part of response closure. Though it is not that hard to remember most commonly used response codes, its not easy to remember the meaning of each response code.

It would be much more helpful for developers if there is a provision for uses to use methods like `ok()` which can refer to HTTP status code `200`

This can function similar to existing API of `HttpHeaders` which allows users to write `accept()` instead of typing `'Accept'`

This makes the API less error prone & more readable

**Comment by thekalinga** [comment]
This class [HttpStatus](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/HttpStatus.java) can be used as a reference for this

**Comment by marcingrzejszczak** [comment]
That's a great option for a first PR. A good reference is the `org.springframework.cloud.contract.spec.internal.HttpHeaders`.
