### ISSUE TITLE
Add support for named, shared global & local sequences

### ISSUE THREAD

**Issue by thekalinga** [spring-cloud/spring-cloud-contract#577]
# Type: Enhancement

Assuming that we have the following contracts for a simple task management application with two APIs

1. List tasks ordered by latest first

```groovy
import static java.util.stream.Collectors.toList
import static org.springframework.cloud.contract.spec.Contract.make

make {
  request {
    method GET()
    urlPath('/tasks/latest')
  }
  response {
    def responseBody = (10..1).stream()
        .map({ _ ->
          return [
              id       : it,
              name     : "Task ${it}",
              completed: anyBoolean()
          ]
        })
        .collect(toList())
    status 200
    headers {
      header(contentType(), applicationJson())
    }
    body(responseBody)
  }
}
```

2. Save a new Task

```groovy
import static org.springframework.cloud.contract.spec.Contract.make

make {
  request {
    method POST()
    urlPath('/tasks')
    headers {
      header(contentType(), applicationJson())
      header(accept(), applicationJson())
    }
    body([
        name: anyNonBlankString()
    ])
  }
  response {
    status 200
    headers {
      header(contentType(), applicationJson())
    }
    body([
        id       : anyNumber(),  // <<---- Numeric sequence, either enter manually/random value can be generated via `anyNumber()`
        name     : fromRequest().body('$.name'),
        completed: false
    ])
  }
}
```

State sharing is a problem with each of the above APIs.

To start with, we should support light weight state sharing such as shared sequences across requests & across contracts. Currently there is no way to generate predictable numbers across either multiple contracts (or) across requests.

In the above two examples, we either have to return fixed number/random number (which gets generated by `anyNumber()`) which does not satisfy the predictable number generation that can only achieved via shared sequences

## Global shared sequence

It would be much more helpful if you can expose an API like `def taskSequence = sequence('task', 1)` that  can give predictable next int via `taskSequence.next()` & `taskSequence.current()` for a sequence with name `task` with a starting value of `1` if task was not already created

This sequence is global sequence, meaning this is shared across contracts & across requests. An usecase for this might be an API listing last 10 tasks created

With this changes, the APIs would look like this

```groovy
import static java.util.stream.Collectors.toList
import static org.springframework.cloud.contract.spec.Contract.make

make {
  request {
    method GET()
    urlPath('/tasks/latest')
  }
  response {
    def latestTaskId = sequence('tasks', 0).current()
    def responseBody
    if (latestTaskId > 0) {
      responseBody = (latestTaskId..1).stream()
          .map({ ->
            return [
                id       : it,
                name     : "Task ${it}",
                completed: anyBoolean()
            ]
          })
          .collect(toList())
    } else {
      responseBody = []
    }
    status 200
    headers {
      header(authorization(), anyNonBlankString())
      header(contentType(), applicationJson())
    }
    body(responseBody)
  }
}
```

In this example, `sequence('tasks')` is a global sequence with starting value of `0`

## Local shared sequence

We also might need to support sequences that are specific to a single contract, i.e shared across requests, but local to a single contract. For example, creating a predictable task sequence when creating tasks. It can be achieved via a new method `def taskLocalSeq = localSequence(1)`. The next value can be accessed via `taskLocalSeq.next()` & current val can be accessed via `taskLocalSeq.current()`

With this, UI developers can expect consistent sequence of numbers, when they are testing the API.

```groovy
import static org.springframework.cloud.contract.spec.Contract.make

make {
  request {
    method POST()
    urlPath('/tasks')
    headers {
      header(authorization(), anyNonBlankString())
      header(contentType(), applicationJson())
      header(accept(), applicationJson())
    }
    body([
        name: anyNonBlankString()
    ])
  }
  response {
    status 200
    headers {
      header(contentType(), applicationJson())
    }
    body([
        id       : sequence('task', 1),
        name     : fromRequest().body('$.name'),
        completed: false
    ])
  }
}
```

In the second example, `sequence('task', 1)` is a global sequence starting with a value of `1`

Note that, we could have used `localSequence('task', 1)` had we intended not to share the task sequence globally if usecase demanded it

Please let me know your thoughts

**Comment by marcingrzejszczak** [comment]
My thoughts are that this is the most complicated example of contract tests I have ever seen and I completely don't understand what kind of a problem you are trying to solve. Contract tests are about semantics and logic and you're trying to enforce some sort of shared state between contracts.

If you have 2 endpoints, one that saves a task, the other that lists then you should have 2 very basic contracts and that's it. I think you're misunderstanding the purpose of the tool or maybe I didn't understand your ideas.

**Comment by thekalinga** [comment]
I'm looking at the generated API from the standpoint of view of the UI developers.

If there is a simple way to generated shared numbers, it makes somewhat predictable mock APIs, like I mentioned in the above examples

**Comment by marcingrzejszczak** [comment]
What does this **generated shared numbers** even mean? Just create 2 simple contracts. One for `POST` and one for `GET`. I completely don't understand this problem.

Contract tests are about ensuring that we can communicate, and not about replicating the business logic. You should use the stubs to validate the communication piece from the UI. All the other tests from the UI should not even make a call to the stubs but return a faked response.

**Comment by thekalinga** [comment]
We are not replicating business logic here. We are just giving a mock API that helps UI developers with some predictable mock API

They don't depend on these sequences for their development, instead it makes API a bit predictable so that UI page refreshes will not give random/same static response as it was on the first instance

There is a middle ground between complete stateless APIs(which is what we have now) & full blown business logic implementation.

A sequence is very similar to database sequence that shared across all requests & contracts represented by an atomic long/int. With this APIs can be made more UI developer friendly with predictable mock APIs. Note that these are still mock APIs, we are not developing the whole API here in mock APIs

**Comment by marcingrzejszczak** [comment]
> They don't depend on these sequences for their development, instead it makes API a bit predictable so that UI page refreshes will not give random/same static response as it was on the first instance

So provide a fixed value for refreshing. Instead of `anyNumber()` just provide a concrete value

> A sequence is very similar to database sequence that shared across all requests & contracts represented by an atomic long/int. With this APIs can be made more UI developer friendly with predictable mock APIs. Note that these are still mock APIs, we are not developing the whole API here in mock APIs

In which case I would put a concrete value

**Comment by thekalinga** [comment]
Looks like I failed so far in making an argument for the sequence usecase

Lemme explain this with a usecase

Here are usecases UI guys want to test

1. Accessing `/tasks/latest` is called for the first time, return zero results
2. They add couple of tasks via `/test`
3. Refresh page for `/tasks/latest` should return as many results as there are tasks added till now (only as many as the user added so far, no more, no less)

How can you achieve this with current API without shared state

**Comment by thekalinga** [comment]
This is one of the most common usecase.

Plz note we are not implementing the actual business logic, which might be quite complex. This is just dumb, but not so dump (because of shared state) contract

**Comment by marcingrzejszczak** [comment]
I would solve this problem in the following manner

I would write 2 contracts for `/tasks/latest`

- latest_tasks_1.groovy - GET /tasks/latest (returns 0 elements)
- latest_tasks_2.groovy - GET /tasks/latest (returns 5 elements)

`contracts for /test`

- test.groovy - `POST /test` returns OK

and that's it. Both these contracts have nothing to do with each other in terms of any logic on the stub side. E.g. I call `POST` once and I still get 5 results back. Or I don't call `POST` at all and I get 5 results back. I would test these two features completely separately.

If you want to really ensure that if you send the POST then it will reflect in the latest tasks then you have to start a separate app and run end to end tests cause this is business logic.

**Comment by thekalinga** [comment]
Sorry, I have initially sent wrong API paths (which I have updated already)

The contracts we need to satisfy are

`GET /tasks/latest` & `POST /tasks`

`POST /tasks` adds a task
`GET /tasks/latest` retrieves existing tasks

> If you want to really ensure that if you send the POST then it will reflect in the latest tasks then you have to start a separate app and run end to end tests cause this is business logic.
This will any way has to be tested on the server side via tests.

I'm taking about UI developer experience when working with mocks. With shared state (somewhat) predictable mock API experience can be achieved. I vaguely remember long back @dsyer talking about shared state when working with contracts long back

Hope he can chip in here

**Comment by marcingrzejszczak** [comment]
I think I cannot pass any other answer than the one that I provided previously. That's why I'm closing this issue
