### ISSUE TITLE
Delay random number generation to runtime

### ISSUE THREAD

**Issue by thekalinga** [spring-cloud/spring-cloud-contract#582]
Question

Most of the APIs such as `POST /tasks` expect a mock response with unique id per call, so that UI can be tested with multiple unique values (tasks in this example)

```
{
  id: 1, << this value should be unique per call at runtime
  ...
}
```

But the contract API seems to be generating fixed random number in advance at build time & returns only this build time fixed value at runtime instead of generating one at runtime.

Since this is a common requirement, we should delay the number generation to runtime.

Testcase:
```groovy
import static org.springframework.cloud.contract.spec.Contract.make

make {
  request {
    method GET()
    urlPath('/random')
  }
  response {
    status 200
    body([
        directRandom       : Math.random(),
        anyNumber       : anyNumber(),
    ])
  }
}
```

One would expect the above API to generate random number per GET, but it returns the same value irrespective of the number of time the API is called

**Comment by marcingrzejszczak** [comment]
`anyNumber()` is indeed a fixed value for the producer and that's a good way to do it. There's no obligation to always generate a new value (it's a contract tests, not a functional test). If you need a unique value being generated you can call the new Random as you wrote.

**Comment by thekalinga** [comment]
Even the random is generating a fixed value

**Comment by thekalinga** [comment]
Can u share an example where I can generate a ransom value per call

**Comment by thekalinga** [comment]
Also a section from wiremock

> Sometimes, returning wholly static responses to stub requests isn’t practical e.g. when there are transaction IDs being passed between request/responses, dates that must be current. Via WireMock’s extension mechanism it is possible to dynamically modify responses, allowing header re-writing and templated responses amongst other things.

http://wiremock.org/docs/extending-wiremock/

So, we do need dynamic value support, such generating current date, e.t.c

**Comment by thekalinga** [comment]
One more project that developed wiremock extensions

https://github.com/teads/wiremock-extensions

**Comment by thekalinga** [comment]
I think the issue need to be reopened as currently there is no provision to do what is mentioned in the issue (neither dynamic number nor dynamic date).
