### ISSUE TITLE
Messaging contracts per topic support in spring-cloud-contract-maven-plugin

### ISSUE THREAD

**Issue by anikitchuk** [spring-cloud/spring-cloud-contract#584]
Each producer that supports [messaging contracts per topic](https://github.com/spring-cloud/spring-cloud-contract/blob/master/docs/src/main/asciidoc/verifier_faq.adoc#how-can-i-define-messaging-contracts-per-topic-not-per-producer) needs to duplicate the part of the logic in its pom that is probably could be hidden inside spring-cloud-contract-maven-plugin, especially downloading and unpacking the jar with contracts from common repo by maven-dependency-plugin: 

```
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-dependency-plugin</artifactId>
   <version>3.0.0</version>
   <executions>
      <execution>
         <id>unpack-dependencies</id>
         <phase>process-resources</phase>
         <goals>
            <goal>unpack</goal>
         </goals>
         <configuration>
            <artifactItems>
               <artifactItem>
                  <groupId>com.example</groupId>
                  <artifactId>common-repo</artifactId>
                  <type>jar</type>
                  <overWrite>false</overWrite>
                  <outputDirectory>${project.build.directory}/contracts</outputDirectory>
               </artifactItem>
            </artifactItems>
         </configuration>
      </execution>
   </executions>
</plugin>
```

and deleting unused contracts by maven-antrun-plugin: 
```
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-antrun-plugin</artifactId>
   <version>1.8</version>
   <executions>
      <execution>
         <phase>process-resources</phase>
         <goals>
            <goal>run</goal>
         </goals>
         <configuration>
            <tasks>
               <delete includeemptydirs="true">
                  <fileset dir="${project.build.directory}/contracts">
                     <include name="**/*" />
                     <!--Producer artifactId-->
                     <exclude name="**/${project.artifactId}/**" />
                     <!--List of the supported topics-->
                     <exclude name="**/${first-topic}/**" />
                     <exclude name="**/${second-topic}/**" />
                  </fileset>
               </delete>
            </tasks>
         </configuration>
      </execution>
   </executions>
</plugin>
```
So could the spring-cloud-contract-maven-plugin be extended to support the above logic?

**Comment by marcingrzejszczak** [comment]
Care for a PR to both Maven and Gradle plugins? :)

**Comment by anikitchuk** [comment]
I knew your answer :) I'd love to, but I'm worrying about the time and effort :)

**Comment by anikitchuk** [comment]
Hi @marcingrzejszczak, as part of this issue, I'm going to change maven plugin at first to have an ability to pass a list of `contractDependencies` to be downloaded from `contractsRepositoryUrl` since we could have not only one common repository with contracts. And also I'm going to add some list of filter patterns for including messaging topics and producers that would be disabled by default. 
That is how I see it: 

```
<contractsRepositoryUrl>http://link/to/your/nexus/or/artifactory/or/sth<contractsRepositoryUrвl>
<contractDependencies>
    <contractDependency>
        <groupId>com.example.*</groupId>
        <artifactId></artifactId>
    </contractDependency>
        <groupId>com.example.*</groupId>
        <artifactId></artifactId>
    <contractDependency>
</contractDependencies>
<filterProducers>
    <filterProducer>producer</filterProducer>
    <filterProducer>kafka-topic</filterProducer>
</filterProducers>
```
What do you think of it?

**Comment by marcingrzejszczak** [comment]
Do we really need to have multiple contract dependencies? That looks like an unnecessary complexity being introduced.

Also, I'm looking through the current plugin capabilities and we have exclusion options (e.g. Maven)

```java
@Parameter
private List<String> excludedFiles;
```

maybe we could do sth similar for explicit, configurable inclusion. There are already properties that we're reusing for that purpose.

`org.springframework.cloud.contract.verifier.config.ContractVerifierConfigProperties#includedContracts` and `org.springframework.cloud.contract.verifier.config.ContractVerifierConfigProperties#includedRootFolderAntPattern`

You can't however set them. They get updated afterward. Maybe that would be a better way to go - I'd like to break as little as possible. WDYT?

**Comment by anikitchuk** [comment]
According to multiple contract dependencies - yes, that what we need for our project, because of multiple common repositories. I'll take a look at the properties you'we provided.

**Comment by marcingrzejszczak** [comment]
I'm sorry I don't understand the concepts of studios. 

I think that you're trying to alter a quite simple scenario to your company's requirements. I don't feel those requirements ATM.

I would like to have all contracts available for a given destination. I don't see any reason why those shouldn't be placed in a single repository.

**Comment by anikitchuk** [comment]
Hi @marcingrzejszczak I've made a PR for maven plugin, pls review. 
And also back to the multiple common repos theme, what if we pass additional repos via ```contractsProperties``` https://github.com/spring-cloud/spring-cloud-contract/blob/b7baea3deea8744bb1e00e64284fafc9b5b7bc02/spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/main/java/org/springframework/cloud/contract/maven/verifier/GenerateTestsMojo.java#L216, and later will parse and download dependencies. Seems to be that what you expect, break as little as possible) What do you think?

**Comment by marcingrzejszczak** [comment]
I like the PR! It looks very simple and concrete. For sure we won't merge it for 2.0.0 but for 2.1.0 - why not? I'll do some further checks before that release. 

As for the multiple repos. Again, I think it's some requirement you have in your company. What I would do is use the `contractsProperties` as you mentioned and I would write a project inside your company that would provide a custom `StubDownloaderBuilder` (https://cloud.spring.io/spring-cloud-static/Finchley.RC1/multi/multi__using_the_pluggable_architecture.html#_using_the_custom_stub_downloader) that would get the aforementioned property and do all the things you want it to do. WDYT?

**Comment by vasilievip** [comment]
> I think it's some requirement you have in your company

Yep, this is our internal hell :)

>that would get the aforementioned property and do all the things you want it to do. WDYT?

We just started this repo-per-studio + repo-with-common-services approach and will evaluate any suggestion/option available. 
Custom stubs downloader seems easy to implement. Thanks!

**Comment by TYsewyn** [comment]
Honestly I think it makes more sense to provide an exclusion pattern rather than an inclusion pattern.
That way it works in the same way like before when we deleted unused contracts using the maven-antrun-plugin.
It also gives a more natural feel to the setup: once you have an agreement your application should always be validated upon that agreement.
Next to that, I also think people are going to make less errors with this setup.
If you forgot to exclude a contract by accident then you'll definitely notice it when your build fails.
In your proposal you won't notice anything unless it's too late when you accidentally forgot to include a contract.
WDYT @anikitchuk, @vasilievip, @marcingrzejszczak?

**Comment by marcingrzejszczak** [comment]
> That way it works in the same way like before when we deleted unused contracts using the `maven-antrun-plugin`.

That's a valid point.

> It also gives a more natural feel to the setup: once you have an agreement your application should always be validated upon that agreement.

Sure, but what about the case where you have a lot of queues and you use only one? Then you have all bunch of exclusions to be written.

> Next to that, I also think people are going to make less errors with this setup.
> If you forgot to exclude a contract by accident then you'll definitely notice it when your build fails.

I feel that including the queue names that you're using is more intuitive, but that's my personal opinion.

> In your proposal you won't notice anything unless it's too late when you accidentally forgot to include a contract.

If we include too much, our build will break cause we are not compliant with those contracts. If we include too little, indeed the tests will pass and the consumers will fail. You might make the mistake of not including enough contracts.

I feel that the inclusion is more natural than the exclusion now, but I don't have an opinion on this. Let's keep this discussion going and share opinions.

**Comment by TYsewyn** [comment]
> Sure, but what about the case where you have a lot of queues and you use only one? Then you have all bunch of exclusions to be written.

Correct, but that's the pitfall of using a shared repository across different applications.
You'll always want to verify each and every contract when you have a repository per application.

> I feel that including the queue names that you're using is more intuitive, but that's my personal opinion.

If you put it like that I completely agree. :)

> If we include too much, our build will break cause we are not compliant with those contracts. If we include too little, indeed the tests will pass and the consumers will fail. You might make the mistake of not including enough contracts.

I'd rather have a failing build than a failing production environment tbh. ¯\\_(ツ)_/¯

**Comment by anikitchuk** [comment]
@TYsewyn, thanks for your feedback, as for me that implemented way seems to be more intuitive too. In our specific case, we don't have a repo per application, but per business unit. And for that reason, we need to verify only certain contracts. 
Btw, @marcingrzejszczak thanks for the like, I knew 2.0.0 in RC now, but is there any ETA for 2.1.0?

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/pull/651
