### ISSUE TITLE
AutoConfigureStubRunner should automatically scan for all stubs

### ISSUE THREAD

**Issue by jkubrynski** [spring-cloud/spring-cloud-contract#586]
When stubs exists on the classpath (for example because they are added to the pom.xml) AutoConfigureStubRunner should automatically scan for all stubs, without the requirement of setting `ids`

**Comment by marcingrzejszczak** [comment]
It won't work that way cause we assume one stub configuration per unpacked file. Here, you would have one configuration per multiple files and ports. We don't want to support that right now, but we'll keep this feature request in mind for future work.
