### ISSUE TITLE
Fix http-server-restdocs so that subs get packaged and deployed by gradle

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-contract#59]
The http client tests only pass in gradle because the Maven build of the server is working. We should make sure somehow that the server builds its own stubs with gradle.

**Comment by marcingrzejszczak** [comment]
Fixed https://github.com/spring-cloud/spring-cloud-contract/commit/e0f206689ed12b63469e6ac10ed26c72b24481f2
