### ISSUE TITLE
spring-cloud-contract-wiremock: ResourcesFileSource is missing mapping from UrlResource when using classpath*: prefix

### ISSUE THREAD

**Issue by reillylm** [spring-cloud/spring-cloud-contract#591]
**Version**: The below snippets are from the latest on `master`.

We would like to retrieve WireMock stubs (not SCC-generated stubs, but plain old handwritten WireMock mappings) from multiple `jar`s during our tests using the `classpath*:` prefix in `@AutoConfigureWireMock`:

`@AutoConfigureWireMock(port = 0, files = "classpath*:/stubs")`

Our dependent `jar`s are placing the mappings under a `stubs` directory in the classpath.

Under the hood, `WireMockConfiguration#registerFiles` is using `PathMatchingResourcePatternResolver#getResources`:

https://github.com/spring-cloud/spring-cloud-contract/blob/a4e79d380f55bd55ed4855583907dfda9c20e6eb/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfiguration.java#L125-L127

which, under the case of a `classpath*:` prefix, returns a list of `UrlResource`s.

However, when we go into `ResourcesFileSource` and perform the mapping from a Spring `Resource` to the equivalent "base" WireMock "resource" type (like `ClasspathFileSource`), there is no mapping for `UrlResource`:

https://github.com/spring-cloud/spring-cloud-contract/blob/a4e79d380f55bd55ed4855583907dfda9c20e6eb/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/file/ResourcesFileSource.java#L55-L62

Should a `resource instanceof UrlResource` case get added to the `ResourcesFileSource` constructor in the case of the `classpath*:` prefix?

**Comment by marcingrzejszczak** [comment]
Hi! Can you show an example of a failing scenario? A small sample or a test?

**Comment by marcingrzejszczak** [comment]
Also which version of sc-contract are you using?

**Comment by reillylm** [comment]
Thanks for getting back so quickly! Just tried it in `2.0.0.M8`.

I think mapping to `SingleRootFileSource` will work in the scenario where the subdirectory is directly under `src/test/resources` (as is the case with `root` in the `AutoConfigureWireMockFilesApplicationWithUrlResourceTests`).

However, when pulling in stubs that come from a `jar` dependency, the resolution from `UrlResource` to `File` is causing this exception:

```
Caused by: java.io.FileNotFoundException: URL [jar:file:/Users/me/.gradle/caches/modules-2/files-2.1/path/to/stubs.jar!/stubs] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/Users/me/.gradle/caches/modules-2/files-2.1/path/to/stubs.jar!/stubs
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:215)
	at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:53)
	at org.springframework.core.io.UrlResource.getFile(UrlResource.java:213)
	at org.springframework.cloud.contract.wiremock.file.ResourcesFileSource.getFile(ResourcesFileSource.java:76)
	... 76 common frames omitted
```

which appears to be happening because of the `jar:` protocol in the URL:

https://github.com/spring-projects/spring-framework/blob/b2f900e518eeb5aabf57a6deb8f267256af7b22b/spring-core/src/main/java/org/springframework/util/ResourceUtils.java#L216-L220

Should the mapping actually be to `ClasspathFileSource`? It looks like that class is doing the proper parsing of the URL and extracting the `jar` portion:

https://github.com/tomakehurst/wiremock/blob/d36516bb76b3b7b8fb84fe2254fc2597b3fce11c/src/main/java/com/github/tomakehurst/wiremock/common/ClasspathFileSource.java#L68-L72

I put together an example demonstrating the external `jar` behavior:

https://github.com/reillylm/scc591-consumer
https://github.com/reillylm/scc591-dependent-api-stubs

`scc591-dependent-api-stubs` contains the WireMock stubs and `scc591-consumer` contains the test with `@AutoConfigureWireMock`. You'll have to run `publishToMavenLocal` on `scc591-dependent-api-stubs` first to make the jar available for the consumer project.

**Comment by marcingrzejszczak** [comment]
Hopefully it works fine now ;)

**Comment by dprichmond** [comment]
I believe this was not fully resolved @marcingrzejszczak 

Basically when classpath* is used as such for me:
`@AutoConfigureWireMock(port = 0, files = "classpath*:/stubs")`

It fails to pull in the wiremock mappings from multiple jars on the classpath that contain a folder named stubs.

After some debugging, I believe the issue begins here:
[https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/file/ResourcesFileSource.java#L83](url)
`return new ClasspathFileSource(pathFromCompressed(uri));`

When pathFromCompressed(uri) returns 'stubs' the ClasspathFileSource appears to default to the first folder it finds, the same one it found previously.

This results in the same source being applied multiple times at `sources[i] = fileOrFallbackToClasspath(resource);` https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/file/ResourcesFileSource.java#L67

I've tested with 2.0.1.RELEASE and 2.1.0.RC3

**Comment by dprichmond** [comment]
Thanks,  @marcingrzejszczak 

Does anyone know a good workaround for this? 
I've tried various things, my latest being @AutoConfigureWireMock(port = 0, files = "classpath*:/stub?/")
with one jar having "stubs" and the other jar containing "stubz".  No success there - but I'm not sure if I'm using the ant path style correctly..

**Comment by marcingrzejszczak** [comment]
Change your annotation to sth like this:

`@AutoConfigureWireMock(port = 0, stubs = "classpath*:/META-INF/**/mappings/**/*.json")`

Don't use `files`, you should use `stubs`.

In your case your ant pattern (assuming that you have `stubs` in the root folder of your stub jar) would be `classpath*:/stub/**/*.json`
