### ISSUE TITLE
Contract for multipart/mixed endpoint

### ISSUE THREAD

**Issue by MoOFueL** [spring-cloud/spring-cloud-contract#599]
## Bug report

When trying to write contract for multipart/mixed endpoint as example below

```
   @PostMapping("/tests")``
    public Test createNew(@RequestPart MultipartFile file1,
                          @RequestPart MultipartFile file2,
                          @RequestPart Test test) {
        return new Test("ok");
    }
```
where **test** part would only be deserialized by spring-boot when **application/json** content-type is specified, groovy-dsl does not allow you to hint or specify content-type for this part

[Example project, representing this issue](https://github.com/MoOFueL/sc-contract-multipart-mixed-issue)

**Comment by henryyonathan90** [comment]
Hi @marcingrzejszczak , is it possible to include this fix on version 1.2.x? 
I have similar problem when trying to create contract for existing projects, and yes it still use spring 4.3.x version so I can't use the 2.0.0.RC1 version.

**Comment by marcingrzejszczak** [comment]
I'll do my best to backport it but I don't know if I'll have time to do it. Feel free to try to cherry-pick the https://github.com/spring-cloud/spring-cloud-contract/commit/b965c49a7efee44a64c72f1c4420899cec0fa4d3 commit to `1.2.x` branch

**Comment by henryyonathan90** [comment]
Kindly check on  #662 , currently that's the fix I am using on my projects. Please do let me know if I am missing something.
