### ISSUE TITLE
Array size assertions are enabled by default and cannot be disabled by properties

### ISSUE THREAD

**Issue by KrystianDziedziola** [spring-cloud/spring-cloud-contract#60]
We are using Gradle to build our project. The problem is, that array size assertions are always generated in tests. According to docs it should be disabled by default.
We've tried to disable this by adding property 'spring.cloud.contract.verifier.assert.size' and setting it to 'false' but it didn't work. Property is added correctly, but size assertions are still generated.
It has been tested on two different projects that are using Spring Cloud Contract Verifier and both of them had the same problem (both of them are using Gradle).

Please check if it really is a problem or we are doing something wrong. Although we've made all the configuration exactly like in the docs and everything else is working correctly.

**Comment by marcingrzejszczak** [comment]
Can you post your gradle build + your contract?

**Comment by KrystianDziedziola** [comment]
I can't post this exact files, because it's not my private project. I'm sending only configuration that is related to this test generation. It's nothing fancy. Pretty much copy-paste from your docs.

build.gradle:
```
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath "org.springframework.cloud:spring-cloud-contract-gradle-plugin:${verifier_version}"
	}
}

apply plugin: 'groovy'
apply plugin: 'spring-cloud-contract'

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-contract-dependencies:${verifier_version}"
	}
}

dependencies {
	testCompile 'org.codehaus.groovy:groovy-all:2.4.6'
	testCompile 'org.spockframework:spock-core:1.0-groovy-2.4'
	testCompile 'org.spockframework:spock-spring:1.0-groovy-2.4'
	testCompile 'org.springframework.cloud:spring-cloud-starter-contract-verifier'
}

contracts {
    targetFramework = 'Spock'
    testMode = 'MockMvc'
    baseClassForTests = 'spec.ApiSpec'
    basePackageForTests = 'org.springframework.cloud.verifier.tests'
    contractsDslDir = file("${project.buildDir}/production/${project.name}-contracts/")
    generatedTestSourcesDir = file(new File("${project.buildDir}/production/${project.name}-tests/"))
    stubsOutputDir = file(new File("${project.buildDir}/production/${project.name}-stubs/"))
}

generateWireMockClientStubs {
    enabled = false
}
```
Contract:
```
org.springframework.cloud.contract.spec.Contract.make {
    request {
        method "GET"
        urlPath('/something') {
            headers {
                header('Accept': 'application/json;charset=UTF-8')
            }
        }
    }

    response {
        status 200
        headers {
            header('content-type': 'application/json;charset=UTF-8')
        }

        body(
                data: [value(
                        firstName: value(client('asd'), server(regex('.*'))),
                        lastName: value(client('asd'), server(regex('.*')))
                )]
        )
    }
}
```

Test:
```
def validate_test() throws Exception {
	given:
		def request = given().header('Accept', 'application/json;charset=UTF-8')

	when:
		def response = given().spec(request).get("/something")

	then:
		response.statusCode == 200
		response.header('content-type')  == 'application/json;charset=UTF-8'
	and:
		DocumentContext parsedJson = JsonPath.parse(response.body.asString())
		assertThatJson(parsedJson).array("data").hasSize(1)
		assertThatJson(parsedJson).array("data").contains("firstName").matches(".*")
		assertThatJson(parsedJson).array("data").contains("lastName").matches(".*")
}
```

**Comment by marcingrzejszczak** [comment]
Thanks - will check it out!

BTW why did you wrap this in `value`

```
 body(
                data: [value(
                        firstName: value(client('asd'), server(regex('.*'))),
                        lastName: value(client('asd'), server(regex('.*')))
                )]
        )
```

shouldn't it be

```
 body(
                data: [
                        firstName: value(client('asd'), server(regex('.*'))),
                        lastName: value(client('asd'), server(regex('.*')))
                ]
        )
``` ?

**Comment by KrystianDziedziola** [comment]
We were always doing this with 'value()' and it all worked just fine in Accurest.
I'll give you an example of how removing value() affects test.

If you have contract like this:
```
org.springframework.cloud.contract.spec.Contract.make {
    request {
        method "GET"
        urlPath('/country') {
            queryParameters {
                parameter 'language': $(client(regex('.*')), server('pol'))
            }
        }
    }

    response {
        status 200
        headers { header('content-type': 'application/json') }

        body(
                countries: [value(
                        name: value(client('Name'), server(regex('.*'))),
                        cities: [value(
                                name: value(client('City'), server(regex('.*'))),
                                postcode: value(client('113123'), server(regex('.*')))
                        )]
                )]
        )
    }
}
```

The test looks like this:
```
def test() throws Exception {
		given:
			def request = given()

		when:
			def response = given().spec(request).get("/country?language=pol")

		then:
			response.statusCode == 200
			response.header('content-type')  == 'application/json'
		and:
			DocumentContext parsedJson = JsonPath.parse(response.body.asString())
			assertThatJson(parsedJson).array("countries").array("cities").hasSize(1)
			assertThatJson(parsedJson).array("countries").hasSize(1)
			assertThatJson(parsedJson).array("countries").array("cities").contains("name").matches(".*")
			assertThatJson(parsedJson).array("countries").array("cities").contains("postcode").matches(".*")
			assertThatJson(parsedJson).array("countries").contains("name").matches(".*")
	}
```
which whould be fine if this array size assertions wasn't there.

And now, when I remove the 'value()':
```
org.springframework.cloud.contract.spec.Contract.make {
    request {
        method "GET"
        urlPath('/country') {
            queryParameters {
                parameter 'language': $(client(regex('.*')), server('pol'))
            }
        }
    }

    response {
        status 200
        headers { header('content-type': 'application/json') }

        body(
                countries: [
                        name: value(client('Name'), server(regex('.*'))),
                        cities: [
                                name: value(client('City'), server(regex('.*'))),
                                postcode: value(client('113123'), server(regex('.*')))
                        ]
                ]
        )
    }
}
```

Generated test:
```
def validate_contactConsultantsContract() throws Exception {
		given:
			def request = given()

		when:
			def response = given().spec(request).get("/country?language=pol")

		then:
			response.statusCode == 200
			response.header('content-type')  == 'application/json'
		and:
			DocumentContext parsedJson = JsonPath.parse(response.body.asString())
			assertThatJson(parsedJson).field("countries").field("name").matches(".*")
			assertThatJson(parsedJson).field("countries").field("cities").field("postcode").matches(".*")
			assertThatJson(parsedJson).field("countries").field("cities").field("name").matches(".*")
	}
```

This array size assertions dissapeared but structure is wrong. "coutries" is now treated as a field but should be an array. The same thing with 'cities'.
When I run this test it fails with exception:
```
java.lang.RuntimeException: com.jayway.jsonpath.PathNotFoundException: Expected to find an object with property ['cities'] in path $['countries'] but found 'net.minidev.json.JSONArray'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'.
```

**Comment by marcingrzejszczak** [comment]
Good to know :D

**Comment by marcingrzejszczak** [comment]
So... there is a  problem with your output JSON. You should have:

```
org.springframework.cloud.contract.spec.Contract.make {
    request {
        method "GET"
        urlPath('/country') {
            queryParameters {
                parameter 'language': $(client(regex('.*')), server('pol'))
            }
        }
    }

    response {
        status 200
        headers { header('content-type': 'application/json') }

        body(
                countries: [
                        name: value(client('Name'), server(regex('.*'))),
                        cities: [
                                [
                                    name: value(client('City'), server(regex('.*'))),
                                    postcode: value(client('113123'), server(regex('.*')))
                                ]
                        ]
                ]
        )
    }
}
```

You're missing `[]`. I assume that you wanted to have an array of cities where a city can have a `name` and `postcode`.

**Comment by KrystianDziedziola** [comment]
For this case I would get response of type:
`List<Country>`
Where model looks something like this:
```
class Country {
	private String name;
	private List<City> cities;
}

class City {
	private String name;
	private String postcode;
}
```
So I think that contract should be:
```
org.springframework.cloud.contract.spec.Contract.make {
    request {
        method "GET"
        urlPath('/country') {
            queryParameters {
                parameter 'language': $(client(regex('.*')), server('pol'))
            }
        }
    }

    response {
        status 200
        headers { header('content-type': 'application/json') }

        body(
                countries: [
                        [
                                name  : value(client('Name'), server(regex('.*'))),
                                cities: [
                                        [
                                                name    : value(client('City'), server(regex('.*'))),
                                                postcode: value(client('113123'), server(regex('.*')))
                                        ]
                                ]
                        ]
                ]
        )
    }
}
```

Maybe using value() there wasn't correct (we won't do this again), but even wrapping it in '[ ]' doesn't solve the problem. The array size assertions are still there.

There is a test generated from this contract:
```
def test() throws Exception {
		given:
			def request = given()

		when:
			def response = given().spec(request)
					.get("/country?language=pol")

		then:
			response.statusCode == 200
			response.header('content-type')  == 'application/json'
		and:
			DocumentContext parsedJson = JsonPath.parse(response.body.asString())
			assertThatJson(parsedJson).array("countries").array("cities").hasSize(1)
			assertThatJson(parsedJson).array("countries").hasSize(1)
			assertThatJson(parsedJson).array("countries").array("cities").contains("name").matches(".*")
			assertThatJson(parsedJson).array("countries").array("cities").contains("postcode").matches(".*")
			assertThatJson(parsedJson).array("countries").contains("name").matches(".*")
	}
```

**Comment by marcingrzejszczak** [comment]
Of course it won't. This is another issue that I have to fix. But at least we're on the same page in terms of `value` usage :)

**Comment by KrystianDziedziola** [comment]
So basically if I want to use Spring Cloud Contract Verifier with arrays/lists within contracts I have to wait for that fix, because that's the right way to do this and it doesn't work, right?

**Comment by marcingrzejszczak** [comment]
There is this code in Verifier

```
private static final String SIZE_ASSERTION_SYSTEM_PROP = "spring.cloud.contract.verifier.assert.size"

// Size verification: https://github.com/Codearte/accurest/issues/279
	private void addSizeVerificationForListWithPrimitives(MethodBufferingJsonVerifiable key, Closure closure, List value) {
		Boolean systemPropValue = Boolean.parseBoolean(System.getProperty(SIZE_ASSERTION_SYSTEM_PROP, "false"))
		Boolean configPropValue = configProperties.assertJsonSize
		boolean configPropSet = configPropValue != null
		if (configPropSet && !configPropValue) {
			return
		} else if (!configPropSet && systemPropValue) {
			return
		}
		log.debug("WARNING: Turning on the incubating feature of JSON array check")
		...
	}
```

I'm really surprised that it's not working. You're using Gradle right? In the buildscript section try adding `System.setProperty('spring.cloud.contract.verifier.assert.size', 'true')`. Also we can move this to https://gitter.im/spring-cloud/spring-cloud-contract Gitter

**Comment by marcingrzejszczak** [comment]
Hmm come to think of it this is wrong

`else if (!configPropSet && systemPropValue) {`

it should be 

`else if (!configPropSet && !systemPropValue) {`

so you have to set the system prop to true (assuming that the `configProperties.assertJsonSize` doesn't work)

**Comment by KrystianDziedziola** [comment]
Yeah, you're right. It turns out, that this property to 'true' disables the array size assertions :D Thanks!

**Comment by marcingrzejszczak** [comment]
LOL - at least we have a workaround :) I'm at this moment working on making this work properly :P

**Comment by Pavan7287** [comment]
Hi Marcin,
I am also facing some issues with groovy contract having a list, My contract looks like:

`package contracts.beer.rest
import org.springframework.cloud.contract.spec.Contract

Contract.make{

    description("""
    Validating A CWP MO For New Customer
    """)

    request{

        method 'POST'
        url    '/ValidateMO'
        body(
                id: $(anyNumber()),
                name: $(producer(regex('[a-zA-Z]+'))),
                age: $(producer(regex('[0-9][2-9]'))),
                salary: $(producer(regex('[1-9][0-9]{5}'))),
                designation: $(producer(regex('[A-Za-z]+'))),
                addressList:[
                        [
                            street: value($(producer(regex('[A-Za-z]+')))),
                            city: value($(producer(regex('[A-Za-z]+')))),
                            zipCode: value($(producer(regex('[0-9]{5}'))))
                        ]
                ],
                phoneNumbers:[
                        $(producer('12345')),
                        $(producer('56789'))
                ],
                personalInformation:[
                    gender: $(producer('Male')),
                    maritialstatus: $(producer('Unmarried'))
                ]
        )
        headers {
            contentType(applicationJson())
        }
    }
    response{
        status 200
        body("""
     {
     "status":"OK"
     }
     """)
        headers{
            contentType(applicationJson())
        }
    }

}`
So here stub got created at producer end:
`{
  "id" : "abdcb032-ce87-445e-bf93-9ba485fdb19d",
  "request" : {
    "url" : "/ValidateMO",
    "method" : "POST",
    "headers" : {
      "Content-Type" : {
        "matches" : "application/json.*"
      }
    },
    "bodyPatterns" : [ {
      "matchesJsonPath" : "$[?(@.['salary'] =~ /[1-9][0-9]{5}/)]"
    }, {
      "matchesJsonPath" : "$.['personalInformation'][?(@.['maritialstatus'] == 'Unmarried')]"
    }, {
      "matchesJsonPath" : "$[?(@.['id'] =~ /-?(\\d*\\.\\d+|\\d+)/)]"
    }, {
      "matchesJsonPath" : "$[?(@.['designation'] =~ /[A-Za-z]+/)]"
    }, {
      "matchesJsonPath" : "$.['addressList'][*][?(@.['zipCode'] =~ /[0-9]{5}/)]"
    }, {
      "matchesJsonPath" : "$.['phoneNumbers'][?(@ == '56789')]"
    }, {
      "matchesJsonPath" : "$.['addressList'][*][?(@.['city'] =~ /[A-Za-z]+/)]"
    }, {
      "matchesJsonPath" : "$.['addressList'][*][?(@.['street'] =~ /[A-Za-z]+/)]"
    }, {
      "matchesJsonPath" : "$.['personalInformation'][?(@.['gender'] == 'Male')]"
    }, {
      "matchesJsonPath" : "$[?(@.['name'] =~ /[a-zA-Z]+/)]"
    }, {
      "matchesJsonPath" : "$[?(@.['age'] =~ /[0-9][2-9]/)]"
    }, {
      "matchesJsonPath" : "$.['phoneNumbers'][?(@ == '12345')]"
    } ]
  },
  "response" : {
    "status" : 200,
    "body" : "{\"status\":\"OK\"}",
    "headers" : {
      "Content-Type" : "application/json"
    },
    "transformers" : [ "response-template" ]
  },
  "uuid" : "abdcb032-ce87-445e-bf93-9ba485fdb19d"
}`

So when I verify my json at consumer end, if I put some wrong value at any index of addressList, test case got passed, but it will fail if data is wrong at all index of addressList. My Testcase at consumer end is as below:
`@Test
    public void validateMO() throws Exception {
        //remove::start[]
        long[] phnNum={12345,56789};
        HashMap<String,String> personalInformation=new HashMap<String,String>();
        personalInformation.put("gender","Male");
        personalInformation.put("maritialstatus","Unmarried");
        BigDecimal sal=new BigDecimal(100000);
        List<Address> addressList =new ArrayList<>();
        addressList.add(new Address("Park Avn","West chester",123451));
        addressList.add(new Address("Park Avn","West chester2",56789));

        mockMvc.perform(MockMvcRequestBuilders.post("/validate")
                .contentType(MediaType.APPLICATION_JSON)
                .content(json.write(new Employee(12,"Aman",25,sal,"Programmer",addressList,phnNum,personalInformation)).getJson()))
                .andExpect(status().isOk())
                .andExpect(content().string("THERE YOU GO"));
        //remove::end[]
    }`

Please help me to find out where is the issue.
