### ISSUE TITLE
Docker hub doesn't contains version 1.2.4.RELEASE for spring-cloud-contract & spring-cloud-contract-stub-runner

### ISSUE THREAD

**Issue by eddumelendez** [spring-cloud/spring-cloud-contract#601]
https://hub.docker.com/r/springcloud/spring-cloud-contract/tags/
https://hub.docker.com/r/springcloud/spring-cloud-contract-stub-runner/tags/

**Comment by marcingrzejszczak** [comment]
Just pushed the missing images. Thanks for the pointer
