### ISSUE TITLE
Cookie Support on Contract DSL

### ISSUE THREAD

**Issue by bertzzie** [spring-cloud/spring-cloud-contract#603]
Hi, 

I want to add cookie in my contract, because my application requires specific cookies to be present, and check its value to be in specific parameters. As of now, after searching everywhere, I couldn't find how to do it.

I tried adding a cookie header in contract like this:

```
headers {
    header: cookie(), "some-key=some-value;"
}
```

and while the cookie header is there, both the generated test and stub don't check the value. I.e. I expect the generated test to have something like:

```
MockMvcRequestSpecification request = given()
                                        .header("Cookie", "some-key=some-value;")
					.cookie(...)
```

but there's only the `header("Cookie", "some-key=some-value;")` part which results in the cookies not put inside `ServletRequest.getCookies()`.

Is there any other way to do this? If there aren't, am I allowed to submit a patch to add this feature? I won't mind if I have to put it into both the 1.2.x and 2.x branches.

Thanks before.

**Comment by marcingrzejszczak** [comment]
It's not supported from what I see. Sure, try filing the PR to `1.2.x` and `master`. Remember about test generation for mockmvc for junit / spock and JaxRs (java / spock)

**Comment by bertzzie** [comment]
Hi,

Thank you for your fast response. I'll start working on it right away, and will open PR as soon as possible.

Regards,

**Comment by marcingrzejszczak** [comment]
No problem! In case of any questions just ping me

**Comment by bertzzie** [comment]
Sure thing! I have successfully build the project, and in process of adding the test generation code now. Should be able to open PR in the next few days. Cheers.

**Comment by marcingrzejszczak** [comment]
Woot! Great, I'm really looking forward to this :)

**Comment by bertzzie** [comment]
Hi @marcingrzejszczak I have opened a PR that should supports JUnit and Spock both on JAX-RS and MockMvc. I didn't add it on spring-message because as far as I understand, there's no cookie concept there.

I need help on stub-runners though, could you give me some pointer on where I can start working on the stub runner? i.e. any docs I can read on how you create the stub runner?

Once I finished working on that, I will start writing the docs and samples for this.

Thank you for your patience. Cheers.

**Comment by marcingrzejszczak** [comment]
I'm just going through your stuff as we speak :)

**Comment by bertzzie** [comment]
Ok thanks. Ping me if there's anything I need to work on more.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/pull/607 and https://github.com/spring-cloud/spring-cloud-contract/commit/2068fdc8cac1199ac4af29c80053f2b2f7084dbf
