### ISSUE TITLE
WebFlux Reactive Hanging error

### ISSUE THREAD

**Issue by ati90ati** [spring-cloud/spring-cloud-contract#606]
I've used spring-cloud-contract (1.2.2.RELEASE and 2.0.0.M8) with Spring Boot WebFlux (2.0.0.RELEASE) Reactive services and because the standalone WireMock has a Jetty of version 9.2.22.v20170606 sometimes it hanging when making calls to WireMock server.
When a new WireMock is available with a newer Jetty (they should do a Jetty upgrade and not stick with 9.2) upgrade to that version and with that fix this hanging problem. For me never hangs with a version of Jetty 9.4.8.v20171121.

Please see related Spring Boot and Reactor-Netty issues:
https://github.com/spring-projects/spring-boot/issues/10569
https://github.com/reactor/reactor-netty/issues/264
https://github.com/tomakehurst/wiremock/issues/914

**Comment by marcingrzejszczak** [comment]
Thanks for the info. Maybe you should also file this issue in WireMock? So that they bump the library?

**Comment by ati90ati** [comment]
I've checked the issues in Wiremock and I found a lot of issues with upgrade to Jetty 9.3.x and 9.4.x
https://github.com/tomakehurst/wiremock/pull/887
https://github.com/tomakehurst/wiremock/issues/407
https://github.com/tomakehurst/wiremock/commit/4368d316ec239bac305f1faadedab24765bbe4b6

I've also added an issue to Wiremock with the WebFlux reactive services hanging problem.
https://github.com/tomakehurst/wiremock/issues/914

**Comment by marcingrzejszczak** [comment]
Great! So I guess we'll have to wait for them to fix it natively.

OTOH by using Spring Cloud Contract WireMock (we implicitly add that if you use the verifier or stub runner dep) you reuse the app server that comes with Boot. So if it gets fixed in Boot you should have it fixed OOB in Contract. That's not the case?

**Comment by ati90ati** [comment]
My examples are in gradle.
I don't know if I understand correctly, but what I have:


    \--- org.springframework.cloud:spring-cloud-contract-wiremock:2.0.0.M8
         +--- com.github.tomakehurst:wiremock-standalone:2.15.0
         +--- org.apache.httpcomponents:httpclient:4.5.5 (*)
         +--- org.springframework.boot:spring-boot-starter:2.0.0.RELEASE (*)
         +--- org.springframework:spring-web:5.0.4.RELEASE (*)
         \--- org.assertj:assertj-core:3.9.1


Spring Cloud Contract WireMock comes with Wiremock standalone version, so it won't use the Spring Boot dependencies.
The Wiremock Standalone version library has the Jetty and all the libs inside it, so with this case you will have the possibility to have two version of Jetty in your code. The one from the standalone jar comes with wiremock.org.eclipse.jetty package and the one from org.eclipse.jetty package.

At this moment to use the Jetty 9.4.x I've do a hackish solution:

    testCompile("com.github.tomakehurst:wiremock:${tomakehurstWiremockVersion}")
    testCompile("org.springframework.cloud:spring-cloud-contract-wiremock:${springCloudContractWiremockVersion}") {
        exclude group: 'com.github.tomakehurst', module: 'wiremock-standalone'
    }


So, here I exclude the standalone jar from contract and added the wiremock dependency, without Jetty.
Jetty comes from Spring boot dependencies with version 9.4.8.v20171121, and luckily, by disabling https for http wiremock (`@TestPropertySource(properties = {"wiremock.server.https-port=-1"})`
 on each test class) works with this version, but this solution should be changed when the standalone comes with Jetty 9.4.x

    +--- com.github.tomakehurst:wiremock:2.16.0
    |    +--- org.eclipse.jetty:jetty-server:9.2.22.v20170606 -> 9.4.8.v20171121
    |    |    +--- javax.servlet:javax.servlet-api:3.1.0
    |    |    +--- org.eclipse.jetty:jetty-http:9.4.8.v20171121
    |    |    |    +--- org.eclipse.jetty:jetty-util:9.4.8.v20171121
    |    |    |    \--- org.eclipse.jetty:jetty-io:9.4.8.v20171121
    |    |    |         \--- org.eclipse.jetty:jetty-util:9.4.8.v20171121
    |    |    \--- org.eclipse.jetty:jetty-io:9.4.8.v20171121 (*)
    |    +--- org.eclipse.jetty:jetty-servlet:9.2.22.v20170606 -> 9.4.8.v20171121
    |    |    \--- org.eclipse.jetty:jetty-security:9.4.8.v20171121
    |    |         \--- org.eclipse.jetty:jetty-server:9.4.8.v20171121 (*)
    |    +--- org.eclipse.jetty:jetty-servlets:9.2.22.v20170606 -> 9.4.8.v20171121
    |    |    +--- org.eclipse.jetty:jetty-continuation:9.4.8.v20171121
    |    |    +--- org.eclipse.jetty:jetty-http:9.4.8.v20171121 (*)
    |    |    +--- org.eclipse.jetty:jetty-util:9.4.8.v20171121
    |    |    \--- org.eclipse.jetty:jetty-io:9.4.8.v20171121 (*)
    |    +--- org.eclipse.jetty:jetty-webapp:9.2.22.v20170606 -> 9.4.8.v20171121
    |    |    +--- org.eclipse.jetty:jetty-xml:9.4.8.v20171121
    |    |    |    \--- org.eclipse.jetty:jetty-util:9.4.8.v20171121
    |    |    \--- org.eclipse.jetty:jetty-servlet:9.4.8.v20171121 (*)

**Comment by marcingrzejszczak** [comment]
It does come with Jetty deps but we reuse whatever application server you define in Boot. Notice that we have a separate starter that reuses the Jetty from WireMock https://github.com/spring-cloud/spring-cloud-contract/tree/master/spring-cloud-contract-starters/spring-cloud-starter-contract-stub-runner-jetty

**Comment by ati90ati** [comment]
My app server is the default from Spring Boot Webflux: Netty.
So I've running my app in Netty and Wiremock in Jetty.
I've tried this (1):

    testCompile("com.github.tomakehurst:wiremock:${tomakehurstWiremockVersion}")
    testCompile("org.springframework.cloud:spring-cloud-contract- wiremock:${springCloudContractWiremockVersion}") {
        exclude group: 'com.github.tomakehurst', module: 'wiremock-standalone'
    }

and as you said with this (I hope I understand ok) (2):

    testCompile("org.eclipse.jetty:jetty-server")
    testCompile("org.eclipse.jetty:jetty-server")
    testCompile("org.eclipse.jetty:jetty-http")
    testCompile("org.eclipse.jetty:jetty-util")
    testCompile("org.eclipse.jetty:jetty-io")
    testCompile("org.eclipse.jetty:jetty-security")
    testCompile("org.eclipse.jetty:jetty-servlet")
    testCompile("org.eclipse.jetty:jetty-servlets")
    testCompile("org.eclipse.jetty:jetty-continuation")
    testCompile("org.eclipse.jetty:jetty-webapp")
    testCompile("org.eclipse.jetty:jetty-xml")
    testCompile("org.eclipse.jetty:jetty-util")
    testCompile("org.springframework.cloud:spring-cloud-contract-wiremock:${springCloudContractWiremockVersion}")

With both Wiremock uses Jetty 9.4.x
Note: I've using Spring Boot 2.0.0.RELEASE

It's very strange for me that with solution 1 work nice and with solution 2 tests stops and hangs randomly until timeout.
I really don't understand this...

Usually stops hanging at the `retrieve()` method in code like this:

    import org.springframework.web.reactive.function.client.WebClient;

    ...

    private final WebClient client;

    public UserServiceClient(final String endpoint, final WebClient.Builder webClientBuilder) {
        this.client = webClientBuilder.clone()
                .baseUrl(endpoint + "/api")
                .build();
    }

    public Mono<UserDto> authenticate(final UserLoginDto userLogin) {
        return client.post().uri("/users/login")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON)
                .body(BodyInserters.fromObject(userLogin))
                .retrieve()
                .bodyToMono(UserDto.class)
                .doOnNext(n -> log.info("Client received {} ", n))
                .doOnError(e -> log.error("Error while authenticating user ", e));
    }


I'll leave the first solution for me. Maybe it's a problem with the wiremock-standalone and Jetty also (without standalone wiremock, just normal and Jetty 9.2.x doesn't works).

Maybe, if possible one time upgrade to a Wiremock with Jetty 9.4.x.

**Comment by marcingrzejszczak** [comment]
I've just bumped WireMock to 2.17.0. In the release notes I can see that Jetty was updated. https://groups.google.com/forum/#!msg/wiremock-user/-XESD3nbs5I/LHN5Y51mCgAJ but only by minor https://github.com/tomakehurst/wiremock/commit/d6ffe4bd5eb424e283c5cc74004cf193ff3a8e86

**Comment by ati90ati** [comment]
The solution to the hanging issue can be found here: https://github.com/tomakehurst/wiremock/issues/914

Wiremock has two new libraries.
 * wiremock-jre8 (works nice with Jetty 9.4)
 * wiremock-jre8-standalone (contains Jetty 9.4)

To have Jetty 9.4 there are two options.

1. Using the wiremock with separate jetty dependencies:
```gradle
    testCompile("com.github.tomakehurst:wiremock-jre8:${tomakehurstWiremockVersion}")
    testCompile("org.springframework.cloud:spring-cloud-contract-wiremock") {
        exclude group: 'com.github.tomakehurst', module: 'wiremock-standalone'
        exclude group: 'com.github.tomakehurst', module: 'wiremock-jre8-standalone'  // exclude for future changes
    }
```

2. Or using the standalone version:

```gradle
    testCompile("com.github.tomakehurst:wiremock-jre8-standalone:${tomakehurstWiremockVersion}")
    testCompile("org.springframework.cloud:spring-cloud-contract-wiremock") {
        exclude group: 'com.github.tomakehurst', module: 'wiremock-standalone'
    }
```

As I see the spring-cloud-contract version 2.2.0.M1 uses the `wiremock-jre8-standalone` so in the future Jetty 9.4 will be supported be default.
