### ISSUE TITLE
OutputMessage stub is not generating stub data when using $()

### ISSUE THREAD

**Issue by lde-avaleo** [spring-cloud/spring-cloud-contract#619]
Hi,

It seems that OutputMessage doesn't have an overloaded method `$(ServerDslProperty server) {...}` similar to `Response#$(ServerDslProperty server) { return value(server) }` thus it doesn't generate stub value if using `$(producer(regex(...))` as do `value(producer(regex(...))`.

Docs says that you can use it interchangeably.

regards,
lde

**Comment by marcingrzejszczak** [comment]
Can you show an example of such a contract?

**Comment by lde-avaleo** [comment]
Contract:
```
final text(length = 255) {
	".{1,${length}}"
}

org.springframework.cloud.contract.spec.Contract.make {
	label 'shouldPublishMessage'
	// input to the contract
	input {
		// the contract will be triggered by a method
		triggeredBy('foo()')
	}
	// output message of the contract
	outputMessage {
		// destination to which the output message will be sent
		sentTo('messageExchange')
		// the body of the output message
		body([
			"properlyGeneratedStubValue": value(producer(regex(text()))),
			"notGeneratedStubValue": $(producer(regex(text()))),
		])
		headers {
			messagingContentType(applicationJson())
		}
	}
}
```
Generated json message with `{"cursor":8}` instead of string value:
`{
    "properlyGeneratedStubValue":"\\u52DF\\uC354\\u2148\\u9E21\\uB3B2",
    "notGeneratedStubValue":{"cursor":8}
}`

I'm using 1.2.4.RELEASE version

**Comment by marcingrzejszczak** [comment]
great, thank you so much, I'll use it as a test to ensure that we're generating a stub without any such things.

**Comment by lde-avaleo** [comment]
No problem, if I can have a wish could you also add support for auto generating values for optional regex like the one below? For now it also generating `{"cursor": ...}` values.

```
org.springframework.cloud.contract.spec.Contract.make {
	label 'shouldPublishMessage'
	// input to the contract
	input {
		// the contract will be triggered by a method
		triggeredBy('foo()')
	}
	// output message of the contract
	outputMessage {
		// destination to which the output message will be sent
		sentTo('messageExchange')
		// the body of the output message
		body([
			"optionalStubValue": value(producer(optional(regex(text()))))
		])
		headers {
			messagingContentType(applicationJson())
		}
	}
}
```

**Comment by marcingrzejszczak** [comment]
that's the similar thing. The `cursor` thing happens when a `Pattern` gets converted to String directly without being converted to a proper value.

**Comment by lde-avaleo** [comment]
Thanks a lot!

**Comment by lde-avaleo** [comment]
Is there any chance to port it to 1.2.x as we're now using 1.2.4.RELEASE??

**Comment by marcingrzejszczak** [comment]
Cherry-picked the change from 2.0.x to 1.2.x

**Comment by lde-avaleo** [comment]
Thank you very much.
