### ISSUE TITLE
OutputMessage header comparision in generated test causes compile error

### ISSUE THREAD

**Issue by lde-avaleo** [spring-cloud/spring-cloud-contract#620]
When using regex in OutputMessage header then generated test doesn't compile.

Contract:
```
org.springframework.cloud.contract.spec.Contract.make {
	label 'shouldPublishMessage'
	// input to the contract
	input {
		// the contract will be triggered by a method
		triggeredBy('foo()')
	}
	// output message of the contract
	outputMessage {
		// destination to which the output message will be sent
		sentTo('messageExchange')
		// the body of the output message
		body([
			"field": "value"
		])
		headers {
			header('Authorization', value(regex('Bearer [A-Za-z0-9\\-\\._~\\+\\/]+=*')))
		}
	}
}
```

Generated test:
```
	def validate_shouldPublishMessage() throws Exception {
		when:
			foo()

		then:
			ContractVerifierMessage response = contractVerifierMessaging.receive('messageExchange')
			assert response != null
			response.getHeader('Authorization')?.toString() ==~ java.util.regex.Pattern.compile('Bearer [A-Za-z0-9\-\._~\+\/]+=*')
		and:
			DocumentContext parsedJson = JsonPath.parse(contractVerifierObjectMapper.writeValueAsString(response.payload))
			assertThatJson(parsedJson).field("['field']").isEqualTo("value")
	}
```

After trying to compile it you'll get error as below:
```
28: unexpected char: '\' @ line 28, column 106.
   ern.compile('Bearer [A-Za-z0-9\-\._~\+\/
```

**Comment by TYsewyn** [comment]
You're correct, that should be `response.getHeader('Authorization')?.toString() ==~ java.util.regex.Pattern.compile('Bearer [A-Za-z0-9-._~+/]+=*')`.
I'll take a look at it!

**Comment by lde-avaleo** [comment]
Are there any chance to port it to 1.2.x  as we're now using 1.2.4.RELEASE??

**Comment by TYsewyn** [comment]
@marcingrzejszczak & I discussed this yesterday and we decided that it's best to upgrade to 2.0.
A lot of functionality has already been added to this major release next to a lot of bug fixing.

**Comment by marcingrzejszczak** [comment]
I woke up today in good mood and tried to cherry pick the 2 commits of yours @TYsewyn and it turned out that there's almost no work needed to merge it so I just pushed it for 1.2.x too. Let's say that Christmas came in earlier this year ;)

**Comment by lde-avaleo** [comment]
Thank you very much.
