### ISSUE TITLE
Publish spring-cloud-contract-gradle-plugin to Gradle plugin portal

### ISSUE THREAD

**Issue by adrian-wozniak** [spring-cloud/spring-cloud-contract#629]
It would be very convenient to have possibility to use new Gradle plugin mechanism with `spring-cloud-contract-gradle-plugin`:

```
plugins {
  id 'spring-cloud-contract' version '1.2.4.RELEASE'
}
```

instead of:
```
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'org.springframework.cloud:spring-cloud-contract-gradle-plugin:1.2.4.RELEASE'
    }
}
apply plugin: 'spring-cloud-contract'
```

**Comment by marcingrzejszczak** [comment]
Yeah, maybe it would. Unfortunately we've released RC1, I guess we'll have have to postpone it to 3.0 cause it would be a breaking change

**Comment by kpb** [comment]
+1
Can we please use the standard gradle plugin mechanism?

**Comment by bjartek** [comment]
Any progress on this?

**Comment by marcingrzejszczak** [comment]
Nope. We would have to modify the way we package and upload artifacts. We can consider adding it for the next major release. Another option is to publish this twice. The old way, and the new way, that way we won't have to wait for the next major release.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/f55e855769ec9c0d7c53fb68cadb2904b3580180

**Comment by kpb** [comment]
Great news! Thanks.

**Comment by szpak** [comment]
It eventually showed up in the [Plugin Portal](https://plugins.gradle.org/plugin/org.springframework.cloud.contract) after manual verification at the Gradle side and it even seems to work.
I'm positively surprised that my changes to the plugin publishing worked first time round :).

**Comment by marcingrzejszczak** [comment]
Thanks a lot @szpak ! Great work, as usual :)
