### ISSUE TITLE
Remove Spring annotations from JUnit Rule sample code

### ISSUE THREAD

**Issue by benwatson528** [spring-cloud/spring-cloud-contract#631]
https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/master/consumer/src/test/java/com/example/BeerControllerWithJUnitTest.java currently includes annotations:

```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = WebEnvironment.MOCK)
@AutoConfigureMockMvc
@AutoConfigureJsonTesters
@DirtiesContext
//@org.junit.Ignore
```

The `@RunWith` and `@SpringBootTest` annotations can be removed and the test should still work. This will make the test clearer for people who are running Spring Cloud Contract tests in non-Spring projects.

This is related to SO question https://stackoverflow.com/questions/50063614/running-spring-cloud-contract-test-in-non-spring-project/50064634

**Comment by marcingrzejszczak** [comment]
As you can see, inside the tests we're using MockMvc to test the consumer's API. The annotations are used to use `MovkMvc`. They have nothing to do to make JUnit rule work. 

Also we don't mention in the docs (https://cloud.spring.io/spring-cloud-static/Edgware.SR3/single/spring-cloud.html#_stub_runner_junit_rule) any special annotations to be added for the JUnit rule to work.
