### ISSUE TITLE
Spring Cloud Stream Application + spring-cloud-starter-contract-stub-runner SpringBootTest fails

### ISSUE THREAD

**Issue by doronl** [spring-cloud/spring-cloud-contract#635]
I have a Spring Boot Application that uses  Spring Cloud Stream with Kafka channels (input and output on the same topic), I also have a SpringBootTest integration test that calls a Spring MVC Controller endpoint (on the same spring boot app) that sends a message into the output channel,  test class is configured this way more or less...

`@RunWith(SpringRunner.class)`
`@ActiveProfiles("test")`
`@SpringBootTest...`

When I add maven dependency of spring-cloud-starter-contract-stub-runner (test scope) it seems that the messages are not arriving to Kafka any more during the integration test... 
Is the stub library taking control over the channels some how? 

Used versions: 
Spring cloud: Finchley.M9
Spring Boot: 2.0.0.RELEASE

**Comment by marcingrzejszczak** [comment]
Can you try with `Finchley.RC1` and Boot `2.0.1.RELEASE` ? Can you also generate a sample that replicates the issue?

**Comment by doronl** [comment]
Both options are quite complicated for me so I debug the tests and found that when the sub runner is imported I get the following dispatcher (in the AbstractSubscribableChannel.getRequiredDispatcher) :

UnicastingDispatcher with handlers: **org.springframework.cloud.stream.test.binder.TestSupportBinder**$1@5c2df62a

While the stub-runner is **not** imported I get the following dispatcher:

UnicastingDispatcher with handlers: **org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler**@6190d17f

**Comment by marcingrzejszczak** [comment]
Thanks for the analysis - I'll try to go through the code again and see what the problem might be. It will be very difficult to help you without the sample though. 

Also, can you check that if you don't add stub runner to the classpath, do you have the `stream-test-binder` dependency on the classpath anyways?

**Comment by doronl** [comment]
Actually since you asked, is seems that if I **excluded** the **spring-cloud-stream-test-support** (that comes as part of the starter) from the import, the issue seemed to be **resolved** and both the the integration tests (that require real channels in my case) and the stub tests seems to pass! 

Do I lose any core stub capability by excluding this jar?

**Comment by marcingrzejszczak** [comment]
That's what I thought.

Partially you lose it. `spring-cloud-stream-test-support` is the test dependency that is required to test stream apps without real channels. If your tests require the real ones then we have a problem.

BUT!

You can use stub messages against a real channel. Here you have an example of an app that uses stub runner and binds to a real broker. https://github.com/spring-cloud-samples/github-analytics-stub-runner-boot-no-eureka you can leverage those concepts in your tests.
