### ISSUE TITLE
401 connecting to dius pact broker

### ISSUE THREAD

**Issue by jorahood** [spring-cloud/spring-cloud-contract#636]
This may be a user error, but I'm trying to download contracts in my provider from the Dius hosted pact broker, which appears to use basic authentication. I've specified the url, username, and password in the spring-cloud-contract-maven-plugin config:

    ...
    <configuration>
      <contractsRepositoryUrl>pact://https://soandso.pact.dius.com.au:443</contractsRepositoryUrl>
      <contractsRepositoryUsername>blah</contractsRepositoryUsername>              
      <contractsRepositoryPassword>blahblah</contractsRepositoryPassword>
      <contractsMode>REMOTE</contractsMode>
    ...

I've verified these credentials work to upload the contracts from the consumer. Why am I getting a 401 when running generate-test-sources to download the contract?

    generateTests failed: Request to path '/' failed with response 'HTTP/1.1 401 Unauthorized'

**Comment by marcingrzejszczak** [comment]
Please don't cross post between stackoverflow and here.

Anyways, believe it or not, but most likely I'm completely ignoring those credentials props (which makes no sense). If you check this out https://cloud.spring.io/spring-cloud-contract/single/spring-cloud-contract.html#pact-stub-downloader you'll see how to pass credentials. Can you pass them in that way and see if it works. I'll leave this issue open to actually reuse the creds that you mentioned.

**Comment by jorahood** [comment]
Passing the credentials in pactbroker.auth.username and pactbroker.auth.password works.
