### ISSUE TITLE
Generate MockMvc tests

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#637]
currently, from the contracts, we generate JUnit or Spock tests that use RestAssured. It would be great to start generating `MockMvc` tests too. That way we can leverage RestDocs too, and we could generate all sorts of documentation out of the box.

**Comment by TYsewyn** [comment]
I'll start checking this/working on this in order to fix/close:
#613 - Generate rest docs from contracts
#617 - Generating http-based client from contract

**Comment by marcingrzejszczak** [comment]
We've decided to pick another flow. The ultimate goal was to use RestDocs. To do that initially we thought that MockMvc tests will need to be generated. That's actually not the case since it's enough to  use the RestAssured & RestDocs integration. You can check the docs for more info https://cloud.spring.io/spring-cloud-contract/single/spring-cloud-contract.html#_generating_spring_rest_docs_snippets_from_the_contracts
