### ISSUE TITLE
Large contract response bodies lead to 'code too large' (producer test) or extremely high wiremock response times

### ISSUE THREAD

**Issue by Hoagiex** [spring-cloud/spring-cloud-contract#638]
Large contract response bodies (in this example, a large json from file), lead to compile errors (code too large) for the producer side, or to timeouts on the client side, when using the stub-runner.

I have setup a small example project at: https://github.com/Hoagiex/spring-cloud-contract-issue-response-too-large

A) Is there any way to force the producer tests method to be fragmented, to prevent the 'code too large'-error?

B) What causes the wiremock to be so slow? Is there any way to speed up the generated wiremock stub?

**Comment by marcingrzejszczak** [comment]
I've analysed this issue and unfortunately I have bad news...

> A) Is there any way to force the producer tests method to be fragmented, to prevent the 'code too large'-error?

Nope, there's none. You'd have to cut the file analysis into several contracts I guess.

> B) What causes the wiremock to be so slow? Is there any way to speed up the generated wiremock stub?

No idea, I guess you'd have to ask the WireMock people about this.

The only "solution" that comes to my mind is actually trying to minimize the contract as such. Meaning that it's highly unlikely that the API requires all 18000 lines of JSON and all of them are mandatory. If that's the case however, then I'd write a `MockMvc` with `RestDocs` test and perform the necessary checks manually. That way you'll test what you need and you'll get the stub too.
