### ISSUE TITLE
Allow validating body content using MockMvc's validation or XMLUnit

### ISSUE THREAD

**Issue by dstepanov** [spring-cloud/spring-cloud-contract#658]
Right now it's not possible to validate XML body using contracts. 

Existing MockMvc code cannot be rewritten into contract:
```
   .andExpect(content().xml(readFileToString("/responses/response.xml"), true))
```

That's a pity because generated test is using `ResponseOptions` but API returns `MockMvcResponse` which has MockMvc instances to access, technically it would only require a simple call to validate body content. I had tried to write custom execute method but there is not way to pass file content there.

Underneath MockMvc is using `XMLUnit` maybe new matchers API can support that library or MockMvc validation.

**Comment by marcingrzejszczak** [comment]
I don't follow. We don't generate `MockMvc` tests. There's another issue related to XML and we're planning on adding any sort of support for XML. We can try to generate stuff in the similar way we do it with JSON via https://github.com/marcingrzejszczak/xmlassert . 

Until now, what you can do is to write `MockMvc` tests manually and assert the XML stuff manually.

**Comment by dstepanov** [comment]
Yes, tests doesn't use `MockMvc`'s validation functionality, technically it can be used out of box.

I think `XMLUnit` support would be enough.

**Comment by marcingrzejszczak** [comment]
> Yes, tests doesn't use MockMvc's validation functionality, technically it can be used out of box.

Yeah, if you write the full support for MockMvc for generated tests which we are not planning on doing. So there's nothing that comes out of the box for now. But maybe I don't follow what you're saying.

**Comment by dstepanov** [comment]
I have tried to implement custom method for server side validation but it looks like there is something wrong:

```
body(execute("equalsXml(\$it, \"${StringEscapeUtils.escapeJava(file('responses/ok.xml'))}\")".toString()))
```

but it generates:

```
assertThat(responseBody).isEqualTo("EXECUTION>>equalsXml($it, ");
```

**Comment by dstepanov** [comment]
Would you be for using XmlUnit for xml server side validation?

**Comment by dstepanov** [comment]
I don't see any added value. If Wiremock is already using it for matching why not to use it for validation?

**Comment by dstepanov** [comment]
I would prefer just simple XMLUnit  in the beginning

**Comment by marcingrzejszczak** [comment]
So you can create your own way of generating tests - spring cloud contract is fully pluggable.

**Comment by dstepanov** [comment]
I was thinking to add default XML comparing by XMLUnit... but you don't want it?

**Comment by marcingrzejszczak** [comment]
I explained it to you in my previous comments.
