### ISSUE TITLE
Starting two different stubs in the same port

### ISSUE THREAD

**Issue by shukad333** [spring-cloud/spring-cloud-contract#660]
Question

We have a hybrid kind of project model where multiple services runs on same port . 
Now say that my consumer C1 depends on P1(producer 1 ) and P2(producer 2) and both runs on the same port .

Is there any way I can configure on the client side , so that both are loaded on the same port ?

**Comment by marcingrzejszczak** [comment]
How can they run on the same port? What you can do is to run a single WireMock instance on one port, but load it with stubs from 2 different producers. If the URLs don't overlap then things should work fine. 

But IMO you could have 2 separate client contract tests, both of which have the http client's port configurable. I don't think you should combine those tests into one.

**Comment by shukad333** [comment]
Thanks for the reply .

How can they run on the same port?  - This is because ours is a mixed architecture and multiple projects are bundled as one fatty jar and deployed to a target port .

Have a follow up doubt too .. 

If Can i run the wiremock on the same server port as the producers are also loaded . Do you have some example which I can refer if this is possible .

**Comment by marcingrzejszczak** [comment]
I have a problem with understanding what you write. Why not do sth like this (pseudocode):

```java

class Client {

    private final int producerAPort;
    private final int producerBPort;

    Client(int producerAPort, int producerBPort) { this.producerAPort = producerAPort; this.producerBPort = producerBPort; }

    void callProducers() {
    // here you have your logic
    }

}
```

Configuration
```java
@Configuration
class ClientConfig {

    @Value("${producera.port:8765}") int producerAPort;
    @Value("${producerb.port:8765}") int producerBPort;

    @Bean Client client() {
        return new Client(this.producerAPort, this.producerBPort);
    }
}
```

Now in your contract tests you do the following:

```java
// all the annotations you need
// notice random ports
@AutoConfigureStubRunner(..., ids="...producer-a", "...producer-b")
public class ClientContractTest {

    @Autowired StubFinder finder;

    int producerAPort;
    int producerBPort;

    @Before
    public void setup(){ 
        this.producerAPort = this.finder.findStubUrl("...producer-a").getPort();
        this.producerBPort = this.finder.findStubUrl("...producer-b").getPort();
    }

    @Test
    public void shouldWorkForTwoProducers() {
        Client client = new Client(this.producerAPort, this.producerBPort);
        
        // test whatever you need
    }

}
```

Does it make sense?

**Comment by shukad333** [comment]
Yes .. Thank you so much ... Will try out and get back in case of any issues .

**Comment by marcingrzejszczak** [comment]
No problem
