### ISSUE TITLE
How to run against the provider which is behind nginx in production

### ISSUE THREAD

**Issue by shukad333** [spring-cloud/spring-cloud-contract#663]
Sorry for bothering you again .

We have a service which runs on port 7200 in production , but we use nginx to map it without hitting port number .

So original url is http://localhost:7300/service/endpoint is now accessed as http://localhost/service/endpoint in production .

Now we are trying to use Spring CDC for the API contract testing and we have generated the stub .

Please give us some inputs on how we can actually write the client side . 
Please note : Our client service is so matured as we will not be able to introduce the port for the call now . 

The below is how the client looks like now : 

```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.MOCK)
@AutoConfigureMockMvc
@AutoConfigureJsonTesters
@AutoConfigureStubRunner(workOffline = true,
        ids = {"com.a.b.c.d:serviceA:+:stubs:7100",
        		"com.e.f.g.h-serviceB:+:stubs:8080"
        })
@Slf4j
public class LICDCTest {

}
```

`serviceB` is the one which we need to access without the port . Please let us know how we can solve this .

**Comment by marcingrzejszczak** [comment]
You're making the same mistake again. Just make the URL `http://localhost/service/endpoint` parametrizable. Exactly in the way, I've done it previously. In your tests, you will create the proper URL that points to the WireMock executed via Stub Runner. So take the example I used previously and change the `port` to `url`. Make the default value `http://localhost/service/endpoint` in the configuration, and in your tests make it point to WireMock.

```java

class Client {

    private final String producerAUrl;
    private final String producerBUrl;

    Client(String producerAUrl, String producerBUrl) { 
        this.producerAUrl = producerAUrl; 
        this.producerBUrl = producerBUrl; 
    }

    void callProducers() {
    // here you have your logic
    }

}
```

Configuration
```java
@Configuration
class ClientConfig {

    @Value("${producera.url:http://localhost:7300/service/endpoint}") String producerAUrl;
    @Value("${producerb.url:http://localhost/service/endpoint}") String producerBUrl;

    @Bean Client client() {
        return new Client(this.producerAUrl, this.producerBUrl);
    }
}
```

Now in your contract tests you do the following:

```java
// all the annotations you need
// notice random ports
@AutoConfigureStubRunner(..., ids="...producer-a", "...producer-b")
public class ClientContractTest {

    @Autowired StubFinder finder;

    int producerAPort;
    int producerBPort;

    @Before
    public void setup(){ 
        this.producerAPort = this.finder.findStubUrl("...producer-a").getPort();
        this.producerBPort = this.finder.findStubUrl("...producer-b").getPort();
    }

    @Test
    public void shouldWorkForTwoProducers() {
        String urlA = "http://localhost:" + this.producerAPort + "/service/endpoint";
        String urlB = "http://localhost:" + this.producerBPort + "/service/endpoint";
        Client client = new Client(urlA, urlB);
        
        // test whatever you need
    }

}
```
