### ISSUE TITLE
Add support for Binary message / http body

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#664]
Currently, we convert everything back and forth to JSON and JSON Paths. We should allow an option that the body are bytes (which we can try to convert to JSON to change it into JSON Paths) but in case that's not true, we should try to support the flow anyways.

Corresponding SO issue - https://stackoverflow.com/questions/50757969/spring-cloud-contract-is-it-possible-use-a-binary-payload-in-message-body-of-c

**Comment by simez** [comment]
The first endpoint I was adding to an existing project required returning a PDF as the body.

I would suggest the behaviour be determined by a response header. `Content-Disposition: attachment` seems to be a standard way of hinting that the consumer/browser that the response should be downloaded.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
