### ISSUE TITLE
[doc] the sample command to run stub docker image does not work

### ISSUE THREAD

**Issue by zxkane** [spring-cloud/spring-cloud-contract#666]
Following the sample command to run stub runner docker image with local repo like below,

```
STUBRUNNER_IDS="cn.xxx.accounting:accounting-configserver:1.0.0:stubs:9876"
STUBRUNNER_REPOSITORY_ROOT="file:///m2/repository"
STUBRUNNER_PORT="8083"
SC_CONTRACT_DOCKER_VERSION=2.0.0.RC2
docker run  --rm --interactive --tty -e "STUBRUNNER_IDS=${STUBRUNNER_IDS}" -e "REPO_WITH_BINARIES_URL=${STUBRUNNER_REPOSITORY_ROOT}" -p "${STUBRUNNER_PORT}:${STUBRUNNER_PORT}" -p "9876:9876" -v ~/.m2:/m2  springcloud/spring-cloud-contract-stub-runner:"${SC_CONTRACT_DOCKER_VERSION}"
```

Then I got below error,

> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.contract.stubrunner.BatchStubRunner]: Factory method 'batchStubRunner' threw exception; nested exception is java.lang.IllegalStateException: No stubs were found on classpath for [cn.xxx.accounting:accounting-configserver]

The sample command miss docker env `STUBRUNNER_STUBS_MODE=REMOTE` when pulling stub from local/remote repository.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/commit/30614360be7b7bf264b98661c878a1e91b875a7b
