### ISSUE TITLE
Add support for GraphQL

### ISSUE THREAD

**Issue by mstachniuk** [spring-cloud/spring-cloud-contract#670]
We can do producer driven contracts like we do witrh RestDocs. We can wrap `GraphQL` object to record the query and the response, convert it to WireMock stub and dump it to `target`

``` groovy
@SpringBootTest
@ContextConfiguration(classes = Main)
class CustomerFetcherSpec extends Specification {

   @Autowired
   GraphQLSchema graphQLSchema

   GraphQL graphQL

   def setup() {
       graphQL = GraphQL.newGraphQL(graphQLSchema).build()
   }

def "should get customer by id"() {
   given:
   def query = """{ customer(id: "2") { … } }"""

   def expected = [ "customer": [ … ] ]

   when:
   def result = graphQL.execute(query)

   then:
   result.data == expected
}

```

**Comment by mstachniuk** [comment]
The whole code example: https://github.com/mstachniuk/graphql-java-example
and my presentation from Devoxx: https://www.slideshare.net/MarcinStachniuk/graphql-when-rest-api-is-to-less-lessons-learned

**Comment by soudmaijer** [comment]
I have read this a few times, but maybe it is just me.... but I was wondering, what is it you are expecting in terms of support from SCC? As far as I see it, you can already verify your GraphQL API with SCC. Construct a GET request with either the GraphQL query as queryParam or a POST with the Query in the body, and the response would be asserting JSON.

**Comment by marcingrzejszczak** [comment]
We thought about using it as a recorder. So if you already have GraphQL tests, we could reuse what you have to generate stubs.

Until then, your approach presented here: https://github.com/sourcelabs-nl/qnh-graphql looks perfect. That means using `EXPLICIT` mode against a running app that uses GraphQL
