### ISSUE TITLE
Documentation is a bit confusing re: accurest

### ISSUE THREAD

**Issue by madorb** [spring-cloud/spring-cloud-contract#671]
I was unaware that accurest was the precursor to SCC so was very confused when reading the docs and at the very start of section 2 it says:

`The Accurest project was initially started by Marcin Grzejszczak and Jakub Kubrynski (codearte.io)`

but there is no context nearby (or anywhere in the doc) that mentions that SCC was initially called accurest. 

Might be useful to call it out, perhaps provide a (very) brief history blurb sort of like spring security does to call out acegi (https://docs.spring.io/spring-security/site/docs/5.0.6.RELEASE/reference/htmlsingle/#history)

**Comment by marcingrzejszczak** [comment]
Good point, thanks for the feedback
