### ISSUE TITLE
verifier_messaging.adoc contains broken hard link to other docs

### ISSUE THREAD

**Issue by ascheman** [spring-cloud/spring-cloud-contract#672]
The file `verifier_messaging.adoc` contains a broken hard link to other parts of the documentation:

    For more information, see https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html/#stub-runner-for-messaging[the Stub Runner Messaging sections].

**Comment by marcingrzejszczak** [comment]
Ooops. Thanks for the pointer! Care for a PR? :)

**Comment by ascheman** [comment]
Sorry, have no idea how to fix this properly (depends on how you generates the resulting single or multi page documents). Otherwise I would be happy to help.
