### ISSUE TITLE
Add back support for camel with boot 2.0

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-contract#673]
Related camel issue - https://issues.apache.org/jira/browse/CAMEL-11430?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by Fetsivalen** [comment]
Hi @marcingrzejszczak ,
Do you have plans to restore Spring Cloud Contracts with Camel support for Spring boot 2.0?
Apache Camel starting from version 2.22.0 already supports Spring boot 2.0:
http://camel.apache.org/camel-2220-release.html
And also present 2.22.1 version which works fine.

**Comment by marcingrzejszczak** [comment]
Yeah we would like to add it but currently we have other issues that are in our backlog. But contributions are more than welcome!

**Comment by Fetsivalen** [comment]
Hi @marcingrzejszczak ,
I'm starting to look into this 
I'm gonna to revert and rebase the change:
https://github.com/spring-cloud/spring-cloud-contract/pull/387
But it's gonna be a big PR.
Would you accept such a PR, or you can advice to which parts should I split it?
