### ISSUE TITLE
The producer side generated tests failed in messaing AMQP.

### ISSUE THREAD

**Issue by hantsy** [spring-cloud/spring-cloud-contract#676]
I have tried to use Spring Cloud Contract 2.0.0 to test my RabbitMQ messaging between service my microservcie  project. 

I have posted it on stackoverflow:

https://stackoverflow.com/questions/51099451/the-generated-testsproducer-side-failed-in-spring-cloud-contract-and-amqp-rabb

And check the codes from my Github:

https://github.com/hantsy/spring-cloud-sample/tree/master/contract-producer-amqp

**Comment by hantsy** [comment]
@marcingrzejszczak I still got failure after upgrade to the latest 2.0.1.BUILD-SNAPSHOT

**Comment by hantsy** [comment]
@marcingrzejszczak I have updated my pom to use the latest build snapshot, still got the old failure.

**Comment by marcingrzejszczak** [comment]
maybe `rm -rf ` the local copies - I've managed to replicate the issue in the test and in your production code. Remember to use `Finchley.BUILD-SNAPSHOT` and `2.0.1.BUILD-SNAPSHOT` version of sc-contract plugin

**Comment by hantsy** [comment]
passed when using latest `Finchley.BUILD-SNAPSHOT`, thanks. @marcingrzejszczak
