### ISSUE TITLE
BaseClass defined using Kotlin - test are generated but build fails with compilation error

### ISSUE THREAD

**Issue by tsypuk** [spring-cloud/spring-cloud-contract#683]
If you are using **Kotlin** to write BaseClass, after defining contracts on build step, compilation fails with the message
`build/generated-test-sources/contracts/org/springframework/cloud/contract/verifier/tests/HelloTest.java:17: error: cannot find symbol`
`public class HelloTest extends BaseClass {`
`                               ^`
`  symbol: class BaseClass`
`2 errors`
`startup failed:`
`Compilation failed; see the compiler error output for details.`

But in case BaseClass is defined as **Java** class - tests are generated and compilation passes

**Comment by tsypuk** [comment]
The problem was in default compilation order for compileTestGroovy

To make it compile and run update **gradle.build**:

`compileTestGroovy {`
`dependsOn tasks.getByPath('compileTestKotlin')`
`classpath += files(compileTestKotlin.destinationDir)`
`}`

**Comment by ar-zare** [comment]
I have the same problem but than using maven.
Do you know how to fix this in maven?

**Comment by marcingrzejszczak** [comment]
Please check this project https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/master/producer_kotlin

**Comment by ar-zare** [comment]
Thanks! I'll do!
