### ISSUE TITLE
how to send json in body of the request 

### ISSUE THREAD

**Issue by svijetha78** [spring-cloud/spring-cloud-contract#698]
```

        Contract.make {
            name 'should create Customer.dedup BE'
            request{
                method 'POST'
                urlPath(BE_CUSTOMER_DEDUP_URL)
                headers {
                    header 'X-INFA-USER-NAME', value(producer(TENANT_NAME), consumer(optional(regex('\\w+'))))
                    header 'X-INFA-USER-ID', value(producer(TENANT_NAME), consumer(optional(regex('\\w+'))))
                    header 'X-INFA-ORG-ID', TENANT_NAME
                    contentType(applicationJson())
                }

               body(SEND JSON payload  )
            
            }
            response {


                status 201
            }
        }
```

In above request we need to send json Payload in request body , is there a way we can do this ?

**Comment by marcingrzejszczak** [comment]
I don't understand. Just put the Json body there. Either via string or a map.

**Comment by johannesjasper** [comment]
@svijetha78 Have a look at the samples repo
https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/master/beer_contracts/src/main/resources/contracts/com/example/beer-api-producer-external/1.0.0/beer-api-consumer/rest/shouldGrantABeerIfOldEnough.groovy#L18

**Comment by marcingrzejszczak** [comment]
Thanks @johannesjasper .

@svijetha78 please read the documentation of the project where we explain that in a lot of details.

**Comment by svijetha78** [comment]
Thanks !
inal PROSPECT_RECORD =[

            "id": 9089,
            "prefix": "Mr.",
            "firstName": "John",
            "lastName": "Validation",
            "deathStatusCode": 6,
            "statusReasonCode": 84,
            "language": "English",
            "statusChangeDate": 102345690,
            "version": 5,
            "deathInd": false,
            "status": 3,
            "state": "NEW",
            "birthDay": "1911-11-11"

]

[
        Contract.make {
            name 'should create household BE'
            request{
                method 'POST'
                urlPath(BE_HOUSEHOLD_URL)
                headers {
                    header 'X-INFA-USER-NAME', value(producer(TENANT_NAME), consumer(optional(regex('\\w+'))))
                    header 'X-INFA-USER-ID', value(producer(TENANT_NAME), consumer(optional(regex('\\w+'))))
                    header 'X-INFA-ORG-ID', TENANT_NAME
                    contentType(applicationJson())
                }
                body(id: 56)
            }
            response {
                status 201
            }
        },
        Contract.make {
            name 'should create prospect  BE'
            request{
                method 'POST'
                urlPath(Prospect_URL)
                headers {
                    header 'X-INFA-USER-NAME', value(producer(TENANT_NAME), consumer(optional(regex('\\w+'))))
                    header 'X-INFA-USER-ID', value(producer(TENANT_NAME), consumer(optional(regex('\\w+'))))
                    header 'X-INFA-ORG-ID', TENANT_NAME
                    contentType(applicationJson())
                }
                body(PROSPECT_RECORD)
            }
            response {
                status 201
            }
        }


]
