### ISSUE TITLE
WireMock proxy with Spring Contract DSL

### ISSUE THREAD

**Issue by abbasadel** [spring-cloud/spring-cloud-contract#711]
Hi, 
Currently, we want to use the Wiremock proxy functionality using Spring Contract DSL. 
Basicly, We want to have something like this:

```
Contract.make {
    request {
        method HttpMethods.HttpMethod.GET
        url '/'

    }

    response {
        status 200
        proxyBaseUrl 'http://otherhost.com/approot'
    }
}
```

Any plans to support this in the future?

Thanks,

**Comment by marcingrzejszczak** [comment]
Not really cause you can use @AutoConfigureWireMock and setup the stubs as you wish. Example: https://github.com/marcingrzejszczak/the-legacy-app/tree/master/stubs_with_proxy

**Comment by amanica** [comment]
> Not really cause you can use @AutoConfigureWireMock and setup the stubs as you wish. Example: https://github.com/marcingrzejszczak/the-legacy-app/tree/master/stubs_with_proxy

I finally figured out you that if you want to use dynamic ports :` @AutoConfigureWireMock(port = Options.DYNAMIC_PORT)`
then you need to tell WireMockSpring to actually use this port if you are overriding the Options bean: `

```
@Configuration static class Config { 
@Bean Options options( @Value("${wiremock.server.port}") int wireMockPort) { 
    ... 
    return WireMockSpring.options() .port(wireMockPort)
    ...
```
