### ISSUE TITLE
Pick contracts from local (contractDirectory) and from Remote (contractDependency) at the same time

### ISSUE THREAD

**Issue by jesantana** [spring-cloud/spring-cloud-contract#714]
**Question**

I am implementing an application that needs to verify several contracts, some of them are defined inside the application itself (under src/test/contracts) and other are defined in an external project and are accessible by the generated jar. Is there a way that I can configure the maven plugin spring-cloud-contract-maven-plugin to get all contracts from both sources at the same time and treat them like if they were coming from the same. (define contractDirectory and contractDependency in the configuration section at the same time)

**Comment by marcingrzejszczak** [comment]
You can: 

- create 2 maven profiles and run the build twice
- you can first download and unzip the stubs, put them into some folder, strip those that you don't need, copy your `src/test/resources/contracts` there too and then in the contract tests point to that folder

**Comment by jesantana** [comment]
Thanks for the help. Your approaches are valid as solutions, although finally we decided to include a task to move all contracts to the same place and avoid the problem.
