### ISSUE TITLE
Support for Repeating Query Parameters

### ISSUE THREAD

**Issue by cosmin-mogos** [spring-cloud/spring-cloud-contract#716]
Given the following controller:

```
@RestController
public class ProducerController {
  public Response check(@RequestParam(name = "type", required = false) List<Integer> types) {
    ...
  }
}
```

The contract below:

```
package contracts.exmple.rest

import org.springframework.cloud.contract.spec.Contract

Contract.make {
  request {
    description("""
Repeated parameters
""")
    method 'GET'
    urlPath('/things') {
      queryParameters {
        parameter type: [1, 2]
      }
    }
  }
  response {
    status 200
  }
}
```
Does not generate the expected producer stub, the test fails with:

```
Failed to convert value of type 'java.lang.String' to required type 'java.util.List'; nested exception is java.lang.NumberFormatException: For input string: "[1,2]"
```
Because the generated `RestTest`, contains:
```
			ResponseOptions response = given().spec(request)
					.queryParam("type","[1, 2]")
					.get("/things");
```
Instead of :
```
			ResponseOptions response = given().spec(request)
					.queryParam("type",1)
					.queryParam("type",2)
					.get("/things");
```
The generated WireMock stub also is incorrect.

Using version 1.2.5.RELEASE of sprint-cloud-contract

**Comment by cosmin-mogos** [comment]
There seems to be a related issue with wiremock, see: https://github.com/tomakehurst/wiremock/issues/398.

In our case we removed the use or repeated query parameters and replaced them with one parameter containing a comma separated list.

**Comment by marcingrzejszczak** [comment]
I guess we can close this until the WireMock issue is fixed...

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by otaconix** [comment]
I ran into this issue this week, and ended up working around it as follows:

```java
Contract.make {
    request {
        method 'GET'
        url($(consumer(regex('/api/?\\?id=[a-zA-Z0-9]+(&id=[a-zA-Z0-9]+)?')), producer('/api?relation_id=EXPLICIT_ID_A&relation_id=EXPLICIT_ID_B')))
    }
    response {
        status 200
    }
}
```

Note the usage of `url` in the request matcher, instead of `urlPath`. If you don't do that, the generated Wiremock mapping won't match, as it'll only check the path (without the query part).
Also: you **must** use a different matcher for your producer if you wish the generated test to include the optional repetition of the query parameter.

Hopefully this'll save someone some guesswork down the line.
