### ISSUE TITLE
Contract DSL and request.addPreferredLocale

### ISSUE THREAD

**Issue by ngrigoriev** [spring-cloud/spring-cloud-contract#735]
I have an API to test that uses Accept-Language and I want my contract tests to cover that part of functionality.

MockHttpServletRequest does not support the generation of the default request locale from Accept-Language header and it is clearly stated in its javadocs.

What are the options for working around this limitation? Can I do something in my contract definition to call addPreferredLocale() on the mock request instead/in addition to setting the header? Are there any better options?

**Comment by ngrigoriev** [comment]
(answering to myself) I have found at least one way to work around this limitation: use real server when testing instead of the local mock, e.g. EXPLICIT test mode etc. Are there any better options? :)

**Comment by marcingrzejszczak** [comment]
Not really. If it's a limitation of MockMvc then there's not much we can do. You could file an issue to MockMvc to add such a feature.
