### ISSUE TITLE
problem with generating assertions for list of objects returned by service

### ISSUE THREAD

**Issue by Krzyych** [spring-cloud/spring-cloud-contract#736]
I have a rest service returning a list of objects. I wrote a contract in groovy which most interesting part is:
`response {
  body([[id: 15]])
  bodyMatchers {
      jsonPath('$.[0].id', byRegex(number()))
  }
}`
which generates following code:
`DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
assertThatJson(parsedJson).array().isEmpty();
// and:
assertThat(parsedJson.read("$.[0].id", String.class)).matches("-?(\\d*\\.\\d+|\\d+)");`

the problem is that assertion isEmpty is generated (similar problem like issue #727)

Another problem is that if I change the jsonPath to:
`jsonPath('$.[*].id', byRegex(number()))`
following assertion is generated:
`assertThat((java.lang.Iterable) parsedJson.read("$.[*].id", java.util.Collection.class)).as("$.[*].id").allElementsMatch("-?(\\d*\\.\\d+|\\d+)");`
but the class AbstractIterableAssert does not have method allElementsMatch, so the code does not compile.

**Comment by marcingrzejszczak** [comment]
> Another problem is that if I change the jsonPath to:
jsonPath('$.[*].id', byRegex(number()))
following assertion is generated:
assertThat((java.lang.Iterable) parsedJson.read("$.[*].id", java.util.Collection.class)).as("$.[*].id").allElementsMatch("-?(\\d*\\.\\d+|\\d+)");
but the class AbstractIterableAssert does not have method allElementsMatch, so the code does not compile.

Are you sure you've provided the Spring Cloud Contract Maven Plugin version? It seems that an old one was picked automatically.

**Comment by Krzyych** [comment]
Automatically it was taken version 2.0.1.RELEASE of spring-cloud-contract-maven-plugin plugin.
Even if I specify this version expilicity the situation is the same:
```
<plugin>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-contract-maven-plugin</artifactId>
    <version>2.0.1.RELEASE</version>
    <extensions>true</extensions>
    <configuration>
        <packageWithBaseClasses>my.package</packageWithBaseClasses>
    </configuration>
</plugin>
```

And I have a dependency to spring-cloud-starter-contract-verifier which has automatically taken version: 2.0.0.M7.

**Comment by marcingrzejszczak** [comment]
> And I have a dependency to spring-cloud-starter-contract-verifier which has automatically taken version: 2.0.0.M7.

this is wrong

please check out https://github.com/spring-cloud-samples/spring-cloud-contract-samples and set your project in the same way
