### ISSUE TITLE
How to verify multiple header values under the same name?

### ISSUE THREAD

**Issue by madamiak** [spring-cloud/spring-cloud-contract#739]
Let's say you want to verify header entries from the response. The response contains the following headers:
```
"Some-Header": "value1",
"Some-Header": "value2",
"Some-Header": "value3"
```
How can I verify if "Some-Header" has 3 entries and their values are `["value1", "value2", "value3"]` using contract DSL?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
