### ISSUE TITLE
String JSON array dropping double quotes

### ISSUE THREAD

**Issue by chuckleslord** [spring-cloud/spring-cloud-contract#760]
Bug report:

When you input a messageBody as a String, it will drop the double quotes if the String is encapsulated with brackets.

The API I am testing expects a String as input. That String just so happens to be formatted as a JSON array (ex. [{"name": "value"}])

However, if I add the string into the messageBody, it'll drop all the double quotes.

Example:

`    input {
        messageFrom("some-exchange")
        messageBody('''
             [{  "myMessageList":{
                   "Message":[  
                      {  
                         "code":"error",
                         "message":"an error code"
                      },
                      {  
                         "code":"error2",
                         "message":"some other error code."
                      }
                   ]
                },
                "action":"ADD",
                "result":"failure",
                "domain":"someAPI"
             }]
            ''')
    }
`

the resulting spock test will have this as the message:
`'''
             [{  myMessageList:{
                   Message:[  
                      {  
                         code:error,
                         message:an error code
                      },
                      {  
                         code:error2,
                         message:some other error code.
                      }
                   ]
                },
                action:ADD,
                result:failure,
                domain:someAPI
             }]
            ''')
    }`

Which cannot be read as a JSON. Is there anything I'm missing or is it truly a bug?

**Comment by marcingrzejszczak** [comment]
That's strange. Can you actually convert this into a map instead of a String and see if you still have such a problem?

**Comment by chuckleslord** [comment]
Thanks for the tip! It worked when I sent the Payload in as a List<String>. Thanks
