### ISSUE TITLE
Support `execute` in request's body parameters 

### ISSUE THREAD

**Issue by dstepanov** [spring-cloud/spring-cloud-contract#761]
```
Contract.make {
	request {
		method POST()
		url '/users/password'
		headers {
			contentType(applicationJson())
		}
		body(
				dateField: $(consumer(regex(xyzDateTime())), producer(execute('todayDate()')))
		)
	}
```

**Comment by marcingrzejszczak** [comment]
You can run `todayDate()` directly from your DSL and each time you will generate that date. There's no need to run any methods.

**Comment by dstepanov** [comment]
Yes, I can execute code in Groovy but if there is a more complicated use-case, like security token etc. I cannot execute method from parameter. In that case I need to build whole JSON in base class if I want to have it supported, but that's limiting match compatibilities.

Specially I don't like that in this case, `execute` gets silently printed to JSON.

**Comment by marcingrzejszczak** [comment]
The amount of work required to make this work would be substantial. As a workaround, what we suggest is that you use `execute` on the request field directly. You will also have to provide quite a big regex for the consumer side.

```groovy
Contract.make {
	request {
		method POST()
		url '/users/password'
		headers {
			contentType(applicationJson())
		}
		body(
				$(consumer(regex('"dateField":' + xyzDateTime())), producer(execute('todayDate()')))
		)
	}
```

If you are willing to contribute this feature, please, be our guest.
