### ISSUE TITLE
Give a special name for generated contract test class

### ISSUE THREAD

**Issue by AlicanAkkus** [spring-cloud/spring-cloud-contract#777]
Hi,

I want to give a suggestion. Can I give a test class name to in a contract? I want to specify test name in contract dsl file. It's now generated test with a package name prefix. Is it possible to add a contract project? :)

may be similar to as below;
```

Contract.make {
    testClassName "RetrieveAllSample"
    request {
        method GET()
        url("/api/v1/samples")
    }
    response {
        status OK()
        headers {
            contentType(applicationJson())
        }
    }
}
```
I've added **testClassName** in a contract.

**Comment by marcingrzejszczak** [comment]
You can't do it. But you can change the method name of that helps. Why would you want to have a different class name?

**Comment by AlicanAkkus** [comment]
thanks, Marcin. there is no any special reason for that except class name readbility. 
changing method name could be useful for us 👍

**Comment by marcingrzejszczak** [comment]
I see. I'll close it for now then and if someone is every interested in this we will consider reopening it.

**Comment by AlicanAkkus** [comment]
thank you 🚀

**Comment by dorofeev-serdg** [comment]
By default tests in a project are separated into the following categories:
- *Test are unit test
- *IT are integration tests

If there is no possibility to set a test name, then it breaks this pattern and any kind of workaround should be implemented.

**Comment by marcingrzejszczak** [comment]
The workaround can be to use a Maven ant run plugin (or a Gradle task)

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-antrun-plugin</artifactId>
    <version>3.1.0</version>
    <executions>
        <execution>
            <id>rename-file</id>
            <phase>process-resources</phase>
            <goals>
                <goal>run</goal>
            </goals>
            <configuration>
                <target>
                    <move file="${project.build.directory}/path/to/generated/tests/ContractVerifierTests.java" 
                          tofile="${project.build.directory}/path/to/generated/tests/ContractVerifierIT.java"/>
                </target>
            </configuration>
        </execution>
    </executions>
</plugin>
```
