### ISSUE TITLE
Support for publishing validation results to Pact Broker

### ISSUE THREAD

**Issue by ogawa-takeshi** [spring-cloud/spring-cloud-contract#778]
Hello. Thank you for supporting Pact.
From version 2.0, Pact Broker is able to publish the verification result of the provider side as the following image shows.
![pact-broker](https://user-images.githubusercontent.com/29126253/47951119-a83a7e80-df9f-11e8-8c4a-212a735e7cf3.png)

How about Spring Cloud Contract releasing Pact's verification result to Pact Broker automatically?

**Comment by marcingrzejszczak** [comment]
Can you elaborate on how the flow would look like?

**Comment by ogawa-takeshi** [comment]
I have created sample code as follows.
https://github.com/tagbangers/sf-2018-spring-cloud-contract-demo

In the sample code, Consumer is Angular and Provider is Spring Data REST.
A Pact file is generated on the Angular side, and varification of the Pact file is executed by the Spring Cloud Contract on the Provider side via the Pact Broker.
While doing so, I would like to notify the Pact Broker of the verification result by Spring Cloud Contract automatically.

**Comment by ymamakis** [comment]
Hi there, 
I am trying to accomplish something similar for different framework mixes so I would +1 that, knowing that it may be harder than what it sounds

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by donalhurley** [comment]
@spring-issuemaster Would it be possible to re-open this issue.

I would also like the verification results to be sent to a Pact broker after the contract tests have successfully executed.
This I think is supported by the `pact-jvm-provider-maven_2.12` maven plugin after you run `mvn pact:verify`.

Would it be possible to configure this in the configuration of the spring maven plugin `spring-cloud-contract-maven-plugin`?
Maybe a switch or flag that would optionally publish the verification results to the pact broker like `contractsPublishVerificationResults` if it is set and `spring-cloud-contract-pact` is the broker implementation?

Proposed configuration.

```
<plugin> 
    <artifactId>spring-cloud-contract-maven-plugin</artifactId>
    <configuration>
        <contractsPublishVerificationResults>true</contractsPublishVerificationResults>
```

**Comment by marcingrzejszczak** [comment]
I don't understand. You can configure the maven plugins to automatically publish results.

**Comment by donalhurley** [comment]
@marcingrzejszczak My apologies but I can't see how that is done from reading the documentation. Can you show how to configure publication of the verification results or point to some example which does it?

**Comment by marcingrzejszczak** [comment]
It's not in the docs. There's an experimental feature that you can use. You can call a method that can convert a DSL to PACT and then use the PACT files to send it to the Broker. 

.Maven
```xml
<build>
   <plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.6.0</version>
				<executions>
					<execution>
						<id>setup-docker</id>
						<phase>test-compile</phase>
						<configuration>
							<executable>./start.sh</executable>
						</configuration>
						<goals>
							<goal>exec</goal>
						</goals>
					</execution>
					<execution>
						<id>convert-dsl-to-pact</id>
						<phase>process-test-classes</phase>
						<configuration>
							<classpathScope>test</classpathScope>
							<mainClass>
								org.springframework.cloud.contract.verifier.util.ToFileContractsTransformer
							</mainClass>
							<arguments>
								<argument>
									org.springframework.cloud.contract.verifier.spec.pact.PactContractConverter
								</argument>
								<argument>${project.basedir}/target/pacts</argument>
								<argument>
									${project.basedir}/src/test/resources/contracts
								</argument>
							</arguments>
						</configuration>
						<goals>
							<goal>java</goal>
						</goals>
					</execution></executions>
			</plugin>
			<plugin>
				<groupId>au.com.dius</groupId>
				<artifactId>pact-jvm-provider-maven_2.12</artifactId>
				<version>${pact-jvm-provider-maven.version}</version>
				<configuration>
					<pactBrokerUrl>http://localhost:8085</pactBrokerUrl>
				</configuration>
				<executions>
					<execution>
						<!-- For this case we upload before running test -->
						<phase>process-test-classes</phase>
						<goals>
							<goal>publish</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

```

**Comment by donalhurley** [comment]
@marcingrzejszczak I think it would be better if it was supported by the `spring-cloud-contract-maven-plugin` with a configuration option if possible which is why I think it would be good to re-open this issue.

**Comment by marcingrzejszczak** [comment]
I understand. However we're not planning on adding such feature.
