### ISSUE TITLE
Generate contracts with RestDocs using RestAssured: support matchers

### ISSUE THREAD

**Issue by ThanksForAllTheFish** [spring-cloud/spring-cloud-contract#784]
Inspired by [this SoF question](https://stackoverflow.com/questions/53170500/spring-cloud-contracts-from-restdocs-custom-matchers): with mockmvc it is possible to use wiremock to define matchers (at least for requests, see https://github.com/spring-cloud/spring-cloud-contract/issues/783).

It would be cool to bring RestAssured to feature parity, at least in this regard.

**Comment by OlgaMaciaszek** [comment]
Hello @ThanksForAllTheFish we don't currently have this in the backlog, but if you would like to work on this, please feel free to submit a PR. Alternatively, just use MockMvc.

**Comment by marcingrzejszczak** [comment]
Let's close this issue until then. If a PR arrives we can reopen it
