### ISSUE TITLE
Contract verifier doesnt wait for DeferredResult

### ISSUE THREAD

**Issue by michalkarolik** [spring-cloud/spring-cloud-contract#80]
Maybe im doing something wrong.. but seems that using DeferredResult somehow breaks waiting for result in contract verifier (or how to call it:) ). It gets empty result as soon as I return DeferredResult from controller, I believe it should wait for actual response underneath?

contract:

```
org.springframework.cloud.contract.spec.Contract.make {

			request {
				method 'GET'
				url '/get'
			}
			response {
                status 200
				body 'Passed'
			}
}
```

controller:

```
@GetMapping
    public DeferredResult<String> get(){

        DeferredResult<String> deferredResult = new DeferredResult<>();
        CompletableFuture.supplyAsync(()-> {
                    deferredResult.setResult("Passed");
                    return deferredResult;
                }
        );
        return deferredResult;
    }
```

running tests:
```
org.junit.ComparisonFailure: expected:<"[Passed]"> but was:<"[]">
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at org.springframework.cloud.contract.verifier.tests.TipTest.validate_getContract(TipTest.java:29)
```

curl:
```
curl localhost:8095/get

Passed
```

do I have to configure something to use contracts to test my API?

**Comment by marcingrzejszczak** [comment]
It's not written in the docs but in the response add the `async()` block

```
org.springframework.cloud.contract.spec.Contract.make {

        request {
            method 'GET'
            url '/get'
        }
        response {
            status 200
            body 'Passed'
            async()
        }
}

```

I'll have to update the docs :/

**Comment by michalkarolik** [comment]
Marcin... I havent even managed to format my question properly.. thanks for fast reply, works! :)

**Comment by marcingrzejszczak** [comment]
Sweet - I'm not closing this issue - it will be a reminder for me to update the docs. Very good catch!

**Comment by marcingrzejszczak** [comment]
waaaat - I'm checking it out

**Comment by michalkarolik** [comment]
maybe it wasnt your change, other docs also have this issue:
https://github.com/spring-cloud/spring-cloud-contract/blob/master/docs/src/main/asciidoc/verifier/stubrunner.adoc

**Comment by marcingrzejszczak** [comment]
I broke with another commit

**Comment by marcingrzejszczak** [comment]
OK I fixed it

**Comment by michalkarolik** [comment]
Should I wait for some CI to build it? Wanted to read this doc :)

**Comment by marcingrzejszczak** [comment]
It's right above this https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_messaging_top_level_elements nothing special ;)
