### ISSUE TITLE
NPE when accessing to body of WireMockHttpServletRequestAdapter

### ISSUE THREAD

**Issue by gulsbh** [spring-cloud/spring-cloud-contract#804]
WireMockHttpServletRequestAdapter body can be null, and it causes NPE.

This line (https://github.com/spring-cloud/spring-cloud-contract/blob/9bafbf66c8f6c94bfae79ec6696ad26431876e54/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/ContractResultHandler.java#L130)

![image](https://user-images.githubusercontent.com/4007926/49095608-1efa2d00-f269-11e8-9d75-ad33801511c0.png)

has changed from version (commit: https://github.com/spring-cloud/spring-cloud-contract/commit/096790e04d6fae6cc1871413ddb3b605b0a75c76#diff-c23d3f85461e0c14a0da7a7ae917862e)

Before it was returning empty byte array. Now we get NPE in this line (https://github.com/spring-cloud/spring-cloud-contract/blob/9bafbf66c8f6c94bfae79ec6696ad26431876e54/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockVerifyHelper.java#L59) because of this change. It should return default empty array.

**Comment by OlgaMaciaszek** [comment]
Makes sense. Thanks for reporting this.
