### ISSUE TITLE
Handle cirucular (consumer/ producer) dependencies between services

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-contract#810]
Currently SCC does not handle circular dependencie between services, but it's reasonable to assume that we could have a service A exposing an HTTP API to service B and, at the same time listening to messages from service B. As both services depend on stubs (and  atuo-generated tests passing) from the other service, there is a cycle and neither can be published.

**Comment by marcingrzejszczak** [comment]
You can solve this by using the `generateStubs` (https://github.com/spring-cloud/spring-cloud-contract/issues/881) feature. So, until the stubs of the other side are generated, you can just toggle that feature on and the off once the other side has finished their work.
