### ISSUE TITLE
Make JSON validation more strict

### ISSUE THREAD

**Issue by dstepanov** [spring-cloud/spring-cloud-contract#815]
I like to use contracts to validate server API but right now validation is not very strict and makes framework look bad.

There are a few cases I can remember:

#### Array item's fields aren't validated together:

```
assertThatJson(parsedJson).array("['payments']").contains("['principalPayment']").isEqualTo(605.86);
assertThatJson(parsedJson).array("['payments']").contains("['principalPayment']").isEqualTo(1211.3);
```

Correct way would be to validate that array `payments` item with index `0` contains a field. There can be an option to ignore the order but objects at the same index should match.

#### Double array `[[{ ... }]]` and single array `[{...}]` generate the same test:

```
assertThatJson(parsedJson).array().array("['payments']").contains("['paymentNumber']").isEqualTo(7);
```

#### Currently there is no way to match an empty json or fail on unknown values

It might be a good idea to not allow unknown fields that aren't covered by a test.

I would prefer for the framework to have the same features as https://github.com/skyscreamer/JSONassert mostly its compare mode http://jsonassert.skyscreamer.org/apidocs/org/skyscreamer/jsonassert/JSONCompareMode.html

**Comment by marcingrzejszczak** [comment]
You can use the `bodyMatchers` section to perform the any precise evaluation you wish.

**Comment by dstepanov** [comment]
How this makes any sense, Marcin? Why would anyone want to write matching manually?

**Comment by dstepanov** [comment]
And are you going to ignore other bugs?

**Comment by marcingrzejszczak** [comment]
If you think that it's a bug, please feel free to file a pull request that fixes it.

**Comment by tn185070** [comment]
@marcingrzejszczak still no interest in implementing a feature to fail on unknown fields? I'm not sure we could implement that ourselves.

**Comment by marcingrzejszczak** [comment]
We're open to pull requests. Atm we don't have the capacity to implement such a feature.

**Comment by pooja-choudhary13** [comment]
@marcingrzejszczak does SCC support fail on unknown fields now ? If not can you please guide me how can i write the code using bodyMatchers or any other configuration to implement this for me ? Thanks in advance!
