### ISSUE TITLE
Unable to validate a complex json with groovy contract

### ISSUE THREAD

**Issue by KanikaDeka** [spring-cloud/spring-cloud-contract#817]
I am new in spring cloud contract and currently developing a spring cloud project where I need to validate a  JSON request. My json includes an array list, here I am facing issues while validating a particular element of the array list. My groovy contract at producer end looks like as below: 

``` 
package contracts.beer.rest
import org.springframework.cloud.contract.spec.Contract

Contract.make{

    description("""
    Validating A CWP MO For New Customer
    """)

    request{

        method 'POST'
        url    '/ValidateMO'
        body(
                id: $(anyNumber()),
                name: $(producer(regex('[a-zA-Z]+'))),
                age: $(producer(regex('[0-9][2-9]'))),
                salary: $(producer(regex('[1-9][0-9]{5}'))),
                designation: $(producer(regex('[A-Za-z]+'))),
                addressList:[
                        [
                            street: value($(producer(regex('[A-Za-z]+')))),
                            city: value($(producer(regex('[A-Za-z]+')))),
                            zipCode: value($(producer(regex('[0-9]{5}'))))
                        ]
                ],
                phoneNumbers:[
                        $(producer('12345')),
                        $(producer('56789'))
                ],
                personalInformation:[
                    gender: $(producer('Male')),
                    maritialstatus: $(producer('Unmarried'))
                ]
        )
        headers {
            contentType(applicationJson())
        }
    }
    response{
        status 200
        body("""
     {
     "status":"OK"
     }
     """)
        headers{
            contentType(applicationJson())
        }
    }
}
```

and corresponding stub generated for this contract is:

```
{
  "id" : "abdcb032-ce87-445e-bf93-9ba485fdb19d",
  "request" : {
    "url" : "/ValidateMO",
    "method" : "POST",
    "headers" : {
      "Content-Type" : {
        "matches" : "application/json.*"
      }
    },
    "bodyPatterns" : [ {
      "matchesJsonPath" : "$[?(@.['salary'] =~ /[1-9][0-9]{5}/)]"
    }, {
      "matchesJsonPath" : "$.['personalInformation'][?(@.['maritialstatus'] == 'Unmarried')]"
    }, {
      "matchesJsonPath" : "$[?(@.['id'] =~ /-?(\\d*\\.\\d+|\\d+)/)]"
    }, {
      "matchesJsonPath" : "$[?(@.['designation'] =~ /[A-Za-z]+/)]"
    }, {
      "matchesJsonPath" : "$.['addressList'][*][?(@.['zipCode'] =~ /[0-9]{5}/)]"
    }, {
      "matchesJsonPath" : "$.['phoneNumbers'][?(@ == '56789')]"
    }, {
      "matchesJsonPath" : "$.['addressList'][*][?(@.['city'] =~ /[A-Za-z]+/)]"
    }, {
      "matchesJsonPath" : "$.['addressList'][*][?(@.['street'] =~ /[A-Za-z]+/)]"
    }, {
      "matchesJsonPath" : "$.['personalInformation'][?(@.['gender'] == 'Male')]"
    }, {
      "matchesJsonPath" : "$[?(@.['name'] =~ /[a-zA-Z]+/)]"
    }, {
      "matchesJsonPath" : "$[?(@.['age'] =~ /[0-9][2-9]/)]"
    }, {
      "matchesJsonPath" : "$.['phoneNumbers'][?(@ == '12345')]"
    } ]
  },
  "response" : {
    "status" : 200,
    "body" : "{\"status\":\"OK\"}",
    "headers" : {
      "Content-Type" : "application/json"
    },
    "transformers" : [ "response-template" ]
  },
  "uuid" : "abdcb032-ce87-445e-bf93-9ba485fdb19d"
}
````` 

Here addressList can contain multiple addresses. so at consumer end suppose I have two different addresses, if pass wrong value of zipcode for both addresses then my testcase got failed, but if I pass one zipcode as wrong and another one correct in that scenario testcase got executed successfully which is wrong behavior. So can anybody tell me where is the issue in my contract? Providing consumer end testcase  also:

```
      @Test
       public void validateMO() throws Exception {
        long[] phnNum={12345,56789};
        HashMap<String,String> personalInformation=new HashMap<String,String>();
        personalInformation.put("gender","Male");
        personalInformation.put("maritialstatus","Unmarried");
        BigDecimal sal=new BigDecimal(100000);
        List<Address> addressList =new ArrayList<>();
        addressList.add(new Address("Park Avn","West chester",123451));
        addressList.add(new Address("Park Avn","West chester2",56789));
        mockMvc.perform(MockMvcRequestBuilders.post("/validate")
                .contentType(MediaType.APPLICATION_JSON)
                .content(json.write(new Employee(12,"Aman",25,sal,"Programmer",addressList,phnNum,personalInformation)).getJson()))
                .andExpect(status().isOk())
                .andExpect(content().string("THERE YOU GO"));
        //remove::end[]
    }
```

**Comment by marcingrzejszczak** [comment]
The jsonpaths assume that there at least an entry that matches. If you want to ensure that a concrete entry matches, you can use the `bodyMatchers` section and define that e.g. an entry with index `[0]` has a concrete value of the regular expression. You can read more about it here https://cloud.spring.io/spring-cloud-static/Finchley.SR2/single/spring-cloud.html#contract-matchers

**Comment by KanikaDeka** [comment]
I want to make it generic... instead of using index[0] or index[1], I want to use *, so that it fails when any of the zipcode is wrong at any index. After writing the validation part in bodyMatcher, it is still failing:

`package contracts.beer.rest
import org.springframework.cloud.contract.spec.Contract

Contract.make{

    description("""
    Validating A CWP MO For New Customer
    """)

    request{

        method 'POST'
        url    '/ValidateMO'
        body(file("cwp_mo.json"))
        bodyMatchers {
            jsonPath('$.id',byRegex("[0-9]{2}"))
            jsonPath('$.name',byRegex('[A-Za-z]+'))
            jsonPath('$.age',byRegex('[2-9][0-9]'))
            jsonPath('$.salary',byRegex('[1-9][0-9]{5}'))
            jsonPath('$.designation',byRegex('[A-Za-z]+'))
            jsonPath("\$.['addressList'][*].['zipCode']", byRegex('[0-9]{5}'))

        }
        headers {
            contentType(applicationJson())
        }
    }
    response{
        status 200
        body("""
     {
     "status":"OK"
     }
     """)
        headers{
            contentType(applicationJson())
        }
    }
}`

**Comment by KanikaDeka** [comment]
> The jsonpaths assume that there at least an entry that matches. If you want to ensure that a concrete entry matches, you can use the `bodyMatchers` section and define that e.g. an entry with index `[0]` has a concrete value of the regular expression. You can read more about it here https://cloud.spring.io/spring-cloud-static/Finchley.SR2/single/spring-cloud.html#contract-matchers

I want to make it generic... instead of using index[0] or index[1], I want to use *, so that it fails when any of the zipcode is wrong at any index. After writing the validation part in bodyMatcher, it is still failing. In bodyMatcher I am writing as below:
`jsonPath("\$.['addressList'][*].['zipCode']", byRegex('[0-9]{5}'))`
