### ISSUE TITLE
spring cloud contract and Zuul proxy in the same project

### ISSUE THREAD

**Issue by kkrawczy** [spring-cloud/spring-cloud-contract#82]
I have a problem to use spring cloud contract in a project where I also use zuul. I describe the problem in here:
http://stackoverflow.com/questions/39642956/configure-spring-cloud-contract-and-zuul-proxy-in-the-same-project
and I was asked to create an issue for that.
Can you see at this point any quick solution that can let me to use spring-cloud-contract ?
thx

**Comment by marcingrzejszczak** [comment]
Hi! I replied to yesterday there - http://stackoverflow.com/questions/39642956/configure-spring-cloud-contract-and-zuul-proxy-in-the-same-project . Either you disable Zuul, or you do a workaround which in fact is a hack that might not work ;)

- switch `stubrunner.cloud.enabled` to disabled
- in a package `org.springframework.cloud.contract.stubrunner.spring.cloud` create `My StubRunnerDiscoveryClientAutoConfig` class that will look more or less like this:

```
@Configuration
public class MyStubRunnerSpringCloudAutoConfiguration {

	@Bean
	@Primary
	public DiscoveryClient myStubRunnerDiscoveryClient(StubFinder stubFinder,
			StubMapperProperties stubMapperProperties,
			@Value("${spring.application.name:unknown}") String springAppName) {
		return new StubRunnerDiscoveryClient(stubFinder, stubMapperProperties, springAppName);
	}

}
```

and add it to your tests as a configuration to import - maybe should help ;) If not then we'll look for something else
