### ISSUE TITLE
> The jsonpaths assume that there at least an entry that matches. If you want to ensure that a concrete entry matches, you can use the `bodyMatchers` section and define that e.g. an entry with index `[0]` has a concrete value of the regular expression. You can read more about it here https://cloud.spring.io/spring-cloud-static/Finchley.SR2/single/spring-cloud.html#contract-matchers

### ISSUE THREAD

**Issue by KanikaDeka** [spring-cloud/spring-cloud-contract#821]
I want to make it generic... instead of using index[0] or index[1], I want to use *, so that it fails when any of the zipcode is wrong at any index. After writing the validation part in bodyMatcher, it is still failing. In bodyMatcher I am writing as below:
`jsonPath("\$.['addressList'][*].['zipCode']", byRegex('[0-9]{5}'))`

_Originally posted by @KanikaDeka in https://github.com/spring-cloud/spring-cloud-contract/issues/817#issuecomment-447773065_

**Comment by marcingrzejszczak** [comment]
Can you please file an issue in the way that it is readable?
