### ISSUE TITLE
Autogenerated test isn't failing if in message body JSON contains array of objects instead of expected single object

### ISSUE THREAD

**Issue by RomanCht** [spring-cloud/spring-cloud-contract#823]
I have a messaging contract:
```groovy
Contract.make {

    description("""Should send a message in kafka topic topic_name""")

    label 'labelName'

    input {
        triggeredBy('triggeredByMethodName()')
    }

    outputMessage {
        sentTo('topic_name')

        body([
                userId: value(consumer(1234567), producer(regex('\\d+'))),
                sessionId: value(consumer(1111111111111), producer(regex('\\d+')))
        ])

        headers {
            contentType(applicationJson())
        }
    }
}
```
And autogenerated test for producer side:
```java
@Test
public void validate_messageSent() throws Exception {
	// when:
		triggeredByMethodName();

	// then:
		ContractVerifierMessage response = contractVerifierMessaging.receive("topic_name");
		assertThat(response).isNotNull();
		assertThat(response.getHeader("Content-Type")).isNotNull();
		assertThat(response.getHeader("Content-Type").toString()).isEqualTo("application/json");
	// and:
		DocumentContext parsedJson = JsonPath.parse(contractVerifierObjectMapper.writeValueAsString(response.getPayload()));
		assertThatJson(parsedJson).field("['userId']").matches("\\d+");
		assertThatJson(parsedJson).field("['sessionId']").matches("\\d+");
}
```
Contract says that message body should contain JSON with single object with 2 fields: userId, sessionId.
But, in case if message will contain JSON with array of objects this test will not fail.
E.g. If, instead of this object
```json
{
    "userId": 1234567,
    "sessionId": 1111111111111
}
```
will be posted the following
```json
[
    {
        "userId": 1234567,
        "sessionId": 1111111111111
    },
    {
        "userId": 12345678,
        "sessionId": 2222222222222
    }
]
```
test will still pass, because generated assertions will search for values of fields 'userId' and 'sessionId' in all objects in array.

I guess, it's natural to expect for this contract to fail validation in such scenario.
It would be nice for framework to autogenerate JSON assertions to validate if it is a single object or an array of objects (instead of just asserting object fields, by searching all objects in array).

**Comment by marcingrzejszczak** [comment]
> It would be nice for framework to autogenerate JSON assertions to validate if it is a single object or an array of objects (instead of just asserting object fields, by searching all objects in array).

Not necessarily. In our opinion the size shouldn't matter cause you want to test things from the semantic perspective.
If you need to assert the size you can read this section of the docs https://cloud.spring.io/spring-cloud-static/Finchley.SR2/single/spring-cloud.html#_limitations

> The support for verifying the size of JSON arrays is experimental. If you want to turn it on, please set the value of the following system property to true: spring.cloud.contract.verifier.assert.size. By default, this feature is set to false. You can also provide the assertJsonSize property in the plugin configuration.

That way you will start generating tests with size verification for arrays. Since that's an experimental feature it might be buggy.

Another option is to provide the size requirements manually via the `bodyMatchers` section.
