### ISSUE TITLE
multipart not working whit testmode JAXRSCLIENT

### ISSUE THREAD

**Issue by utkanozyurek** [spring-cloud/spring-cloud-contract#830]
when testing with JAXRSCLIENT and multipart body is not correctly set in request.

contract:
```
request {
            method 'POST'
            url('/multipart')
            multipart(
                        request: named(
                                name: value(consumer(regex(nonEmpty())), producer('request.json')),
                                content: value(consumer(regex(nonEmpty())), producer(file('multipart/multipartRequest.json').bytes)),
                                contentType: value(consumer(regex(nonEmpty())), producer('application/json'))
                        )
                )
.....
            }
```

created test:
```
Response response = webTarget
					.path("/multipart")
					.request()
					.method("POST");
```

when I change testMode to EXPLICIT it sets the body correctly, for now I will use this workaround. but It would be great if we can use multipart with JAXRSCLIENT

**Comment by OlgaMaciaszek** [comment]
Thanks for reporting it @utkanozyurek . We will work on it.

**Comment by marcingrzejszczak** [comment]
Is this still an issue? I can't seem to replicate this. Do you have a sample that replicates this? Is it also an issue with the latest Spring Cloud Contract version?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by utkanozyurek** [comment]
I tried it with 2.2.1 version of spring-cloud-contract and get the same result. I will try to provide a sample as soon as possible

**Comment by utkanozyurek** [comment]
you can find a sample project in [here](https://github.com/utkanozyurek/SpringCloudContractTest)

**Comment by marcingrzejszczak** [comment]
Actually from what I see it might never worked.  So currently this is not supported. Once more people are interested we can consider implemented it.

**Comment by marcingrzejszczak** [comment]
We'll go with the workaround as the official solution for now. If more people are interested in solving this problem we'll revive it.
