### ISSUE TITLE
Facing issues while using pushStubsToScm with multiple yml contracts

### ISSUE THREAD

**Issue by KanikaDeka** [spring-cloud/spring-cloud-contract#834]
Hi,

I'm trying to push my stubs to Git using pushstubsToScm, I have written contracts in yml.
I'm able to fetch contracts from git and also able to generate stubs but while pushing those stubs back to Git, I'm getting exception saying  
```Execution default of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.0.RC3:pushStubsToScm failed: java.nio.file.DirectoryNotEmptyException: ```

I'm getting this exception only when there are multiple yml contracts in contracts folder.  
When done with multiple groovy contracts it is working fine, even working fine with single yml contract.

please help.

**Comment by marcingrzejszczak** [comment]
Can you show the full stacktrace?

**Comment by KanikaDeka** [comment]
> Can you show the full stacktrace?

PFA for stacktrace

[log.txt](https://github.com/spring-cloud/spring-cloud-contract/files/2723445/log.txt)

**Comment by KanikaDeka** [comment]
> > Can you show the full stacktrace?
> 
> PFA for stacktrace
> 
> [log.txt](https://github.com/spring-cloud/spring-cloud-contract/files/2723445/log.txt)

PFA log.txt file 
[log.txt](https://github.com/spring-cloud/spring-cloud-contract/files/2726068/log.txt)
with Error stacktraces are turned on.

**Comment by KanikaDeka** [comment]
> > Can you show the full stacktrace?

PFA log.txt file
[log.txt](https://github.com/spring-cloud/spring-cloud-contract/files/2726076/log.txt)
with Error stacktraces are turned on.
