### ISSUE TITLE
Servlet API in wiremock causes Boot to activate web app in stub runner app

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-contract#837]
This change made `spring-boot-starter-web` optional: https://github.com/spring-cloud/spring-cloud-contract/blame/34f7cd31edae750a9dcd3a7b5493cd19129c3383/spring-cloud-contract-starters/spring-cloud-starter-contract-stub-runner/pom.xml. It makes sense because the user app might be webflux (or even not a web app).

The problem is that the presence of the Servlet API triggers Spring Boot to think it needs an embedded webserver, and one might not be available now.

We could perhaps solve the problem by adding an `EnvironmentPostProcessor`. If wiremock is there and spring-webmvc is not, set `spring.main.web-application-type=<something>`. I guess `<something>` has to depend on whether or not webflux/netty is present.

**Comment by marcingrzejszczak** [comment]
That's actually no longer the case. Web does not leak out from stub runner modules
