### ISSUE TITLE
Step-aware stubs generated with RestDocs 

### ISSUE THREAD

**Issue by florind** [spring-cloud/spring-cloud-contract#84]
I have a test configuration that always records the mockMvc interactions via the {steps} placeholder as documented here http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documentating-your-api-parameterized-output-directories
I am using 

```
@AutoConfigureRestDocs(value = "build/generated-snippets")
@AutoConfigureMockMvc
@SpringBootTest
public class MyTest {
    @TestConfiguration
    static class TestConfig {
        @Bean
        public RestDocumentationResultHandler restDocumentation() {
            return MockMvcRestDocumentation.document("{method-name}/{step}/",
                    preprocessRequest(prettyPrint()),
                    preprocessResponse(prettyPrint()));
        }
    }
...
//tests follow
}
```

which does indeed record WireMock stubs but they are named {step}.json. For multistep tests, the file will overwrite previous steps.
Looks like WireMockSnippet.document has to change to replace {step} (if operation.name includes it) with the current step (it's available in Operation).

**Comment by marcingrzejszczak** [comment]
Hi! Can you post a sample project on Github with this setup?

**Comment by florind** [comment]
You just have to enable the step-aware spring rest doc generation as per documentation and check how the json files are generated.

**Comment by marcingrzejszczak** [comment]
Ok but I would need to set everything up - if you already have it it will be much easier for me to test your stuff.

**Comment by fbdo** [comment]
Hi! I was strugling with the same issue, and I also don't have a project or a test to showcase it, but what I did as a workaround after checking the code was:

I copied-and-pasted the class org.springframework.cloud.contract.wiremock.restdocs.WireMockSnippet to my project.

I did the following changes:

`    private final PropertyPlaceholderHelper propertyPlaceholderHelper = new PropertyPlaceholderHelper(
            "{", "}");

    @Override
    public void document(Operation operation) throws IOException {
        extractMatchers(operation);
        if (this.stubMapping == null) {
            this.stubMapping = request(operation).willReturn(response(operation)).build();
        }
        String json = Json.write(this.stubMapping);
        RestDocumentationContext context = (RestDocumentationContext) operation
                .getAttributes().get(RestDocumentationContext.class.getName());
        String fileName = this.propertyPlaceholderHelper.replacePlaceholders(operation.getName(),
                new RestDocumentationContextPlaceholderResolverFactory().create(context));
        File output = new File(context.getOutputDirectory(),
                this.snippetName + "/" + fileName + "stub.json");
        output.getParentFile().mkdirs();
        try (Writer writer = new OutputStreamWriter(new FileOutputStream(output))) {
            writer.append(json);
        }
    }`

This fixed the problem locally. I hope this helps who is fighting with the same problem or to fix the issue, later on I may trigger a PR.

**Comment by marcingrzejszczak** [comment]
@florind @fbdo can you provide a sample that I can check out?  It would really help me speed things up

**Comment by marcingrzejszczak** [comment]
ping!

**Comment by fbdo** [comment]
Sorry, I am on vacations with my family, when I am back I can provide one

**Comment by marcingrzejszczak** [comment]
@fbdo no problem :) Enjoy your holidays! :D
