### ISSUE TITLE
spring-cloud-contract-wiremock wrong dynamicPort assigned to wiremock.server.port

### ISSUE THREAD

**Issue by D0rmouse** [spring-cloud/spring-cloud-contract#846]
Hi, I'm using spring-cloud-contract-wiremock to make use of the functionality where the dynamically generated server port is assigned to a property to be used in endpoint definitions.

It seems that there's a bug in the implementation where a different port number is assigned to the `wiremock.server.port` property. 

Here's a [demo project](https://github.com/D0rmouse/spring-cloud-contract-wiremock-bug-demo) which illustrates the bug. `SpringCloudContractWiremockBugDemoApplicationTests` fails where it should succeed, as per [the documentation](https://cloud.spring.io/spring-cloud-contract/multi/multi__spring_cloud_contract_wiremock.html) section 11.3. It speaks of a different property, `wiremock.port`, but I'm guessing this is due to a typo/outdated docs.

**Comment by marcingrzejszczak** [comment]
Yeah, sorry about the property. Can you try with the latest snapshots?

**Comment by marcingrzejszczak** [comment]
Ok, I saw the code. 

First thing is that you're using Finchley with Boot 2.1, that will not work.

Also, there's no interop between the class rule and WireMock rule. You don't have to use the rule at all to  achieve this

```
@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureWireMock(port = 0)
public class SpringCloudContractWiremockBugDemoApplicationTests {

    @Value("${wiremock.server.port}")
    private Integer wireMockServerPort;

    @Test
    public void contextLoads() {
        assertThat(wireMockServerPort).isNotEqualTo(0);
    }

}
```

**Comment by D0rmouse** [comment]
> First thing is that you're using Finchley with Boot 2.1, that will not work.
I know, it should be Greenwich, but it isn't released yet, right? Seems to be ok for this demo project.

> Also, there's no interop between the class rule and WireMock rule.
The example (11.3) suggests there is interop and if there isn't it can never work like documented.

**Comment by marcingrzejszczak** [comment]
There is an interop via the options. But we never mention that we will inject the ports as application properties.

**Comment by D0rmouse** [comment]
```
// Start WireMock on some dynamic port
// for some reason `dynamicPort()` is not working properly
@ClassRule
public static WireMockClassRule wiremock = new WireMockClassRule(
			WireMockSpring.options().dynamicPort());

// A service that calls out over HTTP to localhost:${wiremock.port}
@Autowired
private Service service;
```

The comment on the `@Autowired` attribute suggests `wiremock.port` suggest it contains the dynamic port. Or at lease it's easily interpreted as such. How else would we interpret it?

**Comment by marcingrzejszczak** [comment]
That comment. I haven't noticed that. I'll fix it

**Comment by marcingrzejszczak** [comment]
With this commit https://github.com/spring-cloud/spring-cloud-contract/commit/66f7e9329ead5abe9c84a3dbdb5603281fd009b6 it should be more clear

**Comment by D0rmouse** [comment]
Oh I thought you were changing the code to reflect the documentation :( 

Ah well, I'll look for another solution then...

**Comment by D0rmouse** [comment]
Seems that the intended way it should function is to assign the dynamic port to the property. How else are we going to instruct our Service to connect to the WireMock server? By reflection?

`@AutoConfigureWireMock(port = 0)` does seem to start a WireMock server and assign the port to the property. Wouldn't the rule serve as an alternative if we can't use the annotation?

**Comment by marcingrzejszczak** [comment]
We support the annotation way. Why don't you want to use it?

**Comment by D0rmouse** [comment]
It gives an NPE on in the `WireMockConfiguration` for some reason. Besides that, there could be other reasons for wanting to have access to the rule. 

Also the `[WireMockConfiguration](https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfiguration.java)` JavaDoc suggests using `WireMockSpring` as an alternative, so from my perspective they should be functionally equal.

**Comment by marcingrzejszczak** [comment]
Again, it's an alternative to WireMock options. We extend the options with some additional features. For now, we're not planning to making it work in any other way than via an annotation.

**Comment by D0rmouse** [comment]
Then I would remove the documentation suggesting use of a dynamic port in combination with a `WireMockClassRule, because it's useless like this.

**Comment by marcingrzejszczak** [comment]
I disagree because you can do exactly what I did in the documentation. You can, via the the class rule, retrieve the port at which the WireMock server is running.

**Comment by marcingrzejszczak** [comment]
Please read the contents of the commit

```java
@ActiveProfiles("classrule")
// tag::wiremock_test1[]
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
public class WiremockForDocsClassRuleTests {

	// Start WireMock on some dynamic port
	// for some reason `dynamicPort()` is not working properly
	@ClassRule
	public static WireMockClassRule wiremock = new WireMockClassRule(
			WireMockSpring.options().dynamicPort());

	// end::wiremock_test1[]
	// tag::wiremock_test2[]
	@Before
	public void setup() {
		this.service.setBase("http://localhost:" + wiremock.port());
	}

	// A service that calls out over HTTP to wiremock's port
	@Autowired
	private Service service;

	// Using the WireMock APIs in the normal way:
	@Test
	public void contextLoads() throws Exception {
		// Stubbing WireMock
		wiremock.stubFor(get(urlEqualTo("/resource")).willReturn(aResponse()
				.withHeader("Content-Type", "text/plain").withBody("Hello World!")));
		// We're asserting if WireMock responded properly
		assertThat(this.service.go()).isEqualTo("Hello World!");
	}

}
```

**Comment by D0rmouse** [comment]
`this.service.setBase("http://localhost:" + wiremock.port());`

So I need to add some method like this to my production code or use reflection like I said.
Would be nicer if you could use the `wiremock.server.port` property 🥇
 
The annotation does provide this and IMHO the rule functionality should be similar, but I'll let it go.
