### ISSUE TITLE
Support for Path parameters

### ISSUE THREAD

**Issue by araghuraman1** [spring-cloud/spring-cloud-contract#852]
In a custom ContractConverter (OpenApiContractConverter), there is no support for url path parameters, namely e.g., /a/{b}/c. I would like a new DSL constructor similar to org.springframework.cloud.contract.spec.internal.QueryParameters so that I can invoke it in the custom ContractConverter. Using the queryParameters construct within a request messes up the RequestSpecification which thinks the parameters is a query variable in the URL.

**Comment by OlgaMaciaszek** [comment]
Hello @araghuraman1 you could probably use regex in path. Would that be helpful? If not, please describe more in details the scenario you would like to test and how what path params be helpful for you in contract tests.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
