### ISSUE TITLE
Dynamic properties in `queryParameters` section are not parsed

### ISSUE THREAD

**Issue by tsayen** [spring-cloud/spring-cloud-contract#854]
It looks like dynamic properties don't work for `request.urlPath.queryParameters` when defining contract in Groovy

Relevant part of the contract looks like that:

```
           request {
                method 'GET'
                urlPath('/advise') {
                    queryParameters {
                        parameter('referenceDate': $(
                                consumer(regex(iso8601WithOffset())),
                                producer(execute("todayAtNoon()"))
                        ))
                    }
                }
            }
```
And `todayAtNoon()` is a method in the base test class.
This results in generated of test code:
```
           // when:
			Response response = given().spec(request)
					.queryParam("referenceDate","todayAtNoon()")
```
This of course causes 400 Bad Request, as we're literally sending `"todayAtNoon()"` string to the producer.

The version is `2.0.2.RELEASE`

**Comment by OlgaMaciaszek** [comment]
Hello @tsayen . Thanks for reporting it. It's a good idea. Marking as enhancement and adding to backlog.

**Comment by tsayen** [comment]
Hi @OlgaMaciaszek, I don't really see this issue as an enhancement, it's rather a bug. 

The documentation clearly states you can do something like that: https://cloud.spring.io/spring-cloud-static/spring-cloud-contract/1.1.2.RELEASE/#_executing_custom_methods_on_server_side

But it doesn't work

**Comment by tsayen** [comment]
There is also issue #709, which is about dynamic properties, but in request headers. In that case `execute()` works correctly, it just doesn't work for `queryParameters`

**Comment by PsHype** [comment]
I also have this issue , I think it is bug

**Comment by markgargan** [comment]
Spent half a day looking at this before realising that it's distinct to the queryParameter and not my syntax of the 
producer(execute("myBaseClassTestMethod()"))

It's been a year any update on it?

**Comment by marcingrzejszczak** [comment]
As you can see nothing has changed. We're open to accepting PRs though.

**Comment by markgargan** [comment]
If you can give me a few pointers I'd take a look?

**Comment by marcingrzejszczak** [comment]
You'd need to create a test similar to this one https://github.com/spring-cloud/spring-cloud-contract/blob/2.2.x/spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MethodBodyBuilderSpec.groovy#L1817-L1858 and then check classes such as https://github.com/spring-cloud/spring-cloud-contract/blob/2.2.x/spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcQueryParamsWhen.java that are responsible for generating new query parameters.
