### ISSUE TITLE
Could you enable repeated reads of response body in WireMockRestServiceServer

### ISSUE THREAD

**Issue by yaki123** [spring-cloud/spring-cloud-contract#860]
HI spring Cloud Contract team,

I’m currently using WireMockRestServiceServer to wire mock some external restful services. I notice that the bufferContent feature is not provided in WireMockRestServiceServer from Spring Cloud Contract 2.1.0 RC3. (but it’s already supported in Spring Framework 5.x.)

I was wondering if you could add this feature in your next release?

Adding something like below in WireMockRestServiceServer.java might work:

                public WireMockRestServiceServer bufferContent() {
                                this.bufferContent = true;
                                return this;
                }

                public MockRestServiceServer build() {
                                if (this.bufferContent) {
                                                this.builder.bufferContent();
                                }
                                ...

**Comment by OlgaMaciaszek** [comment]
Hello @yaki123 This makes sense. Would you like to submit a PR?

**Comment by yaki123** [comment]
Yes I'd like to, but I got an error when build spring-cloud-contract-wiremock master branch locally below. It looks like something is not correct in my company's nexus. I will check with our nexus team.
M-C02V514EHTDF:spring-cloud-contract-wiremock x7yv$ mvn clean package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.httpcomponents:httpclient:jar -> duplicate declaration of version (?) @ line 35, column 15
[FATAL] Non-resolvable parent POM for org.springframework.cloud:spring-cloud-contract-parent:2.1.0.BUILD-SNAPSHOT: Failure to find org.springframework.cloud:spring-cloud-build:pom:2.1.2.BUILD-SNAPSHOT in https://mvnrepo.nordstrom.net/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ org.springframework.cloud:spring-cloud-contract-parent:2.1.0.BUILD-SNAPSHOT, /Users/x7yv/GitHub/spring-cloud-contract2/spring-cloud-contract/pom.xml, line 7, column 10

**Comment by OlgaMaciaszek** [comment]
Hello @yaki123 have you managed to resolve the issue?
