### ISSUE TITLE
Allow Consumer to define usage pattern as part of the Contract

### ISSUE THREAD

**Issue by kishorekkota** [spring-cloud/spring-cloud-contract#861]
Enhancement

Our APIs consumption is using Cloud Contracts to define how consumers are using the API and expected response payload..etc. One of the requirement for APIs is to run performance test, to ensure new changes are not causing any response time issue..etc. We are looking to see how we can leverage Cloud Contracts to define usage patter from various different consumers, so it is easy to automate performance testing leveraging consumption patter defined.

Also, defining the usage pattern..like avg transactions per second and/or any peak volume needs as part of the contract allows Produces to be informed and documented on the usage using Cloud contracts.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
