### ISSUE TITLE
Errors when testing for failure with default spring exception handler

### ISSUE THREAD

**Issue by SwEngin** [spring-cloud/spring-cloud-contract#863]
https://github.com/spring-cloud/spring-cloud-contract/issues/751#issue-370651057

The Problem still exists and the project is right now available again

https://github.com/SwEngin/spring-contract-problem

**Comment by marcingrzejszczak** [comment]
The problem doesn't exist cause I've managed to execute this locally and it worked. Please apply the changes I've suggested (you don't have them in your project)

**Comment by SwEngin** [comment]
@marcingrzejszczak please check my response as well as this is spring boot which I don't need Error class or a custom handler to get the correct response `@ResponseStatus(HttpStatus.NOT_ACCEPTABLE)` is completely sufficient
