### ISSUE TITLE
XML slurping prints annoying Error message when Body or Response contains Groovy String with custom variable

### ISSUE THREAD

**Issue by konstantinshevchuk** [spring-cloud/spring-cloud-contract#867]
Enhancement

When you try to put variables in Groovy string e.g. 

`
body(
    value: "something($myVariable)" 
)`

The following errors overflow the console

`[Fatal Error] :1:1: Content is not allowed in prolog.`

This doesn't happen with built-in values like `$(anyNonBlankString())`. 

But this happens for anyIso8601WithOffset() and other date time matchers.

If you take a look inside anyIso8601WithOffset()

`T anyIso8601WithOffset() {
		int d = this.random.nextInt(8) + 1
		return createAndValidateProperty(RegexPatterns.ISO8601_WITH_OFFSET, "201$d-0$d-1${d}T12:23:34.123Z")
}`

Whenever custom variable is used inside Groovy string this error appears.

**Comment by ryanjbaxter** [comment]
Is this related to #868?

**Comment by konstantinshevchuk** [comment]
Yes. This is related to  #868

**Comment by marcingrzejszczak** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-contract/pull/868
