### ISSUE TITLE
+ does not resolve correctly for release builds of stubs

### ISSUE THREAD

**Issue by klubi** [spring-cloud/spring-cloud-contract#876]
Bug report

From my observations using `+` to resolve latest version always resolves latest non-release version.
If latest version in repo is release version, then it won't be picked, instead latest non-release version will be used.

I'm using spring-cloud-starter-contract-stub-runner:2.1.0.RELEASE

My stub runner config:
```yaml
stubrunner:
  stubsMode: LOCAL
  ids:
    - com.xxx:contracts:+:stubs
  min-port: 11000
  max-port: 11000
```
![image](https://user-images.githubusercontent.com/4123293/52373353-c27e6f80-2a5a-11e9-81cf-b98f5e249621.png)

Maven-metadata-local.xml looks like this
```xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>com.xxx</groupId>
  <artifactId>contracts</artifactId>
  <versioning>
    <release>RELEASE.2</release>
    <versions>
      <version>SMB-4048.SNAPSHOT</version>
      <version>SMB-4048.11</version>
      <version>SMB-4048.12</version>
      <version>SMB-4048.13</version>
      <version>SMB-4048.666</version>
      <version>RELEASE.2</version>
    </versions>
    <lastUpdated>20190206202148</lastUpdated>
  </versioning>
</metadata>
```

Logs:
```
Remote repos not passed but the switch to work offline was set. Stubs will be used from your local Maven repository.
Desired version is [+] - will try to resolve the latest version
Resolved version is [SMB-4048.666]
```

With above config I'd expect it to resolve `RELEASE.2` version. Yet it resolves `SMB-4048.666`.

Questions:
- is there a way to resolve stub versions using wildcards (ex `RELEASE.*`)
- is there a way to resolve latest release version of stubs?

**Comment by marcingrzejszczak** [comment]
> is there a way to resolve stub versions using wildcards (ex `RELEASE.*`)

No, but Spring Cloud Contract uses Aether and Aether uses the IVY notation. Try passing `latest.release` according to http://ant.apache.org/ivy/history/latest-milestone/settings/version-matchers.html

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
