### ISSUE TITLE
StubRunner uses local metadata info for determining the version for the stubs to download from remote

### ISSUE THREAD

**Issue by bottenkamp** [spring-cloud/spring-cloud-contract#878]
Question

I have the situation that in my CI environment the provider and consumers might end up being run on the same agent/slave and therefore share the maven repository. Combined with the fact that deriving the version for the stubs to be downloaded when the '+'  is used in the Stubrunner and the stubs should be downloaded from remote, this potentially results in the Stubrunner trying to download the stubs with a wrong version. 

Bug report

The StubRunnes is configured like this:
`@AutoConfigureStubRunner(
        ids = "....it4it.pcf.starter.discovery:backend-microservice-service:+:prod-stubs:8180",
        mappingsOutputFolder = "target/outputmappings",
        stubsMode = StubRunnerProperties.StubsMode.REMOTE,
        repositoryRoot = "https://..../nexus/content/repositories/release/",
        snapshotCheckSkip = true)`

1. the '+' says get the latest version of the provider stubs
2. The stubMode says the stubs should be downloaded from remote repository
3. The repositoryRoot is pointing at my remote release repository

my local maven repository looks like:
      feb  8 15:26 10.1.1
      feb  8 15:28 10.1.2-SNAPSHOT
      feb  8 15:27 maven-metadata-local.xml
      feb  8 15:28 maven-metadata-remote0.xml
      feb  8 15:28 maven-metadata-remote0.xml.sha1
      feb  8 15:28 resolver-status.properties

What I experience:
1. the latest version is picked up from the local repository, using maven-metadata-**local**.xml
2. the latest version is thus 10.1.2-SNAPSHOT
3. the StubRunner tries to download version 10.1.2-SNAPSHOT from remote release repository and fails:

`Exception occurred while trying to download a stub for group [...it4it.pcf.starter.discovery] module [backend-microservice-service] and classifier [prod-stubs] in [remote0 (https://...../nexus/content/repositories/release/, default, releases+snapshots)]
`

Funny thing is that the StubRunner mentions the remote0 repository in the exception it throws. It is clear that it knows it should download from remote0, so why not find the version in maven-metadata-remote0.xml?

Enhancement
The latest version should be derived from maven-metadata-remote0.xml instead of maven-metadata-local.xml

**Comment by bottenkamp** [comment]
Debugged a bit myself. Comes down to method:
`private Map<String, ArtifactRepository> getVersions(RepositorySystemSession session, VersionRangeResult result, VersionRangeRequest request)`
in:
`DefaultVersionRangeResolver`
There is a line in there:
`Metadata metadata = new DefaultMetadata(request.getArtifact().getGroupId(), request.getArtifact().getArtifactId(), "maven-metadata.xml", Nature.RELEASE_OR_SNAPSHOT);`
and it returns a map with all version with there repos, local and remote.
For me this gives me all the remotes and my one local:
"7.0.1" -> "remote0 (https://maven.rabobank.nl/nexus/content/repositories/ip-release/, default, releases+snapshots)"
"5.0.19" -> "remote0 (https://maven.rabobank.nl/nexus/content/repositories/ip-release/, default, releases+snapshots)"
"6.0.4" -> "remote0 (https://maven.rabobank.nl/nexus/content/repositories/ip-release/, default, releases+snapshots)"
**"10.1.2-SNAPSHOT" -> "/home/longrun/.m2/repository (enhanced)"**
"5.0.17" -> "remote0 (https://maven.rabobank.nl/nexus/content/repositories/ip-release/, default, releases+snapshots)"
..
..
So, would changing (making dynamic via a property and not hard coded) the line to:
`Metadata metadata = new DefaultMetadata(request.getArtifact().getGroupId(), request.getArtifact().getArtifactId(), "maven-metadata.xml", Nature.RELEASE);`
help?

**Comment by marcingrzejszczak** [comment]
Which version of Contract are you using?

**Comment by bottenkamp** [comment]
Hello Marcin,
the version is 2.0.1.RELEASE

**Comment by marcingrzejszczak** [comment]
AFAIR we've fixed those kind of issues in 2.1.0.RELEASE via https://github.com/spring-cloud/spring-cloud-contract/issues/643 . Can you double check that it resolves your issues?

**Comment by bottenkamp** [comment]
Thanks. Yes, that seems to fix it. 
Upgraded to Greenwich.RELEASE and spring boot 2.1.1.RELEASE.
Took some effort to get the projects to compile again after the upgrade, but now I upgraded and the contract testing is working. Thanks!
