### ISSUE TITLE
autogenerated test failed in case when there are empty and not empty arrays with the same names

### ISSUE THREAD

**Issue by dev-priporov** [spring-cloud/spring-cloud-contract#880]
If autogenerated test gets an expected body with 2 arrays with the same names, but one of them is an empty, the test will failed. 
Seems that the trouble is in jsonassert actually, but I think SCC should avoid that problem.
The screen shows the line where the test fails. 
![image](https://user-images.githubusercontent.com/9480157/52538539-05a35000-2d85-11e9-8c66-e941f85d4ae2.png)
```
  springBootVersion = '2.1.2.RELEASE'
  springCloudContractVersion = '2.0.1.RELEASE'
  springCloudVersion = 'Greenwich.RELEASE' 
```
Also I made a simple git project which helps to reproduce the issue: https://github.com/dev-priporov/scc-empty-array-issue

**Comment by OlgaMaciaszek** [comment]
Hi, @dev-priporov thanks for reporting it. This is, indeed, a bug. At the same time, this use-case seems to be a rather rare corner-case. So we are going to fix it, but not as a priority. In the meantime, we suggest providing BodyMatchers as a workaround (and in the jsonPath, specifying the array element indexes for each match).

**Comment by marcingrzejszczak** [comment]
Is this problem still open? I think we've fixed a similar issue in the meantime. @dev-priporov can you check out the latest snapshots please?

**Comment by dev-priporov** [comment]
@marcingrzejszczak I will check late, sorry now really have no time for that

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by epm-dev-priporov** [comment]
@marcingrzejszczak Hi, sorry for making that so late. I've updated the version and tried check the issue, but seems that now generated contract test is invalid.

![image](https://user-images.githubusercontent.com/30048339/58184318-8b566600-7cb9-11e9-98db-3e45d348c60e.png)

to reproduce that you can use [https://github.com/dev-priporov/scc-empty-array-issue](url) project

**Comment by OlgaMaciaszek** [comment]
Hi @epm-dev-priporov Thanks; looks like a bug. We will work on a fix.
