### ISSUE TITLE
Spring cloud Contract - 1.2.6

### ISSUE THREAD

**Issue by nagendramithra** [spring-cloud/spring-cloud-contract#885]
Hi,

I am using verifier version 1.2.6 to create the stub and consumer tests. I am facing some problems with dynamic properties.

Producer Side

Contract

Contract.make {
	 description "getAvailablePostals - Contract : 0"
	 request { 
		 method 'POST'
		 url '/xyz/v5/getAvailablePostals'
		 headers { header ('Content-Type', 'application/json;charset=UTF-8') }
		 body (""" {
				  "shipDateAndTime" : "2019-02-13T03:33:43.437-0600"
				  }
				} """)
		stubMatchers {
		 	jsonPath('$.shipDateTime', byTimestamp())
		 }
	 }
	 response {
		 status 200
		 headers { contentType applicationJson() }
		 body (""" {
				   """)
	 }
} 

In the request i have used stubMatcher to match the pattern for the property "shipDateAndTime".

Below are the snip of code from stub

{
  "id" : "5a266ad5-6a9e-47aa-935e-cf9660d34516",
  "request" : {
    "url" : "/xyz/v5/getAvailablePostals",
    "method" : "POST",
    "headers" : {
      "Content-Type" : {
        "equalTo" : "application/json;charset=UTF-8"
      }
    },
    "bodyPatterns" : [  {
      "matchesJsonPath" : "$[?(@.shipDateTime =~ /(([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9]))/)]"
    } ]
  },
  "response" : {
    "status" : 200,
    "body" : "...",
    "headers" : {
      "Content-Type" : "application/json"
    },
    "transformers" : [ "response-template" ]
  },
  "uuid" : "5a266ad5-6a9e-47aa-935e-cf9660d34516"
}

When i try to get the response from stub the stub is failing to validate the shipDateAndTime with the regex. Below is the response i am getting.

Request was not matched

Closest stub
POST
/xyz/v5/getCountryProfile
Content-Type: application/json;charset=UTF-8 
$[?(@.shipDateTime =~

Request
POST
/xyz/v5/getCountryProfile
Content-Type: application/json;charset=UTF-8 
{"shipDateAndTime":"2019-02-13T03:33:43.437-0600"}

From the above response it seems it is not matching the date value in the request with the regex in the stub.

Please suggest on this.

**Comment by OlgaMaciaszek** [comment]
Hello @nagendramithra . Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).
Also, we no longer support the 1.2.x branch. Please try upgrading to 2.0.x or 2.1.x and let us know if the issue is still there.

**Comment by nagendramithra** [comment]
> Hello @nagendramithra . Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).
> Also, we no longer support the 1.2.x branch. Please try upgrading to 2.0.x or 2.1.x and let us know if the issue is still there.

Ok. Thank you.
