### ISSUE TITLE
support required field in contract

### ISSUE THREAD

**Issue by AlicanAkkus** [spring-cloud/spring-cloud-contract#898]
hi,

we use cloud contract with pleasure. sometimes we need to declare which request fields are required or not. is it possible to support this? we can solve by writing comments but this is not feasible for a long time.

**Comment by marcingrzejszczak** [comment]
If a field is inside the contract - it's required. It's as simple as that.

**Comment by marcingrzejszczak** [comment]
And I'm really happy that you're enjoying the project :)
