### ISSUE TITLE
LocalDate instance as a stub value is okay for v1.2.3.RELEASE but for every consequent versions leads to java.lang.StackOverflowError

### ISSUE THREAD

**Issue by mikhail-putilov** [spring-cloud/spring-cloud-contract#900]
Question, possible bug

I've been using `v1.2.3.RELEASE` for a long time and wrote a lot of contracts in the following manner:
```groovy
import java.time.LocalDate

def fixedDate = LocalDate.of(2011, 1, 1)
org.springframework.cloud.contract.spec.Contract groovyDsl = org.springframework.cloud.contract.spec.Contract.make {
    request {
        method('GET')
        url('/dummy')
        headers {
            header("Content-Type": 'application/json')
        }
    }
    response {
        status 204
        body(
                dateField: $(consumer(fixedDate), producer(regex(isoDate())))
        )
    }
}
```
After I tried to update the version of spring-cloud-contract to `v.2.1.0.RELEASE`, my contracts have become no longer valid:
```
java.lang.StackOverflowError
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1043)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
...
```

I haven't found any mentioning about that in the documentation.
Further investigation led me to the conclusion that this strange behavior took place starting from `v.1.2.4.RELEASE`. 

For your convinience, I've written a test to reproduce this behavior (put it in a `WireMockGroovyDslSpec` to run it):
```groovy
def 'should convert groovy dsl stub with LocalDate or at least give a meaningful error/warning'() {
    given:
    def fixedDate = LocalDate.of(2011, 1, 1)
    org.springframework.cloud.contract.spec.Contract groovyDsl = org.springframework.cloud.contract.spec.Contract.make {
        request {
            method('GET')
            url('/dummy')
            headers {
                header("Content-Type": 'application/json')
            }
        }
        response {
            status 204
            body(
                    dateField: $(consumer(fixedDate), producer(regex(isoDate())))
            )
        }
    }
    when:
    String wireMockStub = new WireMockStubStrategy("Test", new ContractMetadata(null, false, 0, null, groovyDsl), groovyDsl).toWireMockClientStub()
    then:
    AssertionUtil.assertThatJsonsAreEqual('''
{
	"request": {
		"method": "GET",
		"headers": {
			"Content-Type": {
				"equalTo": "application/json"
			}
		},
		"url": "/dummy"
	},
	"response": {
		"status": 204,
		"body": "{\\"dateField\\":\\"2011-01-01\\"}",
		"transformers" : [ "response-template", "foo-transformer" ]
	}
}
''', wireMockStub)
    and:
    stubMappingIsValidWireMockStub(wireMockStub)
}
```

The stack trace doesn't give a clear explanation of mistake nor what was wrong. Documentation lacks this kind of details. Either it is a bug or expected behavior, some clarity is needed. Either in a stack trace or in the documentation. Better both, in my opinion.

**Comment by mikhail-putilov** [comment]
Looks like a revision `82fb1cdac3324633883e0b7118dcf30b0378ee67` breaks the behavior of `org.springframework.cloud.contract.verifier.dsl.wiremock.BaseWireMockStubStrategy#toJson`

I'm gonna investigate into this a little more later

**Comment by mikhail-putilov** [comment]
Looks like it is a bug of groovy: https://issues.apache.org/jira/browse/GROOVY-7682

**Comment by marcingrzejszczak** [comment]
Thanks @mikhail-putilov a lot for your analysis. That's why we always encourage to upgrade to the latest version possible. I guess you could try to add your own version of groovy to override the one that we provide. You could pass the `groovy.version` property to override the groovy version (https://github.com/spring-projects/spring-boot/blob/v1.5.19.RELEASE/spring-boot-dependencies/pom.xml#L81)

BTW have you checked if the problem is still there with 1.2.6.RELEASE?

**Comment by mikhail-putilov** [comment]
@marcingrzejszczak  have you noticed that I checked v.2.1.0.RELEASE as well and it was also led to stackoverflow problem?

**Comment by marcingrzejszczak** [comment]
> @marcingrzejszczak have you noticed that I checked v.2.1.0.RELEASE as well and it also led to stackoverflow problem?

Nope, I haven't noticed that. We'll take another look into that. Thanks for keeping an eye on this

**Comment by marcingrzejszczak** [comment]
Our suggestion is not to pass `LocalDate` as an object. Please parse it as `String` and pass it in that form to the DSL body.
