### ISSUE TITLE
Git storage doesn't work if the repo/branch is empty

### ISSUE THREAD

**Issue by jkubrynski** [spring-cloud/spring-cloud-contract#907]
The `pushStubsToScm` goal fails it the master (empty, just created repo) or configured branch are empty.

`Execution default of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.0.RELEASE:pushStubsToScm failed: org.eclipse.jgit.api.errors.RefNotFoundException: Ref test cannot be resolved`

**Comment by marcingrzejszczak** [comment]
Can you provide the full stacktrace please?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
