### ISSUE TITLE
HttpsPortDynamic is automatically set to false

### ISSUE THREAD

**Issue by fdw** [spring-cloud/spring-cloud-contract#910]
I have test configured with `@AutoConfigureWireMock(port = 0)`. However, the context is still marked as dirty as per #883 , because `httpsPortDynamic` has been set to `false`. I tried debugging where this value comes from, but I can only find the information `[...] origin = "wiremock.server.https-port-dynamic" from property source "wiremock"]`. No other (signifcant) property file is used, nor are environment variables set.

The spring-cloud-contract-wiremock version is 2.1.1.RELEASE.

**Comment by boothen** [comment]
I've added a comment to #883. If the context is refreshed as part of the test framework then the HttpsPortDynamic property can be reset to false. I've submitted a PR to resolved this scenario.

**Comment by OlgaMaciaszek** [comment]
New PR for fix: https://github.com/spring-cloud/spring-cloud-contract/pull/1028

**Comment by OlgaMaciaszek** [comment]
@boothen is working on the fix.

**Comment by OlgaMaciaszek** [comment]
New PR with fix: #1040

**Comment by OlgaMaciaszek** [comment]
Should be fixed by #1048
