### ISSUE TITLE
Docker image support for authenticated contracts download

### ISSUE THREAD

**Issue by Dominick1993** [spring-cloud/spring-cloud-contract#913]
We have a scenario where we are using provided spring-cloud-contract docker image for provider verification with contracts published in remote Nexus repository. Our Nexus repositories require authentication even while downloading the artifacts, which we are unable to do currently.

#912 Solves this issue

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/pull/912
