### ISSUE TITLE
Problem with generating wiremock json out of a contract for repeated parameter

### ISSUE THREAD

**Issue by kkrawczy** [spring-cloud/spring-cloud-contract#93]
It seems that there is a problem with generating WireMock's json for repeated parameter.

For a contract with request:
```groovy
request {
    method 'GET'
    urlPath('/user') {
        queryParameters {
            parameter 'ids': '1'
            parameter 'ids': '2'
        }
    }
}
```
the following WireMock's json is generated
```json
"request" : {
    "urlPath" : "/user",
    "method" : "GET",
    "queryParameters" : {
      "ids" : {
        "equalTo" : "2"
      }
    }
}
```
As we can see there is only one parameter ('2') in the WireMock's json.

I want to handle a list of values by repeating parameter, because this is the way feign does it. And I use feign on the consumer side.

**Comment by marcingrzejszczak** [comment]
Thanks for the feedback. Once I'm back from holidays I'll try to fix it :)

**Comment by kkrawczy** [comment]
thx and enjoy your holidays :)

**Comment by marcingrzejszczak** [comment]
@kkrawczy did you manage to achieve this properly with WireMock? Can you show me how it should look like in WireMock? I ask cause it seems that the code from my side is written properly and WireMock's implementation I think is overriding the value

**Comment by kkrawczy** [comment]
Hello,
yes, it seems that it's WireMock that cannot handle this situation. So I guess you can close this issue.
Thx for info.

**Comment by marcingrzejszczak** [comment]
Thanks!
