### ISSUE TITLE
Problem with auto-generated values from regex inside the respose body

### ISSUE THREAD

**Issue by kkrawczy** [spring-cloud/spring-cloud-contract#94]
Based on this documentation:
"You can also provide only one side of the communication using a regular expression. If you do that then automatically we’ll provide the generated string that matches the provided regular expression."
I assumed that for this contract:

``` groovy
response {
    status 200
    body(
        digit: $(producer(regex('[0-9]{1}'))),
        id: $(producer(regex(number()))),
        email: $(producer(regex(email())))
    )
}
```

I will get accordingly digit, number and email in WireMock's json. Instead I have somewhat strange values:

``` json
"response" : {
    "status" : 200,
    "body" : "{\"digit\":{\"cursor\":8},\"id\":{\"cursor\":13},\"email\":{\"cursor\":47}}"
}
```

PS
I don't expect a quick answer, as I learnt that @marcingrzejszczak is on holidays ;)

**Comment by marcingrzejszczak** [comment]
The cursor means that there's a bug in the conversion. I hate bugs and especially those that produce a cursor!

**Comment by cah-daniel-adams01** [comment]
@marcingrzejszczak - was this fix implemented? I am currently experiencing the same issue with the email() and isoDate()/isoDateTime() regex's as well. I just get a cursor value every time. I am currently working on the newest version of the framework:
![image](https://user-images.githubusercontent.com/47675715/60892930-f5a57480-a22d-11e9-8248-1aadfa6b493b.png)

**Comment by marcingrzejszczak** [comment]
yes, it got implemented almost 3 years ago. Can you present a sample that would help as replicate this?

**Comment by adamkrol93** [comment]
I can:
We do have contract like: 
```
  Contract.make {
    request {
        method 'POST'
        urlPath $(test('/resource/resourceId/another-resource/another-resource-id/sth'), stub(regex('/resource/[\\w\\.]+/another-resource/([\\w+\\.-]|%[a-fA-F0-9]{2})+/sth')))
        body($(stub(regex(".+")), test(execute("encrypt('a lot of code')"))))
    }
    response {
        status 201
    }
    // 1 is the highest
    priority 1000
}
```

We have resulted mapping like:
```
{
  "id" : "34203fdf-3605-4d91-9c25-64029917bd07",
  "request" : {
    "urlPathPattern" : "/resource/[\\w\\.]+/another-resource/([\\w+\\.-]|%[a-fA-F0-9]{2})+/sth",
    "method" : "POST",
    "bodyPatterns" : [ {
      "equalToJson" : "{\"cursor\":2}",
      "ignoreArrayOrder" : false,
      "ignoreExtraElements" : false
    } ]
  },
  "response" : {
    "status" : 201,
    "transformers" : [ "response-template" ]
  },
  "uuid" : "34203fdf-3605-4d91-9c25-64029917bd07",
  "priority" : 1000
}

```
