### ISSUE TITLE
Tests are failing in Spring Cloud Contract Verifier module

### ISSUE THREAD

**Issue by Vyacheslau** [spring-cloud/spring-cloud-contract#98]
Tests are failed after running: 
./mvnw clean install -P integration

Details:
Failed tests:   should return a class from the generated path by taking two last folders when package with base classes is provided(org.springframework.cloud.contract.verifier.builder.ClassBuilderSpec): Condition not satisfied:(..)

Tests run: 208, Failures: 1, Errors: 0, Skipped: 0

**Comment by marcingrzejszczak** [comment]
Hmm it's not failing on my machine (or CircleCI or Jenkins) ;) Can you provide some more information? Why is failing? What's your machine etc?

**Comment by Vyacheslau** [comment]
The exact steps to reproduce:
1. CD to spring-cloud-contract root folder
2. Run ./mvnw clean install -P integration (exact command in my case .\mvnw clean install -P integration)

Environment: Windows 8.1 Enterprise.

Please let me know if you need some other info.

**Comment by marcingrzejszczak** [comment]
Yeah so I'll need the exact reason for the failing test. Most likely it's related to File separators in Windows :/

**Comment by Vyacheslau** [comment]
[console_output.txt](https://github.com/spring-cloud/spring-cloud-contract/files/519367/console_output.txt)

[surefire-reports.zip](https://github.com/spring-cloud/spring-cloud-contract/files/519375/surefire-reports.zip)

Attaching console output and test results.

**Comment by marcingrzejszczak** [comment]
Can you try now?

**Comment by Vyacheslau** [comment]
That works now, but fails on:
[INFO] Spring Cloud Contract Stub Runner .................. FAILURE [04:11 min]

with:
Failed tests:   should set inclusion pattern on config when path pattern was explicitly provided with a separator at the beginning(org.springframework.cloud.contract.stubrunner.ContractDownloaderSpec): Condition not satisfied:(..)
  should set inclusion pattern on config when path pattern was explicitly provided without a separator at the beginning(org.springframework.cloud.contract.stubrunner.ContractDownloaderSpec): Condition not satisfied:(..)

Will we track that in that issue?

**Comment by marcingrzejszczak** [comment]
Yes, please. Can you provide the logs?

**Comment by marcingrzejszczak** [comment]
Ok I think I fixed this one - can you check it?

**Comment by Vyacheslau** [comment]
Just checked with your latest changes:
[console_output.txt](https://github.com/spring-cloud/spring-cloud-contract/files/519468/console_output.txt)
[surefire-reports.zip](https://github.com/spring-cloud/spring-cloud-contract/files/519469/surefire-reports.zip)

**Comment by marcingrzejszczak** [comment]
Thanks, hopefully that's fixed. Can you check it?

**Comment by Vyacheslau** [comment]
New results:
[console_output.txt](https://github.com/spring-cloud/spring-cloud-contract/files/519590/console_output.txt)
[surefire-reports.zip](https://github.com/spring-cloud/spring-cloud-contract/files/519591/surefire-reports.zip)

**Comment by marcingrzejszczak** [comment]
Meh, maybe now?

**Comment by Vyacheslau** [comment]
Here is the output:
[surefire-reports.zip](https://github.com/spring-cloud/spring-cloud-contract/files/521777/surefire-reports.zip)
[console_output.txt](https://github.com/spring-cloud/spring-cloud-contract/files/521778/console_output.txt)
